doc-content/enterprise-only/installation/install-testing-proc.adoc
doc-content/enterprise-only/installation/ssh-configuring-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-5042
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5042/#verifying_the_red_hat_decision_manager_installation

Upstream PR BXMSDOC-5042-7.26.x to Upstream 7.26.x Added MySpace to step

---

doc-content/kogito-docs/src/main/asciidoc/openshift/proc_kogito-travel-agency-interacting.adoc

A very minor fix for a GraphQL query in travel agency section :)

minor fix for travel-agency query

---

assemblies/assembly_designing-business-processes/main.adoc
assemblies/assembly_install-on-jws/main.adoc
doc-content/enterprise-only/admin-and-config/clean-log-proc.adoc
doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
doc-content/enterprise-only/admin-and-config/manual-cleanup-con.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

See JIRA: 
https://issues.redhat.com/browse/BXMSDOC-5098
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5098-RHPAM-PD/#manage-log-file-proc)

Upstream master PR for BXMSDOC-5098: Added Managing Log files chapter in process designer doc

---

assemblies/assembly_designing-business-processes/main.adoc
assemblies/assembly_install-on-jws/main.adoc
doc-content/enterprise-only/admin-and-config/clean-log-proc.adoc
doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
doc-content/enterprise-only/admin-and-config/manual-cleanup-con.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

See JIRA: 
https://issues.redhat.com/browse/BXMSDOC-5098
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5098-RHPAM-PD/#manage-log-file-proc)

Upstream 7.33.x PR for BXMSDOC-5098: Added Managing Log files chapter in process designer doc

---

assemblies/assembly_designing-business-processes/main.adoc
assemblies/assembly_install-on-jws/main.adoc
doc-content/enterprise-only/admin-and-config/clean-log-proc.adoc
doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
doc-content/enterprise-only/admin-and-config/manual-cleanup-con.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

See JIRA:
https://issues.redhat.com/browse/BXMSDOC-5098
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5098-7.6/#manage-log-file-proc)

Upstream 7.30.x PR for BXMSDOC-5098: Added Managing Log files chapter in process designer doc

---

assemblies/assembly_designing-business-processes/main.adoc
assemblies/assembly_install-on-jws/main.adoc
doc-content/enterprise-only/admin-and-config/clean-log-proc.adoc
doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
doc-content/enterprise-only/admin-and-config/manual-cleanup-con.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

See JIRA:
https://issues.redhat.com/browse/BXMSDOC-5098
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5098-7.5/#manage-log-file-proc)

Upstream 7.26.x PR for BXMSDOC-5098: Added Managing Log files chapter in process designer doc

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ref-kogito-rn-key-features.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ref-kogito-rn-known-issues.adoc

Per known issue reported in [KOGITO-1835](https://issues.redhat.com/browse/KOGITO-1835). Approved by @krisv , @porcelli , and @ederign in chat.

BXMSDOC-5777: Add VSCode known issue to Kogito RN.

---

assemblies/assembly-kogito-configuring/main.adoc
assemblies/assembly-kogito-developing-decision-services/main.adoc
assemblies/assembly-kogito-developing-process-services/main.adoc
doc-content/kogito-docs/pom.xml
doc-content/kogito-docs/src/main/asciidoc/bpmn/proc-bpmn-model-creating.adoc
doc-content/kogito-docs/src/main/asciidoc/bpmn/proc-management-console-using.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/con-kogito-modelers.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/proc-kogito-vscode-extension.adoc
doc-content/kogito-docs/src/main/asciidoc/dmn/proc-dmn-model-creating.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-travel-agency.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-deploying-on-ocp-console.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-deploying-on-ocp-kogito-cli.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-configure-ocp.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-create-ocp-project.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-create-services.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-deploy-binary.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-enable-data-index.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-enable-messaging.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-enable-persistence.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-interacting.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ref-kogito-rn-known-issues.adoc
doc-content/pom.xml
pom.xml

See [JIRA](https://issues.redhat.com/browse/BXMSDOC-5780)

BXMSDOC-5780: Add RN known issue about Hub extract plus other tweaks for 0.9.1.

---

assemblies/assembly_designing-business-processes/main.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-lifecycle-ref.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-permission-ref.adoc

See JIRA:
https://issues.redhat.com/browse/BXMSDOC-4720
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4720-RHPAM/#bpmn-user-task-lifecycle-ref)

Upstream master PR for BXMSDOC-4720: Added user task lifecycle and permission matrix topics in process designer doc

---

assemblies/assembly_designing-business-processes/main.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-lifecycle-ref.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-permission-ref.adoc

See JIRA:
https://issues.redhat.com/browse/BXMSDOC-4720
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4720-RHPAM/#bpmn-user-task-lifecycle-ref)

Upstream 7.33.x PR for BXMSDOC-4720: Added user task lifecycle and permission matrix topics in process designer doc 

---

assemblies/assembly_designing-business-processes/main.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-lifecycle-ref.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-permission-ref.adoc

See JIRA:
https://issues.redhat.com/browse/BXMSDOC-4720
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4720-7.6/#bpmn-user-task-lifecycle-ref)

Upstream 7.30.x PR for BXMSDOC-4720: Added user task lifecycle and permission matrix topics in process designer doc

---

assemblies/assembly_designing-business-processes/main.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-lifecycle-ref.adoc
doc-content/enterprise-only/bpmn/bpmn-user-task-permission-ref.adoc

See JIRA:
https://issues.redhat.com/browse/BXMSDOC-4720
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4720-7.5/#bpmn-user-task-lifecycle-ref)

Upstream 7.26.x PR for BXMSDOC-4720: Added user task lifecycle and permission matrix topics  in process designer doc 

---

assemblies/assembly_release-notes/main.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5811)
- [7.7-RHPAM-Release notes for Red Hat Process Automation Manager](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.7-RN/) 
- [7.7-RHDM-Release notes for Red Hat Decision Manager](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHDM-7.7-RN/) 
I have added the reference links in the **What's new** and **tech preview** section of the RN document.

Upstream master PR for BXMSDOC-5811: Add reference links for what's new content in 7.7 release notes

---

doc-content/enterprise-only/admin-and-config/safe-points-configuring-proc.adoc

Upstream PR BXMSDOC-4832-master-final to upstream master: Added safe point node list

---

doc-content/enterprise-only/admin-and-config/safe-points-configuring-proc.adoc

Upstream PR BXMSDOC-4832-7.23.x-final to upstream 7.23.x: Added safe point node list

---

doc-content/enterprise-only/admin-and-config/safe-points-configuring-proc.adoc

Upstream PR BXMSDOC-4832-7.26.x-final to upstream 7.26.x: Added safe point node list

---

doc-content/enterprise-only/admin-and-config/safe-points-configuring-proc.adoc

Upstream PR BXMSDOC-4832-7.30.x-final to upstream 7.30.x: Added safe point node list

---

doc-content/enterprise-only/admin-and-config/safe-points-configuring-proc.adoc

Upstream PR BXMSDOC-4832-7.33.x-final to upstream 7.33.x: Added safe point node list

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/openshift/hacep-server-proc.adoc

* Add security steps for HACEP non-Maven server - 7.7 only
* Updated rebuilt date

[BXMSDOC-5814] Add security steps for HACEP non-Maven server - 7.7 only - 7.33.x

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-Async-Sig/#asynchronous-signal-events-con)

Upstream master PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-Async-Sig/#asynchronous-signal-events-con)

Upstream 7.33.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.30.x-7.6-Async/#asynchronous-signal-events-con)

Upstream 7.30.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.26.x-7.5-Async/#asynchronous-signal-events-con)

Upstream 7.26.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.23.x-7.4-Async/#asynchronous-signal-events-con)

Upstream 7.23.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.18.x-7.3-Async/#asynchronous-signal-events-con)
- **3.5. Asynchronous signal events** 
- **3.5.1. Configuring asynchronous signals for intermediate events**
- **3.5.2. Configuring asynchronous signals for end events**

Upstream 7.18.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.14.x-7.2-Async/#asynchronous-signal-events-con)
- **5.5. Asynchronous signal events** 
- **5.5.1. Configuring asynchronous signals for intermediate events**
- **5.5.2. Configuring asynchronous signals for end events**

Upstream 7.14.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

docs/product-assembly_managing-and-monitoring-business-processes/src/main/asciidoc/main.adoc
docs/product-user-guide/src/main/asciidoc/asynchronous-signal-end-events-proc.adoc
docs/product-user-guide/src/main/asciidoc/asynchronous-signal-events-con.adoc
docs/product-user-guide/src/main/asciidoc/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.7.x-7.0-Async/#asynchronous-signal-events-con)
- **5.5. Asynchronous signal events** 
- **5.5.1. Configuring asynchronous signals for intermediate events**
- **5.5.2. Configuring asynchronous signals for end events**

Upstream 7.7.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
doc-content/enterprise-only/processes/asynchronous-signal-end-events-proc.adoc
doc-content/enterprise-only/processes/asynchronous-signal-events-con.adoc
doc-content/enterprise-only/processes/asynchronous-signal-intermediate-events-proc.adoc

- [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.14.x-7.2-Async/#asynchronous-signal-events-con)
- **5.5. Asynchronous signal events** 
- **5.5.1. Configuring asynchronous signals for intermediate events**
- **5.5.2. Configuring asynchronous signals for end events**

Upstream 7.11.x PR for BXMSDOC-2608: Added the asynchronous signal events section in the document.

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/decision-engine-con.adoc

[DECISION ENGINE IN RED HAT PROCESS AUTOMATION MANAGER](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHPAM/#decision-engine-con_decision-engine)
[DECISION ENGINE IN RED HAT DECISION MANAGER](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHDM/#decision-engine-con_decision-engine)

Upstream 7.33.x PR for BXMSDOC-5832: Added cross reference for use case

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/decision-engine-con.adoc

[DECISION ENGINE IN RED HAT PROCESS AUTOMATION MANAGER 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHPAM-7.6/#decision-engine-con_decision-engine)
[DECISION ENGINE IN RED HAT DECISION MANAGER 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHDM-7.6/#decision-engine-con_decision-engine)

Upstream 7.30.x PR for BXMSDOC-5832: Added cross reference for use case in decision engine doc

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/decision-engine-con.adoc

[DECISION ENGINE IN RED HAT PROCESS AUTOMATION MANAGER 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHPAM-7.5/#decision-engine-con_decision-engine)
[DECISION ENGINE IN RED HAT DECISION MANAGER 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHDM-7.5/#decision-engine-con_decision-engine)

Upstream 7.26.x PR for BXMSDOC-5832: Added cross reference for use case in decision engine doc

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/decision-engine-con.adoc

[DECISION ENGINE IN RED HAT PROCESS AUTOMATION MANAGER 7.4](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHPAM-7.4/#decision-engine-con_decision-engine)
[DECISION ENGINE IN RED HAT DECISION MANAGER 7.4](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHDM-7.4/#decision-engine-con_decision-engine)

Upstream 7.23.x PR for BXMSDOC-5832: Added cross reference for use case in decision engine doc

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/decision-engine-con.adoc

[DECISION ENGINE IN RED HAT PROCESS AUTOMATION MANAGER](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHPAM/#decision-engine-con_decision-engine)
[DECISION ENGINE IN RED HAT DECISION MANAGER](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5832-RHDM/#decision-engine-con_decision-engine)

Upstream master PR for BXMSDOC-5832: Added cross reference for use case in decision engine doc

---

doc-content/enterprise-only/openshift/additional-server-managed-deploy-assy.adoc
doc-content/enterprise-only/openshift/environment-authoring-con.adoc
doc-content/enterprise-only/openshift/startupstrategy-enable-proc.adoc
doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc

* OSSS re-enabled for authoring HA in 7.7.1
* SME review
* Typo
* Peer review 1

[BXMSDOC-5910] OSSS re-enabled for authoring HA in 7.7.1, workaround for 7.7.0 - master

---

doc-content/enterprise-only/openshift/additional-server-managed-deploy-assy.adoc
doc-content/enterprise-only/openshift/environment-authoring-con.adoc
doc-content/enterprise-only/openshift/startupstrategy-enable-proc.adoc
doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc

* OSSS re-enabled for authoring HA in 7.7.1
* SME review
* Typo
* Peer review 1

[BXMSDOC-5910] OSSS re-enabled for authoring HA in 7.7.1, workaround for 7.7.0 - 7.33.x

---

doc-content/enterprise-only/admin-and-config/managing-business-central-integrating-remote-git-repositories-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5829)
- [RHPAM-7.7-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHPAM-7.7-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
- [RHDM-7.7-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHDM-7.7-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
Check **Step 5** from section 19.5. Integrating remote Git repositories in both the docs. I have updated the **cp** command. 
**Original:** cp bc-git-integration-push/git-push-2.1-SNAPSHOT.jar _EAP_HOME_/hooks/
**Revised:** cp …

Upstream master PR for BXMSDOC-5829: [DDF] Update the copy command.

---

doc-content/enterprise-only/admin-and-config/managing-business-central-integrating-remote-git-repositories-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5829)
- [RHPAM-7.7-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHPAM-7.7-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
- [RHDM-7.7-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHDM-7.7-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
Check **Step 5** from section 19.5. Integrating remote Git repositories in both the docs. I have updated the **cp** command. 
**Original:** cp bc-git-integration-push/git-push-2.1-SNAPSHOT.jar _EAP_HOME_/hooks/
**Revised:** cp …

Upstream 7.33.x PR for BXMSDOC-5829: [DDF] Update the copy command.

---

doc-content/enterprise-only/admin-and-config/managing-business-central-integrating-remote-git-repositories-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5829)
- [RHPAM-7.6-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHPAM-7.6-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
- [RHDM-7.6-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHDM-7.6-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
Check **Step 5** from section 18.5. Integrating remote Git repositories in both the docs. I have updated the **cp** command. 
**Original:** cp bc-git-integration-push/git-push-2.1-SNAPSHOT.jar _EAP_HOME_/hooks/
**Revised:** cp …

Upstream 7.30.x PR for BXMSDOC-5829: [DDF] Update the copy command.

---

doc-content/enterprise-only/admin-and-config/managing-business-central-integrating-remote-git-repositories-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5829)
- [RHPAM-7.5-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHPAM-7.5-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
- [RHDM-7.5-Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5829-RHDM-7.5-BC-Settings/#managing-business-central-integrating-remote-git-repositories-proc-configuring-central)
Check **Step 5** from section 18.5. Integrating remote Git repositories in both the docs. I have updated the **cp** command. 
**Original:** cp bc-git-integration-push/git-push-2.1-SNAPSHOT.jar _EAP_HOME_/hooks/
**Revised:** cp …

Upstream 7.26.x PR for BXMSDOC-5829: [DDF] Update the copy command.

---

assemblies/assembly_release-notes/main.adoc
doc-content/enterprise-only/release-notes/rn-771-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-771-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc

Document and add the 7.7.1 patch release notes updates.
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5915)
- [Release notes for Red Hat Process Automation Manager 7.7](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5915-7.7.1-RHPAM-ReleaseNotes/#rn-771-known-issues-ref)
- [Release notes for Red Hat Decision Manager 7.7](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5915-7.7.1-RHDM-ReleaseNotes/#rn-771-known-issues-ref)
- Chapter 7: Known issues for 7.7.1
- Chapter 8: Fixed issues for 7.7.1

Upstream master PR for BXMSDOC-5915: Added 7.7.1 patch release notes update in the document.

---

assemblies/assembly_release-notes/main.adoc
doc-content/enterprise-only/release-notes/rn-771-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-771-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc

Document and add the 7.7.1 patch release notes updates.
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5915)
- [Release notes for Red Hat Process Automation Manager 7.7](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5915-7.7.1-RHPAM-ReleaseNotes/#rn-771-known-issues-ref)
- [Release notes for Red Hat Decision Manager 7.7](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5915-7.7.1-RHDM-ReleaseNotes/#rn-771-known-issues-ref)
- Chapter 7: Known issues for 7.7.1
- Chapter 8: Fixed issues for 7.7.1

Upstream 7.33.x PR for BXMSDOC-5915: Added 7.7.1 patch release notes update in the document.

---

doc-content/enterprise-only/springboot/bus-app-swagger_proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5825
[Creating Red Hat Process Automation Manager business applications with Spring Boot](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5825-RHPAM/#bus-app-swagger_business-applications)
[Creating Red Hat Decision Manager business applications with Spring Boot](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5825-RHDM/#bus-app-swagger_business-applications)

BXMSDOC-5825: changed the version of version for cxf-rt-rs-service-description-swagger dependency

---

doc-content/enterprise-only/admin-and-config/assets-filtering-proc.adoc

Upstream PR BXMSDOC-4518 to upstream master

---

doc-content/enterprise-only/admin-and-config/assets-filtering-proc.adoc

Upstream PR BXMSDOC-4518-7.23.x to upstream 7.23.x

---

doc-content/enterprise-only/admin-and-config/assets-filtering-proc.adoc

Upstream PR BXMSDOC-4518-7.26.x to upstream 7.26.x

---

doc-content/enterprise-only/admin-and-config/assets-filtering-proc.adoc

Upstream PR BXMSDOC-4518-7.30.x to upstream 7.30.x

---

doc-content/enterprise-only/admin-and-config/assets-filtering-proc.adoc

Upstream PR BXMSDOC-4518-7.33.x to upstream 7.33.x

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/assets-filtering-proc.adoc
doc-content/enterprise-only/admin-and-config/assets-renaming-proc.adoc
doc-content/enterprise-only/getting-started/assets-creating-proc.adoc

Added additional step to guide to project explorer and publish date change.

Upstream PR Bxmsdoc 4518 7.26.x final to upstream 7.26.x

---

assemblies/assembly_openshift-operator/main.adoc
doc-content/enterprise-only/openshift/customimage-bc-githooks-proc.adoc
doc-content/enterprise-only/openshift/customimage-build-step.adoc
doc-content/enterprise-only/openshift/customimage-con.adoc
doc-content/enterprise-only/openshift/customimage-download-step.adoc
doc-content/enterprise-only/openshift/customimage-jar-proc.adoc
doc-content/enterprise-only/openshift/customimage-nextsteps.adoc
doc-content/enterprise-only/openshift/customimage-push-step.adoc
doc-content/enterprise-only/openshift/customimage-rpm-proc.adoc
doc-content/enterprise-only/openshift/customimage-verify-partstep.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-modify-proc.adoc

* Custom images first draft
* restructured modules to remove duplication of source
* snippets and much new information
* SME review
* final peer review
* xref formatting
* typo

[BXMSDOC-5891] Custom images 

---

doc-content/enterprise-only/openshift/environment-authoring-ha-modify-proc.adoc
doc-content/enterprise-only/openshift/environment-authoring-single-modify-proc.adoc
doc-content/enterprise-only/openshift/environment-immutable-modify-proc.adoc
doc-content/enterprise-only/openshift/environment-immutable-server-kjar-proc.adoc
doc-content/enterprise-only/openshift/environment-managed-modify-proc.adoc
doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc

* External db changes
* Dialects
* typo
* Peer review

[BXMSDOC-6013] External db changes 

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/proc-kogito-creating-project-custom.adoc

update according to https://github.com/kiegroup/kogito-runtimes/pull/567

KOGITO-2482 Add `kogito:scaffold` Mojo

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-defining-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-upload-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5912
Epic: https://issues.redhat.com/browse/BXMSDOC-5614
[DESIGNING A DECISION SERVICE USING SPREADSHEET DECISION TABLES RHPAM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5912-RHPAM-7.8/#decision-tables-defining-proc)
[DESIGNING A DECISION SERVICE USING SPREADSHEET DECISION TABLES RHDM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5912-RHDM-7.8/#decision-tables-defining-proc)

Upstream 7.39.x PR for BXMSDOC-5912: Added a note for multisheet decision table information in decision table document

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-defining-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-upload-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5912
Epic: https://issues.redhat.com/browse/BXMSDOC-5614
Rendered output: 
[DESIGNING A DECISION SERVICE USING SPREADSHEET DECISION TABLES RHPAM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5912-RHPAM-7.8/#decision-tables-defining-proc)
[DESIGNING A DECISION SERVICE USING SPREADSHEET DECISION TABLES RHDM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5912-RHDM-7.8/#decision-tables-defining-proc)

Upstream master PR for BXMSDOC-5912: Added a note for multisheet decision table information in decision table document

---

assemblies/assembly_kie-apis/main.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-spaces-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-endpoints-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-groups-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-permissions-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-roles-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-supported-permissions-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-users-ref.adoc

See JIRAs: https://issues.redhat.com/browse/BXMSDOC-5969
https://issues.redhat.com/browse/BXMSDOC-6027
Epic: https://issues.redhat.com/browse/BXMSDOC-5632
Rendered output: 
[Interacting with Red Hat Process Automation Manager using KIE APIs 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5969-RHPAM-7.8/#knowledge-store-rest-api-con_kie-apis)
[Interacting with Red Hat Decision Manager using KIE APIs 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5969-RHDM-7.8/#knowledge-store-rest-api-con_kie-apis)

Upstream master PR for BXMSDOC-5969: Added a section for Security Management APIs & BAPL-1564

---

assemblies/assembly_kie-apis/main.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-spaces-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-endpoints-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-groups-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-permissions-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-roles-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-supported-permissions-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-users-ref.adoc

See JIRAs: https://issues.redhat.com/browse/BXMSDOC-5969
https://issues.redhat.com/browse/BXMSDOC-6027
Epic: https://issues.redhat.com/browse/BXMSDOC-5632
[Interacting with Red Hat Process Automation Manager using KIE APIs 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5969-RHPAM-7.8/#knowledge-store-rest-api-con_kie-apis)
[Interacting with Red Hat Decision Manager using KIE APIs 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5969-RHDM-7.8/#knowledge-store-rest-api-con_kie-apis)

Upstream 7.39.x PR for BXMSDOC-5969: Added a section for Security Management APIs & BAPL-1564

---

doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-operator-architecture.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-deploying-on-kubernetes.adoc

Signed-off-by: spolti <fspolti@redhat.com>

KOGITO-2264] - Upgrade Operator SDK to 0.18.x

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/0.12.0/ref-kogito-rn-new-features.adoc

New features for Foundation on 0.6.0

New features for Foundation on 0.6.0

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/0.12.0/ref-kogito-rn-new-features.adoc

Add DMN Guided Tour into the `ref-kogito-rn-new-features.adoc`.

DMN Guided Tour on 0.6.0

---

_artifacts/document-attributes.adoc
assemblies/assembly_clustering-eap/dm/master-docinfo.xml
assemblies/assembly_clustering-eap/pam/master-docinfo.xml
assemblies/assembly_install-on-eap/main.adoc
doc-content/enterprise-only/installation/clustering-bc-configure-domain-proc.adoc
doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
doc-content/enterprise-only/installation/clustering-bc-install-proc.adoc
doc-content/enterprise-only/installation/clustering-datagrid-proc.adoc
doc-content/enterprise-only/installation/clustering-dm-ks-configure-domain-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
doc-content/enterprise-only/installation/clustering-ps-configure-standalone_proc.adoc
doc-content/enterprise-only/installation/clustering-ps-install-proc.adoc
doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
doc-content/enterprise-only/installation/eap-dm-install-proc.adoc
doc-content/enterprise-only/installation/eap-execution-server-download-install-proc.adoc
doc-content/enterprise-only/installation/installer-run-cli-proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc

* BXMSDOC-5853-master: Update EAP from 7.2 to 7.3 and ensure ee8 is targeting EAP
* BXMSDOC-5853-master: Adopt feedback

BXMSDOC-5853-master: Update EAP from 7.2 to 7.3 and ensure ee8 is targeting EAP

---

_artifacts/document-attributes.adoc
assemblies/assembly_clustering-eap/dm/master-docinfo.xml
assemblies/assembly_clustering-eap/pam/master-docinfo.xml
assemblies/assembly_install-on-eap/main.adoc
doc-content/enterprise-only/installation/clustering-bc-configure-domain-proc.adoc
doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
doc-content/enterprise-only/installation/clustering-bc-install-proc.adoc
doc-content/enterprise-only/installation/clustering-datagrid-proc.adoc
doc-content/enterprise-only/installation/clustering-dm-ks-configure-domain-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
doc-content/enterprise-only/installation/clustering-ps-configure-standalone_proc.adoc
doc-content/enterprise-only/installation/clustering-ps-install-proc.adoc
doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
doc-content/enterprise-only/installation/eap-dm-install-proc.adoc
doc-content/enterprise-only/installation/eap-execution-server-download-install-proc.adoc
doc-content/enterprise-only/installation/installer-run-cli-proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc

* BXMSDOC-5853-7.39.x: Update EAP from 7.2 to 7.3 and ensure ee8 is targeting EAP
* BXMSDOC-5853-7.39.x: Adopt feedback

BXMSDOC-5853-7.39.x: Update EAP from 7.2 to 7.3 and ensure ee8 is targeting EAP

---

assemblies/assembly_openshift-operator/main.adoc
doc-content/enterprise-only/openshift/customimage-con.adoc
doc-content/enterprise-only/openshift/githooks-prepare-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-pim-proc.adoc
doc-content/enterprise-only/openshift/operator-modify-proc.adoc

* Git hooks operator solution 1
* Git hooks 2
* unrelated typo fix
* SME review Ruben
* Peer review

[BXMSDOC-6038] Git hooks in operator - master

---

assemblies/assembly_openshift-operator/main.adoc
doc-content/enterprise-only/openshift/customimage-con.adoc
doc-content/enterprise-only/openshift/githooks-prepare-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-pim-proc.adoc
doc-content/enterprise-only/openshift/operator-modify-proc.adoc

* Git hooks operator solution 1
* Git hooks 2
* unrelated typo fix
* SME review Ruben
* Peer review

[BXMSDOC-6038] Git hooks in operator - 7.39.x

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/0.12.0/ref-kogito-rn-new-features.adoc

Operator and CLI Release Notes for 0.12

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.7.0.Final-section.adoc

Very minor fix. But it failed if copy&paste :)

Fixed generateModel command

---

assemblies/assembly_openshift-operator/main.adoc
doc-content/enterprise-only/openshift/operator-deploy-start-proc.adoc

* OCP version 4
* removed 4.1 ref
* Peer review

[BXMSDOC-6021] OCP supported version link, remove OCP 4.1 reference - 7.39.x

---

assemblies/assembly_openshift-operator/main.adoc
doc-content/enterprise-only/openshift/operator-deploy-start-proc.adoc

* OCP version 4
* removed 4.1 ref
* Peer review

[BXMSDOC-6021] OCP supported version link, remove OCP 4.1 reference - master

---

doc-content/enterprise-only/openshift/operator-modify-proc.adoc

[BXMSDOC-6018] refer to CRD in modifying operator deployment - 7.39.x

---

doc-content/enterprise-only/openshift/operator-modify-proc.adoc

[BXMSDOC-6018] refer to CRD in modifying operator deployment - master

---

doc-content/enterprise-only/employee-rostering/optashift-ER-running-jar-proc.adoc

[RHPAM draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-6040-pam/#optashift-ER-running-jar-proc)
[RHDM draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-6040-dm/#optashift-ER-running-jar-proc)
[Details in BXMSDOC-6040](https://issues.redhat.com/browse/BXMSDOC-6040)

BXMSDOC-6040 Change maven build command for Employee Rostering starter application

---

doc-content/enterprise-only/admin-and-config/deployment-descriptor-configuration-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-4515
Doc previews:
[Managing and monitoring KIE Server RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4515-RHPAM/#deployment_descriptor_configuration)
[Managing and monitoring KIE Server RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4515-RHDM/#deployment_descriptor_configuration)

Upstream master PR for BXMSDOC-4515: Added recommendation for PerProcessInstance in managing and monitoring process server doc

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/deployment-descriptor-configuration-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-4515
Doc previews:
[Managing and monitoring KIE Server RHPAM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4515-RHPAM-7.5/#deployment_descriptor_configuration)
[Managing and monitoring KIE Server RHDM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4515-RHDM-7.5/#deployment_descriptor_configuration)

Upstream 7.26.x PR for BXMSDOC-4515: Added recommendation for PerProcessInstance in managing and monitoring process server doc

---

doc-content/enterprise-only/project-data/migrating-legacy-designer-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-5818
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5818/#migrating-from-legacy-designer-proc

Upstream PR BXMSDOC-5818 to upstream Master Removing legacy designer enablement note (#150)

---

doc-content/enterprise-only/project-data/migrating-legacy-designer-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-5818
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5818/#migrating-from-legacy-designer-proc

Upstream PR BXMSDOC-5818-7.33.x to upstream 7.33.x Removing legacy designer enablement note (#150)

---

doc-content/enterprise-only/bpmn/bpmn-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5941
Epic: https://issues.redhat.com/browse/BXMSDOC-5752
Doc preview:
[Process designer Business Process Model and Notation (BPMN2) reference guide](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5941-RHPAM/#bpmn-con_bpmn-reference)

Upstream master PR for BXMSDOC-5941: Added general process properties in BPMN reference guide

---

doc-content/enterprise-only/bpmn/bpmn-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5941
Epic: https://issues.redhat.com/browse/BXMSDOC-5752
Doc preview:
[Process designer Business Process Model and Notation (BPMN2) reference guide](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5941-RHPAM-7.8/#bpmn-con_bpmn-reference)

Upstream 7.39.x PR for BXMSDOC-5941: Added general process properties in BPMN reference guide

---

doc-content/enterprise-only/admin-and-config/deployment-descriptor-configuration-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-4515
Doc previews:
[Managing and monitoring KIE Server RHPAM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4515-RHPAM/#deployment_descriptor_configuration)
[Managing and monitoring KIE Server RHDM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-4515-RHDM/#deployment_descriptor_configuration)

Upstream 7.39.x PR for BXMSDOC-4515: Added recommendation for PerProcessInstance in managing and monitoring process server doc

---

doc-content/enterprise-only/openshift/operator-deploy-pim-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc

* Add click to turn on PIM
* Peer review!

[BXMSDOC-6127] Add click to turn on PIM - 7.39.x

---

doc-content/enterprise-only/openshift/operator-deploy-pim-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc

* Add click to turn on PIM
* Peer review!

[BXMSDOC-6127] Add click to turn on PIM - master

---

doc-content/enterprise-only/integration/entando-con.adoc

**JIRAs**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5713) 
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6041)
**Doc preview:** [Integrating Red Hat Process Automation Manager assets in Entando AppBuilder](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6041-RHPAM-Final-note/#entando-con_integrating-with-entando)
**Doc impact:** I have added a warning note for Entando deprecation in **chapter 1** of the Entando doc.

Upstream 7.39.x PR for BXMSDOC-6041: Add a warning note for Entando deprecation in the Entando doc.

---

doc-content/enterprise-only/integration/entando-con.adoc

**JIRAs**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5713) 
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6041)
**Doc preview:** [Integrating Red Hat Process Automation Manager assets in Entando AppBuilder](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6041-RHPAM-Final-note/#entando-con_integrating-with-entando)
**Doc impact:** I have added a warning note for Entando deprecation in **chapter 1** of the Entando doc.

Upstream master PR for BXMSDOC-6041: Add a warning note for Entando deprecation in the Entando doc.

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-7.39.x: Add important note regarding maven repository artifacts
* BXMSDOC-2095-7.39.x: Adopt feedback
* BXMSDOC-2095-7.39.x: Correct typo

BXMSDOC-2095-7.39.x: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-7.33.x: Add important note regarding maven repository artifacts
* BXMSDOC-2095-7.33.x: Adopt feedback
* BXMSDOC-2095-7.33.x: Correct typo

BXMSDOC-2095-7.33.x: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-7.30.x: Add important note regarding maven repository artifacts
* BXMSDOC-2095-7.30.x: Adopt feedback
* BXMSDOC-2095-7.30.x: Correct typo

BXMSDOC-2095-7.30.x: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-7.26.x: Add important note regarding maven repository artifacts
* BXMSDOC-2095-7.26.x: Adopt feedback
* BXMSDOC-2095-7.26.x: Correct typo

BXMSDOC-2095-7.26.x: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-7.23.x: Add important note regarding maven repository artifacts
* BXMSDOC-2095-7.23.x: Adopt feedback
* BXMSDOC-2095-7.23.x: Correct typo

BXMSDOC-2095-7.23.x: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-master: Add important note regarding maven repository artifacts
* BXMSDOC-2095-master: Adopt feedback
* BXMSDOC-2095-master: Correct typo

BXMSDOC-2095-master: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc

* BXMSDOC-2095-7.18.x: Add important note regarding maven repository artifacts
* BXMSDOC-2095-7.18.x: Adopt feedback
* BXMSDOC-2095-7.18.x: Correct typo

BXMSDOC-2095-7.18.x: Add important note regarding maven repository artifacts

---

doc-content/enterprise-only/optimizer/examples-table-ref.adoc

BXMSDOC-5743 removed cheatable link

BXMSDOC-5743 7.39x Removed cheatable link from BO GSG

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/installation/roles-users-con.adoc

Doc previews:
[Installing and configuring Red Hat Process Automation Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHPAM-7.6/#roles-users-con)
[Installing and configuring Red Hat Decision Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHDM-7.6/#roles-users-con)

Upstream 7.30.x PR for BXMSDOC-5459: Added clarification regarding users and roles

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/installation/roles-users-con.adoc

Doc previews:
[Installing and configuring Red Hat Process Automation Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHPAM-7.7/#roles-users-con)
[Installing and configuring Red Hat Decision Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHDM-7.7/#roles-users-con)

Upstream 7.33.x PR for BXMSDOC-5459: Added clarification regarding users and roles

---

docs/product-installation-guide/src/main/asciidoc/roles-users-con.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

Upstream 7.7.x PR for BXMSDOC-5459: Added clarification regarding users and roles

---

_artifacts/document-attributes.adoc
assemblies/assembly_integrating-sso/main.adoc
doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
doc-content/enterprise-only/integration/sso-int-con.adoc
doc-content/enterprise-only/integration/sso-kie-server-client-adapter-proc.adoc
doc-content/enterprise-only/integration/sso-realm-proc.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5731)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6165)
- [RHPAM 7.8 Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHPAM-SSO-QE/)
- [RHDM 7.8 Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHDM-SSO-QE/)
- Updated the versions, links and references in the SSO document. The document is now reflecting the SSO **7.4** version.

Upstream 7.39.x PR for BXMSDOC-6165: Updated the versions, links and references in the SSO document.

---

_artifacts/document-attributes.adoc
assemblies/assembly_integrating-sso/main.adoc
doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
doc-content/enterprise-only/integration/sso-int-con.adoc
doc-content/enterprise-only/integration/sso-kie-server-client-adapter-proc.adoc
doc-content/enterprise-only/integration/sso-realm-proc.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5731)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6165)
- [RHPAM 7.8 Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHPAM-SSO-QE/)
- [RHDM 7.8 Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHDM-SSO-QE/)
- Updated the versions, links and references in the SSO document. The document is now reflecting the SSO **7.4** version.

Upstream master PR for BXMSDOC-6165: Updated the versions, links and references in the SSO document.

---

doc-content/enterprise-only/installation/roles-users-con.adoc

Added clarification in **CHAPTER 2. RED HAT DECISION MANAGER ROLES AND USERS**
Doc previews:
[Installing and configuring Red Hat Process Automation Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHPAM/#roles-users-con)
[Installing and configuring Red Hat Decision Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHDM/#roles-users-con)

Upstream master PR for BXMSDOC-5459: Added clarification regarding users and roles

---

doc-content/drools-docs/src/main/asciidoc/LanguageReference/drl-operator-precedence-ref.adoc

Backport https://github.com/kiegroup/kie-docs/pull/2649 for 7.39.x

Add basic nested property access for 7.39.x

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/DROOLS-4461-date-picker-for-localdate.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/ReleaseNotesWorkbench.7.41.0.Final-section.adoc

For more details see: https://issues.redhat.com/browse/DROOLS-4461
Ensemble together with:
- https://github.com/kiegroup/drools-wb/pull/1369
- https://github.com/kiegroup/kie-wb-common/pull/3322

DROOLS-4461 Add release note for LocalDate tooling support

---

doc-content/enterprise-only/fuse/installing-ba-fuse-karaf-maven-proc.adoc
doc-content/enterprise-only/fuse/installing-on-fuse-eap-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-5862
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5862/#installing-on-fuse-eap-proc

Upstream PR for BXMSDOC-5862 to master Integrating PAM/DM 7.8 with Fuse

---

assemblies/assembly_install-on-eap/main.adoc
doc-content/enterprise-only/admin-and-config/customizing-dashbuilder-con.adoc
doc-content/enterprise-only/admin-and-config/dashbuilder-runtimes-con.adoc
doc-content/enterprise-only/admin-and-config/datasets-dashbuilder-runtimes-con.adoc
doc-content/enterprise-only/admin-and-config/installing-dashbuilder-proc.adoc

* BXMSDOC-5917-master: Create draft of Dashbuilder Runtime section
* BXMSDOC-5917-master: Small changes and corrections to new sections
* BXMSDOC-5917-master: Adopt SME feedback to add link and elaborate on section

BXMSDOC-5917-master: Add Dashbuilder Runtime section

---

assemblies/assembly_install-on-eap/main.adoc
doc-content/enterprise-only/admin-and-config/customizing-dashbuilder-con.adoc
doc-content/enterprise-only/admin-and-config/dashbuilder-runtimes-con.adoc
doc-content/enterprise-only/admin-and-config/datasets-dashbuilder-runtimes-con.adoc
doc-content/enterprise-only/admin-and-config/installing-dashbuilder-proc.adoc

* BXMSDOC-5917-7.39.x: Create draft of Dashbuilder Runtime section
* BXMSDOC-5917-7.39.x: Small changes and corrections to new sections
* BXMSDOC-5917-7.39.x: Adopt SME feedback to add link and elaborate on section

BXMSDOC-5917-7.39.x: Add Dashbuilder Runtime section

---

doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc

* BXMSDOC-5899-7.39.x: Update CodeReady Studio version and add attributes
* BXMSDOC-5899-7.39.x: Adopt QE feedback to correct titles and versions
* BXMSDOC-5895-7.39.x: Update procedure to include standalone sample configuration
* BXMSDOC-5895-7.39.x: Adopt SME feedback

BXMSDOC-5895-7.39.x: Update procedure to include standalone sample configuration

---

doc-content/enterprise-only/openshift/githooks-proc.adoc

* Git hooks known-hosts for template
* Update doc-content/enterprise-only/openshift/githooks-proc.adoc

[BXMSDOC-6130] Git hooks known-hosts for template - master

---

doc-content/enterprise-only/openshift/githooks-proc.adoc

* Git hooks known-hosts for template
* Update doc-content/enterprise-only/openshift/githooks-proc.adoc

[BXMSDOC-6130] Git hooks known-hosts for template - 7.39.x

---

doc-content/enterprise-only/openshift/operator-deploy-pim-proc.adoc

[BXMSDOC-6181] remove PIM external DB - master

---

doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6142
Doc Previews:
[Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6142-RHPAM/#sso-client-adapter-proc)
[Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6142-RHDm/#sso-client-adapter-proc)

Upstream master PR for BXMSDOC-6142: Deleted the step of removing single sign-on element

---

assemblies/assembly_business-optimizer-vrp/dm/master-docinfo.xml
assemblies/assembly_business-optimizer-vrp/main.adoc
assemblies/assembly_business-optimizer-vrp/pam/master-docinfo.xml
doc-content/enterprise-only/optimizer/business-optimizer-database-UI-integration-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizer-logging-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizer-make-executable-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizer-test-application-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizer-try-application-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizr-domain-objects-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizr-gather-objects-proc.adoc
doc-content/enterprise-only/optimizer/intializr-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/adjust-data-dir-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/backend-architecture-con.adoc
doc-content/enterprise-only/vehicle-route-planning/backend-properties-ref.adoc
doc-content/enterprise-only/vehicle-route-planning/download-ref-imp-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-locally-noninteractive-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-vrp-manually-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-con.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-run-openshift-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-troubleshooting-proc.adoc

BXMSDOC-6092-master updated after sanity check

BXMSDOC-6092 7.39.x Emily Sanity Check

---

doc-content/enterprise-only/bpmn/bpmn-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6091

Upstream master PR for BXMSDOC-6091: Fixed the findings from Sanity Check on stage

---

doc-content/enterprise-only/bpmn/bpmn-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6091

Upstream 7.39.x PR for BXMSDOC-6091: Fixed the findings from Sanity Check on stage

---

assemblies/assembly_hacep/main.adoc
doc-content/enterprise-only/openshift/architecture-authoring-con.adoc
doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
doc-content/enterprise-only/openshift/githooks-prepare-proc.adoc
doc-content/enterprise-only/openshift/githooks-proc.adoc
doc-content/enterprise-only/openshift/hacep-con.adoc
doc-content/enterprise-only/openshift/operator-con.adoc
doc-content/enterprise-only/openshift/readwritemany-proc.adoc
doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc

* Sanity check - stage
* Sanity check stage 2
* more stage sanity check changes for cloud

[BXMSDOC-6089] Sanity check changes - cloud - master

---

assemblies/assembly_hacep/main.adoc
doc-content/enterprise-only/openshift/architecture-authoring-con.adoc
doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
doc-content/enterprise-only/openshift/githooks-prepare-proc.adoc
doc-content/enterprise-only/openshift/githooks-proc.adoc
doc-content/enterprise-only/openshift/hacep-con.adoc
doc-content/enterprise-only/openshift/operator-con.adoc
doc-content/enterprise-only/openshift/readwritemany-proc.adoc
doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc

* Sanity check - stage
* Sanity check stage 2
* more stage sanity check changes for cloud

[BXMSDOC-6089] Sanity check changes - cloud - 7.39.x

---

doc-content/enterprise-only/bpmn/bpmn-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6091

Upstream 7.39.x PR for BXMSDOC-6091: Fixed the link issue found in Sanity Check

---

doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
doc-content/enterprise-only/installation/jms-broker-configure_proc.adoc
doc-content/enterprise-only/installation/ldap-ssl-con.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc

* BXMSDOC-6090-master: Update SSO link versions with version attribute {RH-SSO_VERSION}
* BXMSDOC-6090-master: Change file structure so attributes function correctly
* BXMSDOC-6090-master: Adopt feedback to correct link and update attribute

BXMSDOC-6090-master: Update SSO link versions with version attribute {RH-SSO_VERSION}

---

doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
doc-content/enterprise-only/installation/jms-broker-configure_proc.adoc
doc-content/enterprise-only/installation/ldap-ssl-con.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc

* BXMSDOC-6090-7.39.x: Update SSO link versions with version attribute {RH-SSO_VERSION}
* BXMSDOC-6090-7.39.x: Change file structure so attributes function correctly
* BXMSDOC-6090-7.39.x: Adopt feedback to correct link and update attribute

BXMSDOC-6090-7.39.x: Update SSO link versions with version attribute {RH-SSO_VERSION}

---

assemblies/assembly_install-on-jws/main.adoc

[PAM Preview](http://file.ork.redhat.com/~csherrar/BXMSDOC-6090/install-on-jws/PAM/)
[DM Preview](http://file.ork.redhat.com/~csherrar/BXMSDOC-6090/install-on-jws/DM/)

BXMSDOC-6090-master-II: Change URL version to version attribute and add note regarding known issue

---

doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

Updated the URL in the RHPAM and RHDM release notes.

Upstream 7.39.x PR for BXMSDOC-6101: Updated the findings from sanity check on production.

---

doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

Updated the URL in the RHPAM and RHDM release notes.

Upstream master PR for BXMSDOC-6101: Updated the findings from sanity check on production.

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/0.13.0/ref-kogito-rn-fixed-issues.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/0.13.0/ref-kogito-rn-new-features.adoc

Release notes for Kogito Operator and CLI

---

doc-content/kogito-docs/pom.xml
doc-content/pom.xml
pom.xml

the script missed the update of the pom? have to check why.

upgraded to next development version

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/proc-management-console-using.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-operator-deployment-options.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-operator-with-infinispan.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-operator-with-kafka.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-travel-agency.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-clone-repo.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-create-ocp-project.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-create-services.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/proc-kogito-travel-agency-deploy-binary.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/ref-kogito-cli-operations.adoc

@evacchi @radtriste @Kevin-Mok , can you please verify? Thanks.
Links:
* [Jira](url)
* [Enterprise doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6389/)
* [Community doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6389_COMM/#chap-kogito-deploying-on-openshift)

BXMSDOC-6389: Fix kogito-travel-agency paths and links.

---

assemblies/assembly_openshift-operator/main.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-assy.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-mysql-proc.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-postgresql-proc.adoc

* Migration OCP 3 to OCP 4
* SME review
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-assy.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-postgresql-proc.adoc
Co-authored-by: Heena Manwani …

[BXMSDOC-5361] Migration OCP 3 to OCP 4 - 7.39.x 

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-assy.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-mysql-proc.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-postgresql-proc.adoc

* Migration OCP 3 to OCP 4
* SME review
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-assy.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-bc-proc.adoc
* Update doc-content/enterprise-only/openshift/migration-ocp3-4-postgresql-proc.adoc
Co-authored-by: Heena Manwani …

[BXMSDOC-5361] Migration OCP 3 to OCP 4 

---

doc-content/enterprise-only/openshift/additional-server-managed-deploy-assy.adoc
doc-content/enterprise-only/openshift/authoring-deploy-assy.adoc
doc-content/enterprise-only/openshift/fixed-deploy-assy.adoc
doc-content/enterprise-only/openshift/freeform-monitor-deploy-assy.adoc
doc-content/enterprise-only/openshift/freeform-server-managed-deploy-assy.adoc
doc-content/enterprise-only/openshift/monitoring-deploy-assy.adoc
doc-content/enterprise-only/openshift/server-immutable-kjar-deploy-assy.adoc
doc-content/enterprise-only/openshift/server-immutable-s2i-deploy-assy.adoc
doc-content/enterprise-only/openshift/template-deploy-amq-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-centralmavenpwd-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-complete-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-connectcentral-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-githooksparams-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-ha-resources-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-ldap-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-namespace-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-nopubnet-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-optionalmaven-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-prometheus-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-replicas-auth-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-replicas-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-rhsso-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-start-proc.adoc
doc-content/enterprise-only/openshift/template-overview-con.adoc

The OCP title now builds. No structural changes made.

[BXMSDOC-6400] OCP title build - master

---

assemblies/assembly-getting-started-business-optimizer.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-convert-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-con.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-intro-con.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-con.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
doc-content/enterprise-only/admin-and-config/execution-error-management-con.adoc
doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc
doc-content/enterprise-only/integration/sso-basic-auth-proc.adoc
doc-content/enterprise-only/optimizer/optimizer-about-business-optimizer-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/business-process-forms-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/decision-authoring-assets-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.13.0.Final-section.adoc
titles-enterprise/bigbuild/dm/master-docinfo.xml
titles-enterprise/bigbuild/dm/master.adoc
titles-enterprise/bigbuild/dm/title.adoc
titles-enterprise/bigbuild/pam/master-docinfo.xml
titles-enterprise/bigbuild/pam/master.adoc
titles-enterprise/bigbuild/pam/title.adoc
titles-enterprise/bigbuild/title.adoc
titles-enterprise/master-docinfo.xml

[Jira](https://issues.redhat.com/browse/BXMSDOC-6435)

BXMSDOC-6435: Prep bigbuild 7.9 titles list.

---

assemblies/assembly-dmn-models.adoc
doc-content/drools-docs/src/main/asciidoc/DMN-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-boxed-expressions-con.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-feel-data-types-ref.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-feel-variable-function-names-ref.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc

BXMSDOC-6058-master: Add built-in FEEL section to DMN content.

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/dmn-execution-business-process.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6395
Added a Note for Namespace and DMN Model Name fields in **Invoking a Decision Model and Notation (DMN) service in a business process** in the process designer document.
Doc preview:
[Developing Process Services in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6395-RHPAM/#dmn-execution-business-process)

Upstream master PR for BXMSDOC-6395: Added a note for Namespace and DMN Model Name fields value to be same

---

doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-operator-with-prometheus.adoc

Jira Issue : https://issues.redhat.com/browse/KOGITO-2960
depends on 
https://github.com/kiegroup/kogito-cloud-operator/pull/521

[KOGITO-2960] - Prometheus integration with kogito-cloud-operator

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-781-known-issues-ref.adoc

**JIRAs:**
- [7.8 Epic](https://issues.redhat.com/browse/BXMSDOC-5708)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6401)
- [Release notes for Red Hat Process Automation Manager 7.8.1](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHPAM-7.8.1-Final/#rn-781-known-issues-ref)
- [Release notes for Red Hat Decision Manager 7.8.1](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHDM-7.8.1-Final/#rn-781-known-issues-ref)

Upstream 7.39.x PR2 for BXMSDOC-6401: 7.8.1 Release notes docs for DM and PAM

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/customimage-con.adoc
doc-content/enterprise-only/openshift/customimage-smartrouter-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc

* Custom SmartRouter image
* Peer review
* Peer review

[BXMSDOC-6408] Custom SmartRouter image

---

assemblies/assembly-openshift-authoring-managed.adoc
assemblies/assembly-openshift-authoring.adoc
assemblies/assembly-openshift-freeform.adoc
assemblies/assembly-openshift-immutable.adoc
assemblies/assembly-openshift-managed.adoc
assemblies/assembly-openshift-operator.adoc

* Performance requirements 1
* Performance requirements
* peer review

[BXMSDOC-6227] performance requirements

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
doc-content/enterprise-only/openshift/offline-repo-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6477
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6477/#offline-repo-proc_install-on-eap

Upstream PR BXMSDOC-6477 to master Added download page link name (#160)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
doc-content/enterprise-only/openshift/offline-repo-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6477
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6477/#offline-repo-proc_install-on-eap

Upstream PR BXMSDOC-6477 to 7.39.x Added download page link name

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-rule-table-entries-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6500
Doc preview:
[Designing a decision service using spreadsheet decision tables RHPAM 7.9](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6500-RHPAM/#decision-tables-rule-table-entries-ref)
[Designing a decision service using spreadsheet decision tables RHDM 7.9](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6500-RHDM/#decision-tables-rule-table-entries-ref)

Upstream master PR for BXMSDOC-6500: Modified sentence related to @watch annotation usage

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc

* BXMSDOC-6120-master: Add note regarding PostgreSQL and Oracle DDL scripts with Spring Boot
* BXMSDOC-6120-master: Adopt feedback to remove "instead"

BXMSDOC-6120-master: Add note regarding PostgreSQL and Oracle DDL scripts with Spring Boot

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc

* BXMSDOC-6120-7.39.x: Add note regarding PostgreSQL and Oracle DDL scripts with Spring Boot
* BXMSDOC-6120-7.39.x: Adopt feedback to remove "instead"

BXMSDOC-6120-7.39.x: Add note regarding PostgreSQL and Oracle DDL scripts with Spring Boot

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/appe-process-elements.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/RunApplication-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithCases-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithHanldersAndListeners-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithJPA-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithProcesses-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/ElasticSearchBusinessApp-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/JMSBusinessApp-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/10MinWorkbench-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Setup-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/TaskService/TaskEscalationsAndNotifications-section.adoc

Updated URLs from jbpm-console to business-central in documentations

[JBPM-8438] Updating business-central URL in documentation

---

doc-content/kogito-docs/src/main/asciidoc/chap-kogito-release-notes.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/0.15.0/ref-kogito-rn-new-features.adoc

@tarilabs Ready for your review of the KIE DMN note.
Links:
* [Jira](https://issues.redhat.com/browse/BXMSDOC-6532)
* [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6532_COMM/#_kie_dmn_validation_in_kogito)

BXMSDOC-6532: Finish 0.15 RN.

---

doc-content/kogito-docs/pom.xml

Companion PR of https://github.com/kiegroup/kie-docs/pull/2838
for `master-kogito` branch
as requested https://github.com/kiegroup/kie-docs/pull/2838#issuecomment-696196900

BXMSDOC-6539 Demonstrate automatic integrity check of DMN/FEEL builtin fn adoc

---

doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc

[BXMSDOC-6554] approval strategy when subscribing to operator - 7.26.x

---

doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc

[BXMSDOC-6554] approval strategy when subscribing to operator - 7.30.x

---

doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc

[BXMSDOC-6554] approval strategy when subscribing to operator - 7.33.x

---

doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc

[BXMSDOC-6554] approval strategy when subscribing to operator - 7.39.x

---

doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc

[BXMSDOC-6554] approval strategy when subscribing to operator - master

---

doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc

[BXMSDOC-6554] approval strategy when subscribing to operator - 7.23.x

---

doc-content/enterprise-only/openshift/hacep-server-environment-ref.adoc

* add reference to mandatory environment variables
* Clarified formula

[BXMSDOC-6213] Clarification for HACEP env var list 

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/springboot/spring-boot-jms-audit-proc.adoc

[BXMSDOC-6492](https://issues.redhat.com/browse/BXMSDOC-6492)

BXMSDOC-6492 Spring Boot: Configuring JMS Audit Replication

---

doc-content/kogito-docs/src/main/asciidoc/dmn/ref-dmn-feel-builtin-functions.adoc

**JIRA**: https://issues.redhat.com/browse/BXMSDOC-6622
**referenced Pull Requests**: none technically required, but part of an ensemble of PRs to align this doc over multiple repos
Ref:
https://github.com/kiegroup/drools/pull/3122
https://github.com/kiegroup/kie-docs/pull/2868

BXMSDOC-6622 Align DMN builtin function document to resolve minor diff

---

doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-ldap-proc.adoc

* Setting LDAP failover server
* SME review
* SME review fix
* peer review

[BXMSDOC-6453] Setting LDAP failover server - 7.44.x

---

doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-ldap-proc.adoc

* Setting LDAP failover server
* SME review
* SME review fix
* peer review

[BXMSDOC-6453] Setting LDAP failover server 

---

README.md

@sterobin you might want to re-trigger under "Actions" tab in this kie-docs repo, the workflow for the `master-kogito` branch manually (I cannot do it myself since I have no gatekeeper or admin roles)

BXMSDOC-6539 status badge on root README document

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

… (#125)
* Unmanaged immutable KIE server environment in operator
* RWX prereq correction for operator
* controller strategy clarification in operator
* Clarifications for immutable in operator
* add links for configuring immutable on operator
* sanity check

[BXMSDOC-6632] Immutable KIE server and startup strategy changes for operator - master

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

… (#125)
* Unmanaged immutable KIE server environment in operator
* RWX prereq correction for operator
* controller strategy clarification in operator
* Clarifications for immutable in operator
* add links for configuring immutable on operator
* sanity check

[BXMSDOC-6632] Immutable KIE server and startup strategy changes for operator - 7.44.x

---

doc-content/kogito-docs/src/main/asciidoc/configuration/con-trusty-service.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/ref-kogito-app-examples.adoc
doc-content/kogito-docs/src/main/asciidoc/dmn/proc-audit-console-usage.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/0.16.0/ref-kogito-rn-new-features.adoc

@r00ta Ready for your review. @danielezonca @gitgabrio FYI
Links:
* [Jira](https://issues.redhat.com/browse/BXMSDOC-6633)
* [Example applications with Kogito services](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6633_COMM/#ref-kogito-app-examples_kogito-creating-running) - Decided to better organize as well, see specifically the Trusty section.
* [Kogito Trusty Service](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6633_COMM/#con-trusty-service_kogito-configuring) - Added the examples to the end of this and another similar section
* [Release note](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6633_COMM/#_kogito_supporting_services_2)

BXMSDOC-6633: Update trusty service examples.

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-con.adoc

Update doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-con.adoc

[RPHAM-3158] Updating documentation

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/0.16.0/ref-kogito-rn-known-issues.adoc

Add information requirements known issue into the `0.16.0/ref-kogito-rn-known-issues.adoc`.

KOGITO-3572: [DMN Designer] Multiple DRDs support - Add information requirements known issue into the documentation

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-authorization-proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-con.adoc
doc-content/enterprise-only/springboot/bus-app-security-disabling-proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc

[BXMSDOC-6474](https://issues.redhat.com/browse/BXMSDOC-6474)

BXMSDOC-6474 master Configuring Spring Boot Security

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-authorization-proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-con.adoc
doc-content/enterprise-only/springboot/bus-app-security-disabling-proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc

[BXMSDOC-6474](https://issues.redhat.com/browse/BXMSDOC-6474)

BXMSDOC-6474 7.44.x Configuring Spring Boot Security

---

_artifacts/document-attributes.adoc
assemblies/assembly-ba-artificial-intelligence.adoc
doc-content/enterprise-only/ai/ai-con.adoc
titles-enterprise/designing-architecture/title.adoc

[BXMSDOC-6514](https://issues.redhat.com/browse/BXMSDOC-6514)

BXMSDOC-6514 master AI intro section

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/springboot/bus-app-config-data-source_proc.adoc
doc-content/enterprise-only/springboot/bus-app-config-jpa_proc.adoc
doc-content/enterprise-only/springboot/bus-app-upgrade-proc.adoc

[BXMSDOC-6607](https://issues.redhat.com/browse/BXMSDOC-6607)
HTML Draft
http://file.ork.redhat.com/~emmurphy/BXMSDOC-6607-pam/#bus-app-config-data-source_business-applications

BXMSDOC-6607 Provide alternative to oid column in Postgres

---

doc-content/enterprise-only/installation/assembly_installing-on-eap-deployable.adoc
doc-content/enterprise-only/installation/install-download-proc.adoc
doc-content/enterprise-only/installation/install-options-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6427
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6427DM/#install-download-proc_install-on-eap
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6427PAM/#install-download-proc_install-on-eap
Pull request: https://github.com/michelehaglund/kie-docs/pull/164

Upstream PR - BXMSDOC-6427 to Master - Removed SSH sentence - confusing readers

---

doc-content/enterprise-only/installation/assembly_installing-on-eap-deployable.adoc
doc-content/enterprise-only/installation/install-download-proc.adoc
doc-content/enterprise-only/installation/install-options-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6427
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6427DM/#install-download-proc_install-on-eap
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6427PAM/#install-download-proc_install-on-eap
Pull request: michelehaglund#164

Upstream PR - BXMSDOC-6427-7.39.x to 7.39.x - Removed SSH sentence - confusing readers

---

doc-content/enterprise-only/installation/assembly_installing-on-eap-deployable.adoc
doc-content/enterprise-only/installation/install-download-proc.adoc
doc-content/enterprise-only/installation/install-options-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6427
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6427DM/#install-download-proc_install-on-eap
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6427PAM/#install-download-proc_install-on-eap
Pull request: michelehaglund#164

Upstream PR - BXMSDOC-6427-7.44.x to 7.44.x - Removed SSH sentence - confusing readers

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/fuse/installing-on-fuse-eap-proc.adoc

* BXMSDOC-6489-master: Add FUSE_VERSION attribute, and update Fuse versions and links
* BXMSDOC-6489-master: Adopt feedback to update note regarding Fuse integration.
* BXMSDOC-6489-master: Adopt peer review feedback

BXMSDOC-6489-master: Add FUSE_VERSION attribute, and update Fuse versions and links

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/fuse/installing-on-fuse-eap-proc.adoc

* BXMSDOC-6489-7.44.x: Add FUSE_VERSION attribute, and update Fuse versions and links
* BXMSDOC-6489-7.44.x: Adopt feedback to update note regarding Fuse integration.
* BXMSDOC-6489-7.44.x: Adopt peer review feedback

BXMSDOC-6489-7.44.x: Add FUSE_VERSION attribute, and update Fuse versions and links

---

assemblies/assembly-clustering-eap.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/testing-clustering-environment-proc.adoc

* BXMSDOC-6464-7.44.x: Add section on testing clustering environment
* BXMSDOC-6464-7.44.x: Adopt SME feedback
* BXMSDOC-6464-7.44.x: Adopt peer review feedback

BXMSDOC-6464-7.44.x: Add section on testing clustering environment

---

assemblies/assembly-clustering-eap.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/testing-clustering-environment-proc.adoc

* BXMSDOC-6464-master: Add section on testing clustering environment
* BXMSDOC-6464-master: Adopt SME feedback
* BXMSDOC-6464-master: Adopt peer review feedback

BXMSDOC-6464-master: Add section on testing clustering environment

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-included-models-pmml-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6719
https://issues.redhat.com/browse/RHPAM-3251
Doc previews:
Enterprise documents
[Developing Decision Services in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6719-RHPAM/#dmn-included-models-pmml-proc_dmn-models)
[Developing Decision Services in Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6719-RHDM/#dmn-included-models-pmml-proc_dmn-models)
Community document
[Drools](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6719-DROOLS/#dmn-included-models-pmml-proc_dmn-models)

Upstream 7.44.x PR for BXMSDOC-6719: Upgraded JPMML dependency version from 1.4.9 to 1.5.1

---

doc-content/jbpm-docs/src/main/asciidoc/BAM/DashbuilderRuntime-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.44.0.Final/Release.7.44.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.44.0.Final/dashbuilder-runtime-default-page.adoc

AF-2660 docs changes for 7.44 branch.

AF-2660: Allow default pages in Dashbuilder Runtime - Update community docs

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-contextual-menu-ref.adoc

**JIRAs:** 
[Epic](https://issues.redhat.com/browse/BXMSDOC-6288)
[Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6290)
[VIII. Testing a decision service using test scenarios-RHPAM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6288-RHPAM-TS/#test-designer-contextual-menu-ref)
[VIII. Testing a decision service using test scenarios-RHPAM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6288-RHDM-TS/#test-designer-contextual-menu-ref)
In **Table 61.1. Contextual menu options**, replaced & with comma.

Upstream master PR for BXMSDOC-6288: Update the RHPAM/RHDM test scenario document.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-contextual-menu-ref.adoc

**JIRAs:** 
[Epic](https://issues.redhat.com/browse/BXMSDOC-6288)
[Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6290)
[VIII. Testing a decision service using test scenarios-RHPAM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6288-RHPAM-TS/#test-designer-contextual-menu-ref)
[VIII. Testing a decision service using test scenarios-RHPAM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6288-RHDM-TS/#test-designer-contextual-menu-ref)
In **Table 61.1. Contextual menu options**, replaced & with comma.

Upstream 7.44.x PR for BXMSDOC-6288: Update the RHPAM/RHDM test scenario document.

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/springboot/audit-replication-parameters-ref.adoc
doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc
doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc
doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc
doc-content/enterprise-only/springboot/online-maven-configure-proc.adoc
doc-content/enterprise-only/springboot/spring-boot-jms-audit-proc.adoc

WIP: BXMSDOC-6257 Spring Boot overall QE review

BXMSDOC-6257 7.44.x Spring Boot overall QE review

---

assemblies/assembly-interacting-with-processes.adoc
doc-content/enterprise-only/processes/configuring-emails-in-task-notification-proc.adoc

**JIRAs:**
[Epic](https://issues.redhat.com/browse/BXMSDOC-6324)
[Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6596)
**Doc preview:**
[II. Interacting with processes and tasks](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6596-RHPAM-EmailTaskNotification/#configuring-emails-in-task-notification-proc)
Please check chapter **16. Configuring emails in task notification** in the II. Interacting with processes and tasks document.

Upstream master PR for BXMSDOC-6596: Document introduction of emails in Tasks notifications based on BAPL-1595, BAPL-1684.

---

assemblies/assembly-interacting-with-processes.adoc
doc-content/enterprise-only/processes/configuring-emails-in-task-notification-proc.adoc

**JIRAs:**
[Epic](https://issues.redhat.com/browse/BXMSDOC-6324)
[Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6596)
**Doc preview:**
[II. Interacting with processes and tasks](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6596-RHPAM-EmailTaskNotification/#configuring-emails-in-task-notification-proc)
Please check chapter **16. Configuring emails in task notification** in the II. Interacting with processes and tasks document.

Upstream 7.44.x PR for BXMSDOC-6596: Document introduction of emails in Tasks notifications based on BAPL-1595, BAPL-1684.

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-embedded-proc.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-properties-ref.adoc

https://issues.redhat.com/browse/BXMSDOC-6778
I am about to follow-up on https://issues.redhat.com/browse/RHPAM-3226 to further explain this PR and the proposal doc change it contains.

BXMSDOC-6778 DMN runtime listener property detailing configuration

---

_artifacts/document-attributes.adoc
titles-enterprise/integrating/title.adoc

Add and update the following variables: 
* Red Hat Single Sign-On 
* Red Hat AMQ 7.7
* Red Hat AMQ Streams 1.5
* JWS 5.4
* Data Grid 7.3.6
Remove Entando and Policy assembles from the repo.

Upstream 7.44.x PR for BXMSDOC-6784: Update document-attributes.adoc file

---

_artifacts/document-attributes.adoc
titles-enterprise/integrating/title.adoc

Add and update the following variables: 
* Red Hat Single Sign-On 
* Red Hat AMQ 7.7
* Red Hat AMQ Streams 1.5
* JWS 5.4
* Data Grid 7.3.6
Remove Entando and Policy assembles from the repo.

Upsteam Master PR2 for BXMSDOC-6784: Update document-attributes.adoc file

---

_artifacts/snip-conscious-language.adoc
assemblies/assembly-getting-started-decision-services.adoc
titles-enterprise/deploying-and-managing-services/title.adoc
titles-enterprise/deploying-on-openshift/title.adoc
titles-enterprise/designing-architecture/title.adoc
titles-enterprise/developing-decision-services/title.adoc
titles-enterprise/developing-process-services/title.adoc
titles-enterprise/developing-solvers/title.adoc
titles-enterprise/getting-started/title.adoc
titles-enterprise/installing-and-configuring/title.adoc
titles-enterprise/integrating/title.adoc
titles-enterprise/managing-settings/title.adoc
titles-enterprise/release-notes/title.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6680
Rendered output is listed in https://issues.redhat.com/browse/BXMSDOC-6680
Pull request: https://github.com/michelehaglund/kie-docs/pull/166

Upstream PR BXMSDOC-6680-7.44.x to 7.44.x Added Conscious language note to all title docs

---

doc-content/enterprise-only/ai/ai-credit-card-con.adoc

BXMSDOC-6517 conditionalized part of credit card use case example

BXMSDOC-6517 7.44.x added PAM conditions to AI doc

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

* BXMSDOC-6302-master: Add note regarding Postgres OID and BYTEA based schema
* BXMSDOC-6302-master: Minor correction

BXMSDOC-6302-master: Add note regarding Postgres OID and BYTEA based schema

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

* BXMSDOC-6302-7.44.x: Add note regarding Postgres OID and BYTEA based schema
* BXMSDOC-6302-7.44.x: Minor correction

BXMSDOC-6302-7.44.x: Add note regarding Postgres OID and BYTEA based schema

---

_artifacts/snip-conscious-language.adoc
titles-enterprise/release-notes/title.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6680
Rendered output is listed in https://issues.redhat.com/browse/BXMSDOC-6680
Pull request: michelehaglund#166

Upstream PR BXMSDOC-6680-7.44.x to upstream 7.44.x Added Conscious language note to all title docs

---

doc-content/enterprise-only/installation/assembly_installing-on-eap-deployable.adoc
doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

Updates bases on final QE input.
Original jira: https://issues.redhat.com/browse/BXMSDOC-6807
7.9 rendered output
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6807DM/#assembly-install-on-eap
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6807PAM/#assembly-install-on-eap
Pull request: https://github.com/michelehaglund/kie-docs/pull/167/files

Upstream PR BXMSDOC-6807 to Master: Installing and configuring DM/PAM on EAP 

---

doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**JIRAs:** 
- [Epic ](https://issues.redhat.com/browse/BXMSDOC-6294)
- [Release notes for Red Hat Process Automation Manager 7.9](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6794-RHPAM-7.9-RN-Final/)
- [Release notes for Red Hat Decision Manager 7.9](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6794-RHDM-7.9-RN-Final/)

Upstream master PR2 for BXMSDOC-6794: Incorporated Kris's feedback on RHPAM/RHDM 7.9 release notes.

---

doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**JIRAs:** 
- [Epic ](https://issues.redhat.com/browse/BXMSDOC-6294)
- [Release notes for Red Hat Process Automation Manager 7.9](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6794-RHPAM-7.9-RN-Final/)
- [Release notes for Red Hat Decision Manager 7.9](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6794-RHDM-7.9-RN-Final/)

Upstream 7.44.x PR2 for BXMSDOC-6794: Incorporated Kris's feedback on RHPAM/RHDM 7.9 release notes.

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc
doc-content/kogito-docs/src/main/asciidoc/dmn/ref-dmn-feel-builtin-functions.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

@hmanwani-rh Just FYI, my PR to fix missing role and resources tags, as we discussed in chat. I missed A LOT more than I realized in my migration, including the entire bpmn chapter. Embarrassing. I went through all chapters again and verified. Hopefully that's complete now. Merging.

BXMSDOC-6799b: Fix missing role and resources tags.

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Jira issue : https://issues.redhat.com/browse/KOGITO-3378

[KOGITO-3378] - Upgrade from v1alpha1 to v1beta1 CRD version

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6707
Doc preview: 
[Kogito community version](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-6707/#chap-kogito-release-notes)

BXMSDOC-6707: Updated release notes for Kogito 1.0

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

[BXMSDOC-6644] Fix documentation for operator immutable KIE server from Maven repo - 7.26.x

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

[BXMSDOC-6644] Fix documentation for operator immutable KIE server from Maven repo - 7.33.x

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

[BXMSDOC-6644] Fix documentation for operator immutable KIE server from Maven repo - 7.39.x

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

[BXMSDOC-6644] Fix documentation for operator immutable KIE server from Maven repo - 7.30.x

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

[BXMSDOC-6644] Fix documentation for operator immutable KIE server from Maven repo - 7.23.x

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* SSO_ENABLE_CORS operator
* CLarification after discussion

[BXMSDOC-6683] SSO_ENABLE_CORS operator - master

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* SSO_ENABLE_CORS operator
* CLarification after discussion

[BXMSDOC-6683] SSO_ENABLE_CORS operator - 7.44.x

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* SSO_ENABLE_CORS operator
* CLarification after discussion

[BXMSDOC-6683] SSO_ENABLE_CORS operator - 7.39.x

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

Doc preview:
[Designing business processes in Business Central 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6913-7.5-RHPAM/#setup-auto-cleanup-proc)

Upstream 7.26.x PR for BXMSDOC-6913: Updated the steps for setting up automatic cleanup job process

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

Doc preview:
[Designing business processes in Business Central 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6913-7.6-RHPAM/#setup-auto-cleanup-proc)

Upstream 7.30.x PR for BXMSDOC-6913: Updated the steps for setting up automatic cleanup job process

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

Doc preview:
[Designing business processes in Business Central 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6913-7.8-RHPAM/#setup-auto-cleanup-proc)

Upstream 7.39.x PR for BXMSDOC-6913: Updated the steps for setting up automatic cleanup job process

---

assemblies/assembly-openshift-operator.adoc
assemblies/assembly-openshift-templates.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* 7.9.1 specific cloud changes
* SME review
* Peer review

[BXMSDOC-6684] 7.9.1 specific cloud changes - master

---

assemblies/assembly-openshift-operator.adoc
assemblies/assembly-openshift-templates.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

To be merged only when 7.9.1 is released
* 7.9.1 specific cloud changes
* SME review
* Peer review

WIP: [BXMSDOC-6684] 7.9.1 specific cloud changes - 7.44.x

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

Doc preview:
[Designing business processes in Business Central 7.9](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6913-7.9-RHPAM/#setup-auto-cleanup-proc)

Upstream 7.44.x PR for BXMSDOC-6913: Updated the steps for setting up automatic cleanup job process

---

doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

Doc preview:
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6913-RHPAM/#setup-auto-cleanup-proc)

Upstream master PR2 for BXMSDOC-6913: Updated the steps for setting up automatic cleanup job process

---

doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

Doc preview:
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6913-RHPAM-7.10/#manage-log-file-proc)

Upstream 7.48.x PR for BXMSDOC-6913: Updated the steps for setting up automatic cleanup job process

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc

@hmanwani-rh may you take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-apps/pull/564
https://github.com/kiegroup/kie-docs/pull/3123

KOGITO-3894: Anonymous navigation should be allowed when auth is not enabled

---

doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.48.0.Final/ReleaseNotesWorkbench.7.48.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.48.0.Final/properties-panel-show-more-properties-for-dmn-ds-con.adoc

See: https://issues.redhat.com/browse/DROOLS-5788

[7.48.x] DROOLS-5788: [DMN Designer] Show parameters list for Decision Services - Release notes

---

doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.48.0.Final/ReleaseNotesWorkbench.7.48.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.48.0.Final/properties-panel-show-more-properties-for-dmn-ds-con.adoc

See: https://issues.redhat.com/browse/DROOLS-5788

DROOLS-5788: [DMN Designer] Show parameters list for Decision Services - Release notes

---

doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc

**JIRA**: https://issues.redhat.com/browse/DROOLS-5931
**referenced Pull Requests**: 
- https://github.com/kiegroup/drools/pull/3311
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

DROOLS-5931 DMN document with further examples decimal() built-in fn

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc

* EDB Postgres note
* peer review

[BXMSDOC-7047] EDB Postgres note - 7.48.x

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc

* EDB Postgres note
* peer review

[BXMSDOC-7047] EDB Postgres note - master

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc

* EDB Postgres note
* peer review

[BXMSDOC-7047] EDB Postgres note - 7.44.x

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc

* EDB Postgres note
* peer review

[BXMSDOC-7047] EDB Postgres note - 7.39.x

---

_artifacts/snip-conscious-language.adoc
assemblies/assembly-decision-management-architecture.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/snip-conscious-language.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/snip-conscious-language.adoc
titles-enterprise/deploying-and-managing-services/title.adoc
titles-enterprise/deploying-on-openshift/title.adoc
titles-enterprise/developing-decision-services/title.adoc
titles-enterprise/developing-process-services/title.adoc
titles-enterprise/developing-solvers/title.adoc
titles-enterprise/getting-started/title.adoc
titles-enterprise/installing-and-configuring/title.adoc
titles-enterprise/integrating/title.adoc
titles-enterprise/managing-settings/title.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7059
Rendered output links are listed in https://issues.redhat.com/browse/BXMSDOC-7059

BXMSDOC-7059 added conscious language boilerplate to all 7.10 books

---

doc-content/enterprise-only/optimizer/spring-boot-ref-download-proc.adoc

BXMSDOC-6775b master corrected optaplanner-spring-boot-school-timetabling-

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.48.0.Final/Release.7.48.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.48.0.Final/task-details-intermediate-events.adoc

See JIRA: https://issues.redhat.com/browse/JBPM-9515
Added a community release note for BAPL-1764.
Doc preview
[JBPM release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-9515-JBPM/#_jbpm_7_48)

Upstream 7.48.x PR for JBPM-9515: Added community release note for BAPL-1764

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.48.0.Final/Release.7.48.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.48.0.Final/task-details-intermediate-events.adoc

See JIRA: https://issues.redhat.com/browse/JBPM-9515
Added a community release note for BAPL-1764. 
**Doc preview**
[JBPM release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-9515-JBPM/#_jbpm_7_48)

JBPM-9515: Added community release note for BAPL-1764

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7067
Doc preview: 
[Kogito release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7067-kogito-rel-notes/#chap-kogito-release-notes)
@sterobin fyi

BXMSDOC-7067: Finalized release notes for Kogito 1.1.0

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Jira: https://issues.redhat.com/browse/KOGITO-4056
[Stetson] For Kogito 1.2, do not merge until 1.1 released.

KOGITO-4056: Task Console Custom states support

---

assemblies/assembly-install-on-eap.adoc
doc-content/enterprise-only/admin-and-config/customizing-dashbuilder-con.adoc
doc-content/enterprise-only/admin-and-config/dashbuilder-runtimes-con.adoc
doc-content/enterprise-only/admin-and-config/datasets-dashbuilder-runtimes-con.adoc
doc-content/enterprise-only/admin-and-config/installing-dashbuilder-proc.adoc

[BXMSDOC-7044](https://issues.redhat.com/browse/BXMSDOC-7044)
PAM
http://file.ork.redhat.com/~emmurphy/BXMSDOC-7044-pam/#dashbuilder-runtimes-con_install-on-eap
DM
http://file.ork.redhat.com/~emmurphy/BXMSDOC-7044-dm/#dashbuilder-runtimes-con_install-on-eap

BXMSDOC-7044 rework Dashbuilder Runtime installation

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-advanceruntimedata-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-process-con.adoc

[BXMSDOC-7031] Java process engine API changes for 7.10 - master

---

doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc

**JIRA:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6836)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-7099)
- [I. Managing and monitoring KIE Server-RHPAM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7099-MMKS-RHPAM/#controller-eap-configure-proc_execution-server)
- [I. Managing and monitoring KIE Server-RHDM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7099-MMKS-RHDM/#controller-eap-configure-proc_execution-server)

Upstream 7.48.x PR for BXMSDOC-7099: Update the managing & monitoring KIE Server document as per RHPAM/RHDM 7.10 release.

---

doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc

**JIRA:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6836)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-7099)
- [I. Managing and monitoring KIE Server-RHPAM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7099-MMKS-RHPAM/#controller-eap-configure-proc_execution-server)
- [I. Managing and monitoring KIE Server-RHDM](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7099-MMKS-RHDM/#controller-eap-configure-proc_execution-server)

Upstream master PR for BXMSDOC-7099: Update the managing & monitoring KIE Server document as per RHPAM/RHDM 7.10 release.

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/DROOLS-4461-date-picker-for-localdate.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/ReleaseNotesWorkbench.7.41.0.Final-section.adoc

[7.44.x] DROOLS-4461 Remove release note

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/DROOLS-4461-date-picker-for-localdate.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/ReleaseNotesWorkbench.7.41.0.Final-section.adoc

[7.48.x] DROOLS-4461 Remove release note

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/DROOLS-4461-date-picker-for-localdate.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.41.0.Final/ReleaseNotesWorkbench.7.41.0.Final-section.adoc

For more details see: https://issues.redhat.com/browse/DROOLS-4461

DROOLS-4461: Fix new feature announcement version

---

doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc

BXMSDOC-7142-master-kogito: Add table about DMN version support.

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-support-con.adoc

BXMSDOC-7142-7.48.x: Add table for DMN version support.

---

assemblies/assembly-clustering-eap.adoc
doc-content/enterprise-only/installation/clustering-kie-server-failover-proc.adoc
doc-content/enterprise-only/installation/clustering-ps-configure-standalone_proc.adoc

[BXMSDOC-7090](https://issues.redhat.com/browse/BXMSDOC-7090)

BXMSDOC-7090 7.48.x Fail-over of a RUNNING job in kie-server executor

---

assemblies/assembly-clustering-eap.adoc
doc-content/enterprise-only/installation/clustering-kie-server-failover-proc.adoc
doc-content/enterprise-only/installation/clustering-ps-configure-standalone_proc.adoc

[BXMSDOC-7090](https://issues.redhat.com/browse/BXMSDOC-7090)

BXMSDOC-7090 master Fail-over of a RUNNING job in kie-server executor

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/springboot/spring-boot-persistence-proc.adoc

[BXMSDOC-7038](https://issues.redhat.com/browse/BXMSDOC-7038)

BXMSDOC-7038 master Spring Boot: Spring Boot - Multiple Data Sources and Pluggable Variable Persistence

---

assemblies/assembly-patching-and-upgrading.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/installation/product-versioning-con.adoc

[BXMSDOC-6908](https://issues.redhat.com/browse/BXMSDOC-6908)

BXMSDOC-6908 7.48.x Patching and upgrading DM/PAM 7.10

---

assemblies/assembly-patching-and-upgrading.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/installation/product-versioning-con.adoc

[BXMSDOC-6908](https://issues.redhat.com/browse/BXMSDOC-6908)

BXMSDOC-6908 master Patching and upgrading DM/PAM 7.10

---

doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-environment-set-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-install-proc.adoc
doc-content/enterprise-only/websphere/was-controller-classloader-proc.adoc
doc-content/enterprise-only/websphere/was-jms-activation-proc.adoc
doc-content/enterprise-only/websphere/was-jms-factory-create-proc.adoc
doc-content/enterprise-only/websphere/was-jms-queues-create-proc.adoc
doc-content/enterprise-only/websphere/was-ks-classloader-proc.adoc
doc-content/enterprise-only/websphere/was-security-set-proc.adoc

[BXMSDOC-6572](https://issues.redhat.com/browse/BXMSDOC-6572)

BXMSDOC-6572 7.48.x Conscious language installation docs

---

doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-frontend-proc.adoc
doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-environment-set-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-install-proc.adoc
doc-content/enterprise-only/websphere/was-controller-classloader-proc.adoc
doc-content/enterprise-only/websphere/was-jms-activation-proc.adoc
doc-content/enterprise-only/websphere/was-jms-factory-create-proc.adoc
doc-content/enterprise-only/websphere/was-jms-queues-create-proc.adoc
doc-content/enterprise-only/websphere/was-ks-classloader-proc.adoc
doc-content/enterprise-only/websphere/was-security-set-proc.adoc

Removed master, slave, black, white from non-code text in the install guide.
[BXMSDOC-6572](https://issues.redhat.com/browse/BXMSDOC-6572)
[RHPAM](http://file.ork.redhat.com/~emmurphy/BXMSDOC-6572-pam/)
[DM](http://file.ork.redhat.com/~emmurphy/BXMSDOC-6572-dm/ )

BXMSDOC-6572 Conscious language (Install-clustering)

---

_artifacts/document-attributes.adoc
assemblies/assembly-install-on-jws.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/installation/securing-passwords-eap-proc.adoc
doc-content/enterprise-only/installation/securing-passwords-jws-proc.adoc

BXMSDOC-7128 updated with QE comments - JWS

BXMSDOC-7128 7.48.x QE review JWS install

---

assemblies/assembly-integrating-fuse.adoc

[BXMSDOC-7111] note that Fuse integration on Spring Boot not supported - master

---

assemblies/assembly-integrating-fuse.adoc

[BXMSDOC-7111] note that Fuse integration on Spring Boot not supported - 7.48.x

---

assemblies/assembly-integrating-fuse.adoc

[BXMSDOC-7111] note that Fuse integration on Spring Boot not supported - 7.44.x

---

assemblies/assembly_integrating-fuse/main.adoc

[BXMSDOC-7111] note that Fuse integration on Spring Boot not supported - 7.33.x

---

assemblies/assembly_integrating-fuse/main.adoc

[BXMSDOC-7111] note that Fuse integration on Spring Boot not supported - 7.39.x

---

assemblies/assembly_integrating-fuse/main.adoc

[BXMSDOC-7111] note that Fuse integration on Spring Boot not supported - 7.30.x

---

doc-content/enterprise-only/installation/eap-ba-dm-run-proc.adoc
doc-content/enterprise-only/installation/installing-con.adoc

WIP: BXMSDOC-7127 QE review EAP and JWS

BXMSDOC-7127 7.48.x JWS and EAP QE review

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc

Ref: https://issues.redhat.com/browse/BXMSDOC-7115
https://github.com/kiegroup/kogito-examples/pull/539

BXMSDOC-7115 Swagger UI and OAS URLs revision following code change

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7197
Doc previews:
[Kogito release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7197-KOGITO-release-notes/#_additional_properties_for_decision_service_node)

BXMSDOC-7197: Added release note related to decision service properties

---

doc-content/enterprise-only/getting-started/assets-types-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7177

Upstream master PR for BXMSDOC-7177: Fixed a link after sanity check for Managing assets doc

---

doc-content/enterprise-only/getting-started/assets-types-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7177

Upstream 7.48.x PR for BXMSDOC-7177: Fixed a link after sanity check for Managing assets doc

---

_artifacts/document-attributes.adoc
assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/con-dashbuilder-standalone.adoc
doc-content/enterprise-only/openshift/proc-dashbuilder-standalone.adoc
doc-content/enterprise-only/openshift/ref-custom-resource-parameters.adoc

* BXMSDOC-6988-master: Add Dashbuilder standalone section
* BXMSDOC-6988-master: Adopt peer review feedback
* BXMSDOC-6988-master: Add link to Dashbuilder runtimes and correct typos
* BXMSDOC-6988-master: Adopt feedback
* BXMSDOC-6988-master: Adopt feedback

BXMSDOC-6988-master: Add Dashbuilder standalone section

---

_artifacts/document-attributes.adoc
assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/con-dashbuilder-standalone.adoc
doc-content/enterprise-only/openshift/proc-dashbuilder-standalone.adoc
doc-content/enterprise-only/openshift/ref-custom-resource-parameters.adoc

* BXMSDOC-6988-7.48.x: Add Dashbuilder standalone section
* BXMSDOC-6988-7.48.x: Adopt peer review feedback
* BXMSDOC-6988-7.48.x: Add link to Dashbuilder runtimes and correct typos
* BXMSDOC-6988-7.48.x: Adopt feedback
* BXMSDOC-6988-7.48.x: Adopt feedback

BXMSDOC-6988-7.48.x: Add Dashbuilder standalone section

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7146
Doc preview
Community
[Kogito Documentation 1.2](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7146-KOGITO-1.2/#chap-kogito-release-notes)
@sterobin fyi

BXMSDOC-7146: Finalized release notes for Kogito 1.2

---

_artifacts/document-attributes.adoc

Updated :REBUILT:, :MAVEN_ARTIFACT_VERSION:, and 
:BOM_VERSION:

CR2-BOM-update master

---

_artifacts/document-attributes.adoc

Updated :REBUILT:, :MAVEN_ARTIFACT_VERSION:, and 
:BOM_VERSION:

CR2-BOM-update-7.48x

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

See: https://issues.redhat.com/browse/KOGITO-2317
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
[Stetson]: Pending above task to be resolved. This is for 1.3+.

[KOGITO-2317] - Unify Kogito Quarkus and Spring Images

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

* Added information about patternfly update in release notes

Patternfly update added to relase notes

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-defining-decision-logic-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6868
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6868/#dmn-gs-defining-decision-logic-proc
Pull request: https://github.com/michelehaglund/kie-docs/pull/182

Upstream PR BXMSDOC-6868-7.44.x to 7.44.x Removed steps that are automated starting in 7.9

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6898
Doc preview
[Interacting with Red Hat Process Automation Manager Using KIE APIS 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6898-RHPAM-7.8/#knowledge-store-rest-api-requests-proc_kie-apis)

Upstream 7.39.x PR for BXMSDOC-6898: Added accept-language as HTTP Header for REST API

---

doc-content/shared-kie-docs/src/main/asciidoc/GettingInvolved-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServerTaskAssigning/Examples-section.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6575

Upstream master PR for BXMSDOC-6575: Searched for master, slave, blacklist, and whitelist in the content and removed it

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.5
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.5/#runtime-commands-samples-ref_kie-apis)

Upstream 7.26.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.2/#runtime-commands-samples-ref_kie-apis)

Upstream 7.14.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6898
Doc preview
[Interacting with Red Hat Process Automation Manager Using KIE APIS 7.9](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6898-RHPAM-7.9/#knowledge-store-rest-api-requests-proc_kie-apis)

Upstream 7.44.x PR for BXMSDOC-6898: Added accept-language as HTTP Header for REST API

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
**Interacting with Red Hat Process Automation Manager using KIE APIs**
[24.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM/#runtime-commands-samples-ref_kie-apis)
**Interacting with Red Hat Decision Manager using KIE APIs**
[24.1. Sample runtime commands in Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHDM/#runtime-commands-samples-ref_kie-apis)

Upstream master PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Jira issue : https://issues.redhat.com/browse/KOGITO-4555

[KOGITO-4555] - Wrong Image name syntax in Kogito doc

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-780-fixed-issues-ref.adoc

Issue: https://issues.redhat.com/browse/RHPAM-2796
Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-7304
Doc preview: [Release notes for Red Hat Process Automation Manager 7.8](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7304-RHPAM-7.8-RN/#process_engine_2)
Doc impact: Please check section **7.2. Process engine** in RHPAM document.

Upstream 7.39.x PR for BXMSDOC-7304: Include RHPAM-2796 issue in 7.8 RHPAM release notes.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/TestScenarioEditor-section.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-global-settings-panel-con.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-global-settings-panel-dmn-based-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-global-settings-panel-rule-based-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-comparison-legacy-new-ref.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-coverage-report-con.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-coverage-report-dmn-based-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-coverage-report-rule-based-proc.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6749)
- [Associated JIRA](https://issues.redhat.com/browse/BXMSDOC-7056)
**Enterprise document previews:**
- [RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7056-RHPAM-TS/#test-designer-global-settings-panel-con_test-scenarios)
- [RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7056-RHDM-TS/#test-designer-global-settings-panel-con_test-scenarios)
**Drools community document preview** 
Please check the following chapters from drools doc:
- [16.12.2. Global settings for test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7056-Drools-Doc/#test-designer-global-settings-panel-con_drl-rules)
- [16.12.12. Coverage reports …

Upstream master PR for BXMSDOC-7056: Single-source and add test scenarios chapters in the upstream document.

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.7.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.11.0.Final-section.adoc

Dedicated JIRA: https://issues.redhat.com/browse/BXMSDOC-6573
- kie-docs/doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.7.0.Final-section.adoc
- kie-docs/doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.11.0.Final-section.adoc

Upstream master PR2 for BXMSDOC-6573: Searched for master, slave, blacklist, and whitelist in the RN content and removed it.

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.7.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.11.0.Final-section.adoc

Dedicated JIRA: https://issues.redhat.com/browse/BXMSDOC-6573
- kie-docs/doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.7.0.Final-section.adoc
- kie-docs/doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.11.0.Final-section.adoc

Upstream 7.48.x PR2 for BXMSDOC-6573: Searched for master, slave, blacklist, and whitelist in the RN content and removed it.

---

doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
doc-content/enterprise-only/installation/clustering-con.adoc
doc-content/enterprise-only/installation/clustering-datagrid-proc.adoc
doc-content/enterprise-only/installation/clustering-dev-con.adoc
doc-content/enterprise-only/installation/clustering-smart-router-install-proc.adoc
doc-content/enterprise-only/installation/jms-broker-configure_proc.adoc
doc-content/enterprise-only/installation/nfs-server-configure-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/testing-clustering-environment-proc.adoc

BXMSDOC-7057 Clustering holistic review

BXMSDOC-7057 7.48.x Clustering holistic review

---

assemblies/assembly-installing-kie-server-on-wls.adoc
doc-content/enterprise-only/installation/jms-activation-ref.adoc
doc-content/enterprise-only/installation/jms-factories-ref.adoc
doc-content/enterprise-only/installation/jms-queues-ref.adoc
doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
doc-content/enterprise-only/weblogic/controller-wls-was-environment-set-proc.adoc
doc-content/enterprise-only/weblogic/kie-server-wls-environment-set-proc.adoc
doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
doc-content/enterprise-only/weblogic/wls-install-start-proc.adoc
doc-content/enterprise-only/weblogic/wls-jms-create-proc.adoc
doc-content/enterprise-only/weblogic/wls-jms-factory-create-proc.adoc
doc-content/enterprise-only/weblogic/wls-jms-queues-create-proc.adoc
doc-content/enterprise-only/weblogic/wls-was-jms-configure-con.adoc
doc-content/enterprise-only/websphere/controller-wls-was-verify-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-verify-proc.adoc
doc-content/enterprise-only/websphere/was-install-start-proc.adoc
doc-content/enterprise-only/websphere/was-jms-activation-proc.adoc
doc-content/enterprise-only/websphere/was-jms-bus-proc.adoc
doc-content/enterprise-only/websphere/was-jms-factory-create-proc.adoc
doc-content/enterprise-only/websphere/was-jms-queues-create-proc.adoc
doc-content/enterprise-only/websphere/was-security-set-proc.adoc
doc-content/enterprise-only/websphere/was-stop-start-proc.adoc

BXMSDOC-7026 WAS and WLS holistic review

BXMSDOC-7026 7.48.x WAS and WLS holistic review

---

assemblies/assembly-building-custom-dashboard-widgets.adoc
assemblies/assembly-configuring-central.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-components-con.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-creating-dashboard-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/Authoring-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/adding-data-sets-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/data-sets-authoring-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/data-sets-caching-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/editing-data-sets-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/refreshing-data-sets-con.adoc

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-7225
**Enterprise document previews:**
- [RHPAM-IV. Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7225-RHPAM-DataSets/#data-sets-authoring-con_building-custom-dashboard-widgets)
- [RHDM-IV. Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7225-RHDM-DataSets/#data-sets-authoring-con_building-custom-dashboard-widgets)
**Doc impact for enterprise documents:**
- Check section **54. Data sets authoring** in RHPAM doc
- Check section **48. Data sets authoring** in RHDM doc (Same as RHPAM)
**Community document previews:**
- [Drools document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7225-Drools/#data-sets-authoring-con_kie-apis)
- [jBPM …

Upstream master PR for BXMSDOC-7225: Single-source and add "Data sets authoring" chapter in the upstream documents.

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/KOGITO-3858
Kogito doc preview:
[Kogito 1.4.0 release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-3858/#_kogito_runtimes)

KOGITO-3858: Added release notes for error handling feature in Kogito

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7243
Doc preview of Kogito 1.4.0 release notes:
[Kogito documentation for 1.4.0](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7243-KOGITO-release-notes/#chap-kogito-release-notes)

BXMSDOC-7243: Finalized release notes for Kogito 1.4.0

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Jira issue : https://issues.redhat.com/browse/KOGITO-4678

[KOGITO-4678] - Rename kogito-cloud-operator to kogito-operator

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7409

BXMSDOC-7409: Incorporated suggestions from BA Peer review workshop

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.11.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.11.x to 7.11.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.48.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.48.x to 7.48.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.14.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.14.x to 7.14.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.18.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.18.x to 7.18.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.23.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.23.x to 7.23.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.26.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.26.x to 7.26.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.30.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.30.x to 7.30.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.33.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.33.x to 7.33.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.39.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.39.x to 7.39.x Investigate: Group permission resolution in Business Central

---

doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-1259-7.44.x/#business-central-settings-changing-permissions-proc_configuring-central

Upstream PR: BXMSDOC-1259-7.44.x to 7.44.x Investigate: Group permission resolution in Business Central

---

doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc

ref: https://github.com/kiegroup/drools/pull/3483
https://issues.redhat.com/browse/DROOLS-6233

DROOLS-6233 DMN amend wording in comment

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-7.10.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.10.1-known-issues-ref.adoc

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-7418
**Doc preview links:**
- [Release notes for Red Hat Process Automation Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7418-RHPAM-Release/#rn-7.10.1-known-issues-ref)
- [Release notes for Red Hat Decision Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7418-RHDM-Release/#business_central_4)
- Please check **chapters 9 and 10** in the RHPAM document.
- Please check **chapters 9 and 10** in the RHDM document.

Upstream master PR for BXMSDOC-7418: Document 7.10.1 patch RHPAM/RHDM release notes.

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-7.10.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.10.1-known-issues-ref.adoc

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-7418
**Doc preview links:**
- [Release notes for Red Hat Process Automation Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7418-RHPAM-Release/#rn-7.10.1-known-issues-ref)
- [Release notes for Red Hat Decision Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7418-RHDM-Release/#business_central_4)
- Please check **chapters 9 and 10** in the RHPAM document.
- Please check **chapters 9 and 10** in the RHDM document.

Upstream 7.48.x PR for BXMSDOC-7418: Document 7.10.1 patch RHPAM/RHDM release notes.

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/appe-process-elements.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/RunApplication-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithCases-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithHanldersAndListeners-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithJPA-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithProcesses-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/ElasticSearchBusinessApp-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/JMSBusinessApp-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/Services-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/10MinWorkbench-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/FAQ-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Setup-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Integration/CDI-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.1.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.3.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.10.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.14.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.8.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/TaskService/TaskEscalationsAndNotifications-section.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5977_COMM_7.33.x/
Pull request: https://github.com/michelehaglund/kie-docs/pull/187

Upstream PR BXMSDOC-5977-7.33.x to 7.33.x Changed instances of jbpm-console to business-central

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/deployment-synchronization-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/FAQ-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Integration/CDI-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.1.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.3.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.10.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.14.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.8.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5977_COMM_7.44.x/
Pull request: michelehaglund#187

Upstream PR BXMSDOC-5977-7.44.x to 7.44.x Changed instances of jbpm-console to business-central

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/deployment-synchronization-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/FAQ-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.1.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.3.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.10.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.14.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.8.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5977_COMM_7.48.x/
Pull request: michelehaglund#187

Upstream PR BXMSDOC-5977-7.48.x to 7.48.x Changed instances of jbpm-console to business-central

---

doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.52.0.Final/ReleaseNotesWorkbench.7.52.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.52.0.Final/literal-boxed-expressions-have-better-suggestions-con.adoc

See https://issues.redhat.com/browse/KOGITO-4239

KOGITO-4239: [DMN Designer] IntelliSense service - Documentation (release notes)

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/KOGITO-4239
Added release note entry for IntelliSense service in Kogito. 
Following is the doc preview of Kogito documentation
[Kogito Documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4239/#_kogito_tooling)

KOGITO-4239: Added release note for InteliiSense service

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/deployment-synchronization-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/FAQ-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.1.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.3.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5977_COMM_New/
Pull request: https://github.com/michelehaglund/kie-docs/pull/183

Upstream PR BXMSDOC-5977-master-final to Master - jbpm-console url is no longer applicable for jbpm

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/deployment-synchronization-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/FAQ-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.1.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.3.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc

Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5977_COMM_7.52.x/
Pull request: michelehaglund#183

Upstream PR BXMSDOC-5977-master-7.52.x to 7.52.x - jbpm-console url is no longer applicable for jbpm

---

assemblies/assembly-building-custom-dashboard-widgets.adoc
titles-enterprise/deploying-and-managing-services/title.adoc

BMXSDOC-7568 removed Dashbuilder from Managing Settings

BXMSDOC-7568 7.52.x

---

doc-content/enterprise-only/employee-rostering/optashift-ER-building-IntelliJ-IDEA-proc.adoc
doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-db-proc.adoc
doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-proc.adoc
doc-content/enterprise-only/employee-rostering/optashift-ER-openshift-deploy-con.adoc
doc-content/enterprise-only/employee-rostering/optashift-ER-running-jar-proc.adoc

https://issues.redhat.com/browse/BXMSDOC-7478

BXMSDOC-7478 7.52.x Employee Rostering - Change platform to Quarkus

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

DDF JIRA: https://issues.redhat.com/browse/BXMSDOC-7468
**Doc preview link:** 
[III. Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7486-RHPAM-PIM-DDF/#process-instance-migration-installing-service-proc)
Please check section **32.1. Installing the process instance migration service** --> Step 6
I have added a new step related to the driver and classpath.

[DDF] Upstream master PR for BXMSDOC-7468: Add a content related to JDBC driver and classpath in the document.

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

DDF JIRA: https://issues.redhat.com/browse/BXMSDOC-7468
**Doc preview link:** 
[III. Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7486-RHPAM-PIM-DDF/#process-instance-migration-installing-service-proc)
Please check section **32.1. Installing the process instance migration service** --> Step 6
I have added a new step related to the driver and classpath.

[DDF] Upstream 7.52.x PR for BXMSDOC-7468: Add a content related to JDBC driver and classpath in the document.

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

DDF JIRA: https://issues.redhat.com/browse/BXMSDOC-7468
**Doc preview link:** 
[III. Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7486-RHPAM-PIM-DDF/#process-instance-migration-installing-service-proc)

[DDF] Upstream 7.48.x PR for BXMSDOC-7468: Add a content related to JDBC driver and classpath in the document.

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

DDF JIRA: https://issues.redhat.com/browse/BXMSDOC-7468
**Doc preview link:** [Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7486-RHPAM-PIM-DDF/#process-instance-migration-installing-service-proc)

[DDF] Upstream 7.44.x PR for BXMSDOC-7468: Add a content related to JDBC driver and classpath in the document.

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7406
Doc preview:
[Kogito documentation 1.5.0](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7406-KOGITO/#chap-kogito-release-notes)

BXMSDOC-7406: Finalized release notes, added release note links and added known and fixed issues got Kogito 1.5

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-4557
Doc preview:
[Kogito documentation 1.5.0](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4557/#_rest_endpoints_for_tasks_in_kogito)
[Release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4557/#_support_for_user_task_management_using_the_rest_endpoints)

KOGITO-4557: REST endpoints support for comments and attachments in user task

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.49.0.Final/Release.7.49.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.49.0.Final/kafka-custom-format.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.50.0.Final/Release.7.50.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.50.0.Final/pagination-logcleanup.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.51.0.Final/Release.7.51.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.51.0.Final/variable-data-type.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.52.0.Final/Release.7.52.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.52.0.Final/smart-router-tls.adoc

For ftirados assigned JIRAS only

7.49 to 7.52 release notes

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.53.0.Final/ReleaseNotesDrools.7.53.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.53.0.Final/secure-xstream.adoc

https://issues.redhat.com/browse/BXMSDOC-7598
Please review @hmanwani-rh @mariofusco Thanks!

[BXMSDOC-7598] Mention XStream security change in Release Notes

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Jira: https://issues.redhat.com/browse/KOGITO-4337
Description: PostgreSQL persistence support for Job Service. Build three separate artifacts for in-memory, Infinispan and PostgreSQL.

KOGITO-4337: PostgreSQL persistence support for Job Service

---

_artifacts/document-attributes.adoc
assemblies/assembly-business-optimizer-vrp.adoc
doc-content/enterprise-only/vehicle-route-planning/backend-architecture-con.adoc
doc-content/enterprise-only/vehicle-route-planning/backend-properties-ref.adoc
doc-content/enterprise-only/vehicle-route-planning/run-vrp-manually-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-auto-restart-con.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-backend-con.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-backend-config-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-backend-intellij-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-backend-logging-con.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-backend-spring-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-frontend-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-structure-con.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-troubleshooting-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-update-deployed-changes-proc.adoc

Bxmsdoc 7480 VRP - change platform to Quarkus

BXMSDOC-7480 7.52.x VRP - change platform to Quarkus

---

_artifacts/document-attributes.adoc

update-bom master Update BOM version to 00002

---

_artifacts/document-attributes.adoc

update-bom-7.52.x updated to 0002

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.18.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.23.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.26.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.30.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.33.x PR for BXMSDOC-6725: Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.39.x PR for BXMSDOC-6725: Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.44.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/enterprise-only/springboot/bus-app-configure-central-proc.adoc
doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc

* Fill gaps in self-contained JAR build for SpringBoot
* peer review 1
* SME review and more peer review
* more peer review

[BXMSDOC-7609] Fill gaps in self-contained JAR build for SpringBoot - master

---

doc-content/enterprise-only/springboot/bus-app-configure-central-proc.adoc
doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc

* Fill gaps in self-contained JAR build for SpringBoot
* peer review 1
* SME review and more peer review
* more peer review

[BXMSDOC-7609] Fill gaps in self-contained JAR build for SpringBoot - 7.44.x

---

doc-content/enterprise-only/springboot/bus-app-configure-central-proc.adoc
doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc

* Fill gaps in self-contained JAR build for SpringBoot
* peer review 1
* SME review and more peer review
* more peer review

[BXMSDOC-7609] Fill gaps in self-contained JAR build for SpringBoot - 7.52.x

---

doc-content/enterprise-only/springboot/bus-app-configure-central-proc.adoc
doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc

* Fill gaps in self-contained JAR build for SpringBoot
* peer review 1
* SME review and more peer review
* more peer review

[BXMSDOC-7609] Fill gaps in self-contained JAR build for SpringBoot - 7.48.x

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/KOGITO-4502
Doc preview:
[Kogito documentation 1.6.0](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4502/#_task_management)
[Release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4502/#_support_for_task_management_rest_endpoints)

KOGITO-4502: Task management REST endpoints in Kogito

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

see JIRA: https://issues.redhat.com/browse/BXMSDOC-7496
Doc preview:
[Kogito documentation 1.6.0](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4337-revert/#chap-kogito-configuring)
[Kogito 1.6.0 release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4337-revert/#chap-kogito-release-notes)

Consolidated release notes and reverted KOGITO-4337 PR

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

**See JIRA:** https://issues.redhat.com/browse/KOGITO-4337
**Doc preview:**
[Kogito 1.7.0 documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4337-jobs-service/#con-jobs-service_kogito-configuring)
[Kogito release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-4337-jobs-service/#_support_postgresql_persistence_for_jobs_service)

Added KOGITO-4337 changes for Kogito 1.7.0 version

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.54.0.Final/ReleaseNotesDrools.7.54.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.54.0.Final/parallel-lambda-externalization.adoc

https://github.com/kiegroup/droolsjbpm-knowledge/pull/516
https://github.com/kiegroup/kie-benchmarks/pull/115
https://github.com/kiegroup/drools/pull/3591
https://github.com/kiegroup/kie-docs/pull/3539

[DROOLS-6327] Parallel Lambda Externalization 

---

assemblies/assembly-optimizer-migration-8.adoc
doc-content/jbpm-docs/src/main/asciidoc/TaskService/TaskServiceAPIs-section.adoc
titles-enterprise/developing-solvers/title.adoc

BXMSDOC-7589 7.52.x Migration OptaPlanner 7 to OptaPlanner 8

---

assemblies/assembly-integrating-elasticsearch.adoc
doc-content/jbpm-docs/src/main/asciidoc/ElasticSearch-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ElasticSearch/integration-elasticsearch-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/index.adoc
titles-enterprise/integrating/title.adoc

* Integration with ElasticSearch using KIE Server
* SME review
* peer review and final checks

[BXMSDOC-2573] Integration with ElasticSearch - master

---

assemblies/assembly-integrating-elasticsearch.adoc
doc-content/jbpm-docs/src/main/asciidoc/ElasticSearch-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ElasticSearch/integration-elasticsearch-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/index.adoc
titles-enterprise/integrating/title.adoc

* Integration with ElasticSearch using KIE Server
* SME review
* peer review and final checks

[BXMSDOC-2573] Integration with ElasticSearch - 7.52.x

---

doc-content/enterprise-only/fuse/fuse-con.adoc

* Fuse on SpringBoot note
* Update doc-content/enterprise-only/fuse/fuse-con.adoc
Co-authored-by: Toshiya Kobayashi <toshiyakobayashi@gmail.com>
* Peer review
Co-authored-by: Toshiya Kobayashi <toshiyakobayashi@gmail.com>

[BXMSDOC-7472] Fuse on SpringBoot note - 7.52.x

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.52.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-testing-test-scenario-proc.adoc

Upstream 7.48.x PR for BXMSDOC-6725 : Replaces text field with list (#1)

---

doc-content/enterprise-only/admin-and-config/configuring-smart-router-behavior-con.adoc
doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-endpoint-authentication-proc.adoc
doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc
doc-content/enterprise-only/installation/clustering-smart-router-install-proc.adoc
doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc

RHPAM draft:
http://file.ork.redhat.com/~emmurphy/BXMSDOC-7628-pam/

WIP: BXMSDOC-7628 Final QE review: Clustering

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc

RHPAM-3690 local network port conflict, note in the example docs

---

assemblies/assembly-install-on-jws.adoc
assemblies/assembly-installing-kie-server-on-was.adoc
assemblies/assembly-installing-kie-server-on-wls.adoc

BXMSDOC-7452 added maintenance note

BXMSDOC-7452 7.52.x Create support note for JWS, WAS, WLS

---

doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc

… Jar; fix typo (#152)
* Remove BC Monutoring connection from single JAR build for SpringBoot
* Typo fix

[BXMSDOC-7708] temporarily remove BC Monitoring config from SB single Jar - 7.48.x

---

doc-content/enterprise-only/springboot/creating-self-contained-image-proc.adoc

… Jar; fix typo (#152)
* Remove BC Monutoring connection from single JAR build for SpringBoot
* Typo fix

[BXMSDOC-7708] temporarily remove BC Monitoring config from SB single Jar - 7.44.x

---

doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7447
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7447PAM/#secrets-kie-create-proc_openshift-operator
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7447DM/#secrets-kie-create-proc_openshift-operator
Pull request: michelehaglund#191

Upstream PR: BXMSDOC-7447-7.52.x to 7.52.x DDF: Combine steps and reworded based on reader comment

---

doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7447
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7447PAM/#secrets-kie-create-proc_openshift-operator
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7447DM/#secrets-kie-create-proc_openshift-operator
Pull request: https://github.com/michelehaglund/kie-docs/pull/191

Upstream PR: BXMSDOC-7447-7.44.x to 7.44.x DDF: Combine steps and reworded based on reader comment

---

doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7447
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7447PAM/#secrets-kie-create-proc_openshift-operator
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7447DM/#secrets-kie-create-proc_openshift-operator
Pull request: michelehaglund#191

Upstream PR: BXMSDOC-7447-7.48.x to 7.48.x DDF: Combine steps and reworded based on reader comment

---

_artifacts/document-attributes.adoc
assemblies/assembly-getting-started-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-microservices-on-ocp.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-operator-deployment-options.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-probes.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-creating-maven-project.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-enable-probes-quarkus.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-enable-probes-springboot.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-binary-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-custom-image-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-file-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-git-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-openshift.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-set-custom-probes.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservice-deploy-troubleshooting.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

Prepared content for "Deploying Kogito microservices on OpenShift" for Kogito microservices assembly
See JIRA: https://issues.redhat.com/browse/BXMSDOC-7617
Epic: https://issues.redhat.com/browse/BXMSDOC-7153
Doc preview: 
[Deploying Kogito microservices on OpenShift](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7617-RHPAM/#proc-kogito-microservices-deploying-on-openshift_getting-started-kogito-microservices) in RHPAM
[Deploying Kogito microservices on OpenShift](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7617-RHDM/#proc-kogito-microservices-deploying-on-openshift_getting-started-kogito-microservices) in RHDM

Upstream master PR for BXMSDOC-7617: Content for Deploying Kogito microservices on OpenShift chapter

---

_artifacts/document-attributes.adoc
assemblies/assembly-getting-started-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-microservices-on-ocp.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-operator-deployment-options.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-probes.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-creating-maven-project.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-enable-probes-quarkus.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-enable-probes-springboot.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-binary-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-custom-image-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-file-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-git-build.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-openshift.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-set-custom-probes.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservice-deploy-troubleshooting.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

Prepared content for "Deploying Kogito microservices on OpenShift" for Kogito microservices assembly
See JIRA: https://issues.redhat.com/browse/BXMSDOC-7617
Epic: https://issues.redhat.com/browse/BXMSDOC-7153
Doc preview: 
[Deploying Kogito microservices on OpenShift](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7617-RHPAM/#proc-kogito-microservices-deploying-on-openshift_getting-started-kogito-microservices) in RHPAM
[Deploying Kogito microservices on OpenShift](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7617-RHDM/#proc-kogito-microservices-deploying-on-openshift_getting-started-kogito-microservices) in RHDM

Upstream 7.52.x PR for BXMSDOC-7617: Content for Deploying Kogito microservices on OpenShift chapter

---

_artifacts/document-attributes.adoc
assemblies/assembly-custom-tasks-and-work-item-handlers.adoc

* BXMSDOC-7482-7.52.x: Update WIH chapter to include support for standalone editors and VSCode
Also applies to BXMSDOC-7666
* BXMSDOC-7482-7.52.x: Adopt feedback

BXMSDOC-7482-7.52.x: Update WIH chapter to include support for standalone editors and VSCode

---

_artifacts/document-attributes.adoc
assemblies/assembly-custom-tasks-and-work-item-handlers.adoc

* BXMSDOC-7482-master: Update WIH chapter to include support for standalone editors and VSCode
Also applies to BXMSDOC-7666
* BXMSDOC-7482-master: Adopt feedback

BXMSDOC-7482-master: Update WIH chapter to include support for standalone editors and VSCode

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-runtime-data-con.adoc

* New Runtime Data service interface - started edit
* Runtime data desc editing and Process Instalce Migration subprocess note
* Editing runtime data interface
* SME review
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-runtime-data-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-runtime-data-con.adoc …

[BXMSDOC-7435] Process Migration and Runtime Data service update - 7.52.x

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-runtime-data-con.adoc

* New Runtime Data service interface - started edit
* Runtime data desc editing and Process Instalce Migration subprocess note
* Editing runtime data interface
* SME review
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-runtime-data-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-runtime-data-con.adoc …

[BXMSDOC-7435] Process Migration and Runtime Data service update - master

---

assemblies/assembly-process-engine.adoc
doc-content/jbpm-docs/src/main/asciidoc/Persistence-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/Persistence/transaction-retry-con.adoc

* Transaction retries - process engine doc
* fix
* Peer review

[BXMSDOC-7420] Transaction retries - process engine doc - 7.52.x

---

assemblies/assembly-process-engine.adoc
doc-content/jbpm-docs/src/main/asciidoc/Persistence-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/Persistence/transaction-retry-con.adoc

* Transaction retries - process engine doc
* fix
* Peer review

[BXMSDOC-7420] Transaction retries - process engine doc - master

---

doc-content/enterprise-only/integration/sso-central-proc.adoc
doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc

* Changes for custom client resource name for SSO
* QE review change
* Update doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
* SME review and two DDF issues
* Remove optional from Elytron
* Peer review

[BXMSDOC-7486] SSO doc changes for 7.11 - 7.52.x

---

doc-content/enterprise-only/integration/sso-central-proc.adoc
doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc

* Changes for custom client resource name for SSO
* QE review change
* Update doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
* SME review and two DDF issues
* Remove optional from Elytron
* Peer review

[BXMSDOC-7486] SSO doc changes for 7.11 - master

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/fuse/ba-engines-karaf-con.adoc
doc-content/enterprise-only/fuse/fuse-con.adoc
doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
doc-content/enterprise-only/integration/sso-kie-server-con.adoc
doc-content/enterprise-only/integration/sso-realm-proc.adoc
doc-content/enterprise-only/springboot/openshift-springboot-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/ElasticSearch/integration-elasticsearch-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-customformat-proc.adoc

* Misha sanity check 1 commit 1
* SpringBoot OCP update
* Enable SB OCP and a couple more sanity check fixes

[BXMSDOC-7749] Enable SB OCP; Misha sanity checks 1 - 7.52.x

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/fuse/ba-engines-karaf-con.adoc
doc-content/enterprise-only/fuse/fuse-con.adoc
doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
doc-content/enterprise-only/integration/sso-kie-server-con.adoc
doc-content/enterprise-only/integration/sso-realm-proc.adoc
doc-content/enterprise-only/springboot/openshift-springboot-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/ElasticSearch/integration-elasticsearch-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-customformat-proc.adoc

* Misha sanity check 1 commit 1
* SpringBoot OCP update
* Enable SB OCP and a couple more sanity check fixes

[BXMSDOC-7749] Enable SB OCP; Misha sanity checks 1 - master

---

_artifacts/document-attributes.adoc
assemblies/assembly-managing-and-monitoring-execution-server.adoc
doc-content/enterprise-only/admin-and-config/proc-configuring-kie-server-persistence.adoc

**Doc preview:**  [RHPAM-I. Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2811-RHPAM-MMKS-QE/#proc-configuring-kie-server-persistence_execution-server)
**Doc impact:** Please check **18.1. Configuring KIE Server Persistence**

Upstream master PR for BXMSDOC-2811: Document new kie-server persistence feature

---

_artifacts/document-attributes.adoc
assemblies/assembly-managing-and-monitoring-execution-server.adoc
doc-content/enterprise-only/admin-and-config/proc-configuring-kie-server-persistence.adoc

**Doc preview:**  [RHPAM-I. Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2811-RHPAM-MMKS-QE/#proc-configuring-kie-server-persistence_execution-server)
**Doc impact:** Please check **18.1. Configuring KIE Server Persistence**

Upstream 7.52.x PR for BXMSDOC-2811: Document new kie-server persistence feature

---

_artifacts/document-attributes.adoc
assemblies/assembly-managing-and-monitoring-execution-server.adoc
doc-content/enterprise-only/admin-and-config/proc-configuring-kie-server-persistence.adoc

**Doc preview:**  [RHPAM-I. Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2811-RHPAM-7.10/#proc-configuring-kie-server-persistence_execution-server)
**Doc impact:** Please check **18.1. Configuring KIE Server Persistence**

Upstream 7.48.x PR for BXMSDOC-2811: Document new kie-server persistence feature.

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/create-service-task-proc.adoc

* BXMSDOC-7657-master: Adopt feedback to pluralize
* BXMSDOC-7657-master: Adopt feedback to add Wrapped : True in data assignment

BXMSDOC-7657-master: Add note regarding wrapped parameters

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/create-service-task-proc.adoc

* BXMSDOC-7657-7.52.x: Adopt feedback to pluralize
* BXMSDOC-7657-7.52.x: Adopt feedback to add Wrapped : True in data assignment

BXMSDOC-7657-7.52.x: Add note regarding wrapped parameters

---

docs/product-administration-and-configuration-guide/src/main/asciidoc/proc-configuring-kie-server-persistence.adoc
docs/product-assembly_managing-and-monitoring-execution-server/src/main/asciidoc/main.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

Upstream 7.7.x PR for BXMSDOC-2811: Document new kie-server persistence feature.

---

_artifacts/document-attributes.adoc
assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
doc-content/enterprise-only/admin-and-config/proc-configuring-kie-server-persistence.adoc

**Doc preview:**  [RHPAM-I. Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2811-RHPAM-7.4/#proc-configuring-kie-server-persistence_execution-server)
**Doc impact:** Please check **19.1. Configuring Process Server persistence**

Upstream 7.23.x PR for BXMSDOC-2811: Document new kie-server persistence feature.

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
doc-content/enterprise-only/employee-rostering/optashift-ER-running-jar-proc.adoc
doc-content/enterprise-only/optimizer/spring-boot-ref-download-proc.adoc
doc-content/enterprise-only/optimizer/vaccination-scheduler-download-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/download-ref-imp-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-locally-airdistance-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-locally-interactive-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-locally-noninteractive-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-locally-qs-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/run-vrp-manually-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-backend-spring-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-custom-data-sets-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-frontend-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-run-openshift-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/vrp-update-deployed-changes-proc.adoc

BXMSDOC-7709 Update BOM and MAVEN ARTIFACT variables after CR2

BXMSDOC-7709 7.52.x Update BOM and MAVEN ARTIFACT variables after CR2 

---

assemblies/assembly-ba-artificial-intelligence.adoc
assemblies/assembly-getting-started-business-optimizer.adoc
assemblies/assembly-optaplanner-starter-applications.adoc
assemblies/assembly-optimizer-migration-8.adoc
assemblies/assembly-planning.adoc
doc-content/enterprise-only/optimizer/ex-cloudBalancing-ref.adoc
doc-content/enterprise-only/optimizer/ex-nQueens-ref.adoc
doc-content/enterprise-only/optimizer/examples-con.adoc
doc-content/enterprise-only/optimizer/examples-table-ref.adoc
doc-content/enterprise-only/optimizer/optaplanner-7-ref.adoc
doc-content/enterprise-only/optimizer/optimizer-running-the-examples-proc.adoc

BXMSDOC-7645 7.52.x fix new URLS

---

assemblies/assembly-custom-tasks-and-work-item-handlers.adoc
doc-content/enterprise-only/admin-and-config/custom-tasks-work-item-handler-project-customization-con.adoc
doc-content/enterprise-only/admin-and-config/manage-service-tasks-proc.adoc
doc-content/enterprise-only/release-notes/rn-7.10-known-issues-ref.adoc

* BXMSDOC-7726-7.52.x: Adopt SME feedback
* BXMSDOC-7726-7.52.x: Adopt feedback to correct naming changes and add details regarding WorkItemDefinitions

BXMSDOC-7726-7.52.x: Adopt SME feedback regarding WorkItemDefinitions

---

assemblies/assembly-custom-tasks-and-work-item-handlers.adoc
doc-content/enterprise-only/admin-and-config/custom-tasks-work-item-handler-project-customization-con.adoc
doc-content/enterprise-only/admin-and-config/manage-service-tasks-proc.adoc
doc-content/enterprise-only/release-notes/rn-7.10-known-issues-ref.adoc

* BXMSDOC-7726-master: Adopt SME feedback
* BXMSDOC-7726-master: Adopt feedback to correct naming changes and add details regarding WorkItemDefinitions

BXMSDOC-7726-master: Adopt SME feedback regarding WorkItemDefinitions

---

doc-content/enterprise-only/employee-rostering/wb-employee-rostering-example-deploying-in-central-proc.adoc
doc-content/enterprise-only/optimizer/ex-cloudBalancing-ref.adoc
doc-content/enterprise-only/optimizer/ex-vehicleRouting-ref.adoc
doc-content/enterprise-only/optimizer/examples-con.adoc
doc-content/enterprise-only/optimizer/examples-table-ref.adoc

BXMSDOC-7702 7.52.x Emily Sanity Check

---

doc-content/enterprise-only/employee-rostering/wb-employee-rostering-example-deploying-in-central-proc.adoc

BXMSDOC-7746-2 removed broken link

BXMSDOC-7746-2 7.52.x Emily sanity check

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

Doc preview
RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-7.8-RHPAM/#dmn-execution-rest-proc)

Upstream 7.39.x PR for BXMSDOC-5984: Added best practice for Kie server endpoints in DMN

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

Doc preview
RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-7.7-RHPAM/#dmn-execution-rest-proc)

Upstream 7.33.x PR for BXMSDOC-5984: Added best practice for Kie server endpoints in DMN

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

Doc preview
RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-7.10-RHPAM/#dmn-execution-rest-proc_dmn-models)

Upstream 7.48.x PR for BXMSDOC-5984: Added best practice for Kie server endpoints in DMN

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

Doc preview
RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-7.9-RHPAM/#dmn-execution-rest-proc_dmn-models)

Upstream 7.44.x PR for BXMSDOC-5984: Added best practice for Kie server endpoints in DMN

---

doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

JIRA comment: https://issues.redhat.com/browse/RHPAM-3690?focusedCommentId=16358707&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16358707

Fixed the missing note from example applications

---

doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

JIRA comment: https://issues.redhat.com/browse/RHPAM-3690?focusedCommentId=16358707&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16358707

Fixed missing note from example application

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_no_chain.yml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1390
related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1676
https://github.com/kiegroup/kie-soup/pull/211
https://github.com/kiegroup/droolsjbpm-knowledge/pull/529
https://github.com/kiegroup/drools/pull/3693
https://github.com/kiegroup/optaplanner/pull/1390
https://github.com/kiegroup/lienzo-core/pull/149
https://github.com/kiegroup/lienzo-tests/pull/122
https://github.com/kiegroup/appformer/pull/1155
https://github.com/kiegroup/kie-uberfire-extensions/pull/120
https://github.com/kiegroup/jbpm/pull/1959
https://github.com/kiegroup/kie-jpmml-integration/pull/59
https://github.com/kiegroup/droolsjbpm-integration/pull/2525 …

BXMSPROD-1390 github actions flows concurrency

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See: https://issues.redhat.com/browse/KOGITO-5299
In this PR, we are updating the ID of the artifacts based on the new structure.

[KOGITO-5299] - Update to the new addons artifacts id

---

doc-content/enterprise-only/admin-and-config/custom-tasks-work-item-definitions-con.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7803
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7803/#wid_annotation
Pull request: https://github.com/michelehaglund/kie-docs/pull/204

BXMSDOC-7803-7.52.x  to 7.52.x Fixed table format for @WidMavenDepend wid description

---

doc-content/enterprise-only/admin-and-config/custom-tasks-work-item-definitions-con.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7803
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7803/#wid_annotation
Pull request: https://github.com/michelehaglund/kie-docs/pull/204

BXMSDOC-7803-master to Master Fixed table format for @WidMavenDepend wid description

---

_artifacts/document-attributes.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-expressions-syntax-dmn-based-ref.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-expressions-syntax-rule-based-ref.adoc

**DDF JIRA:** https://issues.redhat.com/browse/BXMSDOC-7527

Upstream 7.48.x PR for BXMSDOC-7527: [DDF] Add a note about DMN based test scenarios.

---

_artifacts/document-attributes.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-intro-con.adoc

JIRA: https://issues.redhat.com/browse/BXMSDOC-7690

Upstream 7.48.x PR for BXMSDOC-7690: Remove ambiguous wording about the legacy test scenario designer

---

_artifacts/document-attributes.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-intro-con.adoc

JIRA: https://issues.redhat.com/browse/BXMSDOC-7690
- [RHPAM-VIII. Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7690-TS-RHPAM/#test-scenarios-intro-con_test-scenarios)
- [RHPAM-VIII. Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7690-TS-RHDM/#test-scenarios-intro-con_test-scenarios)
**Doc impact:** Please review and verify **62. Test scenarios** from the doc.

Upstream 7.52.x PR for BXMSDOC-7690: Remove ambiguous wording about the legacy test scenario designer

---

_artifacts/document-attributes.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-intro-con.adoc

JIRA: https://issues.redhat.com/browse/BXMSDOC-7690
- [RHPAM-VIII. Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7690-TS-RHPAM/#test-scenarios-intro-con_test-scenarios)
- [RHPAM-VIII. Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7690-TS-RHDM/#test-scenarios-intro-con_test-scenarios)
**Doc impact:** Please review and verify **62. Test scenarios** from the doc.

Upstream master PR for BXMSDOC-7690: Remove ambiguous wording about the legacy test scenario designer

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Jira: https://issues.redhat.com/browse/BXMSDOC-7791
Preview: http://file.ork.redhat.com/~bdooley/BXMSDOC-7791/

BXMSDOC-7791 Kogito release notes

---

doc-content/enterprise-only/installation/clustering-kie-server-failover-proc.adoc

* BXMSDOC-7701 Adds location of kie-server-services-jbpm-cluster.jar file
* BXMSDOC-7701 Capitalizes jar file

BXMSDOC-7701 Location of kie-server-services-jbpm-cluster.jar

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/executable-model-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7775
Added a sentence in the Executable rule models section to clarify the dependencies.

Upstream 7.48.x PR for BXMSDOC-7775: Clarified executable rule models description

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/executable-model-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7775
Added a sentence in the Executable rule models section to clarify the dependencies.

Upstream 7.52.x PR for BXMSDOC-7775: Clarified executable rule models description

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/executable-model-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7775
Added a sentence in the Executable rule models section to clarify the dependencies.

Upstream master PR for BXMSDOC-7775: Clarified executable rule models description

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-defining-decision-logic-proc.adoc

[BXMSDOC-6724](https://issues.redhat.com/browse/BXMSDOC-6724)

BXMSDOC-6724 Replace 'name' with 'expression'

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/optimizer/optaplanner-solver-con.adoc
doc-content/enterprise-only/optimizer/pinned-planning-entities-con.adoc
doc-content/enterprise-only/optimizer/vaccination-contraints-con.adoc
doc-content/enterprise-only/optimizer/vaccination-native-proc.adoc
doc-content/enterprise-only/optimizer/vaccination-scheduler-con.adoc
doc-content/enterprise-only/optimizer/vaccination-scheduler-download-proc.adoc
doc-content/enterprise-only/optimizer/vaccination-scheduler-package-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/download-ref-imp-proc.adoc

BMXSDOC-7974 removed duplicate line

BXMSDOC-7974. 7.52.x  Updated ID anchor formats

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc

This is a late PR. I forgot to update the docs when implementing [KOGITO-4456](https://issues.redhat.com/browse/KOGITO-4456). @hmanwani-rh  can we also include this one on 1.8.0?

[KOGITO-4456] Rename cloudevents kogito extensions

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-list-map-add-remove-item-proc.adoc

Referenced PRs:
- https://github.com/kiegroup/drools-wb/pull/1503
- https://github.com/kiegroup/drools/pull/3725

DROOLS-6477: Enumerate supported collections by Test Scenarios Designer

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Jira:
https://issues.redhat.com/browse/KOGITO-5538
related PR:
https://github.com/kiegroup/kogito-examples/pull/806
https://github.com/kiegroup/kogito-runtimes/pull/1458
https://github.com/kiegroup/kie-docs/pull/3804

KOGITO-5538 Make REST generation optional for each type of resource

---

.github/workflows/push.yml

**JIRA**: [BXMSPROD-1265](https://issues.redhat.com/browse/BXMSPROD-1265)
**referenced Pull Requests**:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1704
https://github.com/kiegroup/kie-jenkins-scripts/pull/1040
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/160
https://github.com/kiegroup/kie-docs/pull/3806

BXMSPROD-1265: Conscious language initiative

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7928
Doc preview:
[Kogito 1.9 release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7928-KOGITO/#chap-kogito-release-notes)
cc @briandooley

BXMSDOC-7928: Consolidated Kogito release notes and added links

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Doc preview:
http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-1.9-release-notes/#chap-kogito-release-notes

Fixed Kogito 1.9 release notes

---

doc-content/enterprise-only/fuse/fuse-con.adoc
doc-content/enterprise-only/fuse/kie-camel-con.adoc
titles-enterprise/integrating/title.adoc

This PR is WIP until the Fuse 7.9 release. Please merge and publish when Fuse 7.9 is released.

WIP: [BXMSDOC-7783] Fuse marshalling note; restore Fuse doc - 7.52.x

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-embedded-proc.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-remote-java-proc.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

JIRA reference: https://issues.redhat.com/browse/BXMSDOC-8049

BXMSDOC-8049 Remove mention of ideal compilation flag not corresponding to evidence

---

assemblies/assembly-dmn-models.adoc
doc-content/drools-docs/pom.xml
doc-content/drools-docs/src/main/asciidoc/DMN-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc

**JIRA**: https://issues.redhat.com/browse/DROOLS-6529
**referenced Pull Requests**: 
* https://github.com/kiegroup/drools/pull/3769
* https://github.com/kiegroup/kie-docs/pull/3818
* https://github.com/kiegroup/kie-docs/pull/3819

DROOLS-6529 DMN update URL refs in .md following default branch rename

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc

Updates to Knative integration. Must be merged after:
- https://github.com/kiegroup/kogito-runtimes/pull/1476

[KOGITO-5424] Update Knative sections to use the new Add-on

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc

Reverts kiegroup/kie-docs#3820
cc @briandooley @ricardozanini

Revert "[KOGITO-5424] Update Knative sections to use the new Add-on"

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Signed-off-by: Karel Suta <ksuta@redhat.com>

[KOGITO-4336] PostgreSQL persistence support for Data Index

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8035
Doc preview:
[Kogito documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8035-KOGITO/#chap-kogito-release-notes)
cc @briandooley

BXMSDOC-8035: Consolidate, review, and update link in RN for Kogito 1.10

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

This feature target Kogito 1.11.0 release

KOGITO-5569 Upgrade Infinispan

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See BAPL: https://issues.redhat.com/browse/BAPL-1936
Doc preview:
[Kogito documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-BAPL-1936-KOGITO/#chap-kogito-developing-process-services)

BAPL-1936: Added Metadata Attribute property for different nodes in BPMN

---

doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

* BXMSDOC-6808-main: Add optional verification step and link to related procedure.
* BXMSDOC-6808-main: Adopt feedback

BXMSDOC-6808-main: Add optional verification step and link to related procedure

---

doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

* BXMSDOC-6808-7.52.x: Add optional verification step and link to related procedure.
* BXMSDOC-6808-7.52.x: Adopt feedback

BXMSDOC-6808-7.52.x: Add optional verification step and link to related procedure

---

doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

* BXMSDOC-6808-7.48.x: Add optional verification step and link to related procedure.
* BXMSDOC-6808-7.48.x: Adopt feedback

BXMSDOC-6808-7.48.x: Add optional verification step and link to related procedure

---

doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

* BXMSDOC-6808-7.44.x: Add optional verification step and link to related procedure.
* BXMSDOC-6808-7.44.x: Adopt feedback

BXMSDOC-6808-7.44.x: Add optional verification step and link to related procedure

---

doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

* BXMSDOC-6808-5.59.x: Add optional verification step and link to related procedure.
* BXMSDOC-6808-5.59.x: Adopt feedback

BXMSDOC-6808-5.59.x: Add optional verification step and link to related procedure

---

_artifacts/document-attributes.adoc
assemblies/assembly-showcase-application.adoc
doc-content/enterprise-only/cases/case-management-dynamic-tasks-proc.adoc
doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/DesignBuildCases/case-management-dynamic-tasks-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/DesignBuildCases/case-management-install-and-login-to-showcase-proc.adoc

BXMSDOC-8104 Update showcase doc

BXMSDOC-8104 7.59.x Update showcase doc 

---

_artifacts/document-attributes.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/case-management-create-sub-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/case-management-creating-a-case-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/case-management-creating-manager-approval-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/case-management-designing-IT-hardware-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/case-management-it-order-sample-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/order-service-data-object-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/GettingStartedCaseManagement/survey-data-object-proc.adoc

BXMSDOC-8106 updated getting started with case management

BXMSDOC-8106 7.59.x updated getting started with case management 

---

assemblies/assembly-planner-configuration.adoc

BXMSDOC-8107 OptaPlanner Core Micrometer Metrics - BAPL-1986

BXMSDOC-8107 7.59.x  OptaPlanner Core Micrometer Metrics - BAPL-1986

---

assemblies/assembly-optaplanner-school-timetable-quarkus.adoc
doc-content/enterprise-only/optimizer/business-optimizer-test-constraints-quarkus-proc.adoc
doc-content/enterprise-only/optimizer/business-optimizer-test-solver-quarkus-proc.adoc
doc-content/enterprise-only/optimizer/planner-quarkus-database-proc.adoc

BXMSDOC-8108 updated with changes to  Quarkus community doc

BXMSDOC-8108 7.59.x updated with changes to Quarkus community doc

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.11.0.Final/ReleaseNotesKogito.1.11.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8094
Doc preview:
[Kogito 1.11 documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8094-KOGITO/#chap-kogito-release-notes)
fyi @briandooley

BXMSDOC-8094: Consolidated Kogito 1.11 release notes and added releases links

---

_artifacts/document-attributes.adoc
assemblies/assembly-configuring-central.adoc
doc-content/enterprise-only/admin-and-config/managing-business-central-archetype-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArchetypeManagement/con-business-central-archetype-management.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArchetypeManagement/proc-business-central-adding-archetype.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArchetypeManagement/proc-business-central-additional-features-archetype.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArchetypeManagement/proc-business-central-archetype-space-settings.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArchetypeManagement/proc-business-central-creating-archetype-project.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArchetypeManagement/proc-business-central-listing-archetypes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArtifactManagement/con-business-central-artifacts.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArtifactManagement/proc-business-central-download-artifacts.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArtifactManagement/proc-business-central-upload-artifacts.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ArtifactManagement/proc-business-central-view-artifacts.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Workbench-chapter.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-7792
**Community document previews:**
- [Drools document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7792-Drools-BC/#con-business-central-artifacts_kie-apis)
- [jBPM document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7792-jBPM-BC/#con-business-central-artifacts_business-processes)
**Doc impact for community documents:**
- Check **15.11. Artifact management** and **15.12. Archetype management** chapters in **Drools** doc.
- Check **13.11. Artifact management** and **13.12. Archetype management** chapters in **jBPM** doc. (Same as Drools)

Upstream master PR for BXMSDOC-7792: Single-source and add "Artifact management" and "Archetype management" chapters in the upstream community doc.

---

_artifacts/document-attributes.adoc
assemblies/assembly-configuring-central.adoc

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-8172

Upstream main PR for BXMSDOC-8172: Fix the build error for "Configuring Business Central settings and properties" doc in main and 7.59.x branch

---

_artifacts/document-attributes.adoc
assemblies/assembly-configuring-central.adoc

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-8172

Upstream 7.59.x PR for BXMSDOC-8172: Fix the build error for "Configuring Business Central settings and properties" doc in main and 7.59.x branch

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/decision-authoring-assets-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8011
Doc preview:
[Designing your decision management architecture for Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8011-RHPAM/#decision-authoring-assets-ref_decision-management-architecture)

Upstream 7.59.x PR for BXMSDOC-8011: Added reference of Kogito doc in decision architecture doc

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/decision-authoring-assets-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8011
Doc preview:
[Designing your decision management architecture for Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8011-RHPAM/#decision-authoring-assets-ref_decision-management-architecture)

Upstream main PR for BXMSDOC-8011: Added reference of Kogito doc in decision architecture doc

---

assemblies/assembly-getting-started-business-optimizer.adoc
doc-content/enterprise-only/cases/case-management-stages-con.adoc
doc-content/enterprise-only/cases/case-management-using-rules-proc.adoc
doc-content/enterprise-only/optimizer/quarkus-creating-proj-cli-proc.adoc
doc-content/enterprise-only/optimizer/quarkus-creating-proj-proc.adoc
doc-content/enterprise-only/processes/process-instance-details-con.adoc

BXMSDOC-8073 Document BAPL-1947 change steps in Quarkus GSG

BXMSDOC-8073 7.59.x Document BAPL-1947 change steps in Quarkus GSG 

---

assemblies/assembly-process-engine.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-interfaces-ref.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-registration-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-timing-con.adoc

* Event listener development
* Corrections for transactions for event listener development
* SME review change
* SME review change 2
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-timing-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc
* Peer review change

[BXMSDOC-7938] Event listener development - 7.59.x

---

assemblies/assembly-process-engine.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-interfaces-ref.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-registration-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-timing-con.adoc

* Event listener development
* Corrections for transactions for event listener development
* SME review change
* SME review change 2
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-timing-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc
* Update doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc
* Peer review change

[BXMSDOC-7938] Event listener development - main

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.12.0.Final/ReleaseNotesKogito.1.12.0.Final.adoc

https://issues.redhat.com/browse/BXMSDOC-8204
Adding docs for the new experimental ("incubation") Java APIs for custom REST endpoints
cc @hmanwani-rh @csherrar

BXMSDOC-8204 Kogito Public API: Documentation

---

assemblies/assembly-designing-business-processes.adoc
doc-content/enterprise-only/admin-and-config/custom-query-params-ref.adoc
doc-content/enterprise-only/admin-and-config/custom-query-proc.adoc
doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
doc-content/enterprise-only/admin-and-config/manual-cleanup-con.adoc
doc-content/enterprise-only/admin-and-config/setup-auto-cleanup-proc.adoc

* Custom query command
* retrieving results
* Update doc-content/enterprise-only/admin-and-config/custom-query-params-ref.adoc
* Update doc-content/enterprise-only/admin-and-config/custom-query-params-ref.adoc
* typo
* Update doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
* Update doc-content/enterprise-only/admin-and-config/manage-log-file-proc.adoc
* Update doc-content/enterprise-only/admin-and-config/custom-query-proc.adoc
* …

[BXMSDOC-7984] Custom query command - 7.59.x

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Adding missing image parameter.
Signed-off-by: Karel Suta <ksuta@redhat.com>

Fix Data index PostgreSQL custom resource

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.13.0.Final/ReleaseNotesKogito.1.13.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8152
* Added **5.12. Kogito process event add-on** section and single-sourced
* Updated **2.6.1. Kogito messaging add-on** section
* Updated names of Kogito add-ons to be consistent
* Finalized and consolidated release notes for Kogito 1.13
Doc preview:
- [5.12. Kogito process event add-on](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8152-KOGITO/#con-bpmn-process-event-addon_kogito-developing-process-services)
- [2.6.1. Kogito messaging add-on](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8152-KOGITO/#_kogito_messaging_add_on)
- [2.6. Kogito add-ons](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8152-KOGITO/#ref-kogito-add-ons_kogito-creating-running)
- [Kogito 1.13 release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8152-KOGITO/#c …

BXMSDOC-8152: Kogito add-ons, Kafka integration and 1.13 release notes

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-execution-rest-api-proc.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-embedded-process-decision-traffic-example.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/ref-rest-api-dmn-endpoints.adoc

For more details see:
- https://issues.redhat.com/browse/BXMSDOC-8240

BXMSDOC-8240 chnage DMN model namespace base uri

---

doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc

* New property for RHSSO config file
* SME review changes, removed old setting
* Typo
* Peer review

[BXMSDOC-8005] New property for RHSSO config file - main

---

doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc

* New property for RHSSO config file
* SME review changes, removed old setting
* Typo
* Peer review

[BXMSDOC-8005] New property for RHSSO config file - 7.59.x

---

doc-content/enterprise-only/fuse/fuse-con.adoc
doc-content/enterprise-only/fuse/kie-camel-con.adoc

… main (#4030)
* Remove JSON restriction for Fuse
* Remove version mismatch limitations

[BXMSDOC-7985] remove Fuse limitations that no longer apply in 7.12 - 7.59.x

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.14.0.Final/ReleaseNotesKogito.1.14.0.Final.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8319
Doc preview:
[Release notes Kogito 1.14](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8319-KOGITO/#_support_for_jq_expressions_in_serverless_workflow)

BXMSDOC-8319: Release notes for Serverless Workflow updates in Kogito

---

doc-content/enterprise-only/integration/sso-central-client-create-proc.adoc
doc-content/enterprise-only/integration/sso-kie-server-client-proc.adoc
doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc

* BXMSDOC-8207-main: Add note addressing invalid URI URL from KIECLOUD-173
* BXMSDOC-8207-main: Correct formatting of note
* BXMSDOC-8207-main: Adopt feedback to place note in two other locations
* BXMSDOC-8207-main: Correct note
* BXMSDOC-8207-main: Adopt feedback
* BXMSDOC-8207-main: Adopt feedback

BXMSDOC-8207-main: Add note addressing invalid URI URL from KIECLOUD-173

---

doc-content/enterprise-only/integration/sso-central-client-create-proc.adoc
doc-content/enterprise-only/integration/sso-kie-server-client-proc.adoc
doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc

* BXMSDOC-8207-7.59.x: Add note addressing invalid URI URL from KIECLOUD-173
* BXMSDOC-8207-7.59.x: Correct formatting of note
* BXMSDOC-8207-7.59.x: Adopt feedback to place note in two other locations
* BXMSDOC-8207-7.59.x: Correct note
* BXMSDOC-8207-7.59.x: Adopt feedback
* BXMSDOC-8207-7.59.x: Adopt feedback

BXMSDOC-8207-7.59.x: Add note addressing invalid URI URL from KIECLOUD-173

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* BXMSDOC-8080-main: Add note about CORS default and custom option
* BXMSDOC-8080-main: Adopt feedback to add bullet points and correct style

BXMSDOC-8080-main: Add note about CORS default and custom option

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* BXMSDOC-8080-7.59.x: Add note about CORS default and custom option
* BXMSDOC-8080-7.59.x: Adopt feedback to add bullet points and correct style

BXMSDOC-8080-7.59.x: Add note about CORS default and custom option

---

doc-content/jbpm-docs/src/main/asciidoc/Persistence/auditlog-datamodel-ref.adoc

* New fields in audit data model
* SME comment
* SME review

[BXMSDOC-7940] New fields in audit data model - main

---

doc-content/jbpm-docs/src/main/asciidoc/Persistence/auditlog-datamodel-ref.adoc

* New fields in audit data model
* SME comment
* SME review

[BXMSDOC-7940] New fields in audit data model - 7.59.x

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Added Kogito Operator installation content on OpenShift

BXMSDOC-8255: Kogito operator installation content

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* Startup strategy configuration in OpenShift Operator
* Update doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc

[BXMSDOC-8087] Startup strategy configuration in OpenShift Operator - main

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.14.0.Final/ReleaseNotesKogito.1.14.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8284
Consolidated release notes for Kogito 1.14
cc @briandooley

BXMSDOC-8284: Consolidated release notes for Kogito 1.14

---

doc-content/drools-docs/src/main/asciidoc/LanguageReference/drl-rules-WHEN-con.adoc

JIRA: https://issues.redhat.com/browse/BXMSDOC-8345

[BXMSDOC-8345] clarify definition of constraint bindings

---

_artifacts/document-attributes.adoc

Confirmed changes with Karel Suta.

7.12-cr3-bom-update-7.59.x

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.53.0.Final/Release.7.53.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.54.0.Final/Release.7.54.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.54.0.Final/send-task-handler.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.55.0.Final/Release.7.55.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.56.0.Final/Release.7.56.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.56.0.Final/kafka-properties.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.56.0.Final/sort-column.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.57.0.Final/Release.7.57.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.57.0.Final/bulk-claim.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.57.0.Final/kafka-properties.adoc

To be completed by @elguardian when possible.

Pending releases notes (7.53-7.57)

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_no_chain.yml

https://issues.redhat.com/browse/PLANNER-2596
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1857
* https://github.com/kiegroup/kie-soup/pull/246
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/586
* https://github.com/kiegroup/drools/pull/4087
* https://github.com/kiegroup/optaplanner/pull/1746
* https://github.com/kiegroup/lienzo-core/pull/161
* https://github.com/kiegroup/lienzo-tests/pull/134
* https://github.com/kiegroup/appformer/pull/1225
* https://github.com/kiegroup/kie-uberfire-extensions/pull/131
* https://github.com/kiegroup/jbpm/pull/2082
* https://github.com/kiegroup/droolsjbpm-integration/pull/2676
* https://github.com/kiegroup/kie-wb-playground/pull/127
* https://github.com/kiegroup/kie-wb-common/pull/3715
* …

PLANNER-2596 CI jobs: consistent naming

---

doc-content/enterprise-only/processes/process-instance-migration-con.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Overview-section.adoc

* BXMSDOC-8260-main: Update docs from Thorntail to Quarkus
* BXMSDOC-8260-main: Adopt feedback
* BXMSDOC-8260-main: Adopt feedback

BXMSDOC-8260-main: Update docs from Thorntail to Quarkus

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc

@danielezonca @hmanwani-rh 
See https://issues.redhat.com/browse/KOGITO-6311

[KOGITO-6311] Documenting grafana dashboard generation disabling properties

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.15.0.Final/ReleaseNotesKogito.1.15.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8332
Doc preview: http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8332-KOGITO/#chap-kogito-release-notes

BXMSDOC-8332: Consolidated release notes for Kogito 1.15

---

doc-content/enterprise-only/processes/process-instance-migration-con.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Overview-section.adoc

* BXMSDOC-8260-7.59.x: Update docs from Thorntail to Quarkus
* BXMSDOC-8260-7.59.x: Adopt feedback

BXMSDOC-8260-7.59.x: Update docs from Thorntail to Quarkus

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_no_chain.yml
doc-content/enterprise-only/getting-started-kogito/proc-kogito-migrate-drl-expose-ruleunits.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8362

Fixed sanity check findings on main branch

---

doc-content/enterprise-only/getting-started-kogito/proc-kogito-migrate-drl-expose-ruleunits.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8362

Fixed sanity check findings on 7.59.x branch

---

assemblies/assembly-managing-and-monitoring-execution-server.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-support-con.adoc

JIRA: https://issues.redhat.com/browse/BXMSDOC-8368

Kalyani sanity check findings on main branch

---

assemblies/assembly-managing-and-monitoring-execution-server.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-support-con.adoc

JIRA: https://issues.redhat.com/browse/BXMSDOC-8368

Kalyani sanity check findings on 7.59.x branch

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.16.0.Final/ReleaseNotesKogito.1.16.0.Final.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-6418
Added "Serverless Workflow Data Merging support for Action Data Filters" to Release Notes

KOGITO-6418 Serverless Workflow support for Event Data Filters and Data Merging for Events

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.16.0.Final/ReleaseNotesKogito.1.16.0.Final.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-6360
Added "Serverless Workflow Data Merging support for Action Data Filters" to Release Notes

KOGITO-6360 Serverless Workflow Data Merging support for Action Data Filters

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.16.0.Final/ReleaseNotesKogito.1.16.0.Final.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-3917
Added "Serverless Workflow support for State data filters" to Release Notes

KOGITO-3917 Serverless Workflow support for State data filters

---

doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
doc-content/enterprise-only/installation/nfs-server-configure-proc.adoc
doc-content/enterprise-only/installation/roles-users-con.adoc
doc-content/enterprise-only/websphere/controller-wls-was-verify-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-verify-proc.adoc

BXMSDOC-8355 Overall QE review of installation guide

BXMSDOC-8355-7.59.x  Final QE review Installation Guide

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.16.0.Final/ReleaseNotesKogito.1.16.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8359
Doc preview:
[Kogito 1.16 release notes](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8359-KOGITO/#chap-kogito-release-notes)

BXMSDOC-8359: Consolidated release notes for Kogito 1.16

---

assemblies/assembly-deploying-kogito-microservices-on-openshift.adoc
assemblies/assembly-getting-started-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-events-add-on.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-operator-deployment-configs.adoc
doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-interaction-with-kafka.adoc
doc-content/enterprise-only/getting-started-kogito/proc-implementing-message-payload-decorator.adoc

* BXMSDOC-8071-main: Add Kafka and configmap sections
* BXMSDOC-8071-main: Adopt feedback
* BXMSDOC-8071-main: Adopt feedback

BXMSDOC-8071-main: Add Kafka and configmap sections

---

_artifacts/document-attributes.adoc
assemblies/assembly-deploying-kogito-microservices-on-openshift.adoc
assemblies/assembly-getting-started-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-events-add-on.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-operator-deployment-configs.adoc
doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-interaction-with-kafka.adoc
doc-content/enterprise-only/getting-started-kogito/proc-implementing-message-payload-decorator.adoc

* BXMSDOC-8071-7.59.x: Add Kafka and configmap sections
* BXMSDOC-8071-7.59.x: Adopt feedback
* BXMSDOC-8071-7.59.x: Adopt feedback

BXMSDOC-8071-7.59.x: Add Kafka and configmap sections

---

assemblies/assembly-deploying-kogito-microservices-on-openshift.adoc
assemblies/assembly-getting-started-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-modelers.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-creating-maven-project.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
titles-enterprise/getting-started-kogito/title.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8382
BAPL - https://issues.redhat.com/browse/BAPL-2253
Doc preview:
[Getting started with Red Hat build of Kogito microservices](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8382-RHPAM-final/#assembly-getting-started-kogito-microservices)

Upstream main PR for BXMSDOC-8382: Remove Kogito process related docs updates and limit content updates to traditional components

---

doc-content/enterprise-only/installation/eap-users-create-proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc

BXMSDOC-8385 Document additional steps required after running elytron-tool.sh

BXMSDOC-8385 7.59.x Document additional steps required after running elytron-tool.sh

---

doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.54.0.Final/Release.7.54.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.56.0.Final/Release.7.56.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.57.0.Final/Release.7.57.0.Final-section.adoc

Jira https://issues.redhat.com/browse/JBPM-9993

[JBPM-9993] Docs not generated correctly

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/openshift/dashbuilder-standalone-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

* BXMSDOC-8407-main: Add optional step to set routeHostname variable
* BXMSDOC-8407-main: Adopt feedback and add RN
* BXMSDOC-8407-main: Add optional step to dashbuilder standalone

BXMSDOC-8407-main: Add optional step to set routeHostname variable

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/openshift/dashbuilder-standalone-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

* BXMSDOC-8407-7.59.x: Add optional step to set routeHostname variable
* BXMSDOC-8407-7.59.x: Adopt feedback and add RN
* BXMSDOC-8407-7.59.x: Add optional step to dashbuilder standalone

BXMSDOC-8407-7.59.x: Add optional step to set routeHostname variable

---

doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.16.0.Final/ReleaseNotesKogito.1.16.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.17.0.Final/ReleaseNotesKogito.1.17.0.Final.adoc

part of an ensemble:
- https://github.com/kiegroup/kie-docs/pull/4152
- https://github.com/kiegroup/kie-docs/pull/4153

DROOLS-6818 DMN Doc update Drools DMN Engine support DMNv1.4

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/LanguageReference/drl-rule-units-con.adoc

https://issues.redhat.com/browse/DROOLS-6822
There is a warning which tells that Rule Unit is experimental
https://docs.jboss.org/drools/release/7.64.0.Final/drools-docs/html_single/#_rule_units
But we should clearly tell it in other sections as well (Btw, these 2 are duplicate include).
https://docs.jboss.org/drools/release/7.64.0.Final/drools-docs/html_single/#drl-rule-units-con_decision-engine
https://docs.jboss.org/drools/release/7.64.0.Final/drools-docs/html_single/#drl-rule-units-con_drl-rules

[DROOLS-6822] Note Rule Unit is experimental in Drools 7

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.17.0.Final/ReleaseNotesKogito.1.17.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Tracking JIRA: https://issues.redhat.com/browse/BXMSDOC-8421
cc @csherrar

PR for BXMSDOC-8421: Consolidate, review, and update link in RN for Kogito 1.17

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.18.0.Final/ReleaseNotesKogito.1.18.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

**Tracking JIRA:** https://issues.redhat.com/browse/BXMSDOC-8433
cc @csherrar

PR for BXMSDOC-8433: Consolidate, review, and update links in RN for Kogito 1.18

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-7.12.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.12.1-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-8435
- [Release notes for Red Hat Process Automation Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8435-7.12.1-RHPAM-RN/)
- [Release notes for Red Hat Decision Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8435-RHDM-7.12.1-This/#unified_product_deliverable_and_deprecation_of_red_hat_decision_manager_distribution_files)
Added fixed issues and known issues for the 7.12.1 release.

Upstream main PR for BXMSDOC-8435: Update the release notes docs for RHPAM/RHDM 7.12.1

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.19.0.Final/ReleaseNotesKogito.1.19.0.Final.adoc

- Release notes updates for KOGITO-6740 and KOGITO-6744

KOGITO-6740: [SW] Implement Switch state eventTimeout

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**JIRAs:**
- [Dedicated doc JIRA](https://issues.redhat.com/browse/BXMSDOC-8447)
- [Engineering JIRA](https://issues.redhat.com/browse/RHPAM-4226)
- [Release notes for Red Hat Decision Manager 7.12 (Check this)](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8447-RHDM-RN-7.12-IBMPower/#red_hat_decision_manager_7_12_kogito_decision_services_support)
- Added a new **_3.1. Red Hat Decision Manager 7.12 Kogito decision services support_** section in the RHDM document.

Upstream main PR for BXMSDOC-8447: Update RHDM RN 7.12 for IBM Power Support for OpenShift 4.10

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**JIRAs:**
- [Dedicated doc JIRA](https://issues.redhat.com/browse/BXMSDOC-8447)
- [Engineering JIRA](https://issues.redhat.com/browse/RHPAM-4226)
- [Release notes for Red Hat Decision Manager 7.12 (Check this)](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8447-RHDM-RN-7.12-IBMPower/#red_hat_decision_manager_7_12_kogito_decision_services_support)
- Added a new **_3.1. Red Hat Decision Manager 7.12 Kogito decision services support_** section in the RHDM document.

Upstream 7.59.x PR for BXMSDOC-8447: Update RHDM RN 7.12 for IBM Power Support for OpenShift 4.10

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-8435
- [Release notes for Red Hat Process Automation Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8439-7.12.1-RN-RHPAM/)
- [Release notes for Red Hat Decision Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8439-7.12.1-RN-RHDM/#unified_product_deliverable_and_deprecation_of_red_hat_decision_manager_distribution_files)
Added fixed issues and known issues for the 7.12.1 release.

Upstream main branch PR for BXMSDOC-8435: Update the 7.12.1 release notes content for RHPAM/RHDM

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-8435
- [Release notes for Red Hat Process Automation Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8439-7.12.1-RN-RHPAM/)
- [Release notes for Red Hat Decision Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8439-7.12.1-RN-RHDM/#unified_product_deliverable_and_deprecation_of_red_hat_decision_manager_distribution_files)
Added fixed issues and known issues for the 7.12.1 release.

Upstream 7.59.x branch PR for BXMSDOC-8435: Update the 7.12.1 release notes content for RHPAM/RHDM

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

**Tracking JIRA:** https://issues.redhat.com/browse/BXMSDOC-8451
**Kogito 1.19 doc preview:** http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8451-Kogito-1.19/#chap-kogito-release-notes
cc @csherrar

PR for BXMSDOC-8451: Consolidate, review, and update link in RN for Kogito 1.19

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

* BXMSDOC-8424: Add Infinispan content and correct section
* BXMSDOC-8424: Adopt feedback

BXMSDOC-8424: Add Infinispan content and correct section

---

doc-content/kogito-docs/pom.xml
doc-content/pom.xml
pom.xml

the current_kie_version has to be upgraded - if not the script in the kie-docs upload will nevr find the right version

upgraded to recent KIE version

---

doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc

relative to https://github.com/kiegroup/drools/pull/4363
relative to https://github.com/kiegroup/kie-docs/pull/4211 (this PR)
relative to https://github.com/kiegroup/kie-docs/pull/4212

DROOLS-6943 DMN doc update built-in function DMNv1.4

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.21.0.Final/ReleaseNotesKogito.1.21.0.Final.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-6868
This PR depends on: https://github.com/kiegroup/kogito-runtimes/pull/2146 and https://github.com/kiegroup/kogito-runtimes/pull/2184

KOGITO-6868 Added documentation for Source Files Addon

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/openshift/configuring-image-registry-images-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-environment-deploy-assy.adoc

* BXMSDOC-8490-main: Add step about ImageRegistry and image usage for KieApp CR
* BXMSDOC-8490-main: Adopt feedback to restructure
* BXMSDOC-8490-main: Adopt feedback
* BXMSDOC-8490-main: Adopt feedback

BXMSDOC-8490-main: Add step about ImageRegistry and image usage for KieApp CR

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/openshift/configuring-image-registry-images-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-environment-deploy-assy.adoc

* BXMSDOC-8490-7.67.x: Add step about ImageRegistry and image usage for KieApp CR
* BXMSDOC-8490-7.67.x: Adopt feedback to restructure
* BXMSDOC-8490-7.67.x: Adopt feedback
* BXMSDOC-8490-7.67.x: Adopt feedback

BXMSDOC-8490-7.67.x: Add step about ImageRegistry and image usage for KieApp CR

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* Reintroduce and document the DockerImage kind for custom KIE server i… (#179)
* Reintroduce and document the DockerImage kind for custom KIE server image
* Peer review
* 7.12 specific note for DockerImage
* REBUILD

[BXMSDOC-8467] fixed 

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.22.0.Final/ReleaseNotesKogito.1.22.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

jira: https://issues.redhat.com/browse/KOGITO-7077

KOGITO-7077:Add support for collections in data index

---

doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc

https://issues.redhat.com/browse/BXMSDOC-8514

BXMSDOC-8514 fix bug in snippet

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

…… (#179)
* Reintroduce and document the DockerImage kind for custom KIE server image
* Peer review

[BXMSDOC-8467] Reintroduce and document the DockerImage kind for custom KIE server - main

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

…… (#179)
* Reintroduce and document the DockerImage kind for custom KIE server image
* Peer review

[BXMSDOC-8467] Reintroduce and document the DockerImage kind for custom KIE server - 7.67.x

---

.ci/jenkins/Jenkinsfile.upload

https://github.com/kiegroup/kie-jenkins-scripts/pull/1257
https://github.com/kiegroup/kie-docs/pull/4223

fixed path for rsync

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.23.0.Final/ReleaseNotesKogito.1.23.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2177
- https://github.com/kiegroup/kie-docs/pull/4207
- https://github.com/kiegroup/kogito-examples/pull/1240

KOGITO-7064 - Review Kogito persistence instructions adding Java serialization

---

doc-content/jbpm-docs/src/main/asciidoc/Kafka/custom-class-provide-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/integration-kafka-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-customformat-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-emit-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/message-customtask-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/message-receive-event-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/message-send-event-proc.adoc

* Quality improvements
* Convert property lists to tables for AMQ Streams intergation doc
* Peer review 1
* Build fix

[BXMSDOC-7507] Quality improvements for Kafka integration doc - main

---

doc-content/jbpm-docs/src/main/asciidoc/Kafka/custom-class-provide-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/integration-kafka-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-customformat-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-emit-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/message-customtask-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/message-receive-event-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Kafka/message-send-event-proc.adoc

* Quality improvements
* Convert property lists to tables for AMQ Streams intergation doc
* Peer review 1
* Build fix

[BXMSDOC-7507] Quality improvements for Kafka integration doc - 7.67.x

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/architecture-authoring-con.adoc
doc-content/enterprise-only/openshift/configmaps-con.adoc
doc-content/enterprise-only/openshift/githooks-prepare-proc.adoc
doc-content/enterprise-only/openshift/using-configmaps-proc.adoc

* BXMSDOC-8504-main: Add ConfigMap con section and links
* BXMSDOC-8504-main: Add ConfigMap sections
* BXMSDOC-8504-main: Adopt feedback

BXMSDOC-8504-main: Add ConfigMap sections

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/architecture-authoring-con.adoc
doc-content/enterprise-only/openshift/configmaps-con.adoc
doc-content/enterprise-only/openshift/githooks-prepare-proc.adoc
doc-content/enterprise-only/openshift/using-configmaps-proc.adoc

* BXMSDOC-8504-7.67.x: Add ConfigMap con section and links
* BXMSDOC-8504-7.67.x: Add ConfigMap sections
* BXMSDOC-8504-7.67.x: Adopt feedback

BXMSDOC-8504-7.67.x: Add ConfigMap sections

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.23.0.Final/ReleaseNotesKogito.1.23.0.Final.adoc

jiras: https://issues.redhat.com/browse/KOGITO-7235  and https://issues.redhat.com/browse/KOGITO-7219

KOGITO-7235 and KOGITO-7219. added get process source file content

---

assemblies/assembly-managing-and-monitoring-business-processes.adoc
doc-content/enterprise-only/processes/process-instance-migration-con.adoc
doc-content/enterprise-only/processes/using-keystore-vault-proc.adoc

* BXMSDOC-8505-7.67.x-blue: Add section on PIM Keystore Vault
* BXMSDOC-8505-7.67.x-blue: Adopt feedback

BXMSDOC-8505-7.67.x-blue: Add section on PIM Keystore Vault

---

assemblies/assembly-managing-and-monitoring-business-processes.adoc
doc-content/enterprise-only/processes/process-instance-migration-con.adoc
doc-content/enterprise-only/processes/using-keystore-vault-proc.adoc

* BXMSDOC-8505-main: Add section on PIM Keystore Vault
* BXMSDOC-8505-main: Adopt feedback

BXMSDOC-8505-main: Add section on PIM Keystore Vault

---

doc-content/enterprise-only/springboot/bus-app-create_proc.adoc

BXMSDOC-8518-main2 Update Spring Boot commands

BXMSDOC-8518-2 7.67.x-blue Remove start.jbpm.org

---

doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc

* BXMSDOc-8456-main: Add optional step about Decision Manager only configuration.
* BXMSDOC-8456-main: Adopt feedback

BXMSDOc-8456-main: Add optional step about Decision Manager only configuration.

---

doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc

* BXMSDOc-8456-7.67.x-blue: Add optional step about Decision Manager only configuration.
* BXMSDOC-8456-7.67.x-blue: Adopt feedback

BXMSDOC-8456-7.67.x-blue: Add optional step about Decision Manager only configuration.

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc

* BXMSDOC-8462-7.67.x-blue: Add optional step for using Secrets
* BXMSDOC-8462-7.67.x-blue: Adopt feedback

BXMSDOC-8462-7.67.x-blue: Add optional step for using Secrets

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc

* BXMSDOC-8462-main: Add optional step for using Secrets
* BXMSDOC-8462-main: Adopt feedback

BXMSDOC-8462-main: Add optional step for using Secrets

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc

* BXMSDOC-8462-7.67.x: Add optional step for using Secrets
* BXMSDOC-8462-7.67.x: Adopt feedback

BXMSDOC-8462-7.67.x: Add optional step for using Secrets

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.13-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

Epic: https://issues.redhat.com/browse/BXMSDOC-8474
Doc previews:
[Release notes for Red Hat Process Automation Manager 7.13](https://github.com/kiegroup/kie-docs/pull/4298)
[Release notes for Red Hat Decision Manager 7.13](https://github.com/kiegroup/kie-docs/pull/4298)

7.67.x-blue PR for BXMSDOC-8474: Release notes docs for RHPAM/RHDM 7.13

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.13-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Epic:** https://issues.redhat.com/browse/BXMSDOC-8474
[Release notes for Red Hat Process Automation Manager 7.13]()
[Release notes for Red Hat Decision Manager 7.13]()

main PR for BXMSDOC-8474: Release notes docs for RHPAM/RHDM 7.13

---

_artifacts/document-attributes.adoc
assemblies/assembly-clustering-eap.adoc
assemblies/assembly-hacep.adoc
assemblies/assembly-managing-and-monitoring-execution-server.adoc
assemblies/assembly-openshift-templates.adoc
assemblies/assembly-packaging-deploying.adoc
assemblies/assembly-planning.adoc
doc-content/enterprise-only/admin-and-config/maven-external-configure-proc.adoc
doc-content/enterprise-only/admin-and-config/maven-external-export-proc.adoc
doc-content/enterprise-only/installation/installing-con.adoc
doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc
doc-content/enterprise-only/openshift/dashbuilder-standalone-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/Integration/integration-java-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-deployment-options-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/prometheus-monitoring-custom-proc.adoc
titles-enterprise/deploying-on-openshift/title.adoc

Reinstate for the July 29th update

BXMSDOC-8585-blue Temporarily remove the Operator's guide from the OS title

---

doc-content/enterprise-only/release-notes/rn-7.13-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-intro-con.adoc
doc-content/enterprise-only/release-notes/rn-support-ref.adoc

Task: https://issues.redhat.com/browse/BXMSDOC-8584

PR 2 for BXMSDOC-8584: Release notes for IBM Business Automation Manager Open Editions 8.0

---

assemblies/assembly-managing-and-monitoring-execution-server.adoc
doc-content/enterprise-only/openshift/customimage-smartrouter-proc.adoc
doc-content/enterprise-only/openshift/jboss-postconfigure-proc.adoc
doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc
doc-content/enterprise-only/openshift/using-configmaps-proc.adoc

* BXMSDOC-8591-main: Correct file version to attribute
* BXMSDOC-8591-main: Correct EAP version link to attribute
* BXMSDOC-8591-main: Correct GitHub link version from ".0" to ".x"

BXMSDOC-8591-main: Sanity check for 7.13.0

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.13-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

Epic: https://issues.redhat.com/browse/BXMSDOC-8474

New upstream main PR BXMSDOC-8474: Release notes docs for RHPAM/RHDM version 7.13

---

doc-content/enterprise-only/installation/installing-con.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
modules/splitter/batch-solving-con.adoc

BXMSDOC-8593 updated after sanity check

BXMSDOC-8593 main 7.13 Sanity Checks Emily

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-7.13-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.1-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-removed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

Tracking JIRA: https://issues.redhat.com/browse/BXMSDOC-8610
Doc preview:
- [RHPAM-RN-Doc-Preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8610-RHPAM-7.13.1-RN-Updated/)
- [RHDM-RN-Doc-Preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8610-RHDM-7.13.1-RN-Updated/)
Doc impact:
Please check and verify the following sections: 
- [2.6.1. Support for exploded installation of Spring Boot business automation application](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8610-RHPAM-7.13.1-RN-This/#support_for_exploded_installation_of_spring_boot_business_automation_application)
- [5. Removed components](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8610-RHPAM-7.13.1-RN-This/#rn-removed-issues-ref)
- [9. Known issues in Red Hat Process Automation Manager …

Upstream 7.67.x PR for BXMSDOC-8610: Release notes docs for RHPAM/RHDM 7.13.1

---

doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

* BXMSDOC-8564-7.67.x-blue: Add mutual TLS optional step
* BXMSDOC-8564-7.67.x-blue: Adopt feedback to clarify sentence
* BXMSDOC-8564-7.67.x-blue: Adopt feedback

BXMSDOC-8564-7.67.x-blue: Add mutual TLS optional step

---

doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

* BXMSDOC-8564-main: Add mutual TLS optional step
* BXMSDOC-8564-main: Adopt feedback to clarify sentence
* BXMSDOC-8564-main: Adopt feedback

BXMSDOC-8564-main: Add mutual TLS optional step

---

doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

* BXMSDOC-8564-7.67.x: Add mutual TLS optional step
* BXMSDOC-8564-7.67.x: Adopt feedback to clarify sentence
* BXMSDOC-8564-7.67.x: Adopt feedback

BXMSDOC-8564-7.67.x: Add mutual TLS optional step

---

_artifacts/document-attributes.adoc
assemblies/assembly-hacep.adoc
assemblies/assembly-patching-and-upgrading.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-comparison-legacy-new-ref.adoc
doc-content/enterprise-only/fuse/fuse-con.adoc
doc-content/enterprise-only/fuse/installing-ba-fuse-karaf-maven-proc.adoc
doc-content/enterprise-only/installation/about-ba-con.adoc
doc-content/enterprise-only/installation/installer-run-cli-proc.adoc
doc-content/enterprise-only/installation/installer-run-proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/installation/product-versioning-con.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/springboot/bus-app-upgrade-proc.adoc

HTML draft:
http://file.ork.redhat.com/~emmurphy/BXMSDOC-8627/#assembly-patching-and-upgrading
Jira:
https://issues.redhat.com/browse/BXMSDOC-8627

BXMSDOC-8627-blue Update the BAMOE patching section

---

assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-BAMOE-8.0.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-BAMOE-8.0.1-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-intro-con.adoc
doc-content/enterprise-only/release-notes/rn-removed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/service-migration-con.adoc

HTML draft:
http://file.ork.redhat.com/~emmurphy/BXMSDOC-8628/
Jira:
https://issues.redhat.com/browse/BXMSDOC-8628

BXMSDOC-8638 BAMOE 8.0.1 release notes

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc

Jira: https://issues.redhat.com/browse/KOGITO-8207
PR that changes the Source Files Add-On: https://github.com/kiegroup/kogito-runtimes/pull/2600

KOGITO-8207 Updated docs to reflect changes in Source Files Add-On

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/dsl/test.sh
.gitignore
script/uploadDocs.sh

[KOGITO-8326](https://issues.redhat.com/browse/KOGITO-8326)
* https://github.com/kiegroup/kogito-pipelines/pull/734
* https://github.com/kiegroup/kie-ci/pull/1387
* https://github.com/kiegroup/kie-docs/pull/4382
* https://github.com/kiegroup/kie-docs/pull/4388

KOGITO-8326: added script for uploading kie-kogito-docs to filemgmt

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

KIE_VERSION is coming from a parameter

---

.ci/jenkins/dsl/jobs.groovy

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

renamed kie-docs upload job

---

build/release/Readme.md

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

README for kogito-docs tag

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.32.0.Final/ReleaseNotesKogito.1.32.0.Final.adoc

Depends on https://github.com/kiegroup/kogito-docs/pull/273

Use fixed version for SW links

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-postgresql-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
titles-enterprise/bigbuild/title.adoc
titles-enterprise/deploying-on-openshift/title.adoc

BXMSDOC-8648 removed relevant references to OCP 3
* link 2
* link 3 etc.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move …

BXMSDOC-8653 7.67.x baseFilter(AUTH_LDAP_BASE_FILTER) is incompatible with versions earlier than 7.12.0

---

assemblies/assembly-openshift-operator.adoc
doc-content/enterprise-only/openshift/migration-ocp3-4-postgresql-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
titles-enterprise/bigbuild/title.adoc
titles-enterprise/deploying-on-openshift/title.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8648 main Remove OpenShift 3 from product documentation and add note to release note

---

doc-content/enterprise-only/admin-and-config/custom-query-params-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8658] fix wrong table name

---

doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

BXMSDOC-8631 Highlight the supported list of kogito quickstarts
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8631 7.67.x-blue Highlight the supported list of kogito quickstarts

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.23.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.26.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.30.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.33.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.39.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only 7.44.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.48.x

---

doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

BXMSDOC-8631 Highlight the supported list of kogito quickstarts
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8631 7.67.x Highlight the supported list of kogito quickstarts

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.18.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.52.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only -7.59.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only - 7.67.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-asset-execution-options-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[BXMSDOC-8656] Condition a Smart Router reference to PAM only

---

assemblies/assembly-springboot-business-apps.adoc
doc-content/enterprise-only/optimizer/online-maven-con.adoc

BXMSDOC-8629 Need to add steps to configure maven settings.xml before starting to create spring boot based business-application projects.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the …

WIP: BXMSDOC-8629 7.67.x  Add steps to configure maven settings.xml before starting to create spring boot based business-application projects

---

_artifacts/document-attributes.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8660 updated BOM for 7.13.2

---

_artifacts/document-attributes.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Bxmsdoc 8660 b 7.67.x

---

_artifacts/document-attributes.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8660 Update BOM and Maven Artifact for BAMOE 8.0.2

---

doc-content/enterprise-only/installation/about-ba-con.adoc
doc-content/enterprise-only/installation/product-versioning-con.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8659b blue updated ENTERPRISE_VERSION_LONG

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/installation/about-ba-con.adoc
doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
doc-content/enterprise-only/release-notes/rn-7.13-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.1-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.2-known-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8662 main Update 7.13.2 release notes with relevant 8.0.2 changes

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/installation/about-ba-con.adoc
doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
doc-content/enterprise-only/release-notes/rn-7.13-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.1-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.2-known-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8662 7.67.x Update 7.13.2 release notes with relevant 8.0.2 changes

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/installing-dashbuilder-proc.adoc
doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
doc-content/enterprise-only/employee-rostering/er-deploy-script-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
doc-content/enterprise-only/installation/clustering-kie-server-failover-proc.adoc
doc-content/enterprise-only/installation/clustering-smart-router-install-proc.adoc
doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
doc-content/enterprise-only/installation/install-download-proc.adoc
doc-content/enterprise-only/migration/migration-tool-niogit-7.x-proc.adoc
doc-content/enterprise-only/migration/migration-tool-repo-7.x-proc.adoc
doc-content/enterprise-only/openshift/offline-repo-proc.adoc
doc-content/enterprise-only/optimizer/examples-download-proc.adoc
doc-content/enterprise-only/optimizer/spring-boot-ref-download-proc.adoc
doc-content/enterprise-only/optimizer/vaccination-scheduler-download-proc.adoc
doc-content/enterprise-only/springboot/download-maven-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/download-ref-imp-proc.adoc
doc-content/enterprise-only/weblogic/controller-wls-install-proc.adoc
doc-content/enterprise-only/weblogic/kie-server-wls-install-proc.adoc
doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-install-proc.adoc
doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/DesignBuildCases/case-management-install-and-login-to-showcase-proc.adoc

BXSDOC-8661 PAM and DM product and version number updates
* link 2
* link 3 etc.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming …

BXSDOC-8661 7.67.x PAM and DM product and version number updates 

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/admin-and-config/installing-dashbuilder-proc.adoc
doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
doc-content/enterprise-only/employee-rostering/er-deploy-script-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
doc-content/enterprise-only/installation/clustering-kie-server-failover-proc.adoc
doc-content/enterprise-only/installation/clustering-smart-router-install-proc.adoc
doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
doc-content/enterprise-only/installation/install-download-proc.adoc
doc-content/enterprise-only/migration/migration-tool-niogit-7.x-proc.adoc
doc-content/enterprise-only/migration/migration-tool-repo-7.x-proc.adoc
doc-content/enterprise-only/openshift/offline-repo-proc.adoc
doc-content/enterprise-only/optimizer/examples-download-proc.adoc
doc-content/enterprise-only/optimizer/spring-boot-ref-download-proc.adoc
doc-content/enterprise-only/optimizer/vaccination-scheduler-download-proc.adoc
doc-content/enterprise-only/springboot/download-maven-proc.adoc
doc-content/enterprise-only/vehicle-route-planning/download-ref-imp-proc.adoc
doc-content/enterprise-only/weblogic/controller-wls-install-proc.adoc
doc-content/enterprise-only/weblogic/kie-server-wls-install-proc.adoc
doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-install-proc.adoc
doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/DesignBuildCases/case-management-install-and-login-to-showcase-proc.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXSDOC-8661 main PAM and DM product and version number updates 

---

assemblies/assembly-managing-and-monitoring-business-processes.adoc
doc-content/enterprise-only/admin-and-config/using-MVEL-to-set-task-priority.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8484 main Update managing and monitoring business processes doc as per BAPL-2244

---

_artifacts/document-attributes.adoc
assemblies/assembly-managing-and-monitoring-business-processes.adoc
doc-content/enterprise-only/admin-and-config/using-MVEL-to-set-task-priority.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8484 7.67.x Update managing and monitoring business processes doc as per BAPL-2244

---

assemblies/assembly-managing-and-monitoring-business-processes.adoc
doc-content/enterprise-only/admin-and-config/using-MVEL-to-set-task-priority.adoc

BXMSDOC-8484 Update managing and monitoring business processes doc as per BAPL-2244
* link 2
* link 3 etc.
<details>
<summary>
</summary>
> **NOTE**: …

BXMSDOC-8484 7.67.x-blue Update managing and monitoring business processes doc as per BAPL-2244

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-creating-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-deleting-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-editing-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-executing-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-exporting-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8443 blue PIM docs incorrect

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-creating-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-deleting-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-editing-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-executing-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-exporting-plan-proc.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8443 7.67.x  PIM docs incorrect

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/processes/process-instance-migration-installing-service-proc.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8443 7.59.x  PIM docs incorrect

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

BXMSDOC-8404-7.59.x Note on bytea schema for postgresql incorrect
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8404-7.52.x Note on bytea schema for postgresql incorrect

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8404-7.44.x Note on bytea schema for postgresql incorrect

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8404-7.48.x Note on bytea schema for postgresql incorrect

---

doc-content/enterprise-only/admin-and-config/custom-query-params-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8404-7.59.x Note on bytea schema for postgresql incorrect

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

BXMSDOC-8404 main Note on bytea schema for postgresql incorrect
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8404 7.67.x Note on bytea schema for postgresql incorrect

---

doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc

BXMSDOC-8404 main Note on bytea schema for postgresql incorrect
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8404 blue Note on bytea schema for postgresql incorrect

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-rule-set-entries-ref.adoc

**Ports**:
This is a PR for 7.x kie-docs
for 8.x main -> https://github.com/kiegroup/drools/pull/4954
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7320
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to …

[7.x] [DROOLS-7320] Docs : Spreadsheet RuleSet definition "NumericDisabled"

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.35.0.Final/ReleaseNotesKogito.1.35.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

**JIRA**: [KOGITO-8674](https://issues.redhat.com/browse/KOGITO-8674)
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them …

KOGITO-8674: Update release notes for Kogito 1.35

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.36.0.Final/ReleaseNotesKogito.1.36.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Release notes for 1.36.0

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Kogito: Update Metrics path

---

doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-custom-image-build.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8680 main Add note about native builds and containerfile 

---

doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-custom-image-build.adoc

BXMSDOC-8680 Add note about native builds and containerfile
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8680 7.67.x-blue Add note about native builds and containerfile

---

doc-content/enterprise-only/getting-started-kogito/proc-kogito-microservices-deploying-on-ocp-console-custom-image-build.adoc

BXMSDOC-8680 Add note about native builds and containerfile
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8680 7.67.x Add note about native builds and containerfile 

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.39.0.Final/ReleaseNotesKogito.1.39.0.Final.adoc

Doc JIRA: https://issues.redhat.com/browse/KOGITO-9192

PR for KOGITO-9192: Prepared the RN file content for next Kogito release (1.39)

---

_artifacts/document-attributes.adoc
assemblies/assembly-decision-management-architecture.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-BAMOE-8.0.2-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-BAMOE-8.0.3-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-BAMOE-8.0.3-known-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8681 BAMOE 8.0.3 release notes

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_no_chain.yml

Related PR:
- https://github.com/kiegroup/kie-docs/pull/4475

[7.67.x][BXMSPROD-2057] Updating references to the new kie-ci actions folder

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release

[KOGITO-9406](https://issues.redhat.com/browse/KOGITO-9406)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a …

KOGITO-9406: step added for upgrading parameter

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

fixed sed command

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

updated version of release notes

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release
.ci/jenkins/dsl/jobs.groovy

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

added change of release notes number

---

doc-content/kogito-docs/pom.xml
doc-content/pom.xml
pom.xml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

bumped-up kie version

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc

Changed in https://github.com/kiegroup/kogito-runtimes/pull/1750
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Update Micrometer metrics registration

---

doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

NO-ISSUE: Drop mention of kie-tools desktop application

---

doc-content/enterprise-only/release-notes/rn-7.13.4-fixed-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8683-2 updated with SME comments

---

doc-content/enterprise-only/release-notes/rn-7.13.4-fixed-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8683-3 updated with SME comments

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.13.3-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.4-fixed-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

BXMSDOC-8685-7.14.3-main Remove issues with XSS

---

doc-content/enterprise-only/release-notes/rn-7.13.3-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.13.4-fixed-issues-ref.adoc

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

 BXMSDOC-8685-7.67.x removed XSS fixed issues 

---

.ci/jenkins/dsl/test.sh

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Update `kiegroup` repository references to `apache`
