apache/incubator-kie-docs

- kie-docs-code/pom.xml
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/DocumentationBuilderExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/DocumentationRestCallExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/DocumentationRestExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/MigrationFrom6_0To6_2ExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/jms/JmsJavaApiExamples.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/jms/SendJmsExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/objects/MyType.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/rest/RestJavaApiExamples.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/ws/WebserviceJavaApiExamples.java
- kie-docs-code/src/test/java/org/guvnor/rest/backend/documentation/GuvnorSerializationExamplesTest.java
- pom.xml
- shared/Install/Eclipse.xml
@mbiarnes Would you mind looking at this? 
Thanks!
> Changed license header

- kie-docs-code/src/main/java/org/kie/remote/client/documentation/DocumentationBuilderExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/MigrationFrom6_0To6_2ExamplesTODO.java
- kie-docs-code/src/main/java/org/kie/remote/client/documentation/ws/WebserviceJavaApiExamples.java
@mrietveld could you please take a look?
> [JBPM-4928] remove usage of deprecated RuntimeEngineFactories

- shared/Workbench/Authoring/ProjectEditor/ProjectEditor.xml
- shared/Workbench/Installation/Installation.xml
- shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.6.4.0.Final.xml
See https://issues.jboss.org/browse/BPMSPL-252
> BPMSPL-252: [GSS-RFE] Ability to check duplicate of ReleaseId (GroupId, ArtifactId and Version) with existing projects. Updates following QE feedback.

- shared/Workbench/Installation/Installation.xml
See https://issues.jboss.org/browse/GUVNOR-2418
(cherry picked from commit 5b54cd0a72f4d7e248f571bcb6fb156e9c4f50da)
Conflicts:
shared/Workbench/Installation/Installation.xml
> [6.4.x] GUVNOR-2418: Document workaround for why Workbench may not load after login

- shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.6.4.0.Final.xml
See https://bugzilla.redhat.com/show_bug.cgi?id=1320813
(cherry picked from commit 612df87ffb21ba195b8af585c5541f55455a1567)
> BZ1320813: Add Russian and Traditional Chinese to languages

- shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.6.4.0.Final.xml
See https://bugzilla.redhat.com/show_bug.cgi?id=1320813
> [6.4.x] BZ1320813: Add Russian and Traditional Chinese to languages

- jbpm-docs/src/main/docbook/en-US/ReleaseNotes/Release.6.4.0.Final.xml
(cherry picked from commit 316a30a12c72303d7d3b9d6c5c5d2bfae9e60e30)
> N&N pluggable task deadline notifications

- shared/Workbench/UserAndGroupManagement/UserAndGroupManagement.xml
Fixes from @manstis comments here https://github.com/droolsjbpm/kie-docs/pull/81/files/c298ca6a055ca668650d972b580dcade552035ec#r58670774
> Workbench - User and group management fixes.

- shared/Workbench/UserAndGroupManagement/UserAndGroupManagement.xml
Fixes from @manstis comments here https://github.com/droolsjbpm/kie-docs/pull/81/files/c298ca6a055ca668650d972b580dcade552035ec#r58670774
> [6.4.x] Workbench - User and group management fixes.

- jbpm-asciidocs/pom.xml
- jbpm-docs/pom.xml
- jbpm-docs/src/main/docbook/en-US/RemoteAPI/Java-section.xml
- pom.xml
See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/215
- https://github.com/droolsjbpm/kie-docs/pull/104
> DROOLS-1131,JBPM-5080 - docs code dependency management

- drools-docs/src/main/docbook/en-US/Workbench/AuthoringAssets/GuidedDecisionTableEditor.xml
See https://issues.jboss.org/browse/GUVNOR-2568
> GUVNOR-2568: Guided Decision Table Editor: Document BRL Fragments better; especially use of @{..} variable place-holder

- shared-asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc
@manstis Would you mind reviewing and possibly also merging? 
Thanks.
> GUVNOR-2582 : Verification & Validation: Document range checks and single hit [fixes]

- shared-asciidoc/Workbench/RemoteAPI/REST-section.adoc
I have fixed some inconsistencies in REST section of Workbench Integration chapter. Besides small corrections, there were some REST endpoints missing in both the detailed overview of REST calls and in the summary table. I have also simplified sentences where applicable in order not to be confusing.
> Fix inconsistencies in Guvnor REST API section

- shared-asciidoc/Workbench/Installation/Installation-section.adoc
- shared-asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc
https://issues.jboss.org/browse/GUVNOR-2596
Code changes:
https://github.com/droolsjbpm/drools-wb/pull/255
> GUVNOR-2596 : Verification & Validation: Property setting for disabling client side V&V

- jbpm-docs/src/main/asciidoc/TaskService-chapter.adoc
- jbpm-docs/src/main/asciidoc/TaskService/Experimental-section.adoc
- jbpm-docs/src/main/asciidoc/TaskService/TaskServiceInteraction-section.adoc
Based on a recent discussion on an e-mail list.
> jBPM: 'SubTasks' feature documentation

- drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.5.0.Final-section.adoc
Depends on droolsjbpm/drools#866 .
Including an entry for this on the release notes, as requested.
> DROOLS-1235 MBean naming rework

- drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.5.0.Final-section.adoc
Depends (and aligns) on droolsjbpm/drools#890 .
> DROOLS-1236 documentation updates N&N.

- jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
Please refer to https://github.com/droolsjbpm/jbpm/pull/589 Thanks!
> JBPM-5082: Updated the authentication configuration section for the jbpm installer.

- shared/KieServer/RestAPI-section.adoc
@mswiderski Could you please confirm that this endpoint is correct now??
> Fix invalid endpoint in Kie server REST API section

- shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc
See https://issues.jboss.org/browse/GUVNOR-2700
Code change: https://github.com/droolsjbpm/drools-wb/pull/304
> GUVNOR-2700: Guided Decision Table Editor: Add support for caching enumeration lookups

- shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.6.4.0.Final-section.adoc
See https://issues.jboss.org/browse/GUVNOR-2683
> GUVNOR-2683: Test Scenarios: Objects added into previously white listed packages are not updated.

- shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.6.4.0.Final.xml
See https://issues.jboss.org/browse/GUVNOR-2683
> [6.5.x] GUVNOR-2683: Test Scenarios: Objects added into previously white listed packages are not updated.

- docs/drools-docs/topics/ReleaseNotes/ReleaseNotesDrools.7.0.0.Final-section.adoc
Documentation update following droolsjbpm/droolsjbpm-integration#754 .
> Align reactivity support for Collection interfaces.

- docs/jbpm-docs/topics/Installer/Configuration-section.adoc
Description of the issue and script. If there is a better place to have such a note, feel free to let me know.
> JBPM-5476 - vacuumlo deletes active large objects of jBPM CLOB data

- docs/drools-docs/topics/LanguageReference/Rule-section.adoc
- docs/drools-docs/topics/ReleaseNotes/ReleaseNotesDrools.7.0.0.Final-section.adoc
Aligns with droolsjbpm/droolsjbpm-knowledge#205 .
> DROOLS-1244 TimedRuleExectionOption typing mistake

- docs/shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc
https://issues.jboss.org/browse/GUVNOR-2868
> GUVNOR-2868 : Guided Decision Table V&V - Docs

- docs/drools-docs/topics/LanguageReference/Rule-section.adoc
> DROOLS-1424 Variance and standard deviation function in Drools

- docs/shared/Workbench/ExecServer/ExecServer-section.adoc
@mswiderski would you mind to have a look if this corresponds to our discussion?
> JBPM-5642: extend documentation

- docs/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/shared-kie-docs/src/main/asciidoc/KieServer/ReleaseNotes/ReleaseNotesKieServer.7.0.0.Final-section.adoc
@etirelli @mswiderski @psiroky can some of you review this PR, please?
Thanks.
> DROOLS-1509 ServiceResponse XStream marshalling inconsistencies with JAXB

- docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc
See https://issues.jboss.org/browse/GUVNOR-3003
> GUVNOR-3003: [Library] [Assets list] Order assets alphabetically

- docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc
See https://issues.jboss.org/browse/GUVNOR-3003
This is the corollary of https://github.com/kiegroup/kie-docs/pull/255 for 7.0.x
(cherry picked from commit 1c2f2bb2d616e32c2b59c76549d89ddcc5b631e6)
> [7.0.x] GUVNOR-3003: [Library] [Assets list] Order assets alphabetically (#255)

- docs/jbpm-docs/src/main/asciidoc/Console/TaskManagement-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.0.0.Final-section.adoc
Added info related to BPMSPL-653, BPMSPL-638, BPMSPL-637, BPMSPL-632 and JBPM-5873.
> Updated task management and New and Noteworthy in jBPM 7.0.0 sections

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.0.0.Final-section.adoc
This PR depends on https://github.com/kiegroup/kie-docs/pull/258 and https://github.com/kiegroup/jbpm-wb/pull/713
It will be rebased once https://github.com/kiegroup/kie-docs/pull/258 is merged
> BPMSPL-633: Add process instance error count column and popup

- docs/drools-docs/src/main/asciidoc/AuthoringAssets/GuidedDecisionTableEditor-section.adoc
https://issues.jboss.org/browse/GUVNOR-2176
-Small improvement
> GUVNOR-2176 : Guided decision table verification and validation

- docs/shared-kie-docs/src/main/asciidoc/KieServer/OptaplannerRestAPI-section.adoc
* Update the documentation to reflect 7 series API changes.
* Remove REST response examples - IMO these provide a little added value. Instead provide examples of submitting a solution using all xstream, jaxb, json.
> PLANNER-816: Execution server: Update Planner API documentation

- docs/drools-docs/src/main/asciidoc/DMN/DroolsDMNSupport-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEEL-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesDate-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesDateTime-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesString-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesTime-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELVariableNames-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/Overview-section.adoc
@etirelli , providing peer review for your PR# 260.
> Reviewed pull req# 260

- docs/drools-docs/src/main/asciidoc/DMN/Executing_decision_services_from_Kie_Container-task.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesContext-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesDaysTimeDuration-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesFunction-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesList-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesRange-section.adoc
- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypesYearsMonthsDuration-section.adoc
@etirelli ,
Providing peer review for [PR#280](https://github.com/kiegroup/kie-docs/pull/280/).
> Peer reviewed changes in DMN docs PR#280

- docs/drools-docs/src/main/asciidoc/ExperimentalFeatures/RuleUnit-section.adoc
@mariofusco ,
Peer reviewed [PR#273](https://github.com/kiegroup/kie-docs/pull/273) 
Please check.
> Peer review comments

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.1.0.Final-section.adoc
@markcoble ,
peer reviewing the error handling topic from [PR#270](https://github.com/kiegroup/kie-docs/pull/270/).
Pls check.
> Peer reveiwed error handling topic from rn

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.1.0.Final-section.adoc
@nmirasch ,
peer reviewed  section "New Execution Errors View" fron RN from [PR#271](https://github.com/kiegroup/kie-docs/pull/271). Please check.
> peer reviewed execution error view topic

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.0.0.Final-section.adoc
hi @pefernan,
peer reviewed your changes in Form Modeler section in [PR#262](https://github.com/kiegroup/kie-docs/pull/262/). pls review.
> Peer reviewed Form Modeler section in rel notes

- docs/jbpm-docs/src/main/asciidoc/DomainSpecificProcesses/NotificationExample-section.adoc
Hi @tsurdilo ,
Peer reviewed your changes in [PR#281](https://github.com/kiegroup/kie-docs/pull/281)
> Peer reviewed PR#281

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> JBPM-6275: Wrong artifact versions specified in the KC integration section.

- docs/shared-kie-docs/src/main/asciidoc/KieServer/OptaplannerRestAPI-section.adoc
@ge0ffrey REST API update. Can you please review & merge? Thanks
> PLANNER-815: Execution server: Support real-time planning

- docs/shared-kie-docs/src/main/asciidoc/KieServer/OptaplannerRestAPI-section.adoc
@mcimbora,
Provided some minor peer review changes for ur PR  #272 on Planner API changes. Please review.
> Review planner api updates pr272

- docs/shared-kie-docs/src/main/asciidoc/KieServer/ReleaseNotes/ReleaseNotesKieServer.7.0.0.Final-section.adoc
@ge0ffrey Mention Planner REST API changes in ES Release notes.
> PLANNER-825: Mention OptaPlanner REST API changes in 7.0 release notes

- docs/shared-kie-docs/src/main/asciidoc/KieServer/ReleaseNotes/ReleaseNotesKieServer.7.0.0.Final-section.adoc
@ge0ffrey 7.2.x version of https://github.com/kiegroup/kie-docs/pull/307
> [7.2.x] PLANNER-825: Mention OptaPlanner REST API changes in 7.0 release notes

- docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.1.0.Final-section.adoc
@dgutierr ,
Providing minor comments on ur [PR # 278](https://github.com/kiegroup/kie-docs/pull/278/)
Please review.
> Providing minor edits on the Project MetricsDashboard changes in PR#278

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.3.0.Final-section.adoc
@tsurdilo could you please have a look?
> Added 7.3 release notes, included KIE Server Maven plugins

- docs/drools-docs/src/main/asciidoc/LanguageReference/Rule-section.adoc
> Fix Accumulate CE (preferred syntax) asciidoc code block

- docs/product-development-guide/src/main/asciidoc/chap-intelligent-process-server.adoc
Hi,
porting BXMSDOC-1614 from gitlab. You can see rendered docs [here](http://file.brq.redhat.com/~mczernek/BXMSDOC-1614_master/#using_the_intelligent_process_server_ui_extension).
Please merge. Thanks.
> BXMSDOC-1614 - master

- docs/product-development-guide/src/main/asciidoc/chap-intelligent-process-server.adoc
Hi,
This is a cherry-pick of #350. See the rendered docs [here](http://file.brq.redhat.com/~mczernek/BXMSDOC-1614-7_3_x/#using_the_intelligent_process_server_ui_extension).
Please merge. Thanks.
> BXMSDOC-1614 7.3.x

- docs/product-administration-and-configuration-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-development-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-getting-started-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-installation-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-migration-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-user-guide/src/main/asciidoc/bpms/master-docinfo.xml
- docs/product-user-guide/src/main/asciidoc/main.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Cherry-pick of  #352 into 7.3.x branch. See #352 for further info.
Please merge.
> BXMSDOC-1706 - 7.3.x

- docs/product-user-guide/src/main/asciidoc/chap-writing-rules.adoc
Added the following two points in *Verification and Validation of Guided Decision Tables* -> *Introduction* of BRMS User Guide:
- Broken Unique Hit Policy
- Incomplete Ranges
Links:
- [Jira](https://issues.jboss.org/browse/BXMSDOC-1434)
- [Rendered output](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1434/#verification_and_validation_of_guided_decision_tables)
> BXMSDOC-1434 (for upstream master): Updated Verification and Validation section of BRMS User Guide

- docs/product-user-guide/src/main/asciidoc/chap-writing-rules.adoc
Ready to merge with upstream 7.3.x..
Added the following two points in *Verification and Validation of Guided Decision Tables* -> *Introduction* of BRMS User Guide:
- Broken Unique Hit Policy
- Incomplete Ranges
Links:
- [Jira](https://issues.jboss.org/browse/BXMSDOC-1434)
- [Rendered output](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1434/#verification_and_validation_of_guided_decision_tables)
> BXMSDOC-1434 (for upstream 7.3.x): Updated Verification and Validation section of BRMS User Guide

- docs/product-user-guide/src/main/asciidoc/chap-process-designer.adoc
Hi,
porting BXMSDOC-636 to github. SME and peer reviews available in Jira. Rendered docs [here](http://file.brq.redhat.com/~mczernek/BXMSDOC-636-master/#creating_a_work_item). 
Please merge.
> BXMSDOC-636 - porting to master

- docs/product-user-guide/src/main/asciidoc/chap-process-designer.adoc
Cherry-pick of #362. Rendered docs of 7.3.x [here](http://file.brq.redhat.com/~mczernek/BXMSDOC-636-7_3_x/#creating_a_work_item).
Please merge.
> BXMSDOC-636 - porting to 7.3.x

- docs/product-administration-and-configuration-guide/src/main/asciidoc/bpms/master.html
- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-asset-repository.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/main.adoc
- docs/product-user-guide/src/main/asciidoc/chap-project.adoc
- docs/product-user-guide/src/main/asciidoc/organizational-unit-con.adoc
- docs/product-user-guide/src/main/asciidoc/repository-clone-con.adoc
- docs/product-user-guide/src/main/asciidoc/repository-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Pending peer review by @ChristyWatkins, then ready to merge with upstream 7.3.x.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1797)
- [LA Chap Review sheet](https://docs.google.com/spreadsheets/d/1Q7YQx7GE9ks4X8UIPuLM8k0P_8_HQVvaozBORmoD9Bc/edit#gid=0)
- [Admin Guide BRMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BRMS/)
- [Admin Guide BPMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BPMS/)
- [User Guide BRMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BRMS_UG/) - Had to update/remove all references to `kie-config-cli` tool, per change to Admin Guide.
- [User Guide BPMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BPMS_UG/) - Ditto.
> BXMSDOC-1797 (for upstream 7.3.x): Exclude specified chapters from BPM Admin Guide and update affect sections in User Guide

- docs/product-administration-and-configuration-guide/src/main/asciidoc/bpms/master.html
- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-asset-repository.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/main.adoc
- docs/product-user-guide/src/main/asciidoc/chap-project.adoc
- docs/product-user-guide/src/main/asciidoc/organizational-unit-con.adoc
- docs/product-user-guide/src/main/asciidoc/repository-clone-con.adoc
- docs/product-user-guide/src/main/asciidoc/repository-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Pending peer review by @ChristyWatkins, then ready to merge with upstream master.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1797)
- [LA Chap Review sheet](https://docs.google.com/spreadsheets/d/1Q7YQx7GE9ks4X8UIPuLM8k0P_8_HQVvaozBORmoD9Bc/edit#gid=0)
- [Admin Guide BRMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BRMS/)
- [Admin Guide BPMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BPMS/)
- [User Guide BRMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BRMS_UG/) - Had to update/remove all references to `kie-config-cli` tool, per change to Admin Guide.
- [User Guide BPMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1797_BPMS_UG/) - Ditto.
> BXMSDOC-1797 (for upstream master): Exclude specified chapters from BPM Admin Guide and update affect sections in User Guide

- docs/product-release-notes/src/main/asciidoc/bxms-rn-whats-new-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Rendered doc:
http://file.ork.redhat.com/~emmurphy/BXMSDOC-1782/
SME Review:
https://issues.jboss.org/browse/BXMSDOC-1793
Peer Review:
https://issues.jboss.org/browse/BXMSDOC-1792
> BXMSDOC-1782 7.3.x final Update the RN for Beta 02

- docs/drools-docs/src/main/asciidoc/AuthoringAssets/GuidedDecisionTableEditor-section.adoc
See https://issues.jboss.org/browse/GUVNOR-3200
---
---
Part of an ensemble:
- https://github.com/AppFormer/uberfire/pull/861
- https://github.com/kiegroup/kie-wb-common/pull/1190
- https://github.com/kiegroup/drools-wb/pull/636
- https://github.com/kiegroup/kie-wb-distributions/pull/628
- https://github.com/kiegroup/kie-docs/pull/402
> GUVNOR-3200: [Guided Decision Table] Access control to prohibit business users from modifying columns

- docs/drools-docs/src/main/asciidoc/AuthoringAssets/GuidedDecisionTableEditor-section.adoc
See https://issues.jboss.org/browse/GUVNOR-3200
---
Cherry-picked from https://github.com/kiegroup/kie-docs/pull/402
---
Part of an ensemble:
- https://github.com/AppFormer/uberfire/pull/863
- https://github.com/kiegroup/kie-docs/pull/407
- https://github.com/kiegroup/kie-wb-distributions/pull/634
- https://github.com/kiegroup/drools-wb/pull/644
- https://github.com/kiegroup/kie-wb-common/pull/1222
> [7.3.x] GUVNOR-3200: [Guided Decision Table] Access control to prohibit business users from modifying columns

- docs/product-user-guide/src/main/asciidoc/chap-advanced-process-modeling.adoc
No impact from new UI, from what I can see. I went ahead and made a couple of changes while I was there though. Very minimal.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1807)
> BXMSDOC-1807 (for upstream master): Minor updates to chap Advanced Process Modeling in BPMS User Guide for clearer instructions

- docs/product-user-guide/src/main/asciidoc/data-object-deployment-descriptor-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-persistable-modify-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-relationships-proc.adoc
Cherry-picked from branch BXMSDOC-1806-master. Basically just changed "**Authoring** -> **Project Authoring**" to  "**Menu** -> **Projects**" at several points. Otherwise no impact.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1806)
- [Output for BRMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1806_BRMS/#assets_data_models_gloss_chap-data-models)
- [Output for BPMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1806_BPM/#assets_data_models_gloss_chap-data-models)
> BXMSDOC-1806 (for upstream 7.4.x): Updated chap. Data Models in BRMS and BPMS User Guide per 7.0 LA ER3 new UI

- docs/drools-docs/src/main/asciidoc/ExperimentalFeatures/RuleUnit-section.adoc
> DROOLS-1756 Align Rule Unit doc chapter to current OOPath syntax

- docs/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.4.0.Final-section.adoc
(cherry picked from commit 82acd169219149c9b53536d4b381e3a27d3dd47d)
> Placeholder for 7.4.0.Final Workbench N&N

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.4.0.Final-section.adoc
> jBPM release notes for 7.4

- docs/drools-docs/src/main/asciidoc/index.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.2.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/index.adoc
- docs/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/AuthoringPlanningAssets/TerminationEditor-section.adoc
- docs/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/Quickstart/Quickstart-section.adoc
- docs/optaplanner-wb-es-docs/src/main/asciidoc/index.adoc
- docs/pom.xml
- docs/shared-kie-docs/src/main/asciidoc/Android/Android-chapter.adoc
- docs/shared-kie-docs/src/main/asciidoc/KieServer/OptaplannerRestAPI-section.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> Backport several fixes from master

- docs/drools-docs/src/main/asciidoc/index.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.2.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/index.adoc
- docs/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/AuthoringPlanningAssets/TerminationEditor-section.adoc
- docs/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/Quickstart/Quickstart-section.adoc
- docs/optaplanner-wb-es-docs/src/main/asciidoc/index.adoc
- docs/pom.xml
- docs/shared-kie-docs/src/main/asciidoc/Android/Android-chapter.adoc
- docs/shared-kie-docs/src/main/asciidoc/KieServer/OptaplannerRestAPI-section.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
Unfortunately #341 was merged into 7.3.x after 7.4.x was created. This makes 7.4.x being behind 7.3.x which is undesirable. Let's forward port it to make 7.3.x and 7.4.x consistent.
> Backport several fixes from master (#341)

- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-eap.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-business-central-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-configure-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-download-install-proc.adoc
Jira is [here](https://issues.jboss.org/browse/BXMSDOC-1728).
Rendered doc is [here](http://file.ork.redhat.com/~emmurphy/BXMSDOC-1728/).
> BXMSDOC-1728-7.4.x-final to 7.4.x

- docs/product-getting-started-guide/src/main/asciidoc/task_new-project.adoc
Added the following note to Chapter 3 of the GSG LA version.
Important
This business process application example uses the Red Hat JBoss BPM Suite Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information on Red Hat Technology Preview features support scope, see https://access.redhat.com/support/offerings/techpreview/.
Peer review: #439
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-BXMS-1850-master/#business_process_scenario
> Ready to be merged: Add newly provided "Tech Preview" note from template

- docs/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSourceManagement/DataSourceManagement-section.adoc
- adds missing advanced settings documentation
> [master] DROOLS-1748: Drools workbench datasource on Wildfly domain

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
- Fixing wrong (old) links
- Adding new note to ensure removing the SSO tag in the wildfly/EAP configuration file, if present, which is causing issues during logout
Hey @manstis , just fixed some broken links and added a single line note. Can you please take a quick look? Once merged will cherry-pick it to other branches.
Thanks in advance!!
Roger
> Keycloak SSO integration - fixing docs 

- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-configure-proc.adoc
[BXMSDOC-1800](https://issues.jboss.org/browse/BXMSDOC-1800)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1851)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1854)
> BXMSDOC-1800 When installing kie-execution-server only, the server won't start

- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-eap.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-openshift.adoc
- docs/product-installation-guide/src/main/asciidoc/bxms-supported-component-versions-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-bxms-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-configure-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-bxms-con.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-bxms-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-image-install-proc.adoc
[BXMSDOC-1840](https://issues.jboss.org/browse/BXMSDOC-1840)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1845)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1855)
> BXMSDOC-1840 Remove Image Installation section from the IG for LA release -7.4.x

- docs/product-user-guide/src/main/asciidoc/chap-plug-in.adoc
Correction - this one was obviously based off master.
Please merge to Master, will create a separate PR for 7.4.x (LA).
> Bxmsdoc 1761 Master

- docs/product-user-guide/src/main/asciidoc/chap-plug-in.adoc
> BXMSDOC-1761.LA: Changes for LA

- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-business-central-configuration.adoc
[BXMSDOC-1765](https://issues.jboss.org/browse/BXMSDOC-1765)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1853)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1859)
> BXMSDOC-1765 -7.4.x-final

- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-configure-proc.adoc
[BXMSDOC-1765](https://issues.jboss.org/browse/BXMSDOC-1765)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1853)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1859)
> BXMSDOC-1765 Master Final

- docs/product-administration-and-configuration-guide/src/main/asciidoc/appe-properties.adoc
- docs/product-development-guide/src/main/asciidoc/chap-intelligent-process-server.adoc
> Bxmsdoc 1537.master Standalone Controller

- docs/product-administration-and-configuration-guide/src/main/asciidoc/appe-properties.adoc
- docs/product-development-guide/src/main/asciidoc/chap-intelligent-process-server.adoc
Ok to test and merge for 7.4.x
> Bxmsdoc 1537 Standalone Controller

- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-eap.adoc
- docs/product-installation-guide/src/main/asciidoc/bxms-supported-platforms-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-business-central-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-download-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-bxms-con.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-bxms-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ext-repo-create-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-image-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-int-reg-create-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-bpmsuite-mysql-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-bpmsuite-mysql-persistent-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-bpmsuite-s2i-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-businesscentral-monitoring-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-businesscentral-monitoring-smartrouter-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-businesscentral-mysql-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-executionserver-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-temp-executionserver-postgresql-install-proc.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[BXMSDOC-1837](https://issues.jboss.org/browse/BXMSDOC-1837)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1873)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1877)
> BXMSDOC-1837-7.4.x Update the Installation Guide supported components and file names for the LA release.

- docs/product-user-guide/src/main/asciidoc/chap-process-simulation.adoc
Jira: https://issues.jboss.org/browse/BXMSDOC-1762
Rendered doc: http://file.bne.redhat.com/ssainkar/BXMSDOC-1762/html-single/#simulation_and_testing
> Bxmsdoc 1762 7.4.x final

- docs/product-user-guide/src/main/asciidoc/chap-process-simulation.adoc
Jira: https://issues.jboss.org/browse/BXMSDOC-1762
Rendered doc: http://file.bne.redhat.com/ssainkar/BXMSDOC-1762/html-single/#simulation_and_testing
> Bxmsdoc 1762 master

- docs/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSourceManagement/DataSourceManagement-section.adoc
Hello @pefernan , would you mind review this PR?
Thanks
> Add system property for disabling the initialization of the by default drivers

- docs/product-user-guide/src/main/asciidoc/chap-process-designer.adoc
- docs/product-user-guide/src/main/asciidoc/proc-business-central-settings-data-sources.adoc
I cherry-picked changes from Michele's BXMSDOC-1760-7.4.x-final branch and resolved conflicts. Applied to master-based branch BXMSDOC-1894. I tested the build and all is well.
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-1894) for more details.
> BXMSDOC-1894 (for upstream master): Apply changes from BXMSDOC-1760-7.4.x-final to master

- docs/product-development-guide/src/main/asciidoc/assembly_security-management.adoc
- docs/product-development-guide/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/security-management-install-proc.adoc
- docs/product-development-guide/src/main/asciidoc/security-management-sec-policy-con.adoc
- docs/product-development-guide/src/main/asciidoc/security-management-sec-provider-con.adoc
[Jira](https://issues.jboss.org/browse/BXMSDOC-1337)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1903)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1909)
[Rendered Doc](http://file.ork.redhat.com/~emmurphy/BXMSDOC-1337/#assembly_security-management)
> BXMSDOC-1337 7.4.x  Document new Security API

- docs/shared-kie-docs/src/main/asciidoc/KieServer/KieServer-chapter.adoc
- docs/shared-kie-docs/src/main/asciidoc/KieServer/SecuringPasswords.adoc
Jira: https://issues.jboss.org/browse/RHBPMS-4312
> [RHBMPS-4312] Added documentation

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.5.0.Final-section.adoc
@tsurdilo please have a look.
once we are done with service repo setup we need to add it here too.
> added 7.5 new and noteworthy

- docs/product-development-guide/src/main/asciidoc/assembly_security-management.adoc
- docs/product-development-guide/src/main/asciidoc/chap-kie-api.adoc
- docs/product-development-guide/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/security-management-install-proc.adoc
- docs/product-development-guide/src/main/asciidoc/security-management-sec-policy-con.adoc
- docs/product-development-guide/src/main/asciidoc/security-management-sec-provider-con.adoc
@vidya-iyengar please merge this branch to 7.4.x
> Bxmsdoc 1468.LA

- docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc
@ChristyWatkins @vidya-iyengar please merge to 7.4.x branch.
> BXMSDOC 1607.LA

- docs/product-user-guide/src/main/asciidoc/chap-red-hat-jboss-dashboard-builder.adoc
Resolved some merge conflict metadata.
@vidya-iyengar please merge into 7.4.x
> BXMSDOC-1341.LAFix: DataSource Management

- docs/product-release-notes/src/main/asciidoc/con-bxms-rn-introduction.adoc
- docs/product-release-notes/src/main/asciidoc/con-bxms-rn-known-issues.adoc
- docs/product-release-notes/src/main/asciidoc/con-bxms-rn-tech-preview.adoc
- docs/product-release-notes/src/main/asciidoc/con-bxms-rn-whats-new.adoc
- docs/product-release-notes/src/main/asciidoc/main.adoc
[Jira](https://issues.jboss.org/browse/BXMSDOC-1895)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1944)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1937)
[Rendered Doc](http://file.ork.redhat.com/~emmurphy/BXMSDOC-1895/)
> Merge pBXMSDOC-1895-7.4.x-fina Release Notes Update LA Patch (Nov 30) 

- docs/product-development-guide/src/main/asciidoc/chap-intelligent-process-server.adoc
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1816)
[Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1816/#managing_task_instance_data)
> BXMSDOC-1816 (for upstream master): Updated Development Guide with new kie-server REST PUT call for updating taskInstance object

- docs/product-development-guide/src/main/asciidoc/chap-kie-api.adoc
Pending SME and Peer review.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1348)
[Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1348/#sect_query_service) - Scroll to "21.3.6.5 Storing Query Definitions in a kJAR"
> WIP: BXMSDOC-1348 (for upstream master): Updated Dev Guide with new section on Storing Query Definitions in a kJAR

- docs/jbpm-docs/src/main/asciidoc/Installer/Configuration-section.adoc
Doc PR which comes with the PR https://github.com/kiegroup/jbpm/pull/1088
> RHBPMS-5067 - Amend AUTO_INCREMENT on MySQL/MariaDB restart

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.5.0.Final-section.adoc
@tsurdilo could you please have a look?
> Updated jBPM 7.5 N&N

- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-eap.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-openshift.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-installing-con.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-component-versions-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-platforms-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-ba-dm-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ba-dm-con.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ba-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ba-dm-run-proc.adoc
[Jira](https://issues.jboss.org/browse/BXMSDOC-2011)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-2020)
Note: This jira is for file and anchor name changes only so no SME review is required.
> BXMSDOC-2011 7.5.x Update file names and achors in 7.0 Installation Guide

- docs/product-assembly_guided-decision-tables/src/main/asciidoc/ba/master-docinfo.xml
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-action-BRL-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-condition-BRL-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-condition-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-delete-fact-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-edit-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-field-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-field-work-item-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-metadata-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-types-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-work-item-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-errors-ref.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-hit-policies-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-rows-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-types-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-validation-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-validation-disable-proc.adoc
Small but important update, to avoid misleading others. Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-2031).
> BXMSDOC-2031 (for upstream master): Corrected GDT assembly anchor ID and capitalization issues, as template for others

- docs/product-assembly_guided-decision-tables/src/main/asciidoc/ba/master-docinfo.xml
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-action-BRL-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-condition-BRL-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-condition-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-delete-fact-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-edit-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-field-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-field-work-item-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-metadata-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-types-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-columns-work-item-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-errors-ref.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-hit-policies-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-rows-create-proc.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-types-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-validation-con.adoc
- docs/product-user-guide/src/main/asciidoc/guided-decision-tables-validation-disable-proc.adoc
Small but important update, to avoid misleading others. Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-2031).
> BXMSDOC-2031 (for upstream 7.5.x): Corrected GDT assembly anchor ID and capitalization issues, as template for others

- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-eap.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-openshift.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-installing-con.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-component-versions-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-platforms-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-ba-dm-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ba-dm-con.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ba-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/openshift-ba-dm-run-proc.adoc
[Jira](https://issues.jboss.org/browse/BXMSDOC-2011)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-2020)
Note: This jira is for file and anchor name changes only so no SME review is required.
> BXMSDOC-2011 master Update file names and achors in 7.0 Installation Guide

- docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc
This was a 6.4 update request that applies to 7.0 as well.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1182)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1182/#process_instance_migration) (see note on "Process instance migration on the KIE Server")
> BXMSDOC-1182 (for upstream master): Added note on process instance migration on KIE server in Dev Guide

- docs/shared-kie-docs/src/main/asciidoc/KieServer/SecuringPasswords.adoc
Jira: https://issues.jboss.org/browse/JBPM-6721
> [JBPM-6721] Fixed parameter names in example

- docs/product-assembly_DM-70-release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-intro-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Added comments to initial draft. No peer review or SME review need for this merge.
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2130)
[Jira](https://issues.jboss.org/browse/BXMSDOC-2130)
> BXMSDOC-2130 Planning: Update DM 7.0 release notes with comments and placeholder jiras

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
Hey @ederign @tomasdavidorg 
As from this other PR https://github.com/kiegroup/appformer/pull/113, here is an update for the docs about the Keycloak SSO integration as well.
Thanks!
> AF-483: Keycloak SSO docs - Some updates

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> [7.0.x] Keycloak SSO integration - fixes

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> [7.1.x] Keycloak SSO integration - fixes

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> [7.2.x] Keycloak SSO integration - fixes

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> [7.3.x] Keycloak SSO integration - fixes

- docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc
> [7.4.x] Keycloak SSO integration - fixes

- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-deploy-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-manage-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-overview-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-prepare-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/imagestreams-file-install-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-central-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-nos2i-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-s2i-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/main.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/secrets-central-create-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/secrets-kie-create-proc.adoc
* SME review and related changes
* final changes 2105
> Bxmsdoc 2105 master (#7) final

- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-deploy-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-manage-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-overview-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm-openshift-prepare-con.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/imagestreams-file-install-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-central-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-nos2i-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-s2i-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/main.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/secrets-central-create-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/secrets-kie-create-proc.adoc
* SME review and related changes
* final changes 2105
> Bxmsdoc 2105 7.5.x final

- docs/product-assembly_packaging-deploying/src/main/asciidoc/central-configure-maven-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-central-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-runservice-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/main.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/maven-deployment.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-build-deploy-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-deploy-manage-central-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-gav-setting-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-packaging-deploying-overview-con.adoc
* adapting to a rebase as best I can to get new common files
* final draft self-review
* small fixes
* final peer review changes
> Bxmsdoc 2107 master (#6) final merge

- docs/product-assembly_packaging-deploying/src/main/asciidoc/central-configure-maven-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-central-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-runservice-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/main.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/maven-deployment.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-build-deploy-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-deploy-manage-central-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-gav-setting-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/service-packaging-deploying-overview-con.adoc
* adapting to a rebase as best I can to get new common files
* final draft self-review
* small fixes
* final peer review changes
> Bxmsdoc 2107 7.5.x final 

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-con.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-configure-server-managed-by-workbench-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-creating-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-deploying-kie-server-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-unmanaged-server-config-proc.adoc
- docs/product-assembly_business-optimizer/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-REST-API-configuration-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-about-business-optimizer-con.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-domain-editor-con.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-in-an-IDE-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-proc.adoc
@rsynek could you please check that this resolves the final issues you raised in https://issues.jboss.org/browse/BXMSDOC-2146?
Thanks,
Gemma.
> BXMSDOC-2110 SME final review

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-con.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-configure-server-managed-by-workbench-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-creating-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-deploying-kie-server-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-unmanaged-server-config-proc.adoc
- docs/product-assembly_business-optimizer/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-REST-API-configuration-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-about-business-optimizer-con.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-domain-editor-con.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-in-an-IDE-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-proc.adoc
Ready to merge to 7.5.x @vidya-iyengar
> Bxmsdoc 2110.final.7.5.x

- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-intro-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2138-new/#ba-dm-rn-intro-con
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2138
> Bxmsdoc 2138 upstream PR to master - New intro info

- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-intro-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2138-new/#ba-dm-rn-intro-con
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2138
> Bxmsdoc 2138 upstream PR to 7.5.x - New intro info

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-deploying-kie-server-proc.adoc
- docs/product-assembly_business-optimizer/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-rest-api-execution-server-dm-commands-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-score-constraints-guided-rules-proc.adoc
- docs/product-development-guide/src/main/asciidoc/rest-api-repository-calls-ref.adoc
@vidya-iyengar final changes for master.
> Bxmsdoc 1996.master.final

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-deploying-kie-server-proc.adoc
- docs/product-assembly_business-optimizer/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-rest-api-execution-server-dm-commands-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-score-constraints-guided-rules-proc.adoc
- docs/product-development-guide/src/main/asciidoc/rest-api-repository-calls-ref.adoc
@vidya-iyengar final changes to merge to 7.5.x
> Bxmsdoc 1996.7.5.x.final

- docs/product-assembly_decision-manager/src/main/asciidoc/main.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2218/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2218
> Bxmsdoc 2218 Upstream PR to master - Replaced final install on prem guide links

- docs/product-assembly_decision-manager/src/main/asciidoc/main.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2218/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2218
> Bxmsdoc 2218 Upstream PR to 7.5.x - Replaced final install on prem guide links

- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-intro-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2220/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2220
> Bxmsdoc 2220 7.5.x master final to upstream 7.5.x PR

- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-integrating-red-hat-jboss-bxms-with-red-hat-sso.adoc
- docs/product-assembly_installing-dm-on-premise/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-component-versions-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
Final Installation on premise merge
> BXMSDOC-2212 master - Final merge for Installing DM on Premise

- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-integrating-red-hat-jboss-bxms-with-red-hat-sso.adoc
- docs/product-assembly_installing-dm-on-premise/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-component-versions-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
Final installing dm on premise merge, for epic BXMSDOC-1995
> BXMSDOC-2212 - 7.5.x Installing DM on Premise

- docs/product-assembly_DM-7.0-release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-intro-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-BXMSDOC-2220/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2220
> Bxmsdoc 2220 upstream PR to master to replace missing RN title details that were overwritten

- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/code-troubleshooting-ref.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/kieserver-upgrade-proc.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/migration-overview-con.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/projects-central-migrating-proc.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/projects-java-migrating-proc.adoc
* xref fixed
* more SME review changes
* second SME review changes
> Bxmsdoc 1991 master (#10)

- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/code-troubleshooting-ref.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/kieserver-upgrade-proc.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/migration-overview-con.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/projects-central-migrating-proc.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/projects-java-migrating-proc.adoc
* xref fixed
* more SME review changes
* second SME review changes
> Bxmsdoc 1991 7.5.x

- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-central-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-runservice-proc.adoc
* Fixing links that should not be links
* QE verification change
> Bxmsdoc 2107 master (#11)

- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-central-proc.adoc
- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-runservice-proc.adoc
* Fixing links that should not be links
* QE verification change
> Bxmsdoc 2107 7.5.x

- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-BXMSDOC-2220/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2220
> BXMSDOC-2220 Upstream PR to 7.5.x

- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-whats-new-con.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-BXMSDOC-2220/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2220
> BXMSDOC-2220 Upstream PR to Master 

- docs/product-assembly_installing-dm-on-premise/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-artemis-activate-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-ba-dm-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-dc-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-download-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-standalone-properties-con.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
> BXMSDOC-2222 master Changes to clustering and standalone installation

- docs/product-assembly_installing-dm-on-premise/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-artemis-activate-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-ba-dm-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-dc-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-download-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-standalone-properties-con.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
> BXMSDOC-2222 updated clustering and added standalone installation

- docs/product-assembly_business-optimizer/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-REST-API-configuration-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-rest-api-execution-server-dm-commands-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-rest-api-for-execution-server-con.adoc
> Bxmsdoc 2231.master

- docs/product-assembly_business-optimizer/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-REST-API-configuration-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-rest-api-execution-server-dm-commands-ref.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-rest-api-for-execution-server-con.adoc
> Bxmsdoc 2231 SME comments from PR8 included

- docs/jbpm-docs/src/main/asciidoc/TaskService/UsingUserTasksInProcesses-section.adoc
Documentation about how enable/disable autoclaim functionality of swimlanes.
> JBPM-6779: Disable autoclaim functionality of swimlanes

- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-central-proc.adoc
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/appformer/pull/199
https://github.com/kiegroup/kie-docs/pull/694
https://github.com/kiegroup/optaplanner-wb/pull/258
https://github.com/kiegroup/drools-wb/pull/817
https://github.com/kiegroup/kie-tests/pull/18
https://github.com/kiegroup/kie-wb-distributions/pull/695
> AF-1037 : Business-central maven artifacts available at maven2wb without authorization

- docs/product-assembly_packaging-deploying/src/main/asciidoc/kieserver-configure-central-proc.adoc
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/appformer/pull/200
https://github.com/kiegroup/kie-docs/pull/695
https://github.com/kiegroup/optaplanner-wb/pull/259
https://github.com/kiegroup/drools-wb/pull/818
https://github.com/kiegroup/kie-wb-distributions/pull/696
(cherry picked from commit dd2ad7e11478f4fd7e9cea67a1956db16feaa8e8)
> [7.5.x] AF-1037 : Business-central maven artifacts available at maven2wb without authorization

- code/src/test/java/org/guvnor/rest/backend/documentation/GuvnorSerializationExamplesTest.java
https://issues.jboss.org/browse/DROOLS-2336
https://github.com/kiegroup/kie-docs/pull/690
https://github.com/kiegroup/appformer/pull/193
https://github.com/kiegroup/kie-wb-distributions/pull/693
> DROOLS-2336 : [Project Oriented] Add REST tests back into kie-wb-distributions

- docs/product-assembly_installing-dm-on-premise/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-artemis-activate-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-download-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/run-dc-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/run-standalone-properties-con.adoc
https://issues.jboss.org/browse/BXMSDOC-2235
https://issues.jboss.org/browse/BXMSDOC-2222
> BXMSDOC-2222 and BXMSDOC-2235

- docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
- docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Ready for upstream master. See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2267) for details.
> BXMSDOC-2267 (for upstream master): Uncommented cross-refs to test scenarios doc and updated test scenarios doc attribute and its URL attribute

- docs/shared-kie-docs/src/main/asciidoc/KieServer/SecuringPasswords.adoc
> Keytool command fix

- docs/shared-kie-docs/src/main/asciidoc/KieServer/SecuringPasswords.adoc
> Keytool command and system property fixes

- docs/shared-kie-docs/src/main/asciidoc/Workbench/SecurityManagement/SecurityManagement-section.adoc
Fixing some broken links caused by repository moves.
@manstis Can you merge please?
> Fix security management broken links 

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2246) 
- [Contrib Guide](http://ccs-jenkins.gsslab.brq.redhat.com:8080/view/Topic%20branches/job/doc-Red_Hat_JBoss_BxMS_Contribution_Guide-branch-shared-repo/lastSuccessfulBuild/artifact/index.html#_publishing_ba_dm_guides_using_pantheon) steps taken.
> BXMSDOC-2246 (for upstream master): Update REBUILT variable and new doc attributes for Mar 2 2018 patch publish

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[JIRA](https://issues.jboss.org/browse/BXMSDOC-2280)
> BXMSDOC-2280 (for upstream 7.5.x): Update REBUILT attribute for DM 7.0 patch 2.

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-configure-server-managed-by-workbench-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-creating-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-managing-multiple-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-starting-stopping-deleting-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-upgrading-containers-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-download-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-proc.adoc
@martinweiler could you please provide SME review?
> BXMSDOC-2286: Updated download instructions for Optimizer engine

- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-REST-API-configuration-ref.adoc
> BXMSDOC-2231: REST API example changes to reflect ER

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-configure-server-managed-by-workbench-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-creating-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-managing-multiple-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-starting-stopping-deleting-containers-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-upgrading-containers-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-download-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-proc.adoc
@vidya-iyengar the same bug for master.
> Bxmsdoc 2286.master

- docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.7.0.Final-section.adoc
https://issues.jboss.org/browse/AF-1109
> AF-1109 : Update New & Noteworthy

- docs/shared-kie-docs/src/main/asciidoc/Workbench/Embedding/Embedding-section.adoc
https://issues.jboss.org/browse/AF-1028
Removing lies, old perspective names and providing few examples to help use the embed mode.
https://github.com/kiegroup/kie-wb-common/pull/1524
https://github.com/kiegroup/kie-wb-distributions/pull/714
https://github.com/kiegroup/kie-docs/pull/735
> AF-1028 : [Project Oriented] Standalone perspectives are broken

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.7.0.Final-section.adoc
@tsurdilo could you please have a look?
> Updated jBPM 7.7 New and Noteworthy

- docs/product-assembly_dmn-authoring-guide/src/main/asciidoc/main.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-decision-tables-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-example-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-feel-overview-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-options-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-remote-java-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-rest-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-model-creating-proc.adoc
Implemented all changes from QE reviews.
PDF preview for both DM and BA are here: https://www.dropbox.com/sh/pjzcfabmu8tfkm8/AAARju3V1Qlu_2ReJNCKWS3Oa?dl=0
Note that these are built with straight ASCIIdoc so formatting may differ
> BXMS-2104v2-master: Implemented changes identified in QE review (#4)

- docs/product-assembly_dmn-authoring-guide/src/main/asciidoc/main.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-decision-tables-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-example-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-feel-overview-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-options-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-remote-java-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-rest-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-model-creating-proc.adoc
Latest preview: https://www.dropbox.com/sh/pjzcfabmu8tfkm8/AAARju3V1Qlu_2ReJNCKWS3Oa?dl=0
> BXMSDOC-2104: QE review updates for 7.5.x final branch

- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
Added additional QE code readability suggestion for BXMSDOC-2104.
Preview:https://www.dropbox.com/sh/pjzcfabmu8tfkm8/AAARju3V1Qlu_2ReJNCKWS3Oa?dl=0
> BXMSDOC 2104 7.5.x Code Readability

- docs/product-assembly_business-optimizer-ER-sample-openshift/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optashift-ER-openshift-deploy-proc.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optashift-ER-overview-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2494)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-2494_DM/)
> BXMSDOC-2494 (for upstream 7.5.x): Updated Employee Rostering sample on OpenShift doc to fix output issues

- docs/product-user-guide/src/main/asciidoc/dmn-elements-example-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-remote-java-proc.adoc
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2531)
- [Doc preview for PAM 7.0](http://file.rdu.redhat.com/~sterobin/BXMSDOC-2531_PAM/#dmn-invocation-embedded-proc)
> BXMSDOC-2531 (for upstream master): Minor tweaks to DMN doc for PAM 7.0 per Jozef Marko.

- docs/product-user-guide/src/main/asciidoc/dmn-elements-example-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-remote-java-proc.adoc
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2531)
- [Doc preview for PAM 7.0](http://file.rdu.redhat.com/~sterobin/BXMSDOC-2531_PAM/#dmn-invocation-embedded-proc)
> BXMSDOC-2531 (for upstream 7.7.x): Minor tweaks to DMN doc for PAM 7.0 per Jozef Marko.

- docs/drools-docs/src/main/asciidoc/DMN/DroolsDMNSupport-section.adoc
was not rendered correctly
before:
after:
> Fix asciidoc bulletpoint

- docs/drools-docs/src/main/asciidoc/DMN/DroolsDMNSupport-section.adoc
... and DMN TCK url update
/cc @etirelli thoughts? I didn't provide an example in the doc as I'm reluctant that strategy proved faulty as the docs gets outdated, so I believe this is the minimal however should suffice (for now).
> Brief explaination of DMN ItemDefinition representation

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
> BXMSDOC-2628 (for upstream 7.7.x): Updated REBUILT variable per May 10 beta PDFs for PAM 7.0

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
> BXMSDOC-2628 (for upstream master): Updated REBUILT variable per May 10 beta PDFs for PAM 7.0

- docs/product-development-guide/src/main/asciidoc/security-management-install-proc.adoc
- docs/product-user-guide/src/main/asciidoc/chap-red-hat-jboss-dashboard-builder.adoc
- docs/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSourceManagement/DataSourceManagement-section.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/SecurityManagement/SecurityManagement-section.adoc
Accidentally noticed outstanding references to WF 8 and 10
> fixed references to Wildfly 11+

- docs/shared-kie-docs/src/main/asciidoc/Workbench/SecurityManagement/SecurityManagement-section.adoc
> Security Management - Improved introduction section for users, groups and roles

- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/chap-working-with-processes.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/controller-was-install-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-install-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-assets-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-configure-kie-server-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-prep-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-other-changes-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-planner-changes-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-planner-config-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-projects-manual-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-7.0-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-niogit-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-repo-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-verify-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/controller-wls-install-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/controller-wls-was-environment-set-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/kie-server-wls-install-proc.adoc
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2470)
- [Doc preview for PAM 7.0](http://file.rdu.redhat.com/~sterobin/BXMSDOC-MG_BA/#migration-other-changes-con)
- [Doc preview for DM 7.1](http://file.rdu.redhat.com/~sterobin/BXMSDOC-MG_DM/#migration-other-changes-con)
> BXMSDOC-2470 (for upstream master): Updated Migration doc with Business Optimizer config section, latest UI, and new Troubleshooting section

- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/chap-working-with-processes.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/controller-was-install-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-install-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-assets-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-configure-kie-server-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-prep-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-other-changes-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-planner-changes-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-planner-config-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-projects-manual-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-7.0-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-niogit-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-repo-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-verify-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/controller-wls-install-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/controller-wls-was-environment-set-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/kie-server-wls-install-proc.adoc
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2470)
- [Doc preview for PAM 7.0](http://file.rdu.redhat.com/~sterobin/BXMSDOC-MG_BA/#migration-other-changes-con)
- [Doc preview for DM 7.1](http://file.rdu.redhat.com/~sterobin/BXMSDOC-MG_DM/#migration-other-changes-con)
> BXMSDOC-2470 (for upstream 7.7.x): Updated Migration doc with Business Optimizer config section, latest UI, and new Troubleshooting section

- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-prep-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-non-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-projects-manual-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-niogit-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-repo-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-verify-proc.adoc
Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-2483).
> BXMSDOC-2483 (for upstream master): Update migration doc with QE final feedback for PAM 7.0 and DM 7.1

- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-prep-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-non-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-projects-manual-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-niogit-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-tool-repo-7.0-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-verify-proc.adoc
Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-2483).
> BXMSDOC-2483 (for upstream 7.7.x): Update migration doc with QE final feedback for PAM 7.0 and DM 7.1

- docs/product-assembly_integrating-with-entando/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/install-options-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
- docs/product-migration-guide/src/main/asciidoc/kieserver-upgrade-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-assets-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-non-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-overview-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/projects-central-migrating-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/product-for-wls.adoc
- docs/product-user-guide/src/main/asciidoc/entando-app-building-proc.adoc
- docs/product-user-guide/src/main/asciidoc/entando-pages-con.adoc
- docs/product-user-guide/src/main/asciidoc/entando-widgets-con.adoc
- docs/product-user-guide/src/main/asciidoc/kieserver-configure-central-proc.adoc
- docs/product-user-guide/src/main/asciidoc/maven-external-configure-proc.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-pam.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[JIRA](https://issues.jboss.org/browse/BXMSDOC-2684)
> BXMSDOC-2684 (for upstream master): Updated PAM doc title attrs and URL comps

- docs/product-assembly_integrating-with-entando/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/install-options-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
- docs/product-migration-guide/src/main/asciidoc/kieserver-upgrade-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-assets-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-non-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-overview-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/projects-central-migrating-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/product-for-wls.adoc
- docs/product-user-guide/src/main/asciidoc/entando-app-building-proc.adoc
- docs/product-user-guide/src/main/asciidoc/entando-pages-con.adoc
- docs/product-user-guide/src/main/asciidoc/entando-widgets-con.adoc
- docs/product-user-guide/src/main/asciidoc/kieserver-configure-central-proc.adoc
- docs/product-user-guide/src/main/asciidoc/maven-external-configure-proc.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-pam.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[JIRA](https://issues.jboss.org/browse/BXMSDOC-2684)
> BXMSDOC-2684 (for upstream 7.7.x): Updated PAM doc title attrs and URL comps

- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-basic-auth-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-central-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-client-adapter-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-int-con.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-kie-server-client-adapter-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-kie-server-client-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-realm-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-remote-services-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-remote-services-securing-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-third-party-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-token-auth-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-user-add-proc.adoc
- docs/product-assembly_integrating-sso/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-plug-in-install-proc.adoc
[Jira epic](https://issues.jboss.org/browse/BXMSDOC-2302)
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2302/)
> Bxmsdoc 2401 master final Integrating RH-SSO with PAM

- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-basic-auth-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-central-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-client-adapter-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-int-con.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-kie-server-client-adapter-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-kie-server-client-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-realm-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-remote-services-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-remote-services-securing-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-third-party-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-token-auth-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-user-add-proc.adoc
- docs/product-assembly_integrating-sso/src/main/asciidoc/main.adoc
- docs/product-assembly_integrating-sso/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-development-guide/src/main/asciidoc/dev-studio-plug-in-install-proc.adoc
[Jira epic](https://issues.jboss.org/browse/BXMSDOC-2302)
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2302/)
> BXMSDOC-2401 7.7.x Integrating RH-SSO with PAM

- docs/product-assembly_integrating-dev-studio/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/chap-using-jboss-developer-studio-to-create-and-test-processes.adoc
- docs/product-development-guide/src/main/asciidoc/chap-using-jboss-developer-studio-to-create-and-test-rules.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-clone-remote-git-repo-proc.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-import-local-git-repo-proc.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-plug-in-install-proc.adoc
- docs/product-development-guide/src/main/asciidoc/dm-server-configure-proc.adoc
[Jira epic](https://issues.jboss.org/browse/BXMSDOC-2300)
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2300/)
> BXMSDOC 2402 master Integrating Dev Studio with PAM

- docs/product-assembly_integrating-dev-studio/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/chap-using-jboss-developer-studio-to-create-and-test-processes.adoc
- docs/product-development-guide/src/main/asciidoc/chap-using-jboss-developer-studio-to-create-and-test-rules.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-clone-remote-git-repo-proc.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-import-local-git-repo-proc.adoc
- docs/product-development-guide/src/main/asciidoc/dev-studio-plug-in-install-proc.adoc
- docs/product-development-guide/src/main/asciidoc/dm-server-configure-proc.adoc
[Jira epic](https://issues.jboss.org/browse/BXMSDOC-2300)
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2300/)
> BXMSDOC-2402 7.7.x Integrating Dev Studio with PAM

- docs/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
- docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.8.0.Final-section.adoc
https://issues.jboss.org/browse/AF-1205
> AF-1205 : Use system property for default m2 repository

- docs/product-installation-guide/src/main/asciidoc/installer-run-cli-proc.adoc
Very small change to the installer UI text.
> BXMSDOC-2298a master Installing PAM on EAP

- docs/product-installation-guide/src/main/asciidoc/installer-run-cli-proc.adoc
Updated installer section with Tomcat 5 (UI) change.
> BXMSDOC-2298a 7.7.x Installing PAM on EAP

- docs/product-assembly_clustering-eap/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-artemis-activate-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dev-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-kie-server-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ks-runtime-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-runtime-managed-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-pc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-standalone-pc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-run-cli-proc.adoc
This merge also includes a small change to the EAP installation story.
> Bxmsdoc 2294 may21 Master Update Clustering doc  draft

- docs/product-assembly_clustering-eap/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-artemis-activate-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dev-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-kie-server-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ks-runtime-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-runtime-managed-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-pc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-standalone-pc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-run-cli-proc.adoc
This update also includes a small update for the EAP installation story.
> BXMSDOC-2294-may21 7.7.x Update the clustering draft

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
Updated the main.adoc template. Adding RHPAM-1029.
> /BXMSDOC-2606 7.7.x Release notes for RH PAM final changes 

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
Updated the main.adoc template. Adding RHPAM-1029.
> BXMSDOC-2606 master Release notes for PAM 7.0 final changes

- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
Includes most of Ivo's comments.
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2606/)
[Jira](https://issues.jboss.org/browse/BXMSDOC-2760)
> Bxmsdoc 2760 master Release notes for PAM 7.0 update 1

- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
Includes most of Ivo's comments.
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2606/)
[Jira](https://issues.jboss.org/browse/BXMSDOC-2760)
> BXMSDOC-2760 7.7.x Release Notes for PAM 7.0 update 1

- docs/product-release-notes/src/main/asciidoc/rn-tech-preview-con.adoc
Redoing HA bullet update due to merge issues
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2770
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2770/#technology_preview_features
> Bxmsdoc 2770 master final to upstream Master

- docs/product-assembly_business-processes/src/main/asciidoc/main.adoc
- docs/product-assembly_business-processes/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-getting-started-guide/src/main/asciidoc/data-model-proc.adoc
- docs/product-getting-started-guide/src/main/asciidoc/decision-tables-proc.adoc
- docs/product-getting-started-guide/src/main/asciidoc/monitoring-proc.adoc
- docs/product-getting-started-guide/src/main/asciidoc/new-project-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-con.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-create-proc.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2776/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2776
> Upstream MR from Bxmsdoc 2776 master final to master

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Updates to What's New from Ivo Bek.
[BXMSDOC-2780](https://issues.jboss.org/browse/BXMSDOC-2780)
[HTML](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2606)
> BXMSDOC-2780 master Release Notes for PAM 7.0 - update 3

- docs/product-assembly_business-processes/src/main/asciidoc/main.adoc
- docs/product-assembly_business-processes/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-getting-started-guide/src/main/asciidoc/data-model-proc.adoc
- docs/product-getting-started-guide/src/main/asciidoc/decision-tables-proc.adoc
- docs/product-getting-started-guide/src/main/asciidoc/monitoring-proc.adoc
- docs/product-getting-started-guide/src/main/asciidoc/new-project-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-con.adoc
- docs/product-user-guide/src/main/asciidoc/data-objects-create-proc.adoc
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-2776/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-2776
> Upstream MR from Bxmsdoc 2776 7.7.x final to 7.7.x

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-tech-preview-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Updates to What's New from Ivo Bek.
[BXMSDOC-2780](https://issues.jboss.org/browse/BXMSDOC-2780)
[HTML](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2606)
> BXMSDOC-2780 7.7.x Release Notes for PAM 7.0 - update 3

- docs/product-assembly_openshift-authoring/src/main/asciidoc/main.adoc
- docs/product-assembly_openshift-immutable/src/main/asciidoc/main.adoc
- docs/product-assembly_openshift-managed/src/main/asciidoc/main.adoc
- docs/product-assembly_pam-on-openshift/src/main/asciidoc/glusterfs-reconfig-proc.adoc
* GlusterFS reconfig procedure
* SME review and peer review changes
> BXMSDOC-2785 master

- docs/product-administration-and-configuration-guide/src/main/asciidoc/access-control-con.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-business-central-configuration.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-kie-server-configuration.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-configure-server-managed-by-workbench-proc.adoc
- docs/product-assembly_dmn-models/src/main/asciidoc/main.adoc
- docs/product-assembly_integrating-entando/src/main/asciidoc/main.adoc
- docs/product-assembly_managing-and-monitoring-business-processes/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_managing-and-monitoring-business-processes/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-assembly_openshift-authoring/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_openshift-immutable/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_openshift-managed/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_pam-on-openshift/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_pam-on-openshift/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-assembly_release-notes/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-development-guide/src/main/asciidoc/kie-server-clients-ref.adoc
- docs/product-development-guide/src/main/asciidoc/rest-api-kie-store-summary-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-component-versions-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/chap-the-migration-process.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-java-dependencies-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-planner-changes-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-update-knowledge-store-api-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-update-remote-api-proc.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
- docs/product-user-guide/src/main/asciidoc/entando-app-building-proc.adoc
- docs/product-user-guide/src/main/asciidoc/entando-integrating-proc.adoc
- docs/product-user-guide/src/main/asciidoc/entando-pages-con.adoc
- docs/product-user-guide/src/main/asciidoc/entando-widgets-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-2796).
> BXMSDOC-2796 (for upstream master): Implement bug fixes in PAM docs (Migration, DMN, Entando, Managing and monitoring).

- docs/product-administration-and-configuration-guide/src/main/asciidoc/access-control-con.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-business-central-configuration.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-kie-server-configuration.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-configure-server-managed-by-workbench-proc.adoc
- docs/product-assembly_dmn-models/src/main/asciidoc/main.adoc
- docs/product-assembly_integrating-entando/src/main/asciidoc/main.adoc
- docs/product-assembly_managing-and-monitoring-business-processes/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_managing-and-monitoring-business-processes/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-assembly_openshift-authoring/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_openshift-immutable/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_openshift-managed/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_pam-on-openshift/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_pam-on-openshift/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-assembly_release-notes/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-development-guide/src/main/asciidoc/kie-server-clients-ref.adoc
- docs/product-development-guide/src/main/asciidoc/rest-api-kie-store-summary-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-component-versions-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/chap-the-migration-process.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-java-dependencies-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-planner-changes-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-troubleshooting-ref.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-update-knowledge-store-api-proc.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-update-remote-api-proc.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
- docs/product-user-guide/src/main/asciidoc/entando-app-building-proc.adoc
- docs/product-user-guide/src/main/asciidoc/entando-integrating-proc.adoc
- docs/product-user-guide/src/main/asciidoc/entando-pages-con.adoc
- docs/product-user-guide/src/main/asciidoc/entando-widgets-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-2796).
> BXMSDOC-2796 (for upstream 7.7.x): Implement bug fixes in PAM docs (Migration, DMN, Entando, Managing and monitoring).

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
> BXMSDOC-2818 (for upstream master): Update rebuilt variable for 22 June publish

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
> BXMSDOC-2818 (for upstream 7.7.x): Update rebuilt variable for 22 June publish

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-assembly_release-notes/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-release-notes/src/main/asciidoc/rn-rhpam-701-con.adoc
[BXMSDOC-2762](Create Release Notes for RHPAM 7.0.1)
Added[ FIXED ISSUES IN RED HAT PROCESS AUTOMATION MANAGER 7.0.1](file:///home/emmurphy/Repos/kie-docs/docs/product-assembly_release-notes/src/main/asciidoc/pam/build/tmp/en-US/html-single/index.html#rn-rhpam-701-con) section.
> BXMSDOC-2762 master Create Release Notes for RHPAM 7.0.1

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-assembly_release-notes/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-release-notes/src/main/asciidoc/rn-rhpam-701-con.adoc
[BXMSDOC-2762](Create Release Notes for RHPAM 7.0.1)
Added[ FIXED ISSUES IN RED HAT PROCESS AUTOMATION MANAGER 7.0.1](file:///home/emmurphy/Repos/kie-docs/docs/product-assembly_release-notes/src/main/asciidoc/pam/build/tmp/en-US/html-single/index.html#rn-rhpam-701-con) section.
> BXMSDOC-2763- 7.7.x Create Release Notes for RHPAM 7.0.1

- docs/product-assembly_dm-7.0-release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-7.0.1-fixed-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/ba-dm-rn-known-issues-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-ba.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
Pending SME and peer reviews.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2847)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-2847/#ba-dm-rn-7.0.1-fixed-issues-con)
> BXMSDOC-2847 (for upstream 7.5.x): Update DM RN with 7.0.1 updates.

- docs/product-user-guide/src/main/asciidoc/business-central-settings-creating-new-users-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-sets-caching-con.adoc
Pull request for merging BXMSDOC-2396-master-patch: Expansion of data sets concept content to 7.7.x.
[Rendered Output link - http://file.pnq.redhat.com/~gadey/BXMSDOC-2396/]
[Jira link - https://issues.jboss.org/browse/BXMSDOC-2709]
> Pull Request for BXMSDOC-2396-7.7.x-patch: Expansion of data sets concept

- docs/product-user-guide/src/main/asciidoc/business-central-settings-creating-new-users-proc.adoc
- docs/product-user-guide/src/main/asciidoc/data-sets-caching-con.adoc
Pull request for merging **BXMSDOC-2396-master-patch: Expansion of data sets concept** content to master.
[Rendered Output link - http://file.pnq.redhat.com/~gadey/BXMSDOC-2396/]
[Jira link -  https://issues.jboss.org/browse/BXMSDOC-2709]
> Pull Request for BXMSDOC-2396-master-patch: Expansion of data sets concept

- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
> BXMSDOC-2881 (for upstream master): Updated rebuilt variable for PAM 7.0 docs publish.

- docs/product-assembly_clustering-eap/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_cluster-custom-config-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-configure-host-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-create-dev-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-create-runtime-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-custom-config-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dev-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-domain-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-bc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-ps-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-headless-controller-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-install-eap-bc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-kie-server-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ks-runtime-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ks-runtime-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-configure-host-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-runtime-managed-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-pc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-standalone-pc-proc.adoc
[BXMSDOC-2294](https://issues.jboss.org/browse/BXMSDOC-2294)
[HTML](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2294)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-2882)
[QE Review](https://issues.jboss.org/browse/BXMSDOC-2759)
> Bxmsdoc 2294a master Installing and configuring Red Hat Business Automation in an EAP clustered environment

- docs/product-assembly_clustering-eap/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_cluster-custom-config-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-configure-host-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-create-dev-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-create-runtime-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-custom-config-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dev-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-domain-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-bc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-ps-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-elasticsearch-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-headless-controller-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-install-eap-bc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-kie-server-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ks-runtime-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ks-runtime-standalone-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-configure-host-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-runtime-managed-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-pc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-standalone-pc-proc.adoc
[BXMSDOC-2294](https://issues.jboss.org/browse/BXMSDOC-2294)
[HTML](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2294)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-2882)
[QE Review](https://issues.jboss.org/browse/BXMSDOC-2759)
> Bxmsdoc 2294a 7.7.x Installing and configuring Red Hat Business Automation in an EAP clustered environment

- docs/product-installation-guide/src/main/asciidoc/clustering-dm-install-proc.adoc
[BXMSDOC-2786](https://issues.jboss.org/browse/BXMSDOC-2786)
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2786/#clustering-dm-install-proc)
> BXMSDOC-2786: Clarify "An NFS Cluster"

- docs/product-installation-guide/src/main/asciidoc/clustering-bc-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-headless-controller-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-install-proc.adoc
Includes updates from [BXMSDOC-2911](https://issues.jboss.org/browse/BXMSDOC-2911)
[HTML draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2883/)
> BXMSDOC-2883 7.7.x Clustering support comments

- docs/product-assembly_business-optimizer-running-ER-sample/src/main/asciidoc/main.adoc
- docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
- docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc
- docs/product-assembly_installing-dsps-on-was/src/main/asciidoc/main.adoc
- docs/product-assembly_installing-dsps-on-wls/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-assembly_running-employee-rostering-in-wb/src/main/asciidoc/wb-employee-rostering-data-model-proc.adoc
- docs/product-assembly_running-employee-rostering-in-wb/src/main/asciidoc/wb-employee-rostering-example-deploying-in-central-proc.adoc
- docs/product-assembly_test-scenarios/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-engine-installation-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2748) for details.
> BXMSDOC-2748 (for upstream master): Updated Getting started with ds links throughout docs.

- docs/product-assembly_business-optimizer-running-ER-sample/src/main/asciidoc/main.adoc
- docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
- docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
- docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc
- docs/product-assembly_installing-dsps-on-was/src/main/asciidoc/main.adoc
- docs/product-assembly_installing-dsps-on-wls/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-assembly_running-employee-rostering-in-wb/src/main/asciidoc/wb-employee-rostering-data-model-proc.adoc
- docs/product-assembly_running-employee-rostering-in-wb/src/main/asciidoc/wb-employee-rostering-example-deploying-in-central-proc.adoc
- docs/product-assembly_test-scenarios/src/main/asciidoc/main.adoc
- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-engine-installation-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2748) for details.
> BXMSDOC-2748 (for upstream 7.7.x): Updated Getting started with ds links throughout docs.

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.3.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.4.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.5.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.6.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.7.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.8.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.9.0.Final-section.adoc
Hey @manstis @hasys @tiagodolphine 
Here is the _New & Noteworthy_ section for Stunner at community versions `7.8` and `7.9`.  Please can you give it a quick look? Lemme know if any issues or you think I'm missing something.
Thanks!
> JBPM-7412: Stunner - New & Noteworthy section for 7.8 & 7.9 community versions

- docs/drools-docs/src/main/asciidoc/LanguageReference/Rule-section.adoc
> Missing closed paren in code snippet

- docs/drools-docs/src/main/asciidoc/DMN/FEELDataTypes-section.adoc
@sterobin @baldimir would you mind to have a look please?
> BXMSDOC-3005: Fix links for FEEL data types description

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.3.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.6.4.0.Final-section.adoc
- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.5.0.Final-section.adoc
Remove link to missing images
Fix path where link is incorrect
> Fix broken images

- docs/product-assembly_release-notes/src/main/asciidoc/main.adoc
- docs/product-release-notes/src/main/asciidoc/rn-rhpam-702-fixed-issues-con.adoc
- docs/product-release-notes/src/main/asciidoc/rn-whats-new-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[BXMSDOC-2886](https://issues.jboss.org/browse/BXMSDOC-2886)
> BXMSDOC-2886 7.7.x a RHPAM 7.0.2 release notes

- docs/product-release-notes/src/main/asciidoc/rn-known-issues-con.adoc
[BXMSDOC-3044](https://issues.jboss.org/browse/BXMSDOC-3044)
This jira only affect 7.7.x
> BXMSDOC-3044 7.7.x RHPAM 7.0.2 Known Issues sections lists fixed JIRAs

- docs/product-assembly_interacting-with-processes/src/main/asciidoc/main.adoc
Corrected link for product installation in Prerequisites section of Interacting with tasks & processes story
[Documentation JIRA](https://issues.jboss.org/browse/BXMSDOC-3064) 
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-2334/)
> Pull request for BXMSDOC-3064-7.7.x-final to upstream 7.7.x

- docs/product-assembly_interacting-with-processes/src/main/asciidoc/main.adoc
Corrected link for product installation in Prerequisites section of Interacting with tasks & processes story
[Documentation JIRA](https://issues.jboss.org/browse/BXMSDOC-3064) 
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-2334/)
> Pull request for BXMSDOC-3064-master-final to upstream master

- docs/product-assembly_dm-on-openshift/src/main/asciidoc/imagestreams-file-install-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-central-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-nos2i-deploy-proc.adoc
- docs/product-assembly_dm-on-openshift/src/main/asciidoc/kieserver-s2i-deploy-proc.adoc
* fixed Maven user/password for full deployment
* BXMSDOC-2501
> BXMSDOC 2238 and 2501 master

- docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.10.0.Final-section.adoc
@tsurdilo @cristianonicolai do you mind having a quick look?
> jBPM N&N for 7.10

- docs/product-assembly_planning/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_planning/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/components-con.adoc
[rhpam-7.1-planning](http://file.ork.redhat.com/~emmurphy/rhpam-7.1-planning)
[rhdm-7.1-planning](http://file.ork.redhat.com/~emmurphy/rhdm-7.1-planning)
This is a working draft so SME an QE reviews are not required.
> BXMSDOC-3045 7.7.x Planning: Create initial drafts

- docs/product-assembly_planning/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_planning/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/components-con.adoc
[rhpam-7.1-planning](http://file.ork.redhat.com/~emmurphy/rhpam-7.1-planning)
[rhdm-7.1-planning](http://file.ork.redhat.com/~emmurphy/rhdm-7.1-planning)
This is a working draft so SME an QE reviews are not required.
> BXMSDOC-3045 master Planning: Create initial drafts

- docs/shared-kie-docs/src/main/asciidoc/Workbench/Embedding/Embedding-section.adoc
https://issues.jboss.org/browse/DROOLS-2764
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/783
https://github.com/kiegroup/kie-wb-common/pull/1985
https://github.com/kiegroup/drools-wb/pull/894
https://github.com/kiegroup/optaplanner-wb/pull/292
https://github.com/kiegroup/jbpm-wb/pull/1182
https://github.com/kiegroup/kie-wb-distributions/pull/780
https://github.com/kiegroup/kie-docs/pull/946
> DROOLS-2764 : Remove dead code in AuthoringPerspective, AdministrationPerspective and Social Home Page

- docs/product-assembly_dmn-models/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_dmn-models/src/main/asciidoc/main.adoc
- docs/product-assembly_dmn-models/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-user-guide/src/main/asciidoc/dmn-boxed-expressions-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-conformance-levels-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-data-types-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-decision-tables-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-example-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-feel-enhancements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-feel-overview-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-options-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-remote-java-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-rest-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-model-enhancements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-model-example-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-names-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-properties-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-support-con.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2989) for details.
> BXMSDOC-2989 (for upstream master): Updated DMN models doc for DM/PAM 7.1

- docs/product-assembly_dmn-models/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_dmn-models/src/main/asciidoc/main.adoc
- docs/product-assembly_dmn-models/src/main/asciidoc/pam/master-docinfo.xml
- docs/product-user-guide/src/main/asciidoc/dmn-boxed-expressions-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-conformance-levels-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-data-types-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-decision-tables-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-example-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-elements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-feel-enhancements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-feel-overview-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-embedded-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-options-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-remote-java-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-invocation-rest-proc.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-model-enhancements-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-model-example-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-names-con.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-properties-ref.adoc
- docs/product-user-guide/src/main/asciidoc/dmn-support-con.adoc
Ready for upstream 7.7.x
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2989) for details.
> BXMSDOC-2989 (for upstream 7.7.x): Updated DMN models doc for DM/PAM 7.1

- docs/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- docs/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.11.0.Final-section.adoc
Requires https://github.com/kiegroup/drools/pull/2018
/cc @sterobin @etirelli @baldimir @jiripetrlik
> DROOLS-2832 DMN support for DMN v1.2 serialization

- docs/shared-kie-docs/src/main/asciidoc/Workbench/Embedding/Embedding-section.adoc
I updated the obsolete community documentation about the standalone perspectives to reflect what is supported, tested, and documented in the product documentation.
@jhrcek, @Rikkola, could you please review?
> Update standalone perspectives documentation.

- docs/product-assembly_clustering-eap/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_clustering-eap/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dev-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-ks-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-domain-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-bc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-ps-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-headless-controller-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-install-proc.adoc
http://file.ork.redhat.com/~emmurphy/rhpam-7.1-clustering/
http://file.ork.redhat.com/~emmurphy/rhdm-7.1-clustering/
> BXMSDOC-3068 master RHBA clustering initial draft

- docs/product-assembly_clustering-eap/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_clustering-eap/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-bc-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dev-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-dm-ks-configure-domain-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-domain-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-bc-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-download-eap-ps-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-headless-controller-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-con.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-ps-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-smartrouter-install-proc.adoc
http://file.ork.redhat.com/~emmurphy/rhpam-7.1-clustering/
http://file.ork.redhat.com/~emmurphy/rhdm-7.1-clustering/
> BXMSDOC-3068- 7.7.x RHBA Clustering initial drafts

- docs/product-assembly_installing-dsps-on-was/src/main/asciidoc/main.adoc
- docs/product-assembly_installing-dsps-on-wls/src/main/asciidoc/main.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/controller-was-group-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/controller-was-install-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/controller-was-mapping-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/controller-wls-was-verify-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-environment-set-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-group-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-install-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-mapping-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/kie-server-was-verify-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/main.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/was-controller-classloader-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/was-install-start-proc.adoc
- docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/was-ks-classloader-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/controller-wls-install-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/controller-wls-was-environment-set-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/kie-server-wls-install-proc.adoc
- docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/kie-server-wls-verify-proc.adoc
Includes:
[BXMSDOC-2928](https://issues.jboss.org/browse/BXMSDOC-2928)
[BXMSDOC-2929](https://issues.jboss.org/browse/BXMSDOC-2929)
> /BXMSDOC-3049 7.7.x RHBA WAS and WLS installation stories - initial drafts

- docs/product-assembly_install-on-eap/src/main/asciidoc/main.adoc
- docs/product-assembly_install-on-jws/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_install-on-jws/src/main/asciidoc/main.adoc
- docs/product-assembly_planning/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/maven-managing-dependencies-proc.adoc
- docs/product-development-guide/src/main/asciidoc/maven-settings-configuration-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_chap-installation-options.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_chap-installation.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_chap-introduction.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-jws-using-installer.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-using-installer.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-platforms-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/controller-eap-configure-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/controller-jws-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-configure-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-download-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-options-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-jws-cli-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-jws-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-run-cli-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-pam-jws-con.adoc
- docs/product-installation-guide/src/main/asciidoc/jws-datasource-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/jws-zip-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/roles-users-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[BXMSDOC-3069](https://issues.jboss.org/browse/BXMSDOC-3069) (EAP)
[BXMSDOC-3118](https://issues.jboss.org/browse/BXMSDOC-3118) (JWS DM)
> BXMSDOC-3069 master EAP and JWS installation stories initial drafts

- docs/product-assembly_install-on-eap/src/main/asciidoc/main.adoc
- docs/product-assembly_install-on-jws/src/main/asciidoc/dm/master-docinfo.xml
- docs/product-assembly_install-on-jws/src/main/asciidoc/main.adoc
- docs/product-assembly_planning/src/main/asciidoc/main.adoc
- docs/product-development-guide/src/main/asciidoc/maven-managing-dependencies-proc.adoc
- docs/product-development-guide/src/main/asciidoc/maven-settings-configuration-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_chap-installation-options.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_chap-installation.adoc
- docs/product-installation-guide/src/main/asciidoc/_old_chap-introduction.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-on-jws-using-installer.adoc
- docs/product-installation-guide/src/main/asciidoc/assembly_installing-using-installer.adoc
- docs/product-installation-guide/src/main/asciidoc/ba-dm-supported-platforms-ref.adoc
- docs/product-installation-guide/src/main/asciidoc/controller-eap-configure-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/controller-jws-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-dm-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/eap-execution-server-configure-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-download-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/install-options-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-jws-cli-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-jws-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-run-cli-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installer-run-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-con.adoc
- docs/product-installation-guide/src/main/asciidoc/installing-pam-jws-con.adoc
- docs/product-installation-guide/src/main/asciidoc/jws-datasource-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/jws-zip-install-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/roles-users-con.adoc
- docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc
[BXMSDOC-3069](https://issues.jboss.org/browse/BXMSDOC-3069) (EAP)
[BXMSDOC-3118](https://issues.jboss.org/browse/BXMSDOC-3118) (JWS DM)
> BXMSDOC-3069 7.7.x EAP and JWS 7.1 installation stories initial drafts

- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-central-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-user-manage-proc.adoc
- docs/product-assembly_integrating-dev-studio/src/main/asciidoc/main.adoc
- docs/product-assembly_planning/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/components-con.adoc
Fixed build issue in SSO doc, updated the context in Dev Studio, and added SME updates to the Planning doc.
https://issues.jboss.org/browse/BXMSDOC-3071 - Planning
https://issues.jboss.org/browse/BXMSDOC-3098 - SSO
> BXMSDOC-3098 master SSO, Dev Studio, Planning

- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-central-proc.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-user-manage-proc.adoc
- docs/product-assembly_integrating-dev-studio/src/main/asciidoc/main.adoc
- docs/product-assembly_planning/src/main/asciidoc/main.adoc
- docs/product-installation-guide/src/main/asciidoc/components-con.adoc
Fixed build issue in SSO doc, updated the context in Dev Studio, and added SME updates to the Planning doc.
https://issues.jboss.org/browse/BXMSDOC-3071 - Planning
https://issues.jboss.org/browse/BXMSDOC-3098 - SSO
> BXMSDOC-3098 7.7.x SSO, Dev Studio, Planning

- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/code-troubleshooting-ref.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/main.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/migration-planner-changes-ref.adoc
- docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/migration-planner-config-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3180) for details.
> BXMSDOC-3180 (for upstream 7.5.x): Added section on Optimizer config changes in Central for DM 7.0 migration doc.

- doc-content/drools-docs/src/main/asciidoc/index.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/ReleaseInformation/CompatibilityMatrix-chapter.adoc
This PR reduces scrolling done by newcomers finding getting started steps
@sterobin I would appreciate your review when you have a moment.
> Move release notes to last chapter

- doc-content/pom.xml
> [7.11.x] Copy images to target folder

- doc-content/drools-docs/src/main/asciidoc/UserGuide/DecisionTables-section.adoc
@manstis @sterobin please have a look when you have a moment. Also let me know if should be cherry-picked into 7.11.x.
> BAQE-579: Document missing XLS decision table attributes

- doc-content/drools-docs/src/main/asciidoc/UserGuide/DecisionTables-section.adoc
> [7.11.x] BAQE-579: Document missing XLS decision table attributes

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSourceManagement/DataSourceManagement-section.adoc
Part of an ensemble:
* https://github.com/kiegroup/kie-docs/pull/1055
* https://github.com/kiegroup/kie-wb-common/pull/2101
> AF-1549: jdbc drivers should not be download by default

- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
Code here:
https://github.com/kiegroup/appformer/pull/457
@jhrcek @barboras7 @tomasdavidorg @domhanak @ederign @emmurphy1 @sterobin
> AF-1554: document the new SSH over HTTP proxy variables

- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
Code here:
https://github.com/kiegroup/kie-soup/pull/63
@jhrcek @ederign @emmurphy1 @sterobin @manstis
> AF-1528: updated the new env variable that forces maven offline

- assemblies/assembly_install-on-eap/main.adoc
- doc-content/enterprise-only/admin-and-config/assets-executing-proc.adoc
- doc-content/enterprise-only/admin-and-config/maven-managing-dependencies-proc.adoc
- doc-content/enterprise-only/installation/controller-con.adoc
- doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/installation/eap-execution-server-configure-proc.adoc
- doc-content/enterprise-only/installation/git-import-proc.adoc
- doc-content/enterprise-only/installation/install-download-proc.adoc
- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/install-testing-proc.adoc
- doc-content/enterprise-only/installation/installer-jws-cli-proc.adoc
- doc-content/enterprise-only/installation/installer-jws-proc.adoc
- doc-content/enterprise-only/installation/installer-run-cli-proc.adoc
- doc-content/enterprise-only/installation/installer-run-proc.adoc
- doc-content/enterprise-only/installation/installing-con.adoc
- doc-content/enterprise-only/installation/installing-pam-jws-con.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-java-proc.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-maven-proc.adoc
Includes epic [BXMSDOC-2947](https://issues.jboss.org/browse/BXMSDOC-2947) and epic [BXMSDOC-2896](https://issues.jboss.org/browse/BXMSDOC-2896).
[RHPAM-EAP draft](http://file.ork.redhat.com/~emmurphy/rhpam-7.1-eap)
[RHDM-EAP draft](http://file.ork.redhat.com/~emmurphy/rhdm-7.1-eap)
[RHDM-JWS draft](http://file.ork.redhat.com/~emmurphy/rhdm-7.1-jws)
> BXMSDOC-3144  7.11.x RHPAM/RHDM 7.1 EAP installation, RHDM 7.1 JWS installation

- assemblies/assembly_install-on-eap/main.adoc
- doc-content/enterprise-only/admin-and-config/assets-executing-proc.adoc
- doc-content/enterprise-only/admin-and-config/maven-managing-dependencies-proc.adoc
- doc-content/enterprise-only/installation/controller-con.adoc
- doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/installation/eap-execution-server-configure-proc.adoc
- doc-content/enterprise-only/installation/git-import-proc.adoc
- doc-content/enterprise-only/installation/install-download-proc.adoc
- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/install-testing-proc.adoc
- doc-content/enterprise-only/installation/installer-jws-cli-proc.adoc
- doc-content/enterprise-only/installation/installer-jws-proc.adoc
- doc-content/enterprise-only/installation/installer-run-cli-proc.adoc
- doc-content/enterprise-only/installation/installer-run-proc.adoc
- doc-content/enterprise-only/installation/installing-con.adoc
- doc-content/enterprise-only/installation/installing-pam-jws-con.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-java-proc.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-maven-proc.adoc
Includes epic [BXMSDOC-2947](https://issues.jboss.org/browse/BXMSDOC-2947) and epic [BXMSDOC-2896](https://issues.jboss.org/browse/BXMSDOC-2896).
[RHPAM-EAP draft](http://file.ork.redhat.com/~emmurphy/rhpam-7.1-eap)
[RHDM-EAP draft](http://file.ork.redhat.com/~emmurphy/rhdm-7.1-eap)
[RHDM-JWS draft](http://file.ork.redhat.com/~emmurphy/rhdm-7.1-jws)
> BXMSDOC-3144  master RHPAM/RHDM 7.1 EAP installation, RHDM 7.1 JWS installation

- doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
- doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
Replaced PRODUCT_VERSION with PRODUCT_VERSION_LONG in two places, for the clustering doc.
> BXMSDOC-3245 master Final Changes to Clustering doc

- doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc
- doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
Replaced PRODUCT_VERSION with PRODUCT_VERSION_LONG in two places, for the clustering doc.
> BXMSDOC-3245 7.11.x Final Changes to Clustering doc

- assemblies/assembly_decision-manager/main.adoc
- doc-content/enterprise-only/getting-started/new-project-proc.adoc
https://github.com/michelehaglund/kie-docs/pull/72
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-3067/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-3067
> Upstream PR for Bxmsdoc 3067 to Master - Getting started with Decision Services for DM and PAM 7.1

- assemblies/assembly_decision-manager/main.adoc
- doc-content/enterprise-only/getting-started/new-project-proc.adoc
Pull request: https://github.com/michelehaglund/kie-docs/pull/72
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-3067/
Original Jira: https://issues.jboss.org/browse/BXMSDOC-3067
> Upstream PR for Bxmsdoc 3067 to 7.11.x - Getting started with Decision Services for DM and PAM 7.1

- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
These PRs should be merged all together:
https://github.com/kiegroup/kie-soup/pull/65
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/839
https://github.com/kiegroup/appformer/pull/470
https://github.com/kiegroup/kie-wb-common/pull/2135
https://github.com/kiegroup/kie-wb-distributions/pull/818
https://github.com/kiegroup/kie-docs/pull/1094
> AF-1528 revert

- doc-content/drools-docs/src/main/asciidoc/LanguageReference/Rule-section.adoc
@sterobin @manstis would you mind to have a look?
> BAQE-650: document drools.defaultlanguage and drools.defaultcountry

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.12.0.Final-section.adoc
@sterobin @etirelli please have a look.
> 7.12.0.Final Release notes

- doc-content/enterprise-only/admin-and-config/kie-server-bootstrap-switches-ref.adoc
- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/Configuration-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
Upstream master PR for managing & monitoring process server (For PAM 7.1)
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284/#migration-configure-kie-server-proc)
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-2934)
> BXMSDOC-3284: Upstream master PR for managing & monitoring process server (For PAM 7.1)

- doc-content/enterprise-only/admin-and-config/kie-server-bootstrap-switches-ref.adoc
- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/Configuration-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
Upstream 7.11.x PR for managing & monitoring process server (For PAM 7.1)
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284/#migration-configure-kie-server-proc)
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-2934)
> BXMSDOC-3284: Upstream 7.11.x PR for managing & monitoring process server (For PAM 7.1)

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
> BXMSDOC-3289- 7.11.x 7.1 RN updates to Known Issues

- doc-content/pom.xml
@sterobin @manstis would you mind to have a look?
> Increase asciidoctor-maven-plugin version

- doc-content/jbpm-docs/src/main/asciidoc/Console/ErrorManagement-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Console/TaskManagement-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/DomainSpecificProcesses/ServiceRepository-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.8.0.Final-section.adoc
For more details see: https://issues.jboss.org/browse/BAQE-691
@mswiderski @sterobin could you please have a look?
> BAQE-691: Fix build warnings

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.13.0.Final-section.adoc
@tsurdilo @cristianonicolai N&N for 7.13
> jBPM N&N for 7.13 release

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
@emmurphy1 @sterobin @Rikkola @ederign pease review
> removing tomcat 8 support from wb docs

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/GuidedRuleEditor-section.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/XLSDecisionTable-section.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-defining-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-rule-table-entries-ref.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/drl-rules-WHEN-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/drl-rules-central-create-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-errors-ref.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-rules-WHEN-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/LanguageReference/TypeDeclaration-section.adoc
@sterobin @manstis I would like to ask you for a review, when you have a moment.
> BXMSDOC-3292: Update code snippets

- doc-content/enterprise-only/admin-and-config/kie-server-configure-server-managed-by-workbench-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-configuring-githooks-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-using-settings-xml-ref.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-using-usergroupcallback-ref.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-content-manager-proc.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-library-proc.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-standalone-custom-pages-proc.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-standalone-editor-proc.adoc
- doc-content/enterprise-only/installation/eap-execution-server-configure-proc.adoc
This upstream PR has sanity-check fixes for Gaurav's docs.
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-3324)
Fixed the issues listed in the jira for the following three docs:
* MANAGING AND MONITORING PROCESS SERVER - [PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284-pam/), [DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284-dm/)
* USING STANDALONE PERSPECTIVES IN BUSINESS CENTRAL - [PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-2743/), [DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-2743-dm/)
* CONFIGURING BUSINESS CENTRAL SETTINGS AND PROPERTIES - [PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3080-pam/), [DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3080-dm/)
> BXMSDOC-3324-7.11.x-final: Upstream 7.11.x PR

- doc-content/enterprise-only/admin-and-config/kie-server-configure-server-managed-by-workbench-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-configuring-githooks-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-using-settings-xml-ref.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-using-usergroupcallback-ref.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-content-manager-proc.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-library-proc.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-standalone-custom-pages-proc.adoc
- doc-content/enterprise-only/admin-and-config/using-standalone-perspectives-standalone-editor-proc.adoc
- doc-content/enterprise-only/installation/eap-execution-server-configure-proc.adoc
This upstream PR has sanity-check fixes for Gaurav's docs.
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-3324)
Fixed the issues listed in the jira for the following three docs:
* MANAGING AND MONITORING PROCESS SERVER - [PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284-pam/), [DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284-dm/)
* USING STANDALONE PERSPECTIVES IN BUSINESS CENTRAL - [PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-2743/), [DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-2743-dm/)
* CONFIGURING BUSINESS CENTRAL SETTINGS AND PROPERTIES - [PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3080-pam/), [DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3080-dm/)
> BXMSDOC-3324-master-final: Upstream master PR 

- doc-content/enterprise-only/installation/clustering-bc-configure-host-proc.adoc
- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.13.0.Final-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.14.0.Final-section.adoc
@sterobin @emmurphy1 @ederign @jhrcek docs for https://github.com/kiegroup/appformer/pull/469
> AF-1585: properly document automatic port assignment in case of already in use

- docs/jbpm-docs/src/main/asciidoc/CoreEngine/Configuration-section.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/appe-properties.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-bootstrap-switches-ref.adoc
- docs/product-development-guide/src/main/asciidoc/chap-kie-api.adoc
- docs/product-development-guide/src/main/asciidoc/chap-working-with-processes.adoc
- docs/product-installation-guide/src/main/asciidoc/clustering-headless-controller-proc.adoc
- docs/product-installation-guide/src/main/asciidoc/controller-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-configure-kie-server-proc.adoc
- docs/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
Upstream 7.7.x PR for managing & monitoring process server (For PAM 7.0)
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3284-7.7.x/#migration-configure-kie-server-proc)
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-2934)
> BXMSDOC-3284: Upstream 7.7.x PR for managing & monitoring process server (For PAM 7.0)

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/XLSDecisionTable-section.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-con.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-decision-tables-ref.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Activities-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Events-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Process-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Process-section.html
- doc-content/jbpm-docs/src/main/asciidoc/DomainSpecificProcesses/Overview-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Spring/KieSpring-chapter.adoc
Ready for upstream 7.11.x
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3345) for details.
> BXMSDOC-3345-7.11.x: Fixed broken links in community docs.

- doc-content/enterprise-only/getting-started/data-model-proc.adoc
@sterobin @manstis please have a look when you have a moment.
> BXMSDOC-3334: Fix name of data object

- doc-content/enterprise-only/getting-started/data-model-proc.adoc
> [7.11.x] BXMSDOC-3334: Fix name of data object

- assemblies/assembly_release-notes/main.adoc
- doc-content/enterprise-only/release-notes/rn-7.1.1-fixed-issues-ref.adoc
[BXMSDOC-3333](https://issues.jboss.org/browse/BXMSDOC-3333)
[RHPAM RN](http://file.ork.redhat.com/~emmurphy/BXMSDOC-3333-pam/#rn-7.1.1-fixed-issues-ref)
[RHDM RN](http://file.ork.redhat.com/~emmurphy/BXMSDOC-3333-dm/#rn-7.1.1-fixed-issues-ref)
Added Fixed Issues in 7.1.1 chapter.
> BXMSDOC-3333 7.11.x Release notes for BA 7.1.1 patch

- assemblies/assembly_release-notes/main.adoc
- doc-content/enterprise-only/release-notes/rn-7.1.1-fixed-issues-ref.adoc
[BXMSDOC-3333](https://issues.jboss.org/browse/BXMSDOC-3333)
[RHPAM RN](http://file.ork.redhat.com/~emmurphy/BXMSDOC-3333-pam/#rn-7.1.1-fixed-issues-ref)
[RHDM RN](http://file.ork.redhat.com/~emmurphy/BXMSDOC-3333-dm/#rn-7.1.1-fixed-issues-ref)
Added Fixed Issues in 7.1.1 chapter.
> Bxmsdoc 3333 master Release notes for BA 7.1.1 patch

- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
Upgrate to Wildfly 14
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
* https://github.com/kiegroup/optaplanner/pull/437
* https://github.com/kiegroup/optaplanner-wb/pull/304
> AF-1555: Updated WF11 to WF14

- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-integrating-red-hat-jboss-bxms-with-red-hat-sso.adoc
- docs/product-administration-and-configuration-guide/src/main/asciidoc/sso-remote-services-proc.adoc
[BXMSDOC-1696 ](https://issues.jboss.org/browse/BXMSDOC-1696)and [BXMSDOC-3008](https://issues.jboss.org/browse/BXMSDOC-3008)
> BXMSDOC 1696 7.7.x updated SSO section

- doc-content/enterprise-only/integration/sso-remote-services-proc.adoc
[BXMSDOC-1696 ](https://issues.jboss.org/browse/BXMSDOC-1696)and [BXMSDOC-3008](https://issues.jboss.org/browse/BXMSDOC-3008)
> BXMSDOC-1696 master updated SSO section

- docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-integrating-red-hat-jboss-bxms-with-red-hat-sso.adoc
[BXMSDOC-1696 ](https://issues.jboss.org/browse/BXMSDOC-1696)and [BXMSDOC-3008](https://issues.jboss.org/browse/BXMSDOC-3008)
> BXMSDOC-1696 7.5.x

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-properties-ref.adoc
/cc @sterobin submitting first draft.
I expect there will be more details to reference once Epic DROOLS-3068 DMN Compilation test e2e
is finalized, so I would wait for this to be merged once we can completely add any missing details out of that.
/cc @etirelli
> DROOLS-3176 Document DMN org.kie.dmn.compiler.execmodel flag(s)

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.12.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.14.0.Final-section.adoc
Superseeeds https://github.com/kiegroup/kie-docs/pull/1172
/cc @lucamolteni @sterobin
> Support DMN Executable Model classes in kie-maven-plugin

- doc-content/jbpm-docs/src/main/asciidoc/Integration/Maven-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Integration/Spring-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Persistence/Audit-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Persistence/Configuration-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Persistence/Transactions-section.adoc
@mswiderski would you kindly review? There should be no mention of Bitronix in jBPM documentation now.
> JBPM-7946 Replace Bitronix in jBPM engine documentation

- assemblies/assembly_interacting-with-processes/main.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-migrating-process-designer-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-advanced-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-basic-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-advanced-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-viewing-process-instance-history-log-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-viewing-task-history-log-proc.adoc
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3375)
[PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3469-pam/)
[DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3469-dm/)
> BXMSDOC-3469: Upstream master PR for Interacting with processes & tasks 7.2

- assemblies/assembly_interacting-with-processes/main.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-migrating-process-designer-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-advanced-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-basic-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-advanced-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-viewing-process-instance-history-log-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-viewing-task-history-log-proc.adoc
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3375)
[PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3469-pam/)
[DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3469-dm/)
> BXMSDOC-3469: Upstream 7.11.x PR for Interacting with processes & tasks 7.2

- doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/Services-section.adoc
Same change from 6.4 Dev Guide [merge request in GitLab](https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/bxms-docs/merge_requests/325). See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2876) for details.
Note: For some reason this PR is also tracking a lot of extraneous spacing tweaks that were not made in this PR. I've seen this happen before and don't know the cause. Makes no diff in the end though.
> BXMSDOC-2876-master: Update ProcessInstanceMigration section in jBPM community doc

- _artifacts/document-attributes.adoc
- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
Pending SME review. See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3421) for details.
> BXMSDOC-3421-master: Updated patching and upgrading doc for 7.2

- doc-content/enterprise-only/openshift/environment-trial-proc.adoc
* first draft CORS text
* peer review
> BXMSDOC-3099 master

- doc-content/enterprise-only/openshift/environment-trial-proc.adoc
* first draft CORS text
* peer review
> BXMSDOC 3099 7.11.x

- doc-content/enterprise-only/openshift/environment-managed-con.adoc
- doc-content/enterprise-only/openshift/environment-managed-deploy-proc.adoc
* first version of changes for BXMSDOC-3427
* peer review
> BXMSDOC-3427 master

- doc-content/enterprise-only/openshift/environment-managed-con.adoc
- doc-content/enterprise-only/openshift/environment-managed-deploy-proc.adoc
* first version of changes for BXMSDOC-3427
* peer review
> BXMSDOC-3427 7.11.x

- assemblies/assembly_configuring-central/main.adoc
- doc-content/enterprise-only/admin-and-config/business-central-editing-data-sources-proc.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-changing-home-proc.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-creating-new-groups-proc.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-creating-new-users-proc.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-setting-priorities-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-editing-groups-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-process-designer-proc.adoc
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-3293)
[PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3293/)
[DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3293-dm/)
> BXMSDOC-3293: Upstream 7.11.x PR for editing role and group permissions sections

- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- doc-content/enterprise-only/openshift/authoring-params.adoc
- doc-content/enterprise-only/openshift/githooks-proc.adoc
* git hooks
* SME and peer review
> Bxmsdoc 3196 7.11.x - this does apply to 7.1

- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- doc-content/enterprise-only/openshift/authoring-params.adoc
- doc-content/enterprise-only/openshift/githooks-proc.adoc
* git hooks
* SME and peer review
> BXMSDOC-3196 master

- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- doc-content/enterprise-only/openshift/authoring-params.adoc
- doc-content/enterprise-only/openshift/githooks-proc.adoc
* git hooks
* SME and peer review
> BXMSDOC-3196 7.14.x

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.15.0.Final-section.adoc
> DROOLS-3335 Broken DMN resource to inhibit KJAR and report error

- _artifacts/document-attributes.adoc
- assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-process-administration-con.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-viewing-process-instance-history-log-proc.adoc
- doc-content/enterprise-only/processes/process-definitions-con.adoc
- doc-content/enterprise-only/processes/process-instance-details-con.adoc
[Jira ID](https://issues.jboss.org/browse/BXMSDOC-3372)
[PAM Rendered Output 7.2](http://file.pnq.redhat.com/~gadey/BXMSDOC-3483/)
> BXMSDOC-3483: Upstream 7.14.x PR for managing & monitoring business processes for PAM 7.2

- assemblies/assembly_openshift-immutable/main.adoc
- doc-content/enterprise-only/openshift/environment-immutable-con.adoc
- doc-content/enterprise-only/openshift/environment-immutable-modify-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-server-kjar-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-server-proc.adoc
- doc-content/enterprise-only/openshift/externaldb-params.adoc
* KJAR immutable
* SME review
* peer review
> BXMSDOC-3308 master

- assemblies/assembly_openshift-immutable/main.adoc
- doc-content/enterprise-only/openshift/environment-immutable-con.adoc
- doc-content/enterprise-only/openshift/environment-immutable-modify-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-server-kjar-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-server-proc.adoc
- doc-content/enterprise-only/openshift/externaldb-params.adoc
* KJAR immutable
* SME review
* peer review
> BXMSDOC-3308 7.14.x

- doc-content/drools-docs/src/main/asciidoc/Examples-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/Examples/HelloWorldExample-section.adoc
- doc-content/drools-docs/src/main/asciidoc/Examples/running-examples-proc.adoc
- Add new running-examples-proc
- Update Hello World example
> BXMSDOC-3579 master Ron

- doc-content/drools-docs/src/main/asciidoc/Examples-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/Examples/HelloWorldExample-section.adoc
- doc-content/drools-docs/src/main/asciidoc/Examples/running-examples-proc.adoc
> Bxmsdoc 3579 7.14.x ron

- doc-content/drools-docs/src/main/asciidoc/Examples/BackwardChaining-section.adoc
Update backward chaining example
> BXMSDOC-3579-master-Ron: Update backward chaining example

- doc-content/drools-docs/src/main/asciidoc/Examples/BackwardChaining-section.adoc
> BXMSDOC-3579-7.14.x-Ron: Update backward chaining example

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.11.0.Final-section.adoc
> 7.11.x - 7.11 Release Notes: describe new marshallers flag

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.11.0.Final-section.adoc
> 7.14.x - 7.11 Release Notes: describe new marshallers flag

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-embedded-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.15.0.Final-section.adoc
> BXMSDOC-3593: Update DMN docs with new KieRuntimeFactory API

- assemblies/assembly_business-optimizer-ER-sample-openshift/main.adoc
- doc-content/enterprise-only/employee-rostering/er-availability-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-script-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-template-con.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-template-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-employees-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-individualroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-shiftroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-skills-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-solve-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-spots-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-tenants-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-openshift-deploy-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-source-con.adoc
* template deployment, typo fix
* UI changes and style
* add registry auth ref
* Registry auth and namespaces from anotehr branch, to revert before PR to master
* additional peer review changes
* SME review
* RHDM deliverables only
* peer review
* remove separate reg auth
* imagestream install to master version
> Bxmsdoc 3423 master

- assemblies/assembly_business-optimizer-ER-sample-openshift/main.adoc
- doc-content/enterprise-only/employee-rostering/er-availability-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-script-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-template-con.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-template-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-employees-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-individualroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-shiftroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-skills-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-solve-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-spots-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-tenants-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-openshift-deploy-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-source-con.adoc
* template deployment, typo fix
* UI changes and style
* add registry auth ref
* Registry auth and namespaces from anotehr branch, to revert before PR to master
* additional peer review changes
* SME review
* RHDM deliverables only
* peer review
* remove separate reg auth
* imagestream install to master version
> Bxmsdoc 3423 7.14.x

- assemblies/assembly_install-on-eap/main.adoc
- doc-content/enterprise-only/installation/clustering-bc-configure-domain-proc.adoc
- doc-content/enterprise-only/installation/clustering-bc-configure-host-proc.adoc
- doc-content/enterprise-only/installation/clustering-dm-ks-configure-domain-proc.adoc
- doc-content/enterprise-only/installation/clustering-ps-install-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-run-proc.adoc
- doc-content/enterprise-only/installation/eap-dm-install-proc.adoc
- doc-content/enterprise-only/installation/eap-execution-server-download-install-proc.adoc
- doc-content/enterprise-only/installation/install-testing-proc.adoc
- doc-content/enterprise-only/installation/installer-run-cli-proc.adoc
> Bxmsdoc 3393 7.14.x RHPAM/DM EAP Installation

- doc-content/enterprise-only/integration/sso-user-manage-proc.adoc
BXMDOC-3548 updated WEB-INF/classes/security
> BXMSDOC 3548 7.14.x Update Authenticating Business Central through RH-SSO chapter

- assemblies/assembly_interacting-with-processes/main.adoc
- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-deactivate-kie-containers-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tsl-support-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-special-filter-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-special-filter-proc.adoc
Upstream 7.14.x PR.
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3436)
[PAM Rendered Output - Process Server](http://file.pnq.redhat.com/~gadey/BXMSDOC-3436-process-server-pam/)
[DM Rendered Output - Process Server](http://file.pnq.redhat.com/~gadey/BXMSDOC-3436-process-server-dm/)
[PAM Rendered Output - Interacting with processes and tasks](http://file.pnq.redhat.com/~gadey/BXMSDOC-3436-pam/)
> BXMSDOC-3436: Upstream 7.14.x PR for Managing & monitoring process server for DM/PAM 7.2

- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/create-branches-proc.adoc
- doc-content/enterprise-only/project-data/modify-project-proc.adoc
- doc-content/enterprise-only/project-data/modify-projects-overview-con.adoc
- doc-content/enterprise-only/project-data/multiple-branches-project-con.adoc
- doc-content/enterprise-only/project-data/new-project-proc.adoc
- doc-content/enterprise-only/project-data/select-branches-proc.adoc
BXMSDOC-3512: Managing projects in Business Central v7.2
Original JIRA : https://issues.jboss.org/browse/BXMSDOC-3512
Original Epic : https://issues.jboss.org/browse/BXMSDOC-3382
Rendered Output : 
RHDM: http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3512-RHDM-QE-Changes/
RHPAM: http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3512-RHPAM-QE-Changes/
> BXMSDOC-3512 : Upstream 7.14.x PR

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.16.0.Final-section.adoc
@sterobin @kkufova may I ask you for a review? Any suggestions are welcome.
> DROOLS-2932: Add release notes for keyboard control

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
AF-1709: Documenting new system property
> AF-1709: Documenting new system property

- shared/Workbench/Installation/Installation.xml
Description oforg.uberfire.nio.git.ssh.cyphers and
org.uberfire.nio.git.ssh.macs
@porcelli @domhanak
> [AF 1775 6.5.x] SSH Ciphers and MAC configured via args on startup 

- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
@porcelli @emmurphy1 @sterobin
> [AF 1775] Fix typo

- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
https://github.com/kiegroup/appformer/pull/562
> [AF-1733] Turn off the ssl verification when cloning a git project

- _artifacts/document-attributes.adoc
Upstream 7.11.x PR for updating rebuilt variable.
> BXMSDOC-3714: Upstream 7.11.x PR for updating rebuilt variable

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.17.0.Final-section.adoc
> DROOLS-3540 DMN align FEEL built-in function parameters name

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/drl-rules-THEN-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/drl-rules-WHEN-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-decision-tables-con.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-template-proc.adoc
- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-call-solver-proc.adoc
- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-register-solver-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3743) for details.
> BXMSDOC-3743-master: Minor tweaks after 7.2 GA final sanity checks

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.17.0.Final-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.17.0.Final-section.adoc
@kkufova @Rikkola 
@tarilabs small fix for DROOLS-3540
> [DROOLS-3507] Test Scenario is now enabled by default

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.17.0.Final-section.adoc
@tsurdilo @cristianonicolai could one of you review before the branch for 7.17 on Monday?
> jBPM 7.17 N&N

- _artifacts/document-attributes.adoc
- assemblies/assembly_business-optimizer/pam/master-docinfo.xml
- assemblies/assembly_decision-tables/dm/master-docinfo.xml
- assemblies/assembly_decision-tables/drools/master-docinfo.xml
- assemblies/assembly_decision-tables/jbpm/master-docinfo.xml
- assemblies/assembly_decision-tables/main.adoc
- assemblies/assembly_decision-tables/pam/master-docinfo.xml
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/XLSDecisionTable-section.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-con.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-defining-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-rule-table-entries-ref.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-upload-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-use-case-con.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-con.adoc
- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/rules-authoring-assets-ref.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-decision-tables-con.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-support-con.adoc
- doc-content/drools-docs/src/main/asciidoc/Examples/decision-examples-pricing-ref.adoc
- doc-content/enterprise-only/getting-started/assets-types-ref.adoc
See [JIRA](url) for details. This PR also updates version variables for 7.3.
> BXMSDOC-3663-master: Change 'uploaded decision tables' to 'spreadsheet decision tables`, etc.

- assemblies/assembly_dmn-models/main.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-drd-components-ref.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-model-creating-proc.adoc
- doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.17.0.Final-section.adoc
Also remove the note about tech preview state of the DMN designer.
@sterobin @manstis would you mind to have a look?
> DROOLS-1932: Add release notes about decision service

- doc-content/enterprise-only/bpmn/bpmn-artifacts-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-business-rule-task-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-end-events-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-gateways-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-intermediate-events-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-start-events-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
https://github.com/emmurphy1/kie-docs/pull/146
> BXMSDOC-3752 7.14 BPMN ref: update tables and table headings

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
https://github.com/emmurphy1/kie-docs/pull/147
> BXMSDOC-3769 master fixed you are you are typo

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
https://github.com/emmurphy1/kie-docs/pull/147
> BXMSDOC-3769 7.14.x fixed you are you are typo

- doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc
This PR adds a system property to enable/disable Gzip compression on GzipFilter.
Related PRs:
https://github.com/kiegroup/appformer/pull/631
https://github.com/kiegroup/kie-wb-distributions/pull/877
https://github.com/kiegroup/kie-docs/pull/1395
> AF-1817: Gzip Filter

- assemblies/assembly_openshift-ansible-playbook/main.adoc
- assemblies/assembly_openshift-immutable/main.adoc
- assemblies/assembly_openshift-managed/main.adoc
- doc-content/enterprise-only/openshift/apb-deploy-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-monitoring-proc.adoc
- doc-content/enterprise-only/openshift/environment-managed-deploy-proc.adoc
- doc-content/enterprise-only/openshift/imagestreams-file-install-proc.adoc
- doc-content/enterprise-only/openshift/rhdm72-authoring-ha-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-authoring-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-prod-immutable-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-trial-ephemeral-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-authoring-ha-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-authoring-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-kieserver-externaldb-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-kieserver-mysql-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-kieserver-postgresql-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-prod-immutable-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-prod-immutable-monitor-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-prod-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-trial-ephemeral-ref.adoc
- doc-content/enterprise-only/openshift/secrets-central-create-proc.adoc
- doc-content/enterprise-only/openshift/secrets-kie-create-proc.adoc
- doc-content/enterprise-only/openshift/secrets-smartrouter-create-proc.adoc
…#36)
* First QA review changes
* secrets, external DB
* more peer review changes and smart router secret
* Hopefully-final SME/QE review changes
* more review changes
* new template autodocs
> BXMSDOC-3727 and 3729 master

- assemblies/assembly_openshift-ansible-playbook/main.adoc
- assemblies/assembly_openshift-immutable/main.adoc
- assemblies/assembly_openshift-managed/main.adoc
- doc-content/enterprise-only/openshift/apb-deploy-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-monitoring-proc.adoc
- doc-content/enterprise-only/openshift/environment-managed-deploy-proc.adoc
- doc-content/enterprise-only/openshift/imagestreams-file-install-proc.adoc
- doc-content/enterprise-only/openshift/rhdm72-authoring-ha-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-authoring-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-prod-immutable-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhdm72-trial-ephemeral-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-authoring-ha-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-authoring-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-kieserver-externaldb-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-kieserver-mysql-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-kieserver-postgresql-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-prod-immutable-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-prod-immutable-monitor-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-prod-ref.adoc
- doc-content/enterprise-only/openshift/rhpam72-trial-ephemeral-ref.adoc
- doc-content/enterprise-only/openshift/secrets-central-create-proc.adoc
- doc-content/enterprise-only/openshift/secrets-kie-create-proc.adoc
- doc-content/enterprise-only/openshift/secrets-smartrouter-create-proc.adoc
…#36)
* First QA review changes
* secrets, external DB
* more peer review changes and smart router secret
* Hopefully-final SME/QE review changes
* more review changes
* new template autodocs
> BXMSDOC-3727 and 3729 7.14.x

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.18.0.Final-section.adoc
Updated N&N with the latest changes regarding to Streamline Development.
This is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1747
https://github.com/kiegroup/kie-wb-common/pull/2497
https://github.com/kiegroup/kie-docs/pull/1409
> AF-1865: [Streamline Development Lifcycle] Fix backguard compatibilities and improve 'dev mode' deployment policy

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.18.0.Final-section.adoc
Backport of https://github.com/kiegroup/kie-docs/pull/1409
Updated N&N with the latest changes regarding to Streamline Development.
This is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1748
https://github.com/kiegroup/kie-wb-common/pull/2499
https://github.com/kiegroup/kie-docs/pull/1410
> [7.18.x] AF-1865: [Streamline Development Lifcycle] Fix backguard compatibilities and improve 'dev mode' deployment policy

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/TestScenarioPreviewEditor-section.adoc
> Test Scenarios: change 'editor' to 'designer' (master).

- doc-content/enterprise-only/admin-and-config/managing-business-central-configuring-githooks-proc.adoc
Adds segment that describes setup needed for Windows environment.
Back port of - https://github.com/kiegroup/appformer/pull/653
> [7.18.x] BAPL-1141 - Improve Git Hooks mechanism for remote integration

- doc-content/enterprise-only/admin-and-config/managing-business-central-configuring-githooks-proc.adoc
Adds segment that describes setup needed for Windows environment.
@gadeyredhat Hello, please could you take a look and modify to your liking? I was unable to render it locally so help is appreciated.
@pefernan @gadeyredhat @ederign
> BAPL-1141 - Improve Git Hooks mechanism for remote integration

- doc-content/enterprise-only/integration/sso-kie-server-con.adoc
- doc-content/enterprise-only/integration/sso-token-auth-proc.adoc
- doc-content/enterprise-only/integration/sso-user-add-proc.adoc
- doc-content/enterprise-only/integration/sso-user-manage-proc.adoc
* BXMSDOC-3681-master: Add exclusion to code block of jboss-deployment-structure.xml modification step
* BXMSDOC-3681-master: Correct minor errors and change phrasing
* BXMSDOC-3681-master: Revert from "rather than" to "instead of"
> BXMSDOC-3681-master: Integrating Red Hat Business Automation with Red Hat Single Sign-On for DM/PAM 7.3

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.19.0.Final-section.adoc
@sterobin @danielzhe could you please have a look?
> RHDM-779: Automatic Layout release notes

- assemblies/assembly_showcase-application/main.adoc
- doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
Original jira: https://issues.jboss.org/browse/BXMSDOC-3717
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-3717/
> BXMSDOC-3717-master to upstream master - Showcase App for case management

- assemblies/assembly_showcase-application/main.adoc
- doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
Original jira: https://issues.jboss.org/browse/BXMSDOC-3717
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-3717/
> BXMSDOC-3717-7.18.x to upstream 7.18.x - Showcase App for case management

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.19.0.Final-section.adoc
@sterobin @kkufova I will be pleased with your review. As usual, any rewording suggestions are welcome.
> DROOLS-3175: Add context menu shortcut into release notes

- doc-content/enterprise-only/openshift/apb-deploy-proc.adoc
* external db for apb
* peer review formatting fix
> BXMSDOC-3856 master (APB external DB fix)

- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- doc-content/enterprise-only/admin-and-config/error-list-cleanup-ref.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-managed-kie-server-con.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-unmanaged-server-config-proc.adoc
- doc-content/enterprise-only/installation/components-con.adoc
- doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/preemptive-authentication-for-local-projects-proc.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
Upstream master PR for "Managing & monitoring Process server for PAM/DM 7.3" doc.
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3827)
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3827-pam/)
> Upstream master BXMSDOC-3827: Managing & monitoring Process server for PAM/DM 7.3

- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- doc-content/enterprise-only/admin-and-config/error-list-cleanup-ref.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-managed-kie-server-con.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-unmanaged-server-config-proc.adoc
- doc-content/enterprise-only/installation/components-con.adoc
- doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/preemptive-authentication-for-local-projects-proc.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
Upstream 7.18.x PR for "Managing & monitoring Process server for PAM/DM 7.3" doc.
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3827)
[Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3827-pam/)
> Upstream 7.18.x PR for Managing & monitoring Process server for PAM/DM 7.3

- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- doc-content/enterprise-only/admin-and-config/error-list-cleanup-ref.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-accessing-runtime-data-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-managed-kie-server-con.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-unmanaged-server-config-proc.adoc
- doc-content/enterprise-only/installation/components-con.adoc
- doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/preemptive-authentication-for-local-projects-proc.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
Upstream 7.14.x PR for "Managing & monitoring Process server for PAM/DM 7.3" doc.
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3827)
[PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3827-pam/)
[DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3827-dm/)
> Upstream 7.14.x for Managing & monitoring Process server for PAM/DM 7.3

- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- doc-content/enterprise-only/admin-and-config/error-list-cleanup-ref.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-accessing-runtime-data-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-deactivate-kie-containers-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-managed-kie-server-con.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc
- doc-content/enterprise-only/admin-and-config/kie-server-unmanaged-server-config-proc.adoc
- doc-content/enterprise-only/installation/components-con.adoc
- doc-content/enterprise-only/installation/controller-eap-configure-proc.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/preemptive-authentication-for-local-projects-proc.adoc
- doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
Upstream 7.11.x PR for "Managing & monitoring Process server for PAM/DM 7.3" doc.
[Jira Id](https://issues.jboss.org/browse/BXMSDOC-3827)
[PAM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3827-pam/)
[DM Rendered Output](http://file.pnq.redhat.com/~gadey/BXMSDOC-3827-dm/)
Doc is building and rendering all variables correctly.
> Upstream 7.11.x PR for Managing & monitoring Process server for PAM/DM 7.3

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-embedded-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
- doc-content/enterprise-only/admin-and-config/assets-executing-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Integration/Spring-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-requests-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-java-api-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-java-api-requests-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3882) for details.
> BXMSDOC-3882-master: Update all XML-snippet comments with correct syntax.

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-embedded-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
- doc-content/enterprise-only/admin-and-config/assets-executing-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Integration/Spring-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-requests-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-java-api-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-java-api-requests-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3882) for details.
> BXMSDOC-3882-7.18.x: Update all XML-snippet comments with correct syntax.

- assemblies/assembly_decision-management-architecture/main.adoc
- assemblies/assembly_dmn-models/main.adoc
- assemblies/assembly_pmml-models/main.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-remote-java-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-kie-server-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-options-con.adoc
Updated PMML doc with new KIE server execution.
Links:
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-3665)
* [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-3665/#pmml-invocation-kie-server-proc_pmml-models)
> BXMSDOC-3665-master: Update PMML doc with KIE Server execution.

- assemblies/assembly_decision-management-architecture/main.adoc
- assemblies/assembly_dmn-models/main.adoc
- assemblies/assembly_pmml-models/main.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-remote-java-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-kie-server-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-options-con.adoc
Updated PMML doc with new KIE server execution.
Links:
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-3665)
* [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-3665/#pmml-invocation-kie-server-proc_pmml-models)
> BXMSDOC-3665-7.18.x: Update PMML doc with KIE Server execution.

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-embedded-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
- doc-content/enterprise-only/admin-and-config/assets-executing-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Integration/Spring-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-java-api-requests-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-java-api-con.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-java-api-requests-proc.adoc
> BXMSDOC-3882-7.14.x: Update all XML-snippet comments with correct syntax

- assemblies/assembly_bpmn-reference/main.adoc
- doc-content/enterprise-only/bpmn/bpmn-business-rule-task-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-businessrule-task-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-tasks-overview-con.adoc
BXMSDOC-3678 PAM 7.3 BPMN reference
> BXMSDOC-3678 7.18 PAM 7.3 BPMN Ref

- doc-content/enterprise-only/installation/components-con.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/install-download-proc.adoc
- doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
- doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
BXMSDOC-3775 Installing and configuring DM 7.3 and PAM 7.3 on JWS
>  BXMSDOC-3775 7.18.x Installing and configuring DM 7.3 and PAM 7.3 on JWS

- _artifacts/document-attributes-pam.adoc
- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/build-deploy-branches-proc.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-3765
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-3765/
> Upstream PR for BXMSDOC-3765-final to master - Managing projects in Business Central

- _artifacts/document-attributes-pam.adoc
- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/build-deploy-branches-proc.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-3765
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-3765/
> Upstream PR for BXMSDOC-3765-7.18.x to 7.18.x - Managing projects in Business Central

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
* BXMSDOC-3669-master: Update patching and upgrading doc for 7.3
* BXMSDOC-3669-master: Adopt feedback to remove notice about requiring to apply the latest patch before updating to a minor release.
* BXMSDOC-3669-master: Adopt feedback to revert minor change
> BXMSDOC-3669-master: Update patching and upgrading doc for 7.3

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
* BXMSDOC-3669-7.18.x: Update patching and upgrading doc for 7.3
* BXMSDOC-3669-7.18.x: Adopt feedback to remove notice about requiring to apply the latest patch before updating to a minor release.
* BXMSDOC-3669-7.18.x: Adopt feedback to revert minor change
> BXMSDOC-3669-7.18.x: Update patching and upgrading doc for 7.3

- doc-content/enterprise-only/weblogic/wls-install-start-proc.adoc
Original Epic: https://issues.jboss.org/browse/BXMSDOC-3702
Original Task: https://issues.jboss.org/browse/BXMSDOC-3779
Rendered Output: 
[RHPAM-7.3-WLS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3779-WLS-RHPAM/#wls-install-start-proc)
[RHDM-7.3-WLS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3779-WLS/#wls-install-start-proc)
> Upstream master PR for BXMSDOC-3779: WLS: Installing and configuring Process Server for DM/PAM 7.3

- doc-content/enterprise-only/weblogic/wls-install-start-proc.adoc
Original Epic: https://issues.jboss.org/browse/BXMSDOC-3702
Original Task: https://issues.jboss.org/browse/BXMSDOC-3779
Rendered Output: 
[RHPAM-7.3-WLS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3779-WLS-RHPAM/#wls-install-start-proc)
[RHDM-7.3-WLS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3779-WLS/#wls-install-start-proc)
> Upstream 7.18.x PR for WLS: Installing and configuring Process Server for DM/PAM 7.

- assemblies/assembly_openshift-ansible-playbook/main.adoc
- assemblies/assembly_test-scenarios/main.adoc
- doc-content/enterprise-only/project-data/data-objects-create-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3940) for details.
> BXMSDOC-3940-7.18.x: Fix doc issues for Pantheon.

- pom.xml
IIUC we don't need any more the dependencyManagement here
> removed obsolete dependencyManagement

- doc-content/enterprise-only/release-notes/rn-730-fixed-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
- doc-content/enterprise-only/springboot/bus-app-swagger_proc.adoc
Unable to create jira as jira system is down.
> BXMSDOC-3819b 7.18.x Updates to 7.3 RN after sanity check

- doc-content/enterprise-only/integration/entando-integrating-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3934) for details.
> BXMSDOC-3934-master: Implement QE feedback in Entando doc.

- doc-content/enterprise-only/integration/entando-integrating-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3934) for details.
> BXMSDOC-3934-7.18.x: Implement QE feedback in Entando doc.

- assemblies/assembly_integrating-entando/main.adoc
- doc-content/enterprise-only/integration/entando-app-building-proc.adoc
- doc-content/enterprise-only/integration/entando-integrating-proc.adoc
- doc-content/enterprise-only/integration/entando-pages-con.adoc
- doc-content/enterprise-only/integration/entando-widgets-con.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3956) for details.
> BXMSDOC-3956-7.18.x: Update Entando links.

- assemblies/assembly_integrating-entando/main.adoc
- doc-content/enterprise-only/integration/entando-app-building-proc.adoc
- doc-content/enterprise-only/integration/entando-integrating-proc.adoc
- doc-content/enterprise-only/integration/entando-pages-con.adoc
- doc-content/enterprise-only/integration/entando-widgets-con.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3956) for details.
> BXMSDOC-3956-master: Update Entando links.

- doc-content/enterprise-only/admin-and-config/kie-server-accessing-runtime-data-proc.adoc
- doc-content/enterprise-only/integration/sso-token-auth-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3947) for details.
> BXMSDOC-3947-master: Fixed unrendering variable in Managing Process Server doc.

- doc-content/enterprise-only/admin-and-config/kie-server-accessing-runtime-data-proc.adoc
- doc-content/enterprise-only/integration/sso-token-auth-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3947) for details.
> BXMSDOC-3947-7.18.x: Fixed unrendering variable in Managing Process Server doc.

- docs/product-administration-and-configuration-guide/src/main/asciidoc/kie-server-accessing-runtime-data-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3947) for details.
> BXMSDOC-3947-7.7.x: Fixed unrendering variable in Managing Process Server doc.

- docs/product-business-resource-planner-guide/src/main/asciidoc/optimizer-running-the-examples-proc.adoc
Requesting peer revie and merge for DM7 - the doc is not present in PAM7 and subsequent versions
> edit for BXMSDOC-2340

- assemblies/assembly_installing-dsps-on-was/main.adoc
- doc-content/enterprise-only/websphere/was-configure-embedded-engine-proc.adoc
Original Epic: https://issues.jboss.org/browse/BXMSDOC-3700
JIRA: https://issues.jboss.org/browse/BXMSDOC-3915
Rendered output links:
[WAS-RHPAM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3915-was-pam/#was-configure-embedded-engine-proc)
[WAS-RHDM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3915-was-dm/#was-configure-embedded-engine-proc)
> Upstream master PR for BXMSDOC-3915: Installing and configuring Process Server for DM/PAM using WAS

- assemblies/assembly_installing-dsps-on-was/main.adoc
- doc-content/enterprise-only/websphere/was-configure-embedded-engine-proc.adoc
Original Epic: https://issues.jboss.org/browse/BXMSDOC-3700
JIRA: https://issues.jboss.org/browse/BXMSDOC-3915
Rendered output links:
[WAS-RHPAM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3915-was-pam/#was-configure-embedded-engine-proc)
[WAS-RHDM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3915-was-dm/#was-configure-embedded-engine-proc)
> Upstream 7.18.x PR for BXMSDOC-3915: Installing and configuring Process Server for DM/PAM using WAS 

- assemblies/assembly_installing-dsps-on-wls/main.adoc
- doc-content/enterprise-only/weblogic/wls-configure-embedded-engine-proc.adoc
Original Epic: https://issues.jboss.org/browse/BXMSDOC-3702
Jira: https://issues.jboss.org/browse/BXMSDOC-3914
Rendered output links:
[WLS-RHPAM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3915-WLS-pam/#wls-configure-embedded-engine-proc)
[WLS-RHDM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3914-wls-dm/#wls-configure-embedded-engine-proc)
> Upstream master PR for BXMSDOC-3914: Installing and configuring Process Server for DM/PAM using WLS.

- assemblies/assembly_installing-dsps-on-wls/main.adoc
- doc-content/enterprise-only/weblogic/wls-configure-embedded-engine-proc.adoc
Original Epic: https://issues.jboss.org/browse/BXMSDOC-3702
Jira: https://issues.jboss.org/browse/BXMSDOC-3914
Rendered output links:
[WLS-RHPAM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3915-WLS-pam/#wls-configure-embedded-engine-proc)
[WLS-RHDM-7.3](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3914-wls-dm/#wls-configure-embedded-engine-proc)
> Upstream 7.18.x PR for BXMSDOC-3914: Installing and configuring Process Server for DM/PAM using WLS.

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.20.0.Final-section.adoc
@tomasdavidorg @sterobin could you please take a look?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2580
https://github.com/kiegroup/kie-docs/pull/1551
> AF-1903: There is no way to upload multiple documents for Human Task forms

- doc-content/enterprise-only/project-data/project-duplicate-GAV-con.adoc
- doc-content/enterprise-only/project-data/project-duplicate-GAV-manage-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3975) for details.
@pefernan, @ederign This work for that duplicate GAV update?
@csherrar Would you mind taking a quick look? Very short.
> BXMSDOC-3975-master: Update duplicate GAV detection in packaging doc.

- doc-content/enterprise-only/project-data/project-duplicate-GAV-con.adoc
- doc-content/enterprise-only/project-data/project-duplicate-GAV-manage-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3975) for details.
> BXMSDOC-3975-7.18.x: Update duplicate GAV detection in packaging doc.

- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.21.0.Final-section.adoc
Depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1799/files
> JBPM-8347 - jBPM Prometheus N&N

- doc-content/enterprise-only/openshift/operator-createapp-proc.adoc
- doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc
@mramendi @vidya-iyengar 
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
> [RHPAM-2047] update operator docs for 7.3.1 release

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
> DROOLS-3942 DMN Fix wrong snippet for XML/JAXB request/response Traffic Violation

- doc-content/drools-docs/src/main/asciidoc/LanguageReference/Rule-section.adoc
'enabled' attribute description is missing!
> Add 'enabled' attribute description

- doc-content/enterprise-only/admin-and-config/deployment-descriptor-configuration-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4103) for details.
> BXMSDOC-4103-master: Added singleton note in managing KIE Server doc

- assemblies/assembly_release-notes/main.adoc
- doc-content/enterprise-only/release-notes/rn-730-fixed-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-731_fixed-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
BXMSDOC-4089 Release note for DM and PAM 7.3.1
> BXMSDOC-4089 7.18.x 7.3.1 release notes

- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Introduction-section.adoc
Reported by Danial Khoshkhou. Thanks!
> asynchronous typo

- doc-content/enterprise-only/project-data/project-kmodule-configure-proc.adoc
BXMSDOC-2574 added serialization note toe packing doc
> BXMSDOC-2574 7.18.x added serialization note to packing doc

- doc-content/enterprise-only/project-data/project-kmodule-configure-proc.adoc
BXMSDOC-2574 added serialization note toe packing doc
> BXMSDOC-2574 7.14.x added serialization note to packing doc

- doc-content/enterprise-only/project-data/project-kmodule-configure-proc.adoc
BXMSDOC-2574 added serialization note toe packing doc
> BXMSDOC-2574  7.11.x added serialization note to packing doc

- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- assemblies/assembly_packaging-deploying/main.adoc
- doc-content/enterprise-only/admin-and-config/configuring-environment-mode-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4173) for details.
> BXMSDOC-4173-master: Add KIE Server environment mode section to monitoring and packaging docs.

- assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
- assemblies/assembly_packaging-deploying/main.adoc
- doc-content/enterprise-only/admin-and-config/configuring-environment-mode-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4173) for details.
> BXMSDOC-4173-7.18.x: Add KIE Server environment mode section to monitoring and packaging docs.

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-names-con.adoc
See JIRAs for details:
* https://issues.jboss.org/browse/BXMSDOC-4166
* https://issues.jboss.org/browse/BXMSDOC-4182
> BXMSDOC-4166-master: Fix curl syntax issue and variable space description in DMN doc.

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-names-con.adoc
See JIRAs for details:
* https://issues.jboss.org/browse/BXMSDOC-4166
* https://issues.jboss.org/browse/BXMSDOC-4182
> BXMSDOC-4166-7.18.x: Fix curl syntax issue and variable space description in DMN doc.

- doc-content/enterprise-only/optimizer/examples-con.adoc
Please merge as this PR only adds one phrase; this phrase was agreed with Geoffrey as per https://issues.jboss.org/browse/BXMSDOC-4072
> BXMSDOC-4072 note about example supportability

- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/main.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-db-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-eclipse-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-runningwar-proc.adoc
* running WAR; removing workaround
* SME review fix
* peer review changes
> BXMSDOC-4132 master: running prebuilt WAR and removing a build workaround 

- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-swagger-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4192) for details.
> BXMSDOC-4192-7.11.x: Add note about API calls for process instances in KIE APIs doc. 

- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-swagger-proc.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4192) for details.
> BXMSDOC-4192-7.14.x: Add note about API calls for process instances in KIE APIs doc.

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.23.0.Final-section.adoc
@sterobin @karreiro may I ask you for review?
> [DROOLS-1958] Mention Included Models feature in 7.23.0 Release notes

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.23.0.Final-section.adoc
This is cherry-pick of #1620 
@sterobin @karreiro may I ask you for review?
> [7.23.x] DROOLS-1958: Mention Included Models feature in 7.23.0 Release notes

- doc-content/enterprise-only/using-ansible-rhdm-in-ONAP/additional-references-ref.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4008)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4224)
[Policy-based decision and control in ONAP using Ansible and Red Hat Decision Manager 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4224-Ansible-RHDM-in-ONAP/#additional-references-ref)
> Upstream 7.23.x PR for BXMSDOC-4224: Update the Policy-based decision and control in ONAP using Ansible and RHDM doc with 7.4 changes 

- doc-content/enterprise-only/using-ansible-rhdm-in-ONAP/additional-references-ref.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4008)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4224)
[Policy-based decision and control in ONAP using Ansible and Red Hat Decision Manager 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4224-Ansible-RHDM-in-ONAP/#additional-references-ref)
> Upstream master PR for BXMSDOC-4224: Update the Policy-based decision and control in ONAP using Ansible and RHDM doc with 7.4 changes

- assemblies/assembly_business-optimizer-ER-sample-openshift/main.adoc
- doc-content/enterprise-only/employee-rostering/er-availability-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-contracts-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-employees-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-individualroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-publish-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-rotation-edit-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-shiftroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-skills-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-solve-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-spots-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-tenant-create-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-tenant-select-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-using-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-source-con.adoc
* Contracts tab
* SME review - typo
* Peer review
* peer review 2
> BXMSDOC-4221 - Employee rostering Contracts tab - master

- assemblies/assembly_business-optimizer-ER-sample-openshift/main.adoc
- doc-content/enterprise-only/employee-rostering/er-availability-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-contracts-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-employees-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-individualroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-publish-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-rotation-edit-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-shiftroster-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-skills-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-solve-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-spots-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-tenant-create-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-tenant-select-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-using-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-source-con.adoc
* Contracts tab
* SME review - typo
* Peer review
* peer review 2
> BXMSDOC-4221 - Employee rostering Contracts tab - 7.23.x

- assemblies/assembly_decision-manager/dm/master-docinfo.xml
- assemblies/assembly_decision-manager/main.adoc
- assemblies/assembly_decision-manager/pam/master-docinfo.xml
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-new-project-creating-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/Examples/decision-examples-central-con.adoc
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4252) for details.
> BXMSDOC-4252-7.23.x: Update decision service gsg with violation sample project info.

- doc-content/jbpm-docs/src/main/asciidoc/Persistence/Configuration-section.adoc
[JBPM-8380] Remove JBPMHelper. Changes made to persistence documentation for jBPM Engine.
> [JBPM-8380] Remove JBPMHelper

- doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-deployment-options-ref.adoc
@sterobin could you please have a look?
> BXMSDOC-4174: Add trailing endif

- doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-deployment-options-ref.adoc
> [7.23.x] Add trailing endif

- assemblies/assembly_showcase-application/main.adoc
- doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
- doc-content/enterprise-only/cases/case-management-starting-itorders-in-showcase-proc.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4048
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4048/
> Upstream PR BXMSDOC-4048-master Using the Showcase application for case management

- assemblies/assembly_showcase-application/main.adoc
- doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
- doc-content/enterprise-only/cases/case-management-starting-itorders-in-showcase-proc.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4048
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4048/
> Upstream PR BXMSDOC-4048-7.23.x Using the Showcase application for case management

- assemblies/assembly_designing-and-building-cases/main.adoc
- doc-content/enterprise-only/cases/case-management-case-listener-con.adoc
Original jiras: https://issues.jboss.org/browse/BXMSDOC-4049 and https://issues.jboss.org/browse/BXMSDOC-3871
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4049/#case-management-case-listener-con
> Bxmsdoc 4049 7.23.x final to 7.23.x Designing and building cases doc

- assemblies/assembly_case-management-getting-started/main.adoc
- doc-content/enterprise-only/cases/case-management-it-order-sample-proc.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4047
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4047/
> Bxmsdoc 4047 master to upstream Master - Getting started with case management

- assemblies/assembly_case-management-getting-started/main.adoc
- doc-content/enterprise-only/cases/case-management-it-order-sample-proc.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4047
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4047/
> Bxmsdoc 4047 7.23.x final to upstream 7.23.x - Getting started with case management

- doc-content/enterprise-only/springboot/bus-app-auth_con.adoc
[BXMSDOC-4010](https://issues.jboss.org/browse/BXMSDOC-4010)
> BXMSDOC-4010 master PAM/DM 7.4 Springboot documentation

- doc-content/enterprise-only/springboot/bus-app-auth_con.adoc
[BXMSDOC-4010](https://issues.jboss.org/browse/BXMSDOC-4010)
> BXMSDOC-4010 7.23.x PAM/DM 7.4 Springboot documentation

- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/migrating-legacy-designer-proc.adoc
Doc jira: https://issues.jboss.org/browse/BXMSDOC-4066
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4066/#migrating-from-legacy-designer-proc
> Upstream PR BXMSDOC-4066-7.23.x to 7.23.x "Managing projects in Business Central"

- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/migrating-legacy-designer-proc.adoc
Doc jira: https://issues.jboss.org/browse/BXMSDOC-4066
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4066/#migrating-from-legacy-designer-proc
> Upstream PR BXMSDOC-4066-master to master "Managing projects in Business Central" 

- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- assemblies/assembly_openshift-freeform/main.adoc
- assemblies/assembly_openshift-immutable/main.adoc
- assemblies/assembly_openshift-managed/main.adoc
- doc-content/enterprise-only/openshift/template-deploy-ldap-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-rhsso-proc.adoc
* RH-SSO documentation improvements
* format fix after SME review
* peer review
* passive in prereqs as agreed
> BXMSDOC-4184 RH-SSO documentation improvements master

- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- assemblies/assembly_openshift-freeform/main.adoc
- assemblies/assembly_openshift-immutable/main.adoc
- assemblies/assembly_openshift-managed/main.adoc
- doc-content/enterprise-only/openshift/template-deploy-ldap-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-rhsso-proc.adoc
* RH-SSO documentation improvements
* format fix after SME review
* peer review
* passive in prereqs as agreed
> BXMSDOC-4184 RH-SSO documentation improvements 7.23.x

- doc-content/enterprise-only/openshift/additional-server-managed-deploy-assy.adoc
- doc-content/enterprise-only/openshift/authoring-deploy-assy.adoc
- doc-content/enterprise-only/openshift/fixed-deploy-assy.adoc
- doc-content/enterprise-only/openshift/freeform-monitor-deploy-assy.adoc
- doc-content/enterprise-only/openshift/freeform-server-managed-deploy-assy.adoc
- doc-content/enterprise-only/openshift/server-immutable-kjar-deploy-assy.adoc
- doc-content/enterprise-only/openshift/server-immutable-s2i-deploy-assy.adoc
- doc-content/enterprise-only/openshift/template-deploy-prometheus-proc.adoc
* Prometheus and deprecation of prod
* Peer review
> Bxmsdoc 4208 Prometheus enabling master

- doc-content/enterprise-only/openshift/additional-server-managed-deploy-assy.adoc
- doc-content/enterprise-only/openshift/authoring-deploy-assy.adoc
- doc-content/enterprise-only/openshift/fixed-deploy-assy.adoc
- doc-content/enterprise-only/openshift/freeform-monitor-deploy-assy.adoc
- doc-content/enterprise-only/openshift/freeform-server-managed-deploy-assy.adoc
- doc-content/enterprise-only/openshift/server-immutable-kjar-deploy-assy.adoc
- doc-content/enterprise-only/openshift/server-immutable-s2i-deploy-assy.adoc
- doc-content/enterprise-only/openshift/template-deploy-prometheus-proc.adoc
* Prometheus and deprecation of prod
* Peer review
> Bxmsdoc 4208 Prometheus enabling 7.23.x

- assemblies/assembly_managing-assets/main.adoc
- doc-content/enterprise-only/admin-and-config/assets-renaming-proc.adoc
- doc-content/enterprise-only/getting-started/assets-types-ref.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4067
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4067/#assets_types_ref
> Upstream PR for Bxmsdoc 4067-master to Master - Managing assets doc (#103)

- assemblies/assembly_managing-assets/main.adoc
- doc-content/enterprise-only/admin-and-config/assets-renaming-proc.adoc
- doc-content/enterprise-only/getting-started/assets-types-ref.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4067
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4067/#assets_types_ref
> Upstream PR for Bxmsdoc 4067-7.23.x to 7.23.x - Managing assets doc

- doc-content/enterprise-only/openshift/template-deploy-optionalmaven-proc.adoc
* Reference BC procedure for external Maven repo
* it's pom.xml not settings.xml
> BXMSDOC-4297 Reference BC procedure for external Maven repo - 7.23.x

- doc-content/enterprise-only/openshift/template-deploy-optionalmaven-proc.adoc
* Reference BC procedure for external Maven repo
* it's pom.xml not settings.xml
> BXMSDOC-4297 Reference BC procedure for external Maven repo - master

- doc-content/enterprise-only/openshift/environment-immutable-modify-proc.adoc
- doc-content/enterprise-only/openshift/server-immutable-s2i-deploy-assy.adoc
- doc-content/enterprise-only/openshift/template-deploy-amq-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-start-proc.adoc
* AMQ template
* AMQ template 2
* peer review
> BXMSDOC 4162 - AMQ template - master

- doc-content/enterprise-only/openshift/environment-immutable-modify-proc.adoc
- doc-content/enterprise-only/openshift/server-immutable-s2i-deploy-assy.adoc
- doc-content/enterprise-only/openshift/template-deploy-amq-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-start-proc.adoc
* AMQ template
* AMQ template 2
* peer review
> BXMSDOC 4162 - AMQ template - 7.23.x

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/externaldb-params.adoc
- doc-content/enterprise-only/openshift/operator-con.adoc
- doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-start-proc.adoc
- doc-content/enterprise-only/openshift/operator-environment-deploy-assy.adoc
- doc-content/enterprise-only/openshift/operator-modify-proc.adoc
- doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-nopubnet-proc.adoc
* working on operator UI
* still working on Operator UI
* completed full draft for Operator UI doc
* SSO fix and Prometheus
* peer review
> BXMSDOC 4222 Operator UI doc - master

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/externaldb-params.adoc
- doc-content/enterprise-only/openshift/operator-con.adoc
- doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-smartrouter-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-start-proc.adoc
- doc-content/enterprise-only/openshift/operator-environment-deploy-assy.adoc
- doc-content/enterprise-only/openshift/operator-modify-proc.adoc
- doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-externaldb-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-nopubnet-proc.adoc
* working on operator UI
* still working on Operator UI
* completed full draft for Operator UI doc
* SSO fix and Prometheus
* peer review
> BXMSDOC 4222 Operator UI doc - 7.23.x

- doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
- doc-content/enterprise-only/websphere/was-con.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4023)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4107)
[Installing and configuring Process Server on RHPAM-WAS 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4023-RHPAM-WAS/#controller-was-install-proc)
[Installing and configuring Process Server on RHDM-WAS 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4023-RHDM-WAS/#controller-was-install-proc)
> Upstream master PR for BXMSDOC-4023: Update Installing and configuring Process Server on WAS doc per changes in 7.4

- doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
- doc-content/enterprise-only/websphere/was-con.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4023)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4107)
[Installing and configuring Process Server on RHPAM-WAS 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4023-RHPAM-WAS/#controller-was-install-proc)
[Installing and configuring Process Server on RHDM-WAS 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4023-RHDM-WAS/#controller-was-install-proc)
> Upstream 7.23.x PR for BXMSDOC-4023: Update Installing and configuring Process Server on WAS doc per changes in 7.4

- doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
* clarification of KIE_SERVER_CONTAINER_DEPLOYMENT
* SME review
* fix lost endif
* peer review
* small style fixes
* external repo
* removed two colons
> BXMSDOC-3609 clarification of KIE_SERVER_CONTAINER_DEPLOYMENT - master

- doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
* clarification of KIE_SERVER_CONTAINER_DEPLOYMENT
* SME review
* fix lost endif
* peer review
* small style fixes
* external repo
* removed two colons
> BXMSDOC-3609 clarification of KIE_SERVER_CONTAINER_DEPLOYMENT - 7.23.x

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
[BXMSDOC-4017](https://issues.jboss.org/browse/BXMSDOC-4017)
See jira for details.
> BXMSDOC-4017 7.23 Patching and upgrading DM/PAM 7.4

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/patches-applying-proc.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
[BXMSDOC-4017](https://issues.jboss.org/browse/BXMSDOC-4017)
See jira for details.
> BXMSDOC-4017 master Patching and upgrading DM/PAM 7.4

- assemblies/assembly_planning/main.adoc
[BXMSDOC-4012](https://issues.jboss.org/browse/BXMSDOC-4012)
> BXMSDOC-4012 7.23.x  Planning the Installation for DM and PAM 7.4

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/EnumerationEditor-section.adoc
> BXMSDOC-4364: Misplacment of brackets removed

- doc-content/enterprise-only/installation/jms-queues-ref.adoc
- doc-content/enterprise-only/weblogic/wls-jms-queues-create-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4022)
[WLS install doc RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4022-RHPAM-WLS/#wls-jms-queues-create-proc)
[WLS install doc RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4022-RHDM-WLS/#wls-jms-queues-create-proc)
> Upstream master PR for BXMSDOC-4022: Update WLS installation doc as per changes in 7.4

- doc-content/enterprise-only/installation/jms-queues-ref.adoc
- doc-content/enterprise-only/weblogic/wls-jms-queues-create-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4022)
[WLS install doc RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4022-RHPAM-WLS/#wls-jms-queues-create-proc)
[WLS install doc RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4022-RHDM-WLS/#wls-jms-queues-create-proc)
> Upstream 7.23.x PR for BXMSDOC-4022: Update WLS installation doc as per changes in 7.4

- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4001)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4191)
[managing and monitoring process server doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-PAM-NoteAdded/#migration-configure-kie-server-proc)
[managing and monitoring decision server doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-DM-NoteAdded/#migration-configure-kie-server-proc)
> Upstream master PR for BXMSDOC-4191: Update managing and monitoring execution server doc per changes in 7.4

- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4001)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4191)
[managing and monitoring process server doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-PAM-NoteAdded/#migration-configure-kie-server-proc)
[managing and monitoring decision server doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-DM-NoteAdded/#migration-configure-kie-server-proc)
> Upstream 7.23.x PR for BXMSDOC-4191: Update managing and monitoring execution server doc per changes in 7.4

- assemblies/assembly_bpmn-reference/main.adoc
- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
[BXMSDOC-4009](https://issues.jboss.org/browse/BXMSDOC-4009)
> BXMSDOC-4009 master BA 7.4 BPMN Reference

- assemblies/assembly_bpmn-reference/main.adoc
- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
[BXMSDOC-4009](https://issues.jboss.org/browse/BXMSDOC-4009)
> BXMSDOC-4008 7.23.x BA 7.4 BPMN Reference

- assemblies/assembly_executing-processes/main.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4068
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4068/#executing_process
> Upstream PR BXMSDOC-4068 Updating Executing a bus process doc.

- assemblies/assembly_executing-processes/main.adoc
Original Jira: https://issues.jboss.org/browse/BXMSDOC-4068
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-4068/#executing_process
> Upstream PR BXMSDOC-4068-7.23.x to 7.23.x Updating Executing a bus process doc

- _artifacts/document-attributes.adoc
- assemblies/assembly_integrating-sso/main.adoc
- doc-content/enterprise-only/installation/roles-users-con.adoc
- doc-content/enterprise-only/integration/dev-studio-clone-remote-git-repo-proc.adoc
- doc-content/enterprise-only/integration/sso-central-client-create-proc.adoc
- doc-content/enterprise-only/integration/sso-central-proc.adoc
- doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
- doc-content/enterprise-only/integration/sso-int-con.adoc
- doc-content/enterprise-only/integration/sso-kie-server-client-adapter-proc.adoc
- doc-content/enterprise-only/integration/sso-kie-server-con.adoc
- doc-content/enterprise-only/integration/sso-realm-proc.adoc
- doc-content/enterprise-only/integration/sso-user-add-proc.adoc
[BXMSDOC-4016](https://issues.jboss.org/browse/BXMSDOC-4016)
see jira for details
> BXMSDOC-4016 7.23.x Integrating Red Hat Business Automation with Red Hat Single Sign-On for DM/PAM 7.4

- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc
Updated managing and monitoring execution server doc per changes in 7.3
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4191)
[managing and monitoring process server RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-7.3-AddedNote-DM/)
[managing and monitoring process server RHDM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-7.3-AddedNote-PAM/)
> Upstream 7.18.x PR for BXMSDOC-4191: Added a note for system property  

- _artifacts/document-attributes.adoc
- assemblies/assembly_clustering-eap/main.adoc
- assemblies/assembly_planning/main.adoc
- doc-content/enterprise-only/installation/clustering-bc-configure-domain-proc.adoc
- doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
- doc-content/enterprise-only/installation/clustering-bc-install-proc.adoc
- doc-content/enterprise-only/installation/clustering-datagrid-proc.adoc
- doc-content/enterprise-only/installation/clustering-dev-con.adoc
- doc-content/enterprise-only/installation/clustering-quartz-proc.adoc
* BXMSDOC-4262-master: Add quartz timer procedure
* BXMSDOC-4300-master: Replace Elasticsearch with Red Hat Data Grid
* BXMSDOC-4300-master: Add Red Hat Data Grid attributes
* BXMSDOC-4300-master: Replace Elasticsearch with Red Hat Data Grid
* BXMSDOC-4300-master: Adopt feedback and rephrase concept section
* BXMSDOC-4300-master: Adopt feedback to change Data Grid configuration example
* BXMSDOC-4262-master: Correct level offset and change sentence
* BXMSDOC-4018-master: Adopt peer feedback
* BXMSDOC-4018-master: Adopt feedback to remove DM content
> BXMSDOC-4018: Installing and configuring DM/PAM 7.4 in an EAP clustered environment

- _artifacts/document-attributes.adoc
- assemblies/assembly_clustering-eap/main.adoc
- assemblies/assembly_planning/main.adoc
- doc-content/enterprise-only/installation/clustering-bc-configure-domain-proc.adoc
- doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
- doc-content/enterprise-only/installation/clustering-bc-install-proc.adoc
- doc-content/enterprise-only/installation/clustering-datagrid-proc.adoc
- doc-content/enterprise-only/installation/clustering-dev-con.adoc
- doc-content/enterprise-only/installation/clustering-quartz-proc.adoc
* BXMSDOC-4262-7.23.x: Add quartz timer procedure
* BXMSDOC-4300-7.23.x: Replace Elasticsearch with Red Hat Data Grid
* BXMSDOC-4300-7.23.x: Add Red Hat Data Grid attributes
* BXMSDOC-4300-7.23.x: Replace Elasticsearch with Red Hat Data Grid
* BXMSDOC-4300-7.23.x: Adopt feedback and rephrase concept section
* BXMSDOC-4300-7.23.x: Adopt feedback to change Datagrid configuration example
* BXMSDOC-4262-7.23.x: Correct level offset and change sentence
* BXMSDOC-4018-7.23.x: Adopt peer feedback
* BXMSDOC-4018-7.23.x: Adopt feedback to remove DM content
> BXMSDOC-4018-7.23.x: Installing and configuring DM/PAM 7.4 in an EAP clustered environment

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/operator-con.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-start-proc.adoc
- doc-content/enterprise-only/openshift/operator-environment-deploy-assy.adoc
- doc-content/enterprise-only/openshift/operator-modify-proc.adoc
- doc-content/enterprise-only/openshift/operator-subscribe-proc.adoc
* QE verification changes for Operator - DM review
* Further corrections from Karel and Thomas
* Typo fixed
> BXMSDOC-4315 QE verification changes for Operator - DM review - master

- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc
Updated managing and monitoring execution server doc per changes in 7.3
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4191)
[managing and monitoring process server RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-7.2-AddedNote-PAM/)
[managing and monitoring process server RHDM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4191-7.2-AddedNote-DM/)
> Upstream 7.14.x PR for BXMSDOC-4191: Added a note for system property 

- doc-content/enterprise-only/admin-and-config/maven-settings-configuration-ref.adoc
- doc-content/enterprise-only/cases/case-management-install-and-login-to-showcase-proc.adoc
- doc-content/enterprise-only/installation/clustering-download-eap-ps-proc.adoc
- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/eap-dm-install-proc.adoc
- doc-content/enterprise-only/installation/eap-execution-server-download-install-proc.adoc
- doc-content/enterprise-only/installation/install-download-proc.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
> BXMSDOC-4332 7.23.x Update Tomcat installation file section

- _artifacts/document-attributes.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-using-usergroupcallback-ref.adoc
* BXMSDOC-4389-master: Correct typo and URL links
* BXMSDOC-4389-master: Correct attribute for freeform managed URL
> BXMSDOC-4389-master: Sanity check for BA7.4 GA documents

- _artifacts/document-attributes.adoc
- doc-content/enterprise-only/admin-and-config/business-central-settings-changing-permissions-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-using-usergroupcallback-ref.adoc
* BXMSDOC-4389-7.23.x: Correct typo and URL links
* BXMSDOC-4389-7.23.x: Correct attribute for freeform managed URL
> BXMSDOC-4389-7.23.x: Sanity check for BA7.4 GA documents

- doc-content/enterprise-only/installation/clustering-bc-testing-proc.adoc
- doc-content/enterprise-only/installation/ssh-configuring-proc.adoc
- doc-content/enterprise-only/integration/sso-central-client-create-proc.adoc
- doc-content/enterprise-only/integration/sso-kie-server-client-proc.adoc
- doc-content/enterprise-only/release-notes/rn-support-ref.adoc
BXMSDOC-4423 RN and other updates pre 7.4 GA
> BXMSDOC-4423 7.23.x RN and other updates pre 7.4 GA

- doc-content/enterprise-only/bpmn/bpmn-tasks-overview-con.adoc
- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
BXMSDOC-4482 added RHPAM-2259 to Known Issues.
> BXMSDOC-4482 7.23.x Add RHPAM-2239 to RN Known Issues

- assemblies/assembly_packaging-deploying/main.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/kie-scanner-proc.adoc
Links:
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-414)
* [DM/PAM doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-414_PAM/#kie-scanner-proc_packaging-deploying)
* [Community doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-414_DROOLS/#kie-scanner-proc_decision-management-architecture)
> BXMSDOC-414: Add KIE scanner section to packaging content.

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc
This PR add short description about the function count as it is quite usefull and it is not mentioned elsewhere in the documentation.
@kkufova @sterobin may I ask you for a review?
> Mention dmn function - count

- assemblies/assembly_release-notes/main.adoc
- doc-content/enterprise-only/release-notes/rn-741-fixed-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
See jira for details:
[BXMSDOC-4516](https://issues.jboss.org/browse/BXMSDOC-4516)
> BXMSDOC-4516 7.23.x PAM/DM 7.4.1 release notes

- _artifacts/document-attributes.adoc
Updated 7.4 to 7.5 and community version to 7.26. Also speculatively updated the maven versions.
> BXMSDOC-4540a Updated product version

- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
[BXMSDOC-4542](https://issues.jboss.org/browse/BXMSDOC-4542)
> BXMSDOC-4542 master Update sentence in BPMN guide

- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
[BXMSDOC-4542](https://issues.jboss.org/browse/BXMSDOC-4542)
> BXMSDOC-4542 7.23.x Update sentence in BPMN guide

- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
[BXMSDOC-4542](https://issues.jboss.org/browse/BXMSDOC-4542)
> BXMSDOC-4542 7.14.x Update sentence in BPMN guide

- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
[BXMSDOC-4542](https://issues.jboss.org/browse/BXMSDOC-4542)
> BXMSDOC-4542 7.11.x Update sentence in BPMN guide

- doc-content/enterprise-only/admin-and-config/maven-settings-configuration-ref.adoc
- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
- doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
[BXMSDOC-3331](https://issues.jboss.org/browse/BXMSDOC-3331)
> BXMSDOC-3331 master RHPAM 7 Installation Guide is missing steps to set up the database using ddl scripts

- doc-content/enterprise-only/admin-and-config/maven-settings-configuration-ref.adoc
- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
- doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
See jira for details:
[BXMSDOC-3331](https://issues.jboss.org/browse/BXMSDOC-3331)
> Bxmsdoc 3331 7.23.x RHPAM 7 Installation Guide is missing steps to set up the database using ddl scripts

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.24.0.Final/ReleaseNotesDrools.7.24.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.24.0.Final/dmn-pmml-support.adoc
This PR add a DMN PMML support note into release notes
@sterobin @manstis may I ask you for a review?
> 7.24.0 Drools Workbench Release Notes

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-list-map-add-remove-item-proc.adoc
@danielezonca @sterobin may I ask you for a review of this?
> RHDM-1015: Mention supported data types of the map

- assemblies/assembly_dmn-models/main.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-conformance-levels-con.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-model-creating-proc.adoc
- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-support-con.adoc
Links:
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-4585)
* [DMN doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4585_DM/)
> BXMSDOC-4585-master: Update DMN 1.1 model support explanation.

- doc-content/enterprise-only/installation/securing-passwords-jws-proc.adoc
Cherrypick of https://github.com/kiegroup/kie-docs/pull/1855
> [7.26.x] Fix wrong controller password system property

- doc-content/enterprise-only/installation/securing-passwords-jws-proc.adoc
@emmurphy1 Can you please take a look?
> Fix wrong controller password system property

- assemblies/assembly_openshift-ansible-playbook/main.adoc
- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- assemblies/assembly_openshift-freeform/main.adoc
- assemblies/assembly_openshift-immutable/main.adoc
- assemblies/assembly_openshift-managed/main.adoc
- assemblies/assembly_openshift-trial/main.adoc
* Deprecation notes and OpenShift version for templates and APB
> [BXMDCOS-4529] Deprecation notes and OpenShift version for templates and APB - 7.26.x

- assemblies/assembly_openshift-ansible-playbook/main.adoc
- assemblies/assembly_openshift-authoring-managed/main.adoc
- assemblies/assembly_openshift-authoring/main.adoc
- assemblies/assembly_openshift-freeform/main.adoc
- assemblies/assembly_openshift-immutable/main.adoc
- assemblies/assembly_openshift-managed/main.adoc
- assemblies/assembly_openshift-trial/main.adoc
* Deprecation notes and OpenShift version for templates and APB
> [BXMDCOS-4529] Deprecation notes and OpenShift version for templates and APB - master

- doc-content/jbpm-docs/src/main/asciidoc/BPMN2/cust-marshalling-cms-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BPMN2/set-marshalling-proc.adoc
Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-4685).
> BXMSDOC-4685-master: Fix marshalling strategy info in forms content.

- _artifacts/document-attributes.adoc
- assemblies/assembly_installing-dsps-on-was/main.adoc
- doc-content/enterprise-only/installation/securing-passwords-was-proc.adoc
- doc-content/enterprise-only/websphere/kie-server-was-environment-set-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-jms-activation-proc.adoc
- doc-content/enterprise-only/websphere/was-jms-queues-create-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4451)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4623)
[Installing and configuring process server on WAS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4451-WAS-PAM-FP/#was-configure-embedded-engine-proc)
[Installing and configuring process server on WAS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4451-WAS-DM-FP/#was-configure-embedded-engine-proc)
> Upstream master PR for BXMSDOC-4451: Update installing and configuring process/decision server on WAS doc per changes in 7.5

- assemblies/assembly_installing-dsps-on-wls/main.adoc
- doc-content/enterprise-only/installation/securing-passwords-wls-proc.adoc
- doc-content/enterprise-only/weblogic/kie-server-wls-environment-set-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4450)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4622)
[Installing and configuring process server on WLS](file.pnq.redhat.com/~kaldesai/BXMSDOC-4450-WLS-RHPAM-Final/)
[Installing and configuring process server on WLS](file.pnq.redhat.com/~kaldesai/BXMSDOC-4450-WLS-RHDM-Final/)
> Upstream 7.26.x PR for BXMSDOC-4450: Update installing and configuring process/decision server on WLS doc per changes in 7.5

- assemblies/assembly_installing-dsps-on-wls/main.adoc
- doc-content/enterprise-only/installation/securing-passwords-wls-proc.adoc
- doc-content/enterprise-only/weblogic/kie-server-wls-environment-set-proc.adoc
[Epic](https://issues.jboss.org/browse/BXMSDOC-4450)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4622)
[Installing and configuring process server on WLS](file.pnq.redhat.com/~kaldesai/BXMSDOC-4450-WLS-RHPAM-Final/)
[Installing and configuring process server on WLS](file.pnq.redhat.com/~kaldesai/BXMSDOC-4450-WLS-RHDM-Final/)
> Upstream master PR for BXMSDOC-4450: Update installing and configuring process/decision server on WLS doc per changes in 7.5

- assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-processes-bulk-actions-on-tasks-con.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-processes-claiming-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-processes-reassigning-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-processes-releasing-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-processes-resuming-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-processes-suspending-tasks-in-bulk-proc.adoc
- [Epic](https://issues.jboss.org/browse/BXMSDOC-4412)
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-4588)
- [Managing & monitoring business processes in BC 7.5 RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4587-ManagingandMonitoringBP-RHPAM/#managing-business-processes-bulk-actions-on-tasks-con)
> Upstream 7.26.x PR for BXMSDOC-4587: Update managing and monitoring business processes doc per changes in 7.5

- doc-content/enterprise-only/bpmn/bpmn-artifacts-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-connecting-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-gateways-ref.adoc
- doc-content/enterprise-only/bpmn/bpmn-support-con.adoc
- doc-content/enterprise-only/bpmn/bpmn-tasks-overview-con.adoc
Details in the jira:
[BXMSDOC-4414](https://issues.jboss.org/browse/BXMSDOC-4414)
> BXMSDOC-4414 7.26.x BPMN Reference

- assemblies/assembly_interacting-with-processes/main.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-bulk-actions-on-tasks-con.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-claiming-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-viewing-process-variables-con.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-reassigning-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-releasing-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-resuming-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-suspending-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-default-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-viewing-task-variables-con.adoc
- [Epic](https://issues.jboss.org/browse/BXMSDOC-4412)
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-4588)
- [Interacting with Processes & tasks 7.5 RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4588-IPT-RHPAM/#interacting-with-processes-bulk-actions-on-tasks-con)
> Upstream 7.26.x PR for BXMSDOC-4588: Update interacting with processes and tasks doc per changes in 7.5

- assemblies/assembly_interacting-with-processes/main.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-bulk-actions-on-tasks-con.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-claiming-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-process-instances-viewing-process-variables-con.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-reassigning-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-releasing-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-resuming-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-suspending-tasks-in-bulk-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-default-filters-proc.adoc
- doc-content/enterprise-only/processes/interacting-with-processes-tasks-viewing-task-variables-con.adoc
- [Epic](https://issues.jboss.org/browse/BXMSDOC-4412)
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-4588)
- [Interacting with Processes & tasks 7.5 RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4588-IPT-RHPAM/#interacting-with-processes-bulk-actions-on-tasks-con)
> Upstream master PR for BXMSDOC-4588: Update interacting with processes and tasks doc per changes in 7.5

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
[BXMSDOC-4447](https://issues.jboss.org/browse/BXMSDOC-4447)
> BXMSDOC-4447 master Patching and upgrading DM/PAM 7.5

- assemblies/assembly_patching-and-upgrading/main.adoc
- doc-content/enterprise-only/installation/product-versioning-con.adoc
[BXMSDOC-4447](https://issues.jboss.org/browse/BXMSDOC-4447)
> BXMSDOC-4447 7.26.x Patching and upgrading DM/PAM 7.5

- _artifacts/document-attributes.adoc
- assemblies/assembly_install-on-eap/main.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/installer-run-proc.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
- doc-content/enterprise-only/installation/securing-passwords-eap-proc.adoc
- doc-content/enterprise-only/installation/securing-passwords-jws-proc.adoc
[EAP jira](https://issues.jboss.org/browse/BXMSDOC-4445)
[JWS jira](https://issues.jboss.org/browse/BXMSDOC-4446)
> BXMSDOC-4446 7.26.x EAP and JWS 7.5 updates

- assemblies/assembly_business-optimizer-ER-sample-openshift/dm/master-docinfo.xml
- assemblies/assembly_business-optimizer-ER-sample-openshift/drools/master-docinfo.xml
- assemblies/assembly_business-optimizer-ER-sample-openshift/jbpm/master-docinfo.xml
- assemblies/assembly_business-optimizer-ER-sample-openshift/pam/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/dm/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/drools/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/jbpm/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/pam/master-docinfo.xml
- doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-script-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-openshift-deploy-con.adoc
- doc-content/enterprise-only/openshift/imagestreams-file-install-er-proc.adoc
…on (#71)
* Reference implementation download location and removing the term add-on
* SME/QE review changes
* typo
> [BXMSDOC-4711] Update Employee Rostering docs for download location and for QE review - master

- assemblies/assembly_business-optimizer-ER-sample-openshift/dm/master-docinfo.xml
- assemblies/assembly_business-optimizer-ER-sample-openshift/drools/master-docinfo.xml
- assemblies/assembly_business-optimizer-ER-sample-openshift/jbpm/master-docinfo.xml
- assemblies/assembly_business-optimizer-ER-sample-openshift/pam/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/dm/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/drools/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/jbpm/master-docinfo.xml
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/pam/master-docinfo.xml
- doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-script-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-openshift-deploy-con.adoc
- doc-content/enterprise-only/openshift/imagestreams-file-install-er-proc.adoc
…on (#71)
* Reference implementation download location and removing the term add-on
* SME/QE review changes
* typo
> [BXMSDOC-4711] Update Employee Rostering docs for download location and for QE review - 7.26.x

- doc-content/enterprise-only/integration/entando-con.adoc
- [Epic](https://issues.jboss.org/browse/BXMSDOC-4455)
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-4714)
- [Integrating RHPAM assets in Entando AppBuilder 7.5 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4714-PAM-Entando-Preview/#entando-con_integrating-with-entando)
Please review and verify **2nd paragraph** from Chapter 1. Digital Experience Platform (DXP) and AppBuilder.
> Upstream 7.26.x PR for BXMSDOC-4714: Update Entando App Builder doc as per changes in 7.5

- doc-content/enterprise-only/integration/entando-con.adoc
- [Epic](https://issues.jboss.org/browse/BXMSDOC-4455)
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-4714)
- [Integrating RHPAM assets in Entando AppBuilder 7.5 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4714-PAM-Entando-Preview/#entando-con_integrating-with-entando)
Please review and verify **2nd paragraph** from Chapter 1. Digital Experience Platform (DXP) and AppBuilder.
> Upstream master PR for BXMSDOC-4714: Update Entando App Builder doc as per changes in 7.5

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-defining-decision-logic-proc.adoc
as requested here https://github.com/kiegroup/kie-docs/pull/1944#pullrequestreview-300628290
> Cherry-pick 441774b to 7.26.x

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc
as requested here: https://github.com/kiegroup/kie-docs/pull/1945#pullrequestreview-300630130
> Cherry-pick e4049e2 to 7.26.x

- doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
- doc-content/enterprise-only/installation/clustering-dm-ks-configure-domain-proc.adoc
- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/installation/clustering-ps-install-proc.adoc
- doc-content/enterprise-only/installation/clustering-smartrouter-install-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.5.0.Final-section.adoc
* BXMSDOC-3428-master: Adopt suggestions to improve Installing and configuring BA in an EAP clustered environment
- Add example of controller URL
- Add explanation for watcher setting
- Add line regarding template files
- Add commands for add-user.sh and corrected windows commands
- Update EAP doc links
- Update process server curl command
- Add paragraph regarding JVM settings
- Correct typo
* BXMSDOC-3428-master: Adopt feedback to add NFS configuration prerequisite
* BXMSDOC-3428-master: Correct shared folder command
> BXMSDOC-4448-master: Adopt suggestions to improve Installing and configuring BA in an EAP clustered environment

- doc-content/enterprise-only/installation/clustering-bc-configure-standalone_proc.adoc
- doc-content/enterprise-only/installation/clustering-dm-ks-configure-domain-proc.adoc
- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/installation/clustering-ps-install-proc.adoc
- doc-content/enterprise-only/installation/clustering-smartrouter-install-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.5.0.Final-section.adoc
* BXMSDOC-3428-7.26.x: Adopt suggestions to improve Installing and configuring BA in an EAP clustered environment
- Add example of controller URL
- Add explanation for watcher setting
- Add line regarding template files
- Add commands for add-user.sh and corrected windows commands
- Update EAP doc links
- Update process server curl command
- Add paragraph regarding JVM settings
- Correct typo
* BXMSDOC-3428-7.26.x: Adopt feedback to add NFS configuration prerequisite
* BXMSDOC-3428-7.26.x: Correct shared folder command
> BXMSDOC-4448-7.26.x: Adopt suggestions to improve Installing and configuring BA in an EAP clustered environment

- doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
@cristianonicolai Please review it.
> JBPM-8766 Cannot start a task if elytron adapter is installed

- assemblies/assembly_configuring-central/main.adoc
- doc-content/enterprise-only/admin-and-config/exporting-importing-dashbuilder-data-proc.adoc
* BXMSDOC-4688-7.26.x: Add importing and exporting dashbuilder data procedure
* BXMSDOC-4688-7.26.x: Adopt feedback to add warning note
* BXMSDOC-4688-7.26.x: Adopt peer feedback to change warning note
> BXMSDOC-4405-7.26.x: Configuring BC settings & properties for DM/PAM 7.5

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-defining-decision-logic-proc.adoc
- doc-content/enterprise-only/installation/clustering-dev-con.adoc
* Correct image title.
* Change Node1 to `$node1`.
* Move period to end of conditional.
> BXMSDOC-4748-master: Stage sanity check and corrections

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-defining-decision-logic-proc.adoc
- doc-content/enterprise-only/installation/clustering-dev-con.adoc
* Correct image title.
* Change Node1 to `$node1`.
* Move period to end of conditional.
> BXMSDOC-4748-7.26.x: Stage sanity check and corrections

- doc-content/enterprise-only/admin-and-config/manage-tasks-con.adoc
- [Managing & monitoring business processes in RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-FP/#manage-tasks-con-managing-and-monitoring-processes)
> Upstream master PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

- doc-content/enterprise-only/admin-and-config/manage-tasks-con.adoc
- [Managing & monitoring business processes in RHPAM doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-FP/#manage-tasks-con-managing-and-monitoring-processes)
> Upstream 7.26.x PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

- doc-content/enterprise-only/admin-and-config/manage-tasks-con.adoc
- [Managing & monitoring business processes in RHPAM 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-7.4-preview/#manage-tasks-con-managing-and-monitoring-processes)
> Upstream 7.23.x PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/ReleaseNotesDrools.7.30.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/dmn-automatic-layout-enhancements.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/dmn-data-types-ux-enhancements.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/dmn-dos-as-dts.adoc
See:
- https://issues.jboss.org/browse/DROOLS-4549
- https://issues.jboss.org/browse/DROOLS-4548
- https://issues.jboss.org/browse/DROOLS-4547
@sterobin I've packaged all master DMN release notes PRs here (with fixes applied) to keep the things cleaner.
> DROOLS-4549 / DROOLS-4548 / DROOLS-4547: [DMN Designer] DMN 7.30.x - Release notes

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/ReleaseNotesDrools.7.30.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/dmn-automatic-layout-enhancements.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/dmn-data-types-ux-enhancements.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.30.0.Final/dmn-dos-as-dts.adoc
See:
- https://issues.jboss.org/browse/DROOLS-4549
- https://issues.jboss.org/browse/DROOLS-4548
- https://issues.jboss.org/browse/DROOLS-4547
@sterobin I've packaged all 7.30.x DMN release notes PRs here (with fixes applied) to keep the cherry-pick cleaner.
> [7.30.x] DROOLS-4549 / DROOLS-4548 /  DROOLS-4547: [DMN Designer] DMN 7.30.x - Release notes

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/business-central-system-properties-ref.adoc
[BXMSDOC-4960](https://issues.jboss.org/browse/BXMSDOC-4960)
> Bxmsdoc 4960 7.26.x Business Central properties section

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/business-central-system-properties-ref.adoc
[BXMSDOC-4960](https://issues.jboss.org/browse/BXMSDOC-4960)
> BXMSDOC-4960 7.30.x Business Central properties section

- assemblies/assembly_migrating-6.4-to-7.x/main.adoc
- assemblies/assembly_migrating-7.0-to-7.x/main.adoc
- doc-content/enterprise-only/migration/migration-execution-server-con.adoc
- doc-content/enterprise-only/migration/migration-non-execution-server-con.adoc
> BXMSDOC-3863 master Clarification regarding .niogit folder in RHDM when following migration document from BRMS 6.4

- assemblies/assembly_migrating-6.4-to-7.x/main.adoc
- assemblies/assembly_migrating-7.0-to-7.x/main.adoc
- doc-content/enterprise-only/migration/migration-execution-server-con.adoc
- doc-content/enterprise-only/migration/migration-non-execution-server-con.adoc
> BXMSDOC-3863 7.26.x Clarification regarding .niogit folder in RHDM when following migration document from BRMS 6.4

- assemblies/assembly_migrating-6.4-to-7.x/main.adoc
- assemblies/assembly_migrating-7.0-to-7.x/main.adoc
- doc-content/enterprise-only/migration/migration-execution-server-con.adoc
- doc-content/enterprise-only/migration/migration-non-execution-server-con.adoc
> BXMSDOC-3863 7.30.x Clarification regarding .niogit folder in RHDM when following migration document from BRMS 6.4

- docs/product-assembly_migrating-6.4-to-7.x/src/main/asciidoc/main.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-execution-server-con.adoc
- docs/product-migration-guide/src/main/asciidoc/migration-non-execution-server-con.adoc
> BXMSDOC-3863 7.7.x Clarification regarding .niogit folder in RHDM when following migration document from BRMS 6.4

- assemblies/assembly_migrating-6.4-to-7.x/main.adoc
- assemblies/assembly_migrating-7.0-to-7.x/main.adoc
- doc-content/enterprise-only/migration/migration-execution-server-con.adoc
- doc-content/enterprise-only/migration/migration-non-execution-server-con.adoc
> BXMSDOC-3863 7.11.x Clarification regarding .niogit folder in RHDM when following migration document from BRMS 6.4

- _artifacts/document-attributes.adoc
- doc-content/enterprise-only/openshift/hacep-server-proc.adoc
- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
* rename downloadable for HACEP (#79) (#2072)
* HACEP workaround
* corrected JIRA in RN issue
* yaml file name change for HACEP
* BOM version for 7.5.1 as per CR1
> [BXMSDOC-5048] HACEP workaround - docs and RN, 7.5.1 only

- doc-content/enterprise-only/admin-and-config/managing-business-central-integrating-remote-git-repositories-proc.adoc
- doc-content/enterprise-only/openshift/apb-deploy-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-monitoring-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-server-kjar-proc.adoc
- doc-content/enterprise-only/openshift/environment-immutable-server-proc.adoc
- doc-content/enterprise-only/openshift/environment-managed-deploy-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-centralmavenpwd-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-connectcentral-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
- doc-content/enterprise-only/openshift/template-deploy-optionalmaven-proc.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithCases-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithHanldersAndListeners-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithJPA-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithProcesses-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/ElasticSearchBusinessApp-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/JMSBusinessApp-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Designer/Customization-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/Installer/10MinWorkbench-section.adoc
- doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.10.0.Final-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/General/Introduction-section.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/SecurityManagement/SecurityManagement-section.adoc
Cherry-pick #2084 by @jaferkhan for 7.6 release.
> [7.30.x] Corrected usages of the word 'username' across all files (#2084)

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/performance-tuning-drl-ref.adoc
@mariofusco , @baldimir , can you verify this new performance tuning segment on equality operators? Per our discussion in chat and in the performance turning google doc.
Links:
* [JIRA](https://issues.redhat.com/browse/BXMSDOC-5032)
* [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-5032/#performance-tuning-drl-ref_drl-rules)
> BXMSDOC-5032-master: Add DRL performance tuning for equality operators.

- assemblies/assembly_openshift-authoring/main.adoc
Small 7.5.1 change, no review required as it simply takes out a few words. This reflects the change of requirements that happened in 7.5 at the last moment. This change along with many others was fully reviewed in BXMSDOC-5038.
> [XMSDOC-5039] RWX required for all authoring PAM - 7.26.x

- assemblies/assembly_openshift-authoring-managed/main.adoc
- doc-content/enterprise-only/openshift/ba-openshift-overview-con.adoc
- doc-content/enterprise-only/openshift/environment-authoring-con.adoc
- doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
- doc-content/enterprise-only/openshift/template-overview-con.adoc
* Document Tier 1 support for OpenShift Authoring HA template
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* SME review changes for Jakub
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* peer review changes
> [BXMSDOC-5040] Document Tier 1 support for OpenShift Authoring HA template - 7.30.x

- assemblies/assembly_openshift-authoring-managed/main.adoc
- doc-content/enterprise-only/openshift/ba-openshift-overview-con.adoc
- doc-content/enterprise-only/openshift/environment-authoring-con.adoc
- doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
- doc-content/enterprise-only/openshift/template-overview-con.adoc
* Document Tier 1 support for OpenShift Authoring HA template
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* SME review changes for Jakub
* Update doc-content/enterprise-only/openshift/environment-authoring-con.adoc
Co-Authored-By: Jakub Schwan <jakubschwan@users.noreply.github.com>
* peer review changes
> [BXMSDOC-5040] Document Tier 1 support for OpenShift Authoring HA template - master

- _artifacts/document-attributes.adoc
- assemblies/assembly_business-optimizer-modifying-ER-template-IDE/main.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-prepare-proc.adoc
- doc-content/enterprise-only/employee-rostering/er-deploy-s2i-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-IntelliJ-IDEA-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-db-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-commandline-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-building-eclipse-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-modifying-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-overview-source-con.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-running-jar-proc.adoc
- doc-content/enterprise-only/employee-rostering/optashift-ER-runningwar-proc.adoc
[BXMSDOC-4836](https://issues.redhat.com/browse/BXMSDOC-4836)
> BXMSDOC-5023 7.30.x Running and modifying the employee roster starter application for Red Hat Business Optimizer using an IDE for PAM/DM 7.6

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
- doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc
* AMQ configuration
* Removal of Smart Router DM plus peer review
> [BXMSDOC-5045] AMQ configuration - master

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
- doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc
* AMQ configuration
* Removal of Smart Router DM plus peer review
> [BXMSDOC-5045] AMQ configuration - 7.30.x

- doc-content/enterprise-only/getting-started/assets-creating-proc.adoc
[BXMSDOC-4896](https://issues.redhat.com/browse/BXMSDOC-4896)
> BXMSDOC-4896 7.30.x Managing Assets

- doc-content/enterprise-only/installation/jws-con.adoc
[BXMSDOC-4917](https://issues.redhat.com/browse/BXMSDOC-4917)
> BXMSDOC-4917 7.30.x Planning the Installation

- doc-content/enterprise-only/installation/jws-con.adoc
[BXMSDOC-4917](https://issues.redhat.com/browse/BXMSDOC-4917)
> BXMSDOC-4917 master Planning the Installation

- doc-content/enterprise-only/project-data/creating-change-requests-proc.adoc
- doc-content/enterprise-only/project-data/delete-branches-proc.adoc
- doc-content/enterprise-only/project-data/git-import-project-proc.adoc
- doc-content/enterprise-only/project-data/modify-project-proc.adoc
[BXMSDOC-4899](https://issues.redhat.com/browse/BXMSDOC-4899)
> BXMSDOC-5124 master Managing Projects

- doc-content/enterprise-only/project-data/creating-change-requests-proc.adoc
- doc-content/enterprise-only/project-data/delete-branches-proc.adoc
- doc-content/enterprise-only/project-data/git-import-project-proc.adoc
- doc-content/enterprise-only/project-data/modify-project-proc.adoc
[BXMSDOC-4899](https://issues.redhat.com/browse/BXMSDOC-4899)
> BXMSDOC-5124 7.30.x Managing Projects

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.32.0.Final/ReleaseNotesDrools.7.32.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.32.0.Final/dmn-code-completion.adoc
See https://issues.jboss.org/browse/DROOLS-4693
> DROOLS-4693: [DMN Designer] Code Completion - Update release notes

- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc
**JIRA:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-4890)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-4892)
**7.6 doc previews:**
- [Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4890-RHPAM-MMPS/#kie-server-extensions-con_execution-server)
- [Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4890-RHDM-MMPS/#kie-server-extensions-con_execution-server)
**Community doc previews:**
- [Drools Document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-DROOLS-KSSystemProperty/#kie-server-system-properties-ref_kie-apis)
- [jBPM Document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-jBPM-KSSystemProperty/#kie-server-system-properties-ref_kie-apis)
For RHPAM --> Chapter 23: Please check …
> Upstream 7.30.x PR for BXMSDOC-4890: Update managing & monitoring Process/Decision server doc for PAM/DM 7.6

- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc
**JIRA:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-4890)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-4892)
**7.6 doc previews:**
- [Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4890-RHPAM-MMPS/#kie-server-extensions-con_execution-server)
- [Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4890-RHDM-MMPS/#kie-server-extensions-con_execution-server)
**Community doc previews:**
- [Drools Document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-DROOLS-KSSystemProperty/#kie-server-system-properties-ref_kie-apis)
- [jBPM Document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-jBPM-KSSystemProperty/#kie-server-system-properties-ref_kie-apis)
For RHPAM --> Chapter 23: Please check …
> Upstream master PR for BXMSDOC-4890: Update managing & monitoring Process/Decision server doc for PAM/DM 7.6

- doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-background-rule-based-proc.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc
**7.6 doc previews:** 
- [RHPAM 7.6: Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-TS-RHPAM/)
- [RHDM 7.6: Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-TS-RHDM/)
- [RHPAM 7.6: Managing and monitoring process server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-MMPS-RHPAM/)
- [RHDM 7.6: Managing and monitoring decision server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-MMPS-RHDM/)
**Community doc previews:**
- [Drools document for kie server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Drools-Changes/#kie-server-system-properties-ref_kie-apis)
- [jBPM document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-jBPM-Changes/#kie-server-s …
> Upstream master PR: Resolved some typos, outdated content from the kie server and test scenario documents

- doc-content/enterprise-only/openshift/hacep-client-proc.adoc
- doc-content/enterprise-only/openshift/hacep-clientcode-ref.adoc
- doc-content/enterprise-only/openshift/hacep-server-proc.adoc
* Donato's HACEP server build changes
* formatting fix
* Donato review
* AMQ Streams hacep clarification
> [BXMSDOC-5043] HACEP changes based on Donato's comments - 7.30.x

- doc-content/enterprise-only/openshift/hacep-client-proc.adoc
- doc-content/enterprise-only/openshift/hacep-clientcode-ref.adoc
- doc-content/enterprise-only/openshift/hacep-server-proc.adoc
* Donato's HACEP server build changes
* formatting fix
* Donato review
* AMQ Streams hacep clarification
> [BXMSDOC-5043] HACEP changes based on Donato's comments - master

- _artifacts/document-attributes.adoc
- assemblies/assembly_install-on-jws/main.adoc
- doc-content/enterprise-only/admin-and-config/custom-tasks-registering-custom-tasks-proc.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/installer-run-proc.adoc
- doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
- doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
* BXMSDOC-4911-master: Update JWS version attributes from 5.1 to 5.2
* BXMSDOC-4911-master: Update artifact file name versions
* BXMSDOC-4911-master: Change ” character to " in example code
* BXMSDOC-4911-master: Change "on the same server" to "in the same container"
* BXMSDOC-4911-master: Update file name version
* BXMSDOC-4911-master: Update BOM and Maven artifact attributes
> BXMSDOC-4911-master: Installing PAM/DM 7.6 on JWS

- _artifacts/document-attributes.adoc
- assemblies/assembly_install-on-jws/main.adoc
- doc-content/enterprise-only/admin-and-config/custom-tasks-registering-custom-tasks-proc.adoc
- doc-content/enterprise-only/installation/controller-jws-install-proc.adoc
- doc-content/enterprise-only/installation/installer-run-proc.adoc
- doc-content/enterprise-only/installation/jws-jdbc-config_proc.adoc
- doc-content/enterprise-only/installation/jws-zip-install-proc.adoc
- doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
* BXMSDOC-4911-7.30.x: Update JWS version attributes from 5.1 to 5.2
* BXMSDOC-4911-7.30.x: Update artifact file name versions
* BXMSDOC-4911-7.30.x: Change ” character to " in example code
* BXMSDOC-4911-7.30.x: Change "on the same server" to "in the same container"
* BXMSDOC-4911-7.30.x: Update file name version
* BXMSDOC-4911-7.30.x: Update BOM and Maven artifact attributes
> BXMSDOC-4911-7.30.x: Installing PAM/DM 7.6 on JWS

- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
- doc-content/enterprise-only/weblogic/controller-wls-install-proc.adoc
- doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
* BXMSDOC-4875-master: Update artifact file name versions
* BXMSDOC-4875-master: Adopt peer feedback and correct version number
> BXMSDOC-4875-master: Update artifact file name versions and change character

- doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc
- doc-content/enterprise-only/installation/controller-eap-install-proc.adoc
- doc-content/enterprise-only/weblogic/controller-wls-install-proc.adoc
- doc-content/enterprise-only/weblogic/wls-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/controller-was-install-proc.adoc
- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
* BXMSDOC-4875-7.30.x: Update artifact file name versions
* BXMSDOC-4875-7.30.x: Adopt peer feedback and correct version number
> BXMSDOC-4875-7.30.x: Update artifact file name versions and change character

- doc-content/enterprise-only/admin-and-config/central-app-header-customize-proc.adoc
- doc-content/enterprise-only/admin-and-config/central-login-customize-proc.adoc
- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/installation/git-import-proc.adoc
- doc-content/enterprise-only/installation/install-testing-proc.adoc
- doc-content/enterprise-only/installation/ssh-configuring-proc.adoc
* BXMSDOC-4914-7.30.x: Update attribute used for zip files to PRODUCT_VERSION_LONG
* BXMSDOC-4914-7.30.x: Update UI elements and image naming
> BXMSDOC-4914-7.30.x: Update UI elements and image naming

- doc-content/enterprise-only/admin-and-config/central-app-header-customize-proc.adoc
- doc-content/enterprise-only/admin-and-config/central-login-customize-proc.adoc
- doc-content/enterprise-only/installation/eap-data-source-add-proc.adoc
- doc-content/enterprise-only/installation/git-import-proc.adoc
- doc-content/enterprise-only/installation/install-testing-proc.adoc
- doc-content/enterprise-only/installation/ssh-configuring-proc.adoc
* BXMSDOC-4914-master: Update attribute used for zip files to PRODUCT_VERSION_LONG
* BXMSDOC-4914-master: Update UI elements and image naming
> BXMSDOC-4914-master: Update UI elements and image naming

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
- doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc
> BXMSDOC-4924 7.30.x Emily's RN updates

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
* last minute known issue
* link to jira
* Peer review for new known issue
> [BXMSDOC-4920] last minute known issue - master

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
* last minute known issue
* link to jira
* Peer review for new known issue
> [BXMSDOC-4920] last minute known issue - 7.30.x

- _artifacts/document-attributes.adoc
- doc-content/enterprise-only/release-notes/rn-760-fixed-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
- doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
- doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc
BXMSDOC-5164 updated RN with sanity check issues
> BXMSDOC-5164 7.30.x RN sanity check fixes

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
* Known issue RHPAM-2557
* peer review
> [BXMSDOC-4920] Known issue RHPAM-2557 - 7.30.x

- doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc
* Known issue RHPAM-2557
* peer review
> [BXMSDOC-4920] Known issue RHPAM-2557 - master

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.32.0.Final/ReleaseNotesDrools.7.32.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.32.0.Final/scesim-kieserver.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc
@yesamer @jomarko @kaldesai 
https://issues.redhat.com/browse/DROOLS-4883
> [DROOLS-4883] Test Scenario on Kie-server

- doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/kie-scanner-proc.adoc
See Jira: https://issues.redhat.com/browse/BXMSDOC-5178
> BXMSDOC-5178-master: Updated Kie-Scanner Note

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-creating-custom-datatypes-proc.adoc
cherry-pick against branch `7.33.x` as requested here: https://github.com/kiegroup/kie-docs/pull/2188#issuecomment-585190817
> Fix typo for DMN custom data type name

- assemblies/assembly_designing-business-processes/main.adoc
[BXMSDOC-5249](https://issues.redhat.com/browse/BXMSDOC-5249)
> BXMSDOC-5249 7.33 Designing Business Process TOC reorg

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-creating-custom-datatypes-proc.adoc
[BXMSDOC-5249](https://issues.redhat.com/browse/BXMSDOC-5249)
> BXMSDOC-5249 master Designing Business Process TOC reorg

- doc-content/drools-docs/src/main/asciidoc/DMN/dmn-properties-ref.adoc
> BXMSDOC-5425 Document DMN runtime listener prop

- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-constraints-con.adoc
- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-facts-vs-entities-con.adoc
- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-optimizer-drools-rules-proc.adoc
- doc-content/enterprise-only/optimizer/optimizer-NP-complete-vs-NP-hard-con.adoc
- doc-content/enterprise-only/optimizer/optimizer-hard-vs-soft-constraints-con.adoc
- doc-content/enterprise-only/optimizer/optimizer-search-space-con.adoc
[JIRA](https://issues.redhat.com/browse/BXMSDOC-5175)
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5175/)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5175-dm)
> BXMSDOC-5175-7.33.x: Employee Rostering edits

- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-constraints-con.adoc
- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-facts-vs-entities-con.adoc
- doc-content/enterprise-only/employee-rostering/wb-employee-rostering-optimizer-drools-rules-proc.adoc
- doc-content/enterprise-only/optimizer/optimizer-NP-complete-vs-NP-hard-con.adoc
- doc-content/enterprise-only/optimizer/optimizer-hard-vs-soft-constraints-con.adoc
- doc-content/enterprise-only/optimizer/optimizer-search-space-con.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5175
> BXMSDOC-5175-master: Employee Rostering edits

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.33.0.Final/ReleaseNotesDrools.7.33.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.33.0.Final/lambda-externalisation.adoc
https://github.com/kiegroup/droolsjbpm-knowledge/pull/426
https://github.com/kiegroup/drools/pull/2782
https://github.com/kiegroup/kie-docs/pull/2207
> [DROOLS-5105] New release note for lambda externalisation option

- doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/kie-scanner-proc.adoc
JIRA:https://issues.redhat.com/browse/BXMSDOC-5178
[RHPAM 7.6 ](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5178-RHPAM-7.6/)
[RHDM 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5178-RHDM-7.6/)
> Upstream 7.30.x PR for BXMSDOC-5178: Made change in Packaging & deploying doc

- doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/kie-scanner-proc.adoc
JIRA: https://issues.redhat.com/browse/BXMSDOC-5178
[RHPAM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5178-RHPAM-7.5/#kie-scanner-proc_packaging-deploying)
[RHDM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5178-RHDM-7.5/#kie-scanner-proc_packaging-deploying)
> Upstream 7.26.x PR for BXMSDOC-5178: Made a change in Packaging & deploying doc

- doc-content/enterprise-only/openshift/offline-repo-proc.adoc
* Operator offline deployment changes
* Clarified Nexus procedure doc for Operator
* formatting fix
* peer review
* peer review2
> [BXMSDOC-5391] disconnected operator install - 7.33.x

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/jvm-settings-ref.adoc
- doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
* Operator UI updates for 7.7
* KIE server JVM config
* Controller strategy for operator
* more JVM settings part 1
* JVM config full information; external DB driver
* Corrections re internal authentication
* typo fixes
> [BXMSDOC-5261] Operator UI updates for 7.7 - master

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/jvm-settings-ref.adoc
- doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc
- doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc
* Operator UI updates for 7.7
* KIE server JVM config
* Controller strategy for operator
* more JVM settings part 1
* JVM config full information; external DB driver
* Corrections re internal authentication
* typo fixes
> [BXMSDOC-5261] Operator UI updates for 7.7 - 7.33.x

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.34.0.Final/ReleaseNotesDrools.7.34.0.Final-section.adoc
- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.34.0.Final/kie-dmn-validation-in-maven-plugin.adoc
> DROOLS-5020 DMN wire Validator to kie-maven-plugin Maven build

- doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.34.0.Final/kie-dmn-validation-in-maven-plugin.adoc
As requested https://github.com/kiegroup/kie-docs/pull/2228#issuecomment-593282530
> Rewording as per review feedback

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/hacep-server-proc.adoc
- doc-content/enterprise-only/openshift/readwritemany-proc.adoc
- doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc
* RWX clarification and OCP 4.3
* SME review
> [BXMSDOC-5368] operator prereqs clarification and OCP 4.3 - master

- assemblies/assembly_openshift-operator/main.adoc
- doc-content/enterprise-only/openshift/hacep-server-proc.adoc
- doc-content/enterprise-only/openshift/readwritemany-proc.adoc
- doc-content/enterprise-only/openshift/secrets-secrettarget-create-proc.adoc
* RWX clarification and OCP 4.3
* SME review
> [BXMSDOC-5368] operator prereqs clarification and OCP 4.3 - 7.33.x

- assemblies/assembly_configuring-central/main.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-adding-archetype-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-additional-features-archetype-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-archetype-con.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-archetype-space-settings-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-creating-archetype-project-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-listing-archetype-proc.adoc
**JIRA:** 
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5199)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5434)
**7.7 Doc previews:** 
- [RHPAM 7.7 Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5434-RHPAM-Maven-Archetype/#managing-business-central-listing-archetype-proc)
- [RHDM 7.7 Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5434-RHDM-Maven-Archetype/#managing-business-central-listing-archetype-proc)
Added a new chapter as **CHAPTER 6. ARCHETYPE MANAGEMENT** in Configuring Business Central settings and properties doc.
> Upstream master PR for BXMSDOC-5434: Update configuring business central settings and properties doc per changes in RHDM/RHPAM 7.7

- assemblies/assembly_configuring-central/main.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-adding-archetype-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-additional-features-archetype-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-archetype-con.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-archetype-space-settings-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-creating-archetype-project-proc.adoc
- doc-content/enterprise-only/admin-and-config/managing-business-central-listing-archetype-proc.adoc
**JIRA:** 
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5199)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5434)
**7.7 Doc previews:** 
- [RHPAM 7.7 Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5434-RHPAM-Maven-Archetype/#managing-business-central-listing-archetype-proc)
- [RHDM 7.7 Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5434-RHDM-Maven-Archetype/#managing-business-central-listing-archetype-proc)
Added a new chapter as **CHAPTER 6. ARCHETYPE MANAGEMENT** in Configuring Business Central settings and properties doc.
> Upstream 7.33.x PR for BXMSDOC-5434: Update configuring business central settings and properties doc per changes in RHDM/RHPAM 7.7

- doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc
**JIRAs:** 
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5200)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5458)
**7.7 doc previews**
- [RHPAM 7.7 Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5458-RHPAM-SSO/#sso-client-adapter-proc)
- [RHDM 7.7 Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5458-RHDM-SSO/#sso-client-adapter-proc)
Please check **step 9** from section 4.2. Installing the RH-SSO client adapter for Business Central.
> Upstream master PR for BXMSDOC-5458: Update the RH-SSO doc per changes in RHDM/RHPAM 7.7

- assemblies/assembly_hacep/main.adoc
- doc-content/enterprise-only/openshift/hacep-client-proc.adoc
- doc-content/enterprise-only/openshift/hacep-clientcode-ref.adoc
- doc-content/enterprise-only/openshift/hacep-con.adoc
- doc-content/enterprise-only/openshift/hacep-server-environment-ref.adoc
- doc-content/enterprise-only/openshift/hacep-server-maven-proc.adoc
* First version: HACEP security and updateable KJAR
* SME review
* Typo fixes and removing SNAPSHOT
* fix removal of dependency
* OpenShift verison fixes
* Peer review
> [BXMSDOC-5265] [BXMSDOC-5266] HACEP security and updateable KJAR - master

- assemblies/assembly_hacep/main.adoc
- doc-content/enterprise-only/openshift/hacep-client-proc.adoc
- doc-content/enterprise-only/openshift/hacep-clientcode-ref.adoc
- doc-content/enterprise-only/openshift/hacep-con.adoc
- doc-content/enterprise-only/openshift/hacep-server-environment-ref.adoc
- doc-content/enterprise-only/openshift/hacep-server-maven-proc.adoc
* First version: HACEP security and updateable KJAR
* SME review
* Typo fixes and removing SNAPSHOT
* fix removal of dependency
* OpenShift verison fixes
* Peer review
> [BXMSDOC-5265] [BXMSDOC-5266] HACEP security and updateable KJAR - 7.33.x

- doc-content/enterprise-only/admin-and-config/custom-tasks-creating-work-item-handler-projects-proc.adoc
- doc-content/enterprise-only/admin-and-config/manage-service-tasks-proc.adoc
* BXMSDOC-5179-master: Remove RHPAM-1772 workaround
* BXMSDOC-5179-master: Add optional step to remove service tasks
* BXMSDOC-5179-master: Remove "-Dmaven.test.skip=true" property
> BXMSDOC-5179-master: Create custom tasks/workitem handlers using RHPAM 7.7

- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/create-archetype-project-proc.adoc
See JIRA:
https://issues.redhat.com/browse/BXMSDOC-5410
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5410-RHPAM/#create_archetype_project)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5410-RHDM/#create_archetype_project)
> BXMSDOC-5410: New Section "Creating a project using Archetypes" for Managing Projects

- assemblies/assembly_managing-projects/main.adoc
- doc-content/enterprise-only/project-data/create-archetype-project-proc.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5410
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5410-RHPAM/#create_archetype_project)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5410-RHDM/#create_archetype_project)
> BXMSDOC-5410: New Section "Creating a project using Archetypes" for Managing Projects doc

- doc-content/enterprise-only/project-data/reviewing-change-requests-proc.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5358
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5358-RHPAM/#reviewing-change-requests-proc_managing-projects)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5358-RHDM/#reviewing-change-requests-proc_managing-projects)
> BXMSDOC-5358: Changed the button name to Squash and Merge in Change Requests for Managing Projects

- doc-content/enterprise-only/processes/process-instance-details-con.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5353
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5353-RHPAM/#process-instance-details-con-managing-and-monitoring-processes)
> BXMSDOC-5353: Navigation between subprocess and parent process in Managing and Monitoring BP doc for PAM

- doc-content/enterprise-only/processes/process-instance-details-con.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5353
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5353-RHPAM/#process-instance-details-con-managing-and-monitoring-processes)
> BXMSDOC-5353: Navigation between subprocess and parent process in Managing and Monitoring BP for PAM

- assemblies/assembly_packaging-deploying/main.adoc
- doc-content/enterprise-only/admin-and-config/deployment-unit-create-proc.adoc
- doc-content/enterprise-only/project-data/container-alias-con.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-central-proc.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5162
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5162-RHPAM/#container-alias-con_packaging-deploying)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5162-RHDM/#container-alias-con_packaging-deploying)
> BXMSDOC-5162: Added KIE Container Aliases section in Packaging and Deploying doc

- assemblies/assembly_packaging-deploying/main.adoc
- doc-content/enterprise-only/admin-and-config/deployment-unit-create-proc.adoc
- doc-content/enterprise-only/project-data/container-alias-con.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-central-proc.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5162
[RHPAM 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5162-RHPAM7.6/#container-alias-con_packaging-deploying)
[RHDM 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5162-RHDM7.6/#container-alias-con_packaging-deploying)
> BXMSDOC-5162-7.30.x: Added KIE Container Aliases section in Packaging and Deploying doc

- assemblies/assembly_packaging-deploying/main.adoc
- doc-content/enterprise-only/admin-and-config/deployment-unit-create-proc.adoc
- doc-content/enterprise-only/project-data/container-alias-con.adoc
- doc-content/enterprise-only/project-data/project-build-deploy-central-proc.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5162
[RHPAM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5162-RHPAM7.5/#container-alias-con_packaging-deploying)
[RHDM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5162-RHDM7.5/#container-alias-con_packaging-deploying)
> BXMSDOC-5162-7.26.x: Added KIE Container Aliases section in Packaging and Deploying doc

- assemblies/assembly_designing-and-building-cases/main.adoc
- doc-content/enterprise-only/cases/case-management-clean-case-log-proc.adoc
- doc-content/enterprise-only/cases/case-management-closing-cases-ref.adoc
Original jira: https://issues.redhat.com/browse/BXMSDOC-5099
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5099/#case-management-clean-case-log-proc
> Upstream pull request: BXMSDOC-5099 to upstream master New CaseLogCleanupCommand command

- assemblies/assembly_designing-and-building-cases/main.adoc
- doc-content/enterprise-only/cases/case-management-clean-case-log-proc.adoc
- doc-content/enterprise-only/cases/case-management-closing-cases-ref.adoc
Original jira: https://issues.redhat.com/browse/BXMSDOC-5099
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5099/#case-management-clean-case-log-proc
> Upstream pull request: BXMSDOC-5099 to 7.33.x New CaseLogCleanupCommand command

- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-install-start-proc.adoc
Jira: https://issues.redhat.com/browse/BXMSDOC-5509
> Upstream PR for fixed links found during 7.7.x doc sanity check

- doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
- doc-content/enterprise-only/websphere/was-install-start-proc.adoc
Jira: https://issues.redhat.com/browse/BXMSDOC-5509
> Upstream PR to 7.33.x for fixed links found during 7.7.x doc sanity check

- doc-content/enterprise-only/installation/installer-run-proc.adoc
* BXMSDOC-5183-master: Update installation procedure
* BXMSDOC-5183-master: Update UI elements
* BXMSDOC-5183-master: Adopt peer feedback
> BXMSDOC-5183-master: Update installation procedure

- doc-content/enterprise-only/installation/installer-run-proc.adoc
* BXMSDOC-5183-7.33.x: Update installation procedure
* BXMSDOC-5183-7.33.x: Update UI elements
* BXMSDOC-5183-7.33.x: Adopt peer feedback
> BXMSDOC-5183-7.33.x: Update installation procedure

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-jobs-ref.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-projects-ref.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-spaces-ref.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5527
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5527-RHPAM/#knowledge-store-rest-api-endpoints-ref_kie-apis)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5527-RHDM/#knowledge-store-rest-api-branches-ref_kie-apis)
> Upstream master PR for BXMSDOC-5527: Changed the parameter table columns size as 15%,45%,15%,25%

- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-jobs-ref.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-projects-ref.adoc
- doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-spaces-ref.adoc
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5527
[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5527-RHPAM/#knowledge-store-rest-api-endpoints-ref_kie-apis)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5527-RHDM/#knowledge-store-rest-api-branches-ref_kie-apis)
> Upstream 7.33.x PR for BXMSDOC-5527: Changed the parameter table columns size as 15%,45%,15%,25%

- _artifacts/document-attributes.adoc
- doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
- doc-content/enterprise-only/openshift/offline-repo-proc.adoc
- doc-content/enterprise-only/openshift/rhdm77-prod-immutable-kieserver-amq-ref.adoc
- doc-content/enterprise-only/openshift/rhdm77-prod-immutable-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhpam77-kieserver-externaldb-ref.adoc
- doc-content/enterprise-only/openshift/rhpam77-prod-immutable-kieserver-amq-ref.adoc
- doc-content/enterprise-only/openshift/rhpam77-prod-immutable-kieserver-ref.adoc
* New offliner procedure
* Review and link issues
* Rebuilt date
> [BXMSDOC-5363] New offliner procedure, also link issues, rebuilt date - master

- _artifacts/document-attributes.adoc
- doc-content/enterprise-only/openshift/externaldb-build-proc.adoc
- doc-content/enterprise-only/openshift/offline-repo-proc.adoc
- doc-content/enterprise-only/openshift/rhdm77-prod-immutable-kieserver-amq-ref.adoc
- doc-content/enterprise-only/openshift/rhdm77-prod-immutable-kieserver-ref.adoc
- doc-content/enterprise-only/openshift/rhpam77-kieserver-externaldb-ref.adoc
- doc-content/enterprise-only/openshift/rhpam77-prod-immutable-kieserver-amq-ref.adoc
- doc-content/enterprise-only/openshift/rhpam77-prod-immutable-kieserver-ref.adoc
* New offliner procedure
* Review and link issues
* Rebuilt date
> [BXMSDOC-5363] New offliner procedure, also link issues, rebuilt date - 7.33.x

- doc-content/enterprise-only/integration/codeready-studio-installing-runtime-environments-proc.adoc
[Integrating Red Hat CodeReady Studio with Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHPAM/#codeready-studio-installing-runtime-environments-proc)
[Integrating Red Hat CodeReady Studio with Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHDM/#codeready-studio-installing-runtime-environments-proc)
> Upstream master PR for BXMSDOC-5517: Replaced decision engine with process engine for PAM doc

- doc-content/enterprise-only/integration/dev-studio-installing-runtime-environments-proc.adoc
[RHPAM 7.3](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHPAM7.3/#dev-studio-installing-runtime-environments-proc)
[RHDM 7.3](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHDM7.3/#dev-studio-installing-runtime-environments-proc)
> Upstream 7.18.x PR for BXMSDOC-5517: Replaced decision engine with process engine for PAM doc

- doc-content/enterprise-only/springboot/bus-app-create_proc.adoc
This change will have upstream 7.26, 7.30, and 7.33 PRs to cover 7.5 - 7.7
Original jira: https://issues.redhat.com/browse/BXMSDOC-5091
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5091/#bus-app-create_business-applications
> Upstream PR BXMSDOC-5091 to upstream Master added missing closing bracket to code snippet (#136)

- doc-content/enterprise-only/installation/install-testing-proc.adoc
Added missing Step 7 for version 7.5. Future versions OK.
Original jira: https://issues.redhat.com/browse/BXMSDOC-5042
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5042/#verifying_the_red_hat_decision_manager_installation
> Upstream PR BXMSDOC-5042-7.26.x to upstream 7.26.x Added missing MySpace step to 7.5 doc
