apache/incubator-kie-docs

jbpm-asciidocs/src/main/asciidoc/RemoteAPI/REST-section.adoc
jbpm-docs/src/main/docbook/en-US/RemoteAPI/REST-section.xml

Add /deployment/processes REST call which is already implemented in DeploymentsResourceImpl.
(docbook is generated from adoc following the guidance in https://issues.jboss.org/browse/JBPM-4568)

Add /deployment/processes REST call

---

shared/KIE/BuildDeployUtilizeAndRun/KIEDeploying.xml

With reference to Drools-usage Google group discussion Ref.
https://groups.google.com/d/topic/drools-usage/XpFlRNjuc9c/discussion
Report below summary for reference.
I think statement is missing to describe
what happens to already existing KieSession and KieBase; from the
current description I would have assumed only "new" stuff gets
up-to-date, but (fortunately!) also some type of already-existing
KieSession and KieBase gets automatically updated.
Current behavior "From this moment on" proved by code actually is:
1- already existing KieBase, generated with getKieBase() : it does get
automatically updated. This is the use case of named KieBase or default
KieBase referenced from kmodule.xml 
2- already existing KieBase, generated with newKieBase() : NOT
automatically updated. This is the …

KieScanner behavior for already existing KieBases and KieSessions

---

shared/Workbench/Installation/Installation.xml

@psiroky Please merge? 
Thanks!

GUVNOR-2335 - adding documentation about the 'org.uberfire.nio.git.hooks' property used to add Git hook scripts to repositories

---

shared/KieServer/Install.xml

Hi,
I saw a bug report for an [incorrect URL](https://bugzilla.redhat.com/show_bug.cgi?id=1270787). I think this changes it, correct? 
This is upstream issue only. Hope this helps a bit.

6.4.x - Change incorrect URL

---

drools-asciidocs/src/main/asciidoc/LanguageReference/Rule-section.adoc
drools-docs/src/main/docbook/en-US/LanguageReference/Rule.xml

Make explicit full-extended call to method is the proper way for 
running a query from a rule's RHS.
Make explicit the full-extended call to method is the only supported
method for running a query from a rule's RHS.

DROOLS-1232 calling getQueryResults() from RHS would hang indefinitely.

---

shared/KieServer/JavaClientAPI.xml
shared/KieServer/RestAPI.xml

[6.5.x] [JBPM-5250] kie-server: add few examples of containers filtering

---

drools-docs/src/main/asciidoc/index.adoc
jbpm-docs/src/main/asciidoc/index.adoc
optaplanner-wb-es-docs/src/main/asciidoc/index.adoc

* TOC was previously before the content. Since
the displays are wide enough these days, movfing
the TOC to left is great way to make navigation
in the docs easier
This is how it looks like:

Move TOC to left side of the page

---

jbpm-docs/src/main/docbook/en-US/Installer/Configuration.xml

Please refer to https://github.com/droolsjbpm/jbpm/pull/585 Thanks!

JBPM-5082: Updated the authentication configuration section for the jbpm installer.

---

shared/Workbench/Installation/Installation-section.adoc

See https://groups.google.com/forum/#!topic/drools-setup/fx67PiV5uMs
Document alternative workaround for "Loading..." hanging.
@csadilek Would you mind reviewing?

Document additional workaround for 'hanging' loading of Workbench

---

drools-docs/src/main/asciidoc/ComplexEventProcessing/TemporalReasoning-section.adoc
jbpm-docs/src/main/asciidoc/TaskService/TaskServiceAPIs-section.adoc
shared/Spring/KieSpring-chapter.adoc

Running `mvn clean install` in kie-docs emits the following asciidoctor warnings.
This PR fixes them
asciidoctor: WARNING: ComplexEventProcessing/TemporalReasoning-section.adoc: line 13: invalid style for paragraph: bibliography
asciidoctor: WARNING: dropping line containing reference to missing attribute: sourcedir
asciidoctor: WARNING: TaskService/TaskServiceAPIs-section.adoc: line 80: section title out of sequence: expected level 3, got level 4

Fix asciidoctor warnings

---

.gitignore
docs/shared/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc

- Made the images visible for "GUVNOR-2431: Redesign Copy, Save, Rename, Restore and Delete Popups"
- Added the OSX .DS_Store to .gitignore

Minor fixes

---

docs/drools-docs/topics/ReleaseNotes/ReleaseNotesDrools.6.5.0.Final-section.adoc
docs/drools-docs/topics/ReleaseNotes/ReleaseNotesDrools.7.0.0.Final-section.adoc

The table was not properly closed via |===.

Fix broken drools-docs rendering

---

docs/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.0.0.Final-section.adoc

Peer reviewed the last section of Release Notes 7.0.0: "Renaming and unification of configuration files".
Corrected minor language and structural changes.

Reviewed section-Renaming and unification of configuration files

---

docs/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.0.0.Final-section.adoc

Minor correction on [PR #255 ](https://github.com/kiegroup/kie-docs/pull/255): The possessive form ('s- apostrophe 's' ) is used with only nouns referring to people.

Correction in the usage of possessive form

---

docs/jbpm-docs/src/main/asciidoc/CoreEngine/Configuration-section.adoc
docs/jbpm-docs/src/main/asciidoc/CoreEngine/Services-section.adoc

-Addition of Quartz Timer Service section
-Note about removing jbpm.ut.jndi.lookup property for non-WAS deployments
@mswiderski @krisv @mdproctor

Addition of Quartz Timer Service section (in relation to recent issues seen in the field)

---

docs/shared-kie-docs/src/main/asciidoc/Android/Android-chapter.adoc

AsciiDoc attributes are used like `{this}`. So the result before the fix was `<version>$8.0.0-SNAPSHOT</version>` with the extra, unwanted dollar sign.

Remove redundant character in attribute reference

---

docs/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc

* As per: [XSD](https://github.com/kiegroup/jbpm/blob/master/jbpm-runtime-manager/src/main/resources/deployment-descriptor.xsd#L76)

Fix bad XML tag in deployment descriptor docs.

---

docs/drools-docs/src/main/asciidoc/index.adoc
docs/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.2.0.Final-section.adoc
docs/jbpm-docs/src/main/asciidoc/RuntimeManagement-chapter.adoc
docs/jbpm-docs/src/main/asciidoc/index.adoc
docs/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/AuthoringPlanningAssets/TerminationEditor-section.adoc
docs/optaplanner-wb-es-docs/src/main/asciidoc/Workbench/Quickstart/Quickstart-section.adoc
docs/optaplanner-wb-es-docs/src/main/asciidoc/index.adoc
docs/pom.xml
docs/shared-kie-docs/src/main/asciidoc/KieServer/OptaplannerRestAPI-section.adoc
docs/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc

* Fixed broken links between different books (typically optaplanner-wb-docs -> optaplanner-docs) which used the old `html_single` format that got lost after migration to AsciiDoc.
* Added KIE Server chapter to jbpm-docs book. Now that this chapter is in all books, it can be cross referenced instead using a URL link. Besides that it's relevant for jBPM users so I don't see a reason why it shouldn't be a part of jbpm-docs.
* Fixed a few inconsistencies between `drools-docs/index.adoc` and `jbpm-docs/index.adoc`.
* Fixed a few typos.

Fix links and typos

---

docs/product-user-guide/src/main/asciidoc/assets-creating-proc.adoc
docs/product-user-guide/src/main/asciidoc/assets-projects-gloss.adoc
docs/product-user-guide/src/main/asciidoc/assets-types-ref.adoc
docs/product-user-guide/src/main/asciidoc/business-central-con.adoc
docs/product-user-guide/src/main/asciidoc/chap-assets.adoc
docs/product-user-guide/src/main/asciidoc/chap-plug-in.adoc
docs/product-user-guide/src/main/asciidoc/chap-project.adoc

I've merged (with a separate PR) my BXMSDOC-1708 working branch changes with this one on my fork, and now this one is ready for upstream merging to the following **upstream** target branches:
- master
- 7.3.x
**This PR is for upstream master.** I've created a separate PR for upstream 7.3.x.
PLEASE NOTE: There was no SME or peer review for this because the required change is very small, and is something new that we're not doing and that no one else on the team can say one way or another. This is a very small implementation of a team-wide change coming soon. I have, however, carefully reviewed the rendered output at the two (only two) points where the IDs were being rendered previously, and they're not anymore. So all clear.
Corrected topic ID/links for the following topics, to allow topic …

BXMSDOC-1708-final (for upstream master): Corrected topic ID/links from BXMSDOC-1627 (part of User Guide modularization)

---

docs/product-user-guide/src/main/asciidoc/assets-creating-proc.adoc
docs/product-user-guide/src/main/asciidoc/assets-projects-gloss.adoc
docs/product-user-guide/src/main/asciidoc/assets-types-ref.adoc
docs/product-user-guide/src/main/asciidoc/business-central-con.adoc
docs/product-user-guide/src/main/asciidoc/chap-assets.adoc
docs/product-user-guide/src/main/asciidoc/chap-plug-in.adoc
docs/product-user-guide/src/main/asciidoc/chap-project.adoc

I've created this working branch based on upstream 7.3.x branch, and have cherry-picked the PR for BXMSDOC-1708-final (which was already merged upstream) into it. This branch is now ready for upstream merging to 7.3.x.
PLEASE NOTE: There was no SME or peer review for this because it is based on the already-approved changes merged upstream from BXMSDOC-1708-final (master).
Corrected topic ID/links for the following topics, to allow topic reuse (this will be a universally adopted change at some point soon):
- assets-creating-proc.adoc
- assets-projects-gloss.adoc
- assets-types-ref.adoc
- chap-assets.adoc
- chap-project.adoc
JIRA: https://issues.jboss.org/browse/BXMSDOC-1708
Rendered output (the topics IDs for "Assets" and "Projects" sections now are correctly hidden, instead of being …

BXMSDOC-1708-7.3.x-final (for upstream 7.3.x): Corrected topic ID/links from BXMSDOC-1627 (part of User Guide modularization)

---

docs/product-administration-and-configuration-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-development-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-getting-started-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-ibm-websphere-installation-and-configuration-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-installation-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-migration-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-user-guide/src/main/asciidoc/bpms/master-docinfo.xml
docs/product-user-guide/src/main/asciidoc/main.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

Porting BXMSDOC-1706 from gitlab to github. Jira approved by our current DPM - getting ready for Friday publish.
Also fixed bug with user guide not showing the writer adoc - hence deleted newline in `docs/product-user-guide/src/main/asciidoc/main.adoc`.
Feel free to merge.

BXMSDOC-1706 - master

---

docs/product-user-guide/src/main/asciidoc/chap-deploying-projects.adoc

@vidya-iyengar Corrected typo in the chap-deploying-projects.adoc file that was preventing the book from building correctly past Chapter 15. This was probably left behind from an old merge conflict.

Corrected typo in chap-deploying-projects.adoc

---

docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc

Ready to merge with upstream 7.3.x.
Cherry-picked single commit from BXMSDOC-1463-master (added single line of code and copied one sentence and code snippet from another section of the Dev Guide).
Lines affected are 1424-1443. I have no idea what those other diffs are. Similar behavior in GitLab when I just merged the PR for 6.4-preview. Just a handful of deletions/additions of the exact same content, as if copied and pasted in place. Weird. No actual change except mine, though.
JIRA: https://issues.jboss.org/browse/BXMSDOC-1463
Didn't bother with providing rendered output. Very small change, shown sufficiently in PR diffs.
The SME review/approval was given in the above JIRA itself, and the Peer Review (approved) is a sub-task, as usual.

BXMSDOC-1463 (for upstream 7.3.x): Add 'target' parameter to enable advanced queries in Intelligent Process Server 

---

docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc

Added single line of code and copied one sentence and code snippet from another section of the Dev Guide.
Lines affected are 1424-1443. I have no idea what those other diffs are. Similar behavior in GitLab when I just merged the PR for 6.4-preview. Just a handful of deletions/additions of the exact same content, as if copied and pasted in place. Weird. No actual change except mine, though.
JIRA: https://issues.jboss.org/browse/BXMSDOC-1463
Didn't bother with providing rendered output. Very small change, shown sufficiently in PR diffs.
The SME review/approval was given in the above JIRA itself, and the Peer Review (approved) is a sub-task, as usual.

BXMSDOC-1463 (for upstream master): Add 'target' parameter to enable advanced queries in Intelligent Process Server 

---

docs/product-development-guide/src/main/asciidoc/chap-install-and-setup-jboss-developer-studio.adoc
docs/product-development-guide/src/main/asciidoc/chap-remote-api.adoc

Added note #7 in "Example JMS Usage" code sample to explain how to adjust default session type for generic resource adapters.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1709)
- [Output](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1709/#example_jms_usage)

BXMSDOC-1709 (for upstream master): Updated JMS session property for generic resource adapters in Dev Guide

---

docs/product-development-guide/src/main/asciidoc/chap-install-and-setup-jboss-developer-studio.adoc
docs/product-development-guide/src/main/asciidoc/chap-remote-api.adoc

Ready to merge with upstream 7.3.x.
Cherry-picked changes from BXMSDOC-1709-master, which added note #7 in "Example JMS Usage" code sample to explain how to adjust default session type for generic resource adapters.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1709)
- [Output](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1709/#example_jms_usage)

BXMSDOC-1709 (for upstream 7.3.x): Updated JMS session property for generic resource adapters in Dev Guide

---

docs/product-user-guide/src/main/asciidoc/data-object-deployment-descriptor-proc.adoc
docs/product-user-guide/src/main/asciidoc/data-objects-create-proc.adoc
docs/product-user-guide/src/main/asciidoc/data-objects-persistable-modify-proc.adoc
docs/product-user-guide/src/main/asciidoc/data-objects-relationships-proc.adoc

Basically just changed "**Authoring** -> **Project Authoring**" to  "**Menu** -> **Projects**" at several points. Otherwise no impact.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1806)
- [Output for BRMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1806_BRMS/#assets_data_models_gloss_chap-data-models)
- [Output for BPMS](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1806_BPM/#assets_data_models_gloss_chap-data-models)
@vidya-iyengar, @gsheldon, @emmurphy1, and @michelehaglund:
I'm just saying this:
- "Go to **Menu** -> **Projects** . . ."
- "Got to **Menu** -> **Deployments** . . ."
- etc.
Not this:
- "Go to **Menu** -> **Design** -> **Projects** . . ."
- Got to **Menu** -> **DevOps** -> **Deployments** . . ."
- etc.
I'm not positive that …

BXMSDOC-1806 (for upstream master): Updated chap. Data Models in BRMS and BPMS User Guide per 7.0 LA ER3 new UI

---

docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc

In [BXMSDOC-1646](https://github.com/kiegroup/kie-docs/commit/d91763a00822e47ee56edc4512af77b62a4a54dd), the initial underscore was removed before all anchor names in chap-human-tasks-management. This is great and what we want to do going forward, but the corresponding cross-references were not likewise updated, resulting in broken links. Gemma is out and couldn't fix the cross-refs at the moment, and I don't have the time, so I instead just put back the initial underscores for now to fix the broken links.
Links:
- [BXMSDOC-1646](https://github.com/kiegroup/kie-docs/commit/d91763a00822e47ee56edc4512af77b62a4a54dd) (previous PR commit that introduced the issue)
- [JIRA for this fix](https://issues.jboss.org/browse/BXMSDOC-1830)

BXMSDOC-1830 (for upstream master): Fixed broken cross-refs in Dev Guided introduced in BXMSDOC-1646

---

docs/product-user-guide/src/main/asciidoc/chap-advanced-process-modeling.adoc

Cherry-picked from branch BXMSDOC-1807-master. No impact from new UI, from what I can see. I went ahead and made a couple of changes while I was there though. Very minimal.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1807)

BXMSDOC-1807 (for upstream 7.4.x): Minor updates to chap Advanced Process Modeling in BPMS User Guide for clearer instructions

---

docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc

Cherry-picked change from BXMSDOC-1830. In [BXMSDOC-1646](https://github.com/kiegroup/kie-docs/commit/d91763a00822e47ee56edc4512af77b62a4a54dd), the initial underscore was removed before all anchor names in chap-human-tasks-management. This is great and what we want to do going forward, but the corresponding cross-references were not likewise updated, resulting in broken links. Gemma is out and couldn't fix the cross-refs at the moment, and I don't have the time, so I instead just put back the initial underscores for now to fix the broken links.
Links:
- [BXMSDOC-1646](https://github.com/kiegroup/kie-docs/commit/d91763a00822e47ee56edc4512af77b62a4a54dd) (previous PR commit that introduced the issue)
- [JIRA for this …

BXMSDOC-1830 (for upstream 7.4.x): Fixed broken cross-refs in Dev Guided introduced in BXMSDOC-1646

---

docs/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSourceManagement/DataSourceManagement-section.adoc

- adds missing advanced settings documentation
(cherry picked from commit 90646b396cb12f5cf54ded6f3e87b14f04423255)

[7.4.x] DROOLS-1748: Drools workbench datasource on Wildfly domain

---

docs/product-installation-guide/src/main/asciidoc/eap-bxms-run-proc.adoc

[BXMSDOC-1800](https://issues.jboss.org/browse/BXMSDOC-1800)
[SME Review](https://issues.jboss.org/browse/BXMSDOC-1851)
[Peer Review](https://issues.jboss.org/browse/BXMSDOC-1854)

BXMSDOC-1800 When installing kie-execution-server only, the server won't start

---

code/pom.xml
pom.xml

Fixes build error from missing guvnor artifacts.

AF-593+: Move Guvnor modules to uberfire and kie-wb-common.

---

docs/product-development-guide/src/main/asciidoc/chap-intelligent-process-server.adoc

Cherry-picked from BXMSDOC-1816-master.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1816)
[Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1816/#managing_task_instance_data)

BXMSDOC-1816 (for upstream 7.4.x): Updated Development Guide with new kie-server REST PUT call for updating taskInstance object

---

docs/product-development-guide/src/main/asciidoc/chap-kie-api.adoc

The branch BXMSDOC-1348 was merged prematurely by gatekeeper before SME and peer reviews. This new branch, with suffix B, implements SME and peer feedback to the same change.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1348)
[Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1348/#sect_query_service) - Scroll to "21.3.6.5 Storing Query Definitions in a kJAR"

BXMSDOC-1348-B (for upstream master): Update section on Storing Query Definitions in a kJAR in Dev Guide

---

docs/product-development-guide/src/main/asciidoc/chap-kie-api.adoc

Cherry-picked changes from BXMSDOC-1348-B, which contained the changes from BXMSDOC-1348.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-1348)
[Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1348/#sect_query_service) - Scroll to "21.3.6.5 Storing Query Definitions in a kJAR"

BXMSDOC-1348 (for upstream 7.4.x): Update section on Storing Query Definitions in a kJAR in Dev Guide

---

docs/shared-kie-docs/src/main/asciidoc/Product/author-group.adoc

[Sample doc (User Guide)](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1968/)

BXMSDOC-1968 (for upstream master): Added Mikhail Ramendik to author-group.adoc.

---

docs/shared-kie-docs/src/main/asciidoc/Product/author-group.adoc

Ready for upstream 7.4.x.
[Sample doc (User Guide)](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1968/)

BXMSDOC-1968 (for upstream 7.4.x): Add Mikhail Ramendik to author-group.adoc.

---

docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-scheduler-service.adoc
docs/product-administration-and-configuration-guide/src/main/asciidoc/main.adoc

For upstream master.
This was part of a 6.4 JIRA that impacted 7.0. I know we've moved past 6.4 things for now, but the JIRA is half complete and was waiting SME approval, who said to apply this change to 7.0 as is. So need to do so to close the JIRA. Very small and isolated piece that's easy and worth it to carry forward.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1101)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1101/#chap_scheduler_service)

BXMSDOC-1101 (for upstream master): Added new Scheduler Service chapter to Admin and Config Guide

---

docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-scheduler-service.adoc
docs/product-administration-and-configuration-guide/src/main/asciidoc/main.adoc

For upstream 7.5.x.
This was part of a 6.4 JIRA that impacted 7.0. I know we've moved past 6.4 things for now, but the JIRA is half complete and was waiting SME approval, who said to apply this change to 7.0 as is. So need to do so to close the JIRA. Very small and isolated piece that's easy and worth it to carry forward.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1101)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1101/#chap_scheduler_service)

BXMSDOC-1101 (for upstream 7.5.x): Added new Scheduler Service chapter to Admin and Config Guide

---

docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-ba.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc

Minor. This change defines :CENTRAL: as Business Central when used in BA docs and Decision Central when used in DM docs. I wanted this in so others could begin using it throughout their deliverables.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-2038)

BXMSDOC-2038 (for upstream master): Added :CENTRAL: attribute to BA and DM attribute docs

---

docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-ba.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc

Ready to merge with upstream 7.5.x.
Minor. This change defines :CENTRAL: as Business Central when used in BA docs and Decision Central when used in DM docs. I wanted this in so others could begin using it throughout their deliverables.
[JIRA](https://issues.jboss.org/browse/BXMSDOC-2038)

BXMSDOC-2038 (for upstream 7.5.x): Added :CENTRAL: attribute to BA and DM attribute docs

---

docs/product-user-guide/src/main/asciidoc/assets-types-ref.adoc
docs/product-user-guide/src/main/asciidoc/business-central-con.adoc
docs/product-user-guide/src/main/asciidoc/chap-assets.adoc
docs/product-user-guide/src/main/asciidoc/chap-data-models.adoc
docs/product-user-guide/src/main/asciidoc/chap-deploying-projects.adoc
docs/product-user-guide/src/main/asciidoc/chap-project.adoc

This is a minor, under-the-hood clean-up effort to rectify the misuse of the :context: variable to date (by me) before others perpetuate it or get confused. Now that I've got the method down, tested, and documented in the contrib guide. See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2041) for details.

BXMSDOC-2041 (for upstream master): Corrected :context: variable in User Guide

---

docs/product-user-guide/src/main/asciidoc/assets-types-ref.adoc
docs/product-user-guide/src/main/asciidoc/business-central-con.adoc
docs/product-user-guide/src/main/asciidoc/chap-assets.adoc
docs/product-user-guide/src/main/asciidoc/chap-data-models.adoc
docs/product-user-guide/src/main/asciidoc/chap-deploying-projects.adoc
docs/product-user-guide/src/main/asciidoc/chap-project.adoc

Ready to merge with upstream 7.5.x.
This is a minor, under-the-hood clean-up effort to rectify the misuse of the :context: variable to date (by me) before others perpetuate it or get confused. Now that I've got the method down, tested, and documented in the contrib guide. See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2041) for details.

BXMSDOC-2041 (for upstream 7.5.x): Corrected :context: variable in User Guide

---

docs/product-development-guide/src/main/asciidoc/chap-human-tasks-management.adoc

This was a 6.4 update request that applies to 7.0 as well.
Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-1182)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1182/#process_instance_migration) (see note on "Process instance migration on the KIE Server")

BXMSDOC-1182 (for upstream 7.5.x): Added note on process instance migration on KIE server in Dev Guide

---

docs/product-business-resource-planner-guide/pom.xml

`org.optaplanner:optaplanner-docs` already exists in the `optaplanner` repository. The module doesn't seem to be built so it doesn't matter much but the change removes an apparent circular dependency between `optaplanner` and `kie-docs` repositories which will make the `repo-dep-tree.pl` script work correctly.

Avoid duplicate GAVs across repositories

---

docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc
docs/product-user-guide/src/main/asciidoc/decision-tables-upload-proc.adoc
docs/product-user-guide/src/main/asciidoc/drl-rules-maven-create-proc.adoc
docs/product-user-guide/src/main/asciidoc/rules-authoring-assets-ref.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-ba.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2169) for details.

BXMSDOC-2169 (for upstream master): Added doc attributes for new DM deliverable name and URL components.

---

docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc
docs/product-user-guide/src/main/asciidoc/decision-tables-upload-proc.adoc
docs/product-user-guide/src/main/asciidoc/drl-rules-maven-create-proc.adoc
docs/product-user-guide/src/main/asciidoc/rules-authoring-assets-ref.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-ba.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes-dm.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2169) for details.

BXMSDOC-2169 (for upstream 7.5.x): Added doc attributes for new DM deliverable name and URL components.

---

docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2210) for details.

BXMSDOC-2210 (for upstream master): Removed links to 'Testing a decision service' in all 'Designing' assemblies.

---

docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2210) for details.

BXMSDOC-2210 (for upstream 7.5.x): Removed links to 'Testing a decision service' in all 'Designing' assemblies.

---

docs/product-administration-and-configuration-guide/src/main/asciidoc/appe-properties.adoc
docs/product-installation-guide/src/main/asciidoc/install-standalone-properties-con.adoc
docs/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc

Removing system properties which no loger work from workbench installation docs.
I grepped through the whole kiegroup code base and removed those which are no longer present anywhere.
@ederign could you please check if it's ok to remove all properties related to clustering? I didn't find any occurrence of those in our code base.
@Rikkola I also removed some properties related to importing examples. I suspect that "org.kie.demo" is also useless now, but there are many occurrences throughout our code base, so leaving that in..

Remove no longer effective system properties

---

docs/product-assembly_decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_drl-rules/src/main/asciidoc/main.adoc
docs/product-assembly_guided-decision-tables/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rule-templates/src/main/asciidoc/main.adoc
docs/product-assembly_guided-rules/src/main/asciidoc/main.adoc
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

Ready for upstream 7.5.x. See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2267) for details.

BXMSDOC-2267 (for upstream 7.5.x): Uncommented cross-refs to test scenarios doc and updated test scenarios doc attribute and its URL attribute

---

docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

Links:
- [JIRA](https://issues.jboss.org/browse/BXMSDOC-2246) 
- [Contrib Guide](http://ccs-jenkins.gsslab.brq.redhat.com:8080/view/Topic%20branches/job/doc-Red_Hat_JBoss_BxMS_Contribution_Guide-branch-shared-repo/lastSuccessfulBuild/artifact/index.html#_publishing_ba_dm_guides_using_pantheon) steps taken.

BXMSDOC-2246 (for upstream 7.5.x): Update REBUILT variable and new doc attributes for Mar 2 2018 patch publish

---

dashbuilder-docs/src/main/docbook/en-US/master.xml
drools-docs/src/main/docbook/en-US/master.xml
jbpm-docs/src/main/docbook/en-US/master.xml

fixing issue with build error https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/6.5.x/job/kie-docs-6.5.x/107/consoleText
```
[ERROR] Failed to execute goal org.jboss.maven.plugins:maven-jdocbook-plugin:2.3.9:generate (default-generate) on project jbpm-docs: XSLT problem: error performing translation [null] : org.xml.sax.SAXParseException; systemId: http://docbook.org/xml/5.0/dtd/docbook.dtd; lineNumber: 1; columnNumber: 1; The markup declarations contained or pointed to by the document type declaration must be well-formed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.maven.plugins:maven-jdocbook-plugin:2.3.9:generate (default-generate) on project jbpm-docs: XSLT problem
```

[6.5.x] fixed URL to docbook DTD

---

docs/drools-docs/src/main/asciidoc/DroolsRunning-chapter.adoc

Change from:
`A rule flow group is a group of rules associated by the "ruleflow-group" rule attribute.
These rules can only fire when the group is activate.`
to:
`A rule flow group is a group of rules associated by the "ruleflow-group" rule attribute.
These rules can only fire when the group is activated.`

DroolsRunning-chapter.adoc: Change "activate" to "activated"

---

docs/product-user-guide/src/main/asciidoc/appe-service-tasks.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2366) for details.

BXMSDOC-2366 (for upstream master): Updated supported ContentType for REST Task in User Guide content, per 6.4 update.

---

docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc

BXMSDOC-2881 (for upstream 7.7.x): Updated rebuilt variable for PAM 7.0 docs publish.

---

docs/product-user-guide/src/main/asciidoc/chap-process-designer.adoc

Pending customer review and approval.
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2797) for details.

BXMSDOC-2797 (for upstream 7.7.x): Updated Enabling document attachments seciton in User Guide content, per 6.4 update from customer feedback.

---

docs/product-user-guide/src/main/asciidoc/chap-process-designer.adoc

Pending customer review and approval.
See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2797) for details.

BXMSDOC-2797 (for upstream master): Updated Enabling document attachments seciton in User Guide content, per 6.4 update from customer feedback.

---

docs/product-assembly_openshift-authoring/src/main/asciidoc/main.adoc
docs/product-assembly_openshift-immutable/src/main/asciidoc/main.adoc
docs/product-assembly_openshift-managed/src/main/asciidoc/main.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-ha-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-ha-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-single-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-single-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-immutable-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-immutable-server-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-managed-deploy-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-managed-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/externaldb-build-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/externaldb-params.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2826) for details.

BXMSDOC-2826 (for upstream 7.7.x): New external db section in Deploying OpenShift docs, for Misha

---

docs/product-assembly_openshift-authoring/src/main/asciidoc/main.adoc
docs/product-assembly_openshift-immutable/src/main/asciidoc/main.adoc
docs/product-assembly_openshift-managed/src/main/asciidoc/main.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-ha-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-ha-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-single-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-authoring-single-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-immutable-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-immutable-server-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-managed-deploy-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/environment-managed-modify-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/externaldb-build-proc.adoc
docs/product-assembly_pam-on-openshift/src/main/asciidoc/externaldb-params.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2826) for details.

BXMSDOC-2826 (for upstream master): New external db section in Deploying OpenShift docs, for Misha

---

docs/product-administration-and-configuration-guide/src/main/asciidoc/access-control-con.adoc
docs/product-administration-and-configuration-guide/src/main/asciidoc/chap-business-central-configuration.adoc

`no_build` and `no_search` parameters no longer available in business-central.
https://issues.jboss.org/browse/AF-703

Remove unsupported business central parameters

---

docs/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
docs/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.9.0.Final-section.adoc

Fix 7.9.0 Release notes of Drools
@mariofusco @kkufova

[DROOLS-2805] Release notes for 7.9.0 Final are not linked correctly

---

doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/Services-section.adoc

Since RHPAM-400 and RHPAM-1122,
- Changing active timers is possible as they are rescheduled
- Active recurring timers can be migrated
So remaining restriction is "Remove" only

Minor fix about timer migration restriction

---

doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSourceManagement/DataSourceManagement-section.adoc

Part of an ensemble:
* https://github.com/kiegroup/kie-docs/pull/1056
* https://github.com/kiegroup/kie-wb-common/pull/2102
Cherry-picked from https://github.com/kiegroup/kie-docs/pull/1055

[7.11.x] AF-1549: jdbc drivers should not be download by default

---

assemblies/assembly_managing-assets/main.adoc
assemblies/assembly_managing-projects/main.adoc

No Jira for this fix
Minor change to two main.adoc files. Changed role from `process-admin` to `developer` in both the Managing assets and Managing projects docs.

Upstream PR to master from BXMSDOC-minorFix-master Changing instance of  `process-admin` to `developer`

---

assemblies/assembly_managing-assets/main.adoc
assemblies/assembly_managing-projects/main.adoc

No Jira for this fix
Minor change to two main.adoc files. Changed role from process-admin to developer in both the Managing assets and Managing projects docs.

Upstream PR to 7.11.x from BXMSDOC-minorFix-7.11.x Changing instance of `process-admin` to `developer

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/XLSDecisionTable-section.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/decision-tables-con.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-decision-tables-ref.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Activities-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Events-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Process-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Process-section.html
doc-content/jbpm-docs/src/main/asciidoc/DomainSpecificProcesses/Overview-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Spring/KieSpring-chapter.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-3345) for details.

BXMSDOC-3345-master: Fixed broken links in community docs.

---

doc-content/enterprise-only/admin-and-config/managing-business-central-githook-notifications-internationalize-con.adoc

Adding a note to regarding encodings
@ederign @gadeyredhat could you please take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2358
https://github.com/kiegroup/jbpm-wb/pull/1263
https://github.com/kiegroup/kie-docs/pull/1320

[7.14.x] JBPM-7997: garbled message in start process form when OS locale is Japanese

---

doc-content/enterprise-only/installation/install-standalone-properties-con.adoc
doc-content/enterprise-only/installation/run-standalone-properties-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/Installation-section.adoc

Description oforg.uberfire.nio.git.ssh.cyphers and 
org.uberfire.nio.git.ssh.macs
@porcelli @domhanak

[AF-1775] SSH Ciphers and MAC configured via args on startup 

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-commands-samples-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-server-containers.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-1531) for details.

BXMSDOC-1531-master: Added note in APIs doc about not using KIE Scanner with processes.

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-commands-samples-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-server-containers.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-1531) for details.

BXMSDOC-1531-7.14.x: Added note in APIs doc about not using KIE Scanner with processes.

---

_artifacts/document-attributes-dm.adoc
_artifacts/document-attributes-drools.adoc
_artifacts/document-attributes-jbpm.adoc
_artifacts/document-attributes-op.adoc
_artifacts/document-attributes-pam.adoc
_artifacts/document-attributes.adoc

For RHDM, deliverables continue to be called decision-central, decisioncentral, etc., despite global change. So updating the previous global edit to doc variables in order to restore this.

BXMSDOC-3875-master: Update doc attributes with correct DM-specific Central variables for file names and URL components.

---

_artifacts/document-attributes-dm.adoc
_artifacts/document-attributes-drools.adoc
_artifacts/document-attributes-jbpm.adoc
_artifacts/document-attributes-op.adoc
_artifacts/document-attributes-pam.adoc
_artifacts/document-attributes.adoc

For RHDM, deliverables continue to be called decision-central, decisioncentral, etc., despite global change. So updating the previous global edit to doc variables in order to restore this.

BXMSDOC-3875-7.18.x: Update doc attributes with correct DM-specific Central variables for file names and URL components.

---

_artifacts/document-attributes.adoc
assemblies/assembly_case-management-getting-started/main.adoc
assemblies/assembly_decision-manager/main.adoc
assemblies/assembly_decision-services-using-guided-rules/main.adoc
assemblies/assembly_designing-and-building-cases/main.adoc
assemblies/assembly_executing-processes/main.adoc
assemblies/assembly_managing-and-monitoring-business-processes/main.adoc
assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
assemblies/assembly_showcase-application/main.adoc

* Correct EAP URL versions from 7.3 to 7.2
* Change link titles to attributes
* Update REBUILD variable to Wednesday, March 27, 2019

Correct EAP URL versions from 7.3 to 7.2, change link titles to attributes, and update REBUILD variable

---

doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc

<distributable> tag should not be uncommented. We don't use the eap clustering.

Remove step with uncommenting of <distributable> tag

---

doc-content/enterprise-only/installation/clustering-download-eap-bc-proc.adoc

<distributable> tag should not be uncommented. We don't use the eap clustering.

[7.18.x] Remove step with uncommenting of <distributable> tag

---

doc-content/enterprise-only/installation/run-standalone-properties-con.adoc

BXMSDOC-2274 added Ddesignerdataobjects=false

Bxmsdoc 2274 7.18 Tomcat installation misses 'datadesignerobject' setting

---

doc-content/enterprise-only/project-data/project-kmodule-configure-proc.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-2907) for details.

BXMSDOC-2907-master: Add content about KIE repo cache settings in packaging doc.

---

doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-kie-server-proc.adoc

@lanceleverich, @jiripetrlik, can you please verify this small update to the PMML doc for 7.4? Per [RHDM-867](https://issues.jboss.org/browse/RHDM-867). This is the only required change for this doc, from our previous conversations.
Links:
* [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-3961_PAM/#pmml-invocation-kie-server-proc_pmml-models)
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-3960)

BXMSDOC-3961-master: Add note about XStream issue on Java 11 for PMML.

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-swagger-proc.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4192) for details.

BXMSDOC-4192-master: Add note about API calls for process instances in KIE APIs doc.

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-swagger-proc.adoc

See [JIRA](https://issues.jboss.org/browse/BXMSDOC-4192) for details.

BXMSDOC-4192-7.18.x: Add note about API calls for process instances in KIE APIs doc.

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.0.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.1.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.2.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.3.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.4.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.6.5.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.0.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.1.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.11.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.12.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.13.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.14.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.15.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.17.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.18.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.24.0.Final/ReleaseNotesDrools.7.24.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.7.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.9.0.Final-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.24.0.Final/Release.7.24.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.16.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.17.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.18.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.19.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.23.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ReleaseNotes/ReleaseNotesWorkbench.7.24.0.Final/ReleaseNotesWorkbench.7.24.0.Final-section.adoc

@jomarko, @tarilabs, @cristianonicolai, @nmirasch @pefernan, you guys seem to be the top contributors to the community release notes, so would you mind briefly reviewing this PR for anything of question or concern? This is the change to the community RN file structure starting with 7.24 to accommodate single sourcing with enterprise (plus a few other needed tweaks), which I announced at length to you all, team leads, and BSIG in a few emails. 
For a detailed description/illustration of this change and the reasons for it, search your email for the BSIG message with subject line "Single sourcing community and enterprise release notes beginning 7.24 / 7.5 release".
Summary of what I changed:
* For Drools, jBPM, and Workbench, I added a release-specific folder within which the same-as-always …

BXMSDOC-4237-master: Updated community RN structure to accommodate single sourcing with enterprise.

---

assemblies/assembly_decision-manager/dm/master-docinfo.xml
assemblies/assembly_decision-manager/main.adoc
assemblies/assembly_decision-manager/pam/master-docinfo.xml
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-new-project-creating-proc.adoc
doc-content/drools-docs/src/main/asciidoc/Examples/decision-examples-central-con.adoc

@etirelli, @csherrar, can you review and approve this PR for the traffic violation sample update to the decision service getting started guide? I added the violation project to the list of sample projects in BC and I updated the doc preface to mention that users can either follow the steps in the doc to create the project and assets or just open and review the sample project. I'm leaving it to Clifton, when he updates the doc overall, to decide whether to align the naming of the project in the steps to be exactly as the sample project, or to keep them slightly different on purpose to distinguish them.
Links:
* [Doc preview for PAM](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4252_PAM/)
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-4252)

BXMSDOC-4252-master: Update decision service gsg with violation sample project info.

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-rest-api-endpoints-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-rest-api-requests-swagger-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-endpoints-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-swagger-proc.adoc

@sutaakar, @cristianonicolai, @csherrar, can you please verify this update to the KIE APIs doc? I added the notes about Swagger system properties for KIE Server and Controller, per Karel's suggestion.
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-1936)
* [Doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-1936/#kie-server-rest-api-requests-swagger-proc_kie-apis)

BXMSDOC-1936-master: Add note on Swagger systerm property to KIE APIs doc.

---

doc-content/drools-docs/pom.xml
doc-content/jbpm-docs/pom.xml
doc-content/optaplanner-wb-es-docs/pom.xml

enabled the maven-jar-plugin again because the disabling of it causes much more problems then the problem:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project appformer-js: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
This error has to solved ASAP.

revoked the disabling of maven-jar-plugin

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/BuildDeployUtilizeAndRun/executable-model-con.adoc

Added paragraph on number of query arguments

 [DROOLS-4292] executable-model fails with more than 5 arguments query

---

doc-content/enterprise-only/installation/jms-queues-ref.adoc
doc-content/enterprise-only/weblogic/wls-jms-queues-create-proc.adoc

[RHPAM-7.3-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.3-JNDI-JMS-Names-PAM/#wls-jms-queues-create-proc)
[RHDM-7.3-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.3-JNDI-JMS-Names-DM/#wls-jms-queues-create-proc)

Upstream 7.18.x PR for BXMSDOC-3437: Corrected JMS JNDI queue names in WLS installation doc  

---

doc-content/enterprise-only/installation/jms-queues-ref.adoc
doc-content/enterprise-only/weblogic/wls-jms-queues-create-proc.adoc

[RHPAM-7.2-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.2-JNDI-JMS-Names-PAM/#wls-jms-queues-create-proc)
[RHDM-7.2-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.2-JNDI-JMS-Names-DM/#wls-jms-queues-create-proc)

Upstream 7.14.x PR for BXMSDOC-3437: Corrected JMS JNDI queue names in WLS installation doc 

---

doc-content/enterprise-only/installation/jms-queues-ref.adoc
doc-content/enterprise-only/weblogic/wls-jms-queues-create-proc.adoc

[RHPAM-7.1-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.1-JNDI-JMS-Names-PAM/#wls-jms-queues-create-proc)
[RHDM-7.1-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.1-JNDI-JMS-Names-DM/#wls-jms-queues-create-proc)

Upstream 7.11.x PR for BXMSDOC-3437: Corrected JMS JNDI queue names in WLS installation doc 

---

docs/product-installation-guide/src/main/asciidoc/jms-queues-ref.adoc
docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/kie-server-wls-environment-set-proc.adoc
docs/product-oracle-weblogic-installation-and-configuration-guide/src/main/asciidoc/wls-jms-queues-create-proc.adoc

[RHPAM-7.0-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.0-JNDI-JMS-Names-PAM/#wls-jms-queues-create-proc)
[RHDM-7.0-WLS Installation doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-3437-7.0-JNDI-JMS-Names-DM/#wls-jms-queues-create-proc)

Upstream 7.7.x PR for BXMSDOC-3437: Corrected JMS JNDI queue names in WLS installation doc 

---

assemblies/assembly_interacting-with-processes/main.adoc

[Epic](https://issues.jboss.org/browse/BXMSDOC-3982)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4496)
[Interacting with process and task RHPAM 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4496-RHPAM-RemovedChapter9/)
As per the Ivo Bek's feedback, **Chapter 9. Migrating business processes from new to legacy process designer** is outdated. So, I have removed the content from the Interacting with processes and tasks 7.4 document.

Upstream master PR for BXMSDOC-4496: Removed the outdated content from the interacting with processes and tasks document.

---

assemblies/assembly_interacting-with-processes/main.adoc

[Epic](https://issues.jboss.org/browse/BXMSDOC-3982)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4496)
[Interacting with process and task RHPAM 7.4 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4496-RHPAM-RemovedChapter9/)
As per the Ivo Bek's feedback, **Chapter 9. Migrating business processes from new to legacy process designer** is outdated. So, I have removed the content from the Interacting with processes and tasks 7.4 document.

Upstream 7.23.x PR for BXMSDOC-4496: Removed the outdated content from the interacting with processes and tasks document.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/enumerations-define-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-columns-create-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-create-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-hit-policies-examples-ref.adoc

@evacchi, I've gone through the guided decision tables doc per our discussion to make it clearer that the examples given are merely examples, and honestly, I only found a few areas where I clarified. The rest are all pretty clearly indicated as examples to me, and all use the same loan app example from BC. The only deviation is the hit policies section, which uses the different example that more clearly displays hit policy behavior. And there too I've tried to make it clearer that it's just an example.
I'm not sure what more can really be done, that's still within reason based on other priorities. Please let me know if you see clear and straightforward ways to improve this per your JIRA thoughts and our previous conversation.
Links:
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-4258)
* …

BXMSDOC-4258: Tweaks to GDT content examples.

---

doc-content/enterprise-only/release-notes/rn-known-issues-ref.adoc

Details in jira
[BXMSDOC-4540](https://issues.jboss.org/browse/BXMSDOC-4540)

BXMSDOC-4540 7.23.x RN 7.4.1 Known Issues Guided Rules exposes parenthesis outside of expression

---

assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/KieServer-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/prometheus-monitoring-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/prometheus-monitoring-custom-proc.adoc

@vblagoje @sutaakar , can you SME and QE review this? Valdimir said they merged it for 7.25 / 7.5 last minute and ideally would like for the new doc section to be included with the cutoff. Links below. **Please see also my questions below.**
@mramendi, can you also have a glance from the OCP perspective at the same time? So that anything you voice can be in the live conversation during SME/QE review.
Links:
* [DM doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4559_DM/#prometheus-monitoring-custom-proc_execution-server)
* [PAM doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4559_PAM/#prometheus-monitoring-custom-proc_execution-server) - Same, but for PAM
* [Drools doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4559_DROOLS/#prometheus-monitoring-custom-proc_ki …

BXMSDOC-4559-master: Add section on custom Prometheus metrics.

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Details in [JIRA](https://issues.jboss.org/browse/BXMSDOC-4650).
@tarilabs, does this doc update answer that customer's [stack overflow question](https://stackoverflow.com/questions/57627740/how-to-invoke-decision-service-as-a-stateless-session-in-kie-redhat-decision-ma) about KIE session ID, and is it good with you? I know you suggested in your email to link to the managing projects doc, but I decided to just tell them what they need to know in a note instead. Reason is that even with the link, it's still a bit buried, as you noticed (would need to link very specifically to KIE sessions and then expand that bullet). Plus we try to reduce doc links where we can and just give customers the info they need where they need it as much as possible.
Let me know what you think.

BXMSDOC-4650-master: Add note about KIE session ID in KIE APIs doc.

---

_artifacts/document-attributes.adoc
assemblies/assembly_installing-dsps-on-was/main.adoc
doc-content/enterprise-only/installation/securing-passwords-was-proc.adoc
doc-content/enterprise-only/websphere/kie-server-was-environment-set-proc.adoc
doc-content/enterprise-only/websphere/was-data-source-create-proc.adoc
doc-content/enterprise-only/websphere/was-jms-activation-proc.adoc
doc-content/enterprise-only/websphere/was-jms-queues-create-proc.adoc

[Epic](https://issues.jboss.org/browse/BXMSDOC-4451)
[JIRA](https://issues.jboss.org/browse/BXMSDOC-4623)
[Installing and configuring process server on WAS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4451-WAS-PAM-FP/#was-configure-embedded-engine-proc)
[Installing and configuring process server on WAS](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4451-WAS-DM-FP/#was-configure-embedded-engine-proc)

Upstream 7.26.x PR for BXMSDOC-4451: Update installing and configuring process/decision server on WAS doc per changes in 7.5

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

See: https://en.wikipedia.org/wiki/Node.js
And:
> ".NET" redirects here.
https://en.wikipedia.org/wiki/.NET_Framework

Fix spelling of `Node.js` (platform) and `.NET` (framework)

---

_artifacts/document-attributes.adoc
assemblies/assembly_kie-apis/main.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/KieServer-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/ejb-api-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/ejb-api-services-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/ejb-api-war-proc.adoc

@mswiderski @MarianMacik, can you SME/QE verify this new chapter on the EJB API for 7.x? It comes from the 6.4 Dev Guide, but with updates, tweaks, and cleanup. Doc previews below.
**IMPORTANT**: I will cherry-pick this as is to 7.1+. Let me know if you see any issues with that.
Links:
* [JIRA](https://issues.jboss.org/browse/BXMSDOC-4721)
* [PAM doc preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4721_PAM/#ejb-api-con_kie-apis)
* [jBPM doc  preview](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4721_JBPM/#ejb-api-con_kie-apis) - Same, but with community conditions
@cristianonicolai You're welcome to have a look as well.

BXMSDOC-4721-master: Add EJB API section to APIs content.

---

assemblies/assembly_configuring-central/main.adoc
assemblies/assembly_decision-engine/main.adoc
assemblies/assembly_drl-rules/main.adoc
assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-validation-disable-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/performance-tuning-drl-ref.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc
doc-content/drools-docs/src/main/asciidoc/LanguageReference-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/LanguageReference/drl-rules-WHEN-con.adoc
doc-content/drools-docs/src/main/asciidoc/LanguageReference/drl-rules-WHEN-elements-ref.adoc
doc-content/enterprise-only/admin-and-config/configuring-environment-mode-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/KieServer-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/performance-tuning-kie-server-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Workbench-chapter.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/performance-tuning-business-central-ref.adoc

Starting 7.6, we have been asked to add performance tuning sections to relevant stories, according to [BAPL-1467](https://issues.jboss.org/browse/BAPL-1467) as outlined in the [Performance tuning content google doc](https://docs.google.com/document/d/1Y0IrlbBTnTG2la3HZl6hwjyPjxEWIfQEPRjl5q3Ppzc/edit?usp=sharing). These sections merely highlight what is typically already documented in context. **This is just a start to this effort and is for 7.6.** The sections will be expanded and changed over coming releases.
To be QE verified:
@baldimir , can you QE verify the following sections:
* [Performance tuning considerations with the decision engine](http://file.rdu.redhat.com/~sterobin/BXMSDOC-4963_ENG/#performance-tuning-decision-engine-ref_decision-engine)
* [Performance tuning considerations …

BXMSDOC-4963-master: Add performance tuning sections to relevant stories

---

doc-content/enterprise-only/admin-and-config/manage-tasks-con.adoc

- [Managing & monitoring business processes in RHPAM 7.3 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-7.3-preview/#manage-tasks-con-managing-and-monitoring-processes)

Upstream 7.18.x PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

---

doc-content/enterprise-only/admin-and-config/manage-tasks-proc.adoc

- [Managing & monitoring business processes in RHPAM 7.2 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-7.2-preview/#manage-tasks-proc-managing-and-monitoring-processes)
Please check and verify the small paragraph I have added in **5.5. Managing tasks** section.

Upstream 7.14.x PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

---

docs/product-user-guide/src/main/asciidoc/manage-tasks-proc.adoc

- [Managing & monitoring business processes in RHPAM 7.0 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-7.0-preview/#manage-tasks-proc-managing-and-monitoring-processes)
Please check and verify the small paragraph I have added in **5.5. Managing tasks** section.

Upstream 7.7.x PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

---

doc-content/enterprise-only/admin-and-config/manage-tasks-proc.adoc

- [Managing & monitoring business processes in RHPAM 7.1 doc preview](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4380-MMBP-7.1-preview/#manage-tasks-proc-managing-and-monitoring-processes)
Please check and verify the small paragraph I have added in **5.5. Managing tasks** section.

Upstream 7.11.x PR for BXMSDOC-4380: user with process-admin role can't see task in Tasks page

---

docs/product-assembly_migrating-from-BRMS-6.4-to-DM-7.0/src/main/asciidoc/main.adoc

BXMSDOC-3863 7.5.x Clarification regarding .niogit folder in RHDM when following migration document from BRMS 6.4

---

doc-content/drools-docs/src/main/asciidoc/Examples/decision-examples-central-proc.adoc
doc-content/enterprise-only/getting-started/deploying-application-proc.adoc
doc-content/enterprise-only/processes/deploy-proc.adoc
doc-content/enterprise-only/project-data/build-deploy-branches-proc.adoc
doc-content/enterprise-only/project-data/project-build-deploy-central-proc.adoc
doc-content/enterprise-only/project-data/revise-project-version-proc.adoc
doc-content/enterprise-only/springboot/bus-app-import_proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/deploy-business-process-proc.adoc

@ederign  (SME) and @barboras7 (QE) , can you verify this minor doc update from [BAPL-893](https://issues.jboss.org/browse/BAPL-893) (deployment verification link)? I basically added the following mention in several related docs:
>To review project deployment details, click **View deployment details** in the deployment banner at the top of the screen or in the **Deploy** drop-down menu. This option directs you to the **Menu** -> **Deploy** -> **Execution Servers** page.
It touches several documents, but this is specifically to resolve the "Packaging and deploying a project" doc for 7.6, linked below. I confirmed with all squad members for this doc that this was the only relevant 7.6 change for the doc.
Links:
* [Doc epic](https://issues.jboss.org/browse/BXMSDOC-4795)
* …

BXMSDOC-4971-master: Update build and deploy steps with mention of verification link.

---

docs/product-user-guide/src/main/asciidoc/kie-server-configure-central-proc.adoc

- [v7.0-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHPAM-7.0-preview/#kie-server-configure-central-proc_execution-server)
Please check the **Chapter. 8** in the RHPAM doc preview.

Upstream 7.7.x (RHPAM) PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.1-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHPAM-7.1-preview/#kie-server-configure-central-proc_execution-server)
- [v7.1-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHDM-7.1-preview/#kie-server-configure-central-proc_execution-server)

Upstream 7.11.x PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.2-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHPAM-7.2-preview/#kie-server-configure-central-proc_execution-server)
- [v7.2-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHDM-7.2-preview/#kie-server-configure-central-proc_execution-server)

Upstream 7.14.x PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.3-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHPAM-7.3-preview/#kie-server-configure-central-proc_execution-server)
- [v7.3-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHDM-7.3-preview/#kie-server-configure-central-proc_execution-server)

Upstream 7.18.x PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.4-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHPAM-7.4-preview/#kie-server-configure-central-proc_execution-server)
- [v7.4-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHDM-7.4-preview/#kie-server-configure-central-proc_execution-server)

Upstream 7.23.x PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.5-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHPAM-7.5-preview/#kie-server-configure-central-proc_execution-server)
- [v7.5-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-DDF-RHDM-7.5-preview/#kie-server-configure-central-proc_execution-server)

Upstream 7.26.x PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.6-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-MMPS-RHPAM-DDF/#kie-server-configure-central-proc_execution-server)
- [v7.6-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-MMPS-RHDM-DDF/#kie-server-configure-central-proc_execution-server)

Upstream 7.30.x PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/kie-server-configure-central-proc.adoc

- [v7.6-Managing and monitoring Process Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-MMPS-RHPAM-DDF/#kie-server-configure-central-proc_execution-server)
- [v7.6-Managing and monitoring Decision Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-4985-MMPS-RHDM-DDF/#kie-server-configure-central-proc_execution-server)

Upstream master PR for BXMSDOC-4985: [DDF] kie server controller parameter is incorrect.

---

doc-content/enterprise-only/admin-and-config/managing-business-central-integrating-remote-git-repositories-proc.adoc
doc-content/enterprise-only/openshift/apb-deploy-proc.adoc
doc-content/enterprise-only/openshift/environment-immutable-monitoring-proc.adoc
doc-content/enterprise-only/openshift/environment-immutable-server-kjar-proc.adoc
doc-content/enterprise-only/openshift/environment-immutable-server-proc.adoc
doc-content/enterprise-only/openshift/environment-managed-deploy-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-centralmavenpwd-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-connectcentral-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-mandatory-proc.adoc
doc-content/enterprise-only/openshift/template-deploy-optionalmaven-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithCases-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithHanldersAndListeners-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithJPA-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/AppWithProcesses-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/ElasticSearchBusinessApp-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/BusinessApplications/Tutorials/JMSBusinessApp-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Designer/Customization-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/Installer/10MinWorkbench-section.adoc
doc-content/jbpm-docs/src/main/asciidoc/ReleaseNotes/Release.7.10.0.Final-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/Install-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/General/Introduction-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/SecurityManagement/SecurityManagement-section.adoc

Hello people,
This pull request is an attempt to correct the invalid usages of the word `username` so that the documentation conforms with the style guide in this matter (as mentioned [here](https://github.com/kiegroup/kie-docs/pull/2075#pullrequestreview-325333622) by @sterobin).
Please note that I have intentionally not touched `rhpam7*.adoc` and `rhdm7*.adoc` files per [this comment](https://github.com/kiegroup/kie-docs/pull/2075#issuecomment-561268085).
Please let me know if I have made any mistake.
Thanks,
Jafer

Corrected usages of the word 'username' across all files

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-background-rule-based-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc

**7.6 doc previews:** 
- [RHPAM 7.6: Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-TS-RHPAM/)
- [RHDM 7.6: Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-TS-RHDM/)
- [RHPAM 7.6: Managing and monitoring process server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-MMPS-RHPAM/)
- [RHDM 7.6: Managing and monitoring decision server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Changes-MMPS-RHDM/)
**Community doc previews:**
- [Drools document for kie server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-Drools-Changes/#kie-server-system-properties-ref_kie-apis)
- [jBPM document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5141-jBPM-Changes/#kie-server-s …

Upstream 7.30.x PR: Resolved some typos, outdated content from the kie server and test scenario documents

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-creating-custom-datatypes-proc.adoc

@sterobin I believe throughout the tutorial/doc they are referred with the `t` prefix

Fix typo for DMN custom data type name

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-properties-ref.adoc

backport to `7.30.x` for Product-7.7 of #2194
(the DMN feature is available since `7.27.0.Final` community)

BXMSDOC-5425 Document DMN runtime listener prop

---

doc-content/pom.xml

https://issues.redhat.com/browse/PLANNER-1839
- kiegroup/droolsjbpm-build-bootstrap/pull/1192
- kiegroup/kie-docs/pull/2200 (optional)
- kiegroup/optaplanner/pull/696
- kiegroup/optaweb-employee-rostering/pull/395
- kiegroup/optaweb-vehicle-routing/pull/268
@sterobin This PR is **optional**. I noticed slight changes in the HTML output after the upgrade, for example:
- darker background of some code blocks, improving their visibility,
- change in ruby code syntax highlighting.
Nothing serious. But please review carefully before merging. Feel free to reject if you don't want to have the maven plugin ant its dependencies' versions managed by `kie-parent`. Notice that after accepting this change it will still be easy to override the dependencies' version by setting:
```xml
<properties> …
```

PLANNER-1839: Have Asciidoctor managed by kie-parent

---

doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc

I have added the changes in the **clustering-headless-controller-proc.adoc** file to resolve the cross-reference issue in the managing and monitoring KIE Server doc. 
Following assemblies are affected: 
- assembly_clustering-eap
- assembly_managing-and-monitoring-execution-server

Upstream 7.30.x PR for BXMSDOC-5201: Corrected the NFS server cross reference issue.

---

doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc

I have added the changes in the **clustering-headless-controller-proc.adoc** file to resolve the cross-reference issue in the managing and monitoring KIE Server doc. 
Following assemblies are affected: 
- assembly_clustering-eap
- assembly_managing-and-monitoring-execution-server
Following docs are affected: 
- [RHPAM 7.7 Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5201-RHPAM-MM-KIE-Server/)
- [RHDM 7.7 Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5201-RHDM-MM-KIE-Server/)
- [RHPAM 7.7 Installing and configuring Red Hat Process Manager in a Red Hat JBoss EAP clustered environment](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5201-RHPAM-clustering-eap/)
- [RHDM 7.7 Installing and configuring Red Hat Decision Manager …

Upstream 7.33.x PR for BXMSDOC-5201: Corrected the NFS server cross reference issue.

---

doc-content/enterprise-only/installation/clustering-headless-controller-proc.adoc

I have added the changes in the **clustering-headless-controller-proc.adoc** file to resolve the cross-reference issue in the managing and monitoring KIE Server doc. 
Following assemblies are affected: 
- assembly_clustering-eap
- assembly_managing-and-monitoring-execution-server
Following docs are affected: 
- [RHPAM 7.7 Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5201-RHPAM-MM-KIE-Server/)
- [RHDM 7.7 Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5201-RHDM-MM-KIE-Server/)
- [RHPAM 7.7 Installing and configuring Red Hat Process Manager in a Red Hat JBoss EAP clustered environment](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5201-RHPAM-clustering-eap/)
- [RHDM 7.7 Installing and configuring Red Hat Decision Manager …

Upstream master PR for BXMSDOC-5201: Corrected the NFS server cross reference issue.

---

doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc

**JIRAs:** 
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5200)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5458)
**7.7 doc previews**
- [RHPAM 7.7 Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5458-RHPAM-SSO/#sso-client-adapter-proc)
- [RHDM 7.7 Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5458-RHDM-SSO/#sso-client-adapter-proc)
Please check **step 9** from section 4.2. Installing the RH-SSO client adapter for Business Central.

Upstream 7.33.x PR for BXMSDOC-5458: Update the RH-SSO doc per changes in RHDM/RHPAM 7.7

---

assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
doc-content/enterprise-only/admin-and-config/deployment-descriptors-con.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5201)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5240)
- [7.7 RHPAM Managing and Monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5240-RHPAM-MMES/#migration-configure-kie-server-proc)
- [7.7 RHDM Managing and Monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5240-RHDM-MMES/#migration-configure-kie-server-proc)
**Following changes are incorporated in the doc:**
- Properties *org.kie.server.persistence.dialect* and *org.kie.server.persistence.ds* they are only present in RHPAM and removed from RHDM.
- This chapter *Configuring Smart Router for TLS support* is only present in RHPAM doc as Smart Router is applicable to RHPAM only.
- Business central doesn't …

Upstream master PR for BXMSDOC-5240: Updated the Managing & monitoring KIE Server doc as per RHPAM/RHDM 7.7

---

assemblies/assembly_managing-and-monitoring-execution-server/main.adoc
doc-content/enterprise-only/admin-and-config/deployment-descriptors-con.adoc
doc-content/enterprise-only/installation/patches-applying-proc.adoc
doc-content/enterprise-only/migration/migration-configure-kie-server-proc.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-5201)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5240)
- [7.7 RHPAM Managing and Monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5240-RHPAM-MMES/#migration-configure-kie-server-proc)
- [7.7 RHDM Managing and Monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5240-RHDM-MMES/#migration-configure-kie-server-proc)
**Following changes are incorporated in the doc:**
- Properties *org.kie.server.persistence.dialect* and *org.kie.server.persistence.ds* they are only present in RHPAM and removed from RHDM.
- This chapter *Configuring Smart Router for TLS support* is only present in RHPAM doc as Smart Router is applicable to RHPAM only.
- Business central doesn't …

Upstream 7.33.x PR for BXMSDOC-5240: Updated the Managing & monitoring KIE Server doc as per RHPAM/RHDM 7.7

---

doc-content/enterprise-only/integration/codeready-studio-installing-runtime-environments-proc.adoc

[Integrating Red Hat CodeReady Studio with Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHPAM/#codeready-studio-installing-runtime-environments-proc)
[Integrating Red Hat CodeReady Studio with Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHDM/#codeready-studio-installing-runtime-environments-proc)

Upstream 7.33.x PR for BXMSDOC-5517: Replaced decision engine with process engine for PAM doc

---

doc-content/enterprise-only/integration/codeready-studio-installing-runtime-environments-proc.adoc

[Integrating Red Hat CodeReady Studio with Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHPAM/#codeready-studio-installing-runtime-environments-proc)
[Integrating Red Hat CodeReady Studio with Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHDM/#codeready-studio-installing-runtime-environments-proc)

Upstream 7.30.x PR BXMSDOC-5517: Replaced decision engine with process engine in PAM doc

---

doc-content/enterprise-only/integration/dev-studio-installing-runtime-environments-proc.adoc

[RHPAM 7.4](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHPAM7.4/#dev-studio-installing-runtime-environments-proc)
[RHDM 7.4](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHDM7.4/#dev-studio-installing-runtime-environments-proc)

Upstream 7.23.x PR for BXMSDOC-5517: Replaced decision engine with process engine for PAM doc

---

doc-content/enterprise-only/integration/codeready-studio-installing-runtime-environments-proc.adoc

[RHPAM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHPAM7.5/#codeready-studio-installing-runtime-environments-proc)
[RHDM 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5517-RHDM7.5/#codeready-studio-installing-runtime-environments-proc)

Upstream 7.26.x PR for BXMSDOC-5517: Replaced decision engine with process engine for PAM doc

---

doc-content/enterprise-only/springboot/bus-app-create_proc.adoc

Upstream PR for 7.26 to cover 7.5
Original jira: https://issues.redhat.com/browse/BXMSDOC-5091
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5091/#bus-app-create_business-applications

Upstream PR BXMSDOC-5091-7.26.x to upstream 7.26.x added missing closing bracket to code snippet

---

doc-content/enterprise-only/springboot/bus-app-create_proc.adoc

Upstream PR for 7.30 to cover 7.6
Original jira: https://issues.redhat.com/browse/BXMSDOC-5091
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5091/#bus-app-create_business-applications

Upstream PR BXMSDOC-5091-7.30.x to upstream 7.30.x added missing closing bracket to code snippet

---

doc-content/enterprise-only/springboot/bus-app-create_proc.adoc

Upstream PR for 7.33 to cover 7.7
Original jira: https://issues.redhat.com/browse/BXMSDOC-5091
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5091/#bus-app-create_business-applications

Upstream PR BXMSDOC-5091-7.33.x to upstream 7.33.x added missing closing bracket to code snippet

---

_artifacts/document-attributes.adoc
assemblies/assembly_kogito-creating-running/main.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/proc_kogito-running-app.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/ref_kogito-glossary.adoc
doc-content/kogito-docs/src/main/asciidoc/index.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con_kogito-on-ocp.adoc

@krisv , @porcelli , @ricardozanini , @ibek , I've added a Kogito glossary based on our [google doc](https://docs.google.com/document/d/1khJCEWc5zTok3YTygt6vqKc2BPcgh9C01nC17BvV9rE/edit#heading=h.9xf9elwpgzg4) and discussion, with tweaks and clarifications to tie in to the other documentation and links for more info.
Can you all review and let me know if you're good with this? Doc links below. After your feedback and approval, will move it forward.
Many of the links refer to a new "Configuring Kogito supporting services and runtime capabilities" doc/content that is pending merge and thus are broken. Once that PR is merged, those links will render for community. For enterprise, those links might never render until GA, unless we can figure a way to do so for the dynamic FTP that will be …

BXMSDOC-5553-master-kogito: Add Kogito glossary

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-EXPECT-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5115)
- [7.7-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHPAM-TS-CustomerTicket-Final/#test-scenarios-legacy-EXPECT-proc)
- [7.7-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHDM-TS-CustomerTicket-Final/#test-scenarios-legacy-EXPECT-proc)
Added a note regarding the validation of list in the **16.1.2. Adding EXPECT results in test scenarios (legacy)** section in **step 4**.

Upstream master PR for BXMSDOC-5115: Added a note regarding validation of list in legacy test scenario content.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-EXPECT-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5115)
- [7.7-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHPAM-TS-CustomerTicket-Final/#test-scenarios-legacy-EXPECT-proc)
- [7.7-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHDM-TS-CustomerTicket-Final/#test-scenarios-legacy-EXPECT-proc)
Added a note regarding the validation of list in the **16.1.2. Adding EXPECT results in test scenarios (legacy)** section in **step 4**.

Upstream 7.33.x PR for BXMSDOC-5115: Added a note regarding validation of list in legacy test scenario content.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-EXPECT-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5115)
- [7.6-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHPAM-7.6-TS-CT/#test-scenarios-legacy-EXPECT-proc)
- [7.6-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHDM-7.6-TS-CT/#test-scenarios-legacy-EXPECT-proc)
Added a note regarding the validation of list in the **16.1.2. Adding EXPECT results in test scenarios (legacy)** section in **step 4**.

Upstream 7.30.x PR for BXMSDOC-5115: Added a note regarding validation of list in legacy test scenario content.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-EXPECT-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5115)
- [7.5-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHPAM-7.5-TS-CT/#test-scenarios-legacy-EXPECT-proc)
- [7.5-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5115-RHDM-7.5-TS-CT/#test-scenarios-legacy-EXPECT-proc)
Added a note regarding the validation of list in the **16.1.2. Adding EXPECT results in test scenarios (legacy)** section in **step 4**.

Upstream 7.26.x PR for BXMSDOC-5115: Added a note regarding validation of list in legacy test scenario content.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-create-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5123)
- [7.5-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHPAM-7.5-TS-CT/#test-scenarios-legacy-create-proc)
- [7.5-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHDM-7.5-TS-CT/#test-scenarios-legacy-create-proc)
Added a note regarding the LocalDate in section 16.1.

Upstream 7.26.x PR for BXMSDOC-5123: LocalDate data type supported in legacy test scenario.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-create-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5123)
- [7.6-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHPAM-7.6-TS-CT/#test-scenarios-legacy-create-proc)
- [7.6-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHDM-7.6-TS-CT/#test-scenarios-legacy-create-proc)
Added a note regarding the LocalDate in section 16.1.

Upstream 7.30.x PR for BXMSDOC-5123: LocalDate data type supported in legacy test scenario.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-create-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5123)
- [7.7-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHPAM-7.7-TS-CT/#test-scenarios-legacy-create-proc)
- [7.7-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHDM-7.7-TS-CT/#test-scenarios-legacy-create-proc)
Added a note regarding the `LocalDate` in section 16.1.

Upstream 7.33.x PR for BXMSDOC-5123: LocalDate data type supported in legacy test scenario.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-legacy-create-proc.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5123)
- [7.7-RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHPAM-7.7-TS-CT/#test-scenarios-legacy-create-proc)
- [7.7-RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-5123-RHDM-7.7-TS-CT/#test-scenarios-legacy-create-proc)
Added a note regarding the `LocalDate` in section 16.1.

Upstream master PR for BXMSDOC-5123: LocalDate data type supported in legacy test scenario.

---

assemblies/assembly_release-notes/main.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-5811)
- [7.7-RHPAM-Release notes for Red Hat Process Automation Manager](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHPAM-7.7-RN/) 
- [7.7-RHDM-Release notes for Red Hat Decision Manager](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-2608-RHDM-7.7-RN/) 
I have added the reference links in the **What's new** and **tech preview** section of the RN document.

Upstream 7.33.x PR for BXMSDOC-5811: Add reference links for what's new content in 7.7 release notes

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.7/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.7/#dmn-data-types-ref_dmn-models)

Upstream master PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.7/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.7/#dmn-data-types-ref_dmn-models)

Upstream 7.33.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.6/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.6/#dmn-data-types-ref_dmn-models)

Upstream 7.30.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.5/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.5/#dmn-data-types-ref_dmn-models)

Upstream 7.26.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.4/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.4/#dmn-data-types-ref_dmn-models)

Upstream 7.23.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.3/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.3/#dmn-data-types-ref_dmn-models)

Upstream 7.18.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.2/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.2/#dmn-data-types-ref_dmn-models)

Upstream 7.14.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-data-types-ref.adoc

RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHPAM-7.1/#dmn-data-types-ref_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5831-RHDM-7.1/#dmn-data-types-ref_dmn-models)

Upstream 7.11.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

docs/product-user-guide/src/main/asciidoc/dmn-data-types-ref.adoc

Upstream 7.7.x PR for BXMSDOC-5831: replaced ] with ) in DMN doc

---

doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-endpoint-authentication-proc.adoc
doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc

**Affected documents:** 
- RHPAM and RHDM Managing and monitoring KIE Server
- Installing and configuring RHPAM/RHDM in a Red Hat JBoss EAP clustered environment
Managing and monitoring KIE Server book was not building due to cross-reference links issue. Updated the links.

Upstream master PR for BXMSDOC-5953: Corrected the cross reference links in the documents.

---

doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-endpoint-authentication-proc.adoc
doc-content/enterprise-only/admin-and-config/kie-server-smart-router-enable-tls-support-proc.adoc

**Affected documents:** 
- RHPAM and RHDM Managing and monitoring KIE Server
- Installing and configuring RHPAM/RHDM in a Red Hat JBoss EAP clustered environment
Managing and monitoring KIE Server book was not building properly due to cross-reference links issue. Updated the links.

Upstream 7.33.x PR for BXMSDOC-5953: Corrected the cross reference links in the documents.

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/rules-attributes-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5933
Rendered output
[Designing a decision service using DRL rules RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5933-RHPAM/#rules-attributes-ref_drl-rules)
[Designing a decision service using DRL rules RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5933-RHDM/#rules-attributes-ref_drl-rules)

Upstream master PR for BXMSDOC-5933: Added limitation for consequences written in JAVA dialects

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/proc-bpmn-model-creating.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/con-kogito-modelers.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/proc-kogito-vscode-extension.adoc
doc-content/kogito-docs/src/main/asciidoc/dmn/proc-dmn-model-creating.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/con-kogito-travel-agency.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/0.11.0/ref-kogito-rn-new-features.adoc
doc-content/kogito-docs/src/main/asciidoc/test-scenarios/proc-test-scenarios-creating.adoc

@ederign , can you please review and verify both the doc update and the release note update for the VSCode release in Marketplace? I also made a few other changes summarized below.
**Important:** @paulovmr When I follow the standard instructions to [install and use the Business Modeler Hub](http://file.rdu.redhat.com/~sterobin/BXMSDOC-6024_CR/#proc-kogito-modelers_kogito-creating-running), I get the following error, similar to what you and I saw before. Is this a bug in the code, the docs, or with me :) ?
**Summary of changes:**
* Updated section on installing VSCode extension bundle directly in VSCode
* Updated all instances of "1.44.0 or later" to recommend 1.46.0 or later instead, to ensure users have access to the VSCode extension via Marketplace, and to have access to latest updates …

BXMSDOC-6024: Update doc content with new VSCode support

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5871
Epic: https://issues.redhat.com/browse/BXMSDOC-5626
[Decision engine in Red Hat Process Automation Manager 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5871-RHPAM-7.8/#performance-tuning-decision-engine-ref_decision-engine)
[Decision engine in Red Hat Decision Manager 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5871-RHDM-7.8/#performance-tuning-decision-engine-ref_decision-engine)

Upstream 7.39.x PR for BXMSDOC-5871: Added Lambda externalization section in performance tuning chapter for decision engine doc

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5871
Epic: https://issues.redhat.com/browse/BXMSDOC-5626
Rendered output: 
[Decision engine in Red Hat Process Automation Manager 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5871-RHPAM-7.8/#performance-tuning-decision-engine-ref_decision-engine)
[Decision engine in Red Hat Decision Manager 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5871-RHDM-7.8/#performance-tuning-decision-engine-ref_decision-engine)

Upstream master PR for BXMSDOC-5871: Added Lambda externalization section in performance tuning chapter for decision engine doc

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-properties-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5425
[Designing a decision service using DMN models RHPAM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5425-RHPAM-7.8/#dmn-properties-ref_dmn-models)
[Designing a decision service using DMN models RHDM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5425-RHDM-7.8/#dmn-properties-ref_dmn-models)

Upstream 7.39.x PR for BXMSDOC-5425: Added example for DMNRuntimeListener property as part of kmodule.xml

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-properties-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5425
[Designing a decision service using DMN models RHPAM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5425-RHPAM-7.8/#dmn-properties-ref_dmn-models)
[Designing a decision service using DMN models RHDM 7.8](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5425-RHDM-7.8/#dmn-properties-ref_dmn-models)

Upstream master PR for BXMSDOC-5425: Added example for DMNRuntimeListener property as part of kmodule.xml

---

doc-content/enterprise-only/bpmn/bpmn-end-events-ref.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/appe-process-elements.adoc

Changed the description for Terminate end event
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5957
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5957-RHPAM/#terminate_end_event)
[Process designer Business Process Model and Notation (BPMN2) reference guide](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5957-bpmn-RHPAM/#terminate_end_event)

Upstream master PR for BXMSDOC-5957: Made changes for terminate end event description in process designer doc

---

doc-content/enterprise-only/bpmn/bpmn-end-events-ref.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/appe-process-elements.adoc

Changed the description for Terminate end event
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5957
[Designing business processes in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5957-RHPAM-7.8/#terminate_end_event)
[Process designer Business Process Model and Notation (BPMN2) reference guide](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5957-RHPAM-BPMN-7.8/#terminate_end_event)

Upstream 7.39.x PR for BXMSDOC-5957: Made changes for terminate end event description

---

doc-content/enterprise-only/installation/roles-users-con.adoc

Added clarification in **CHAPTER 2. RED HAT DECISION MANAGER ROLES AND USERS**
Doc previews:
[Installing and configuring Red Hat Process Automation Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHPAM/#roles-users-con)
[Installing and configuring Red Hat Decision Manager on Red Hat JBoss EAP](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5459-EAP-RHDM/#roles-users-con)

Upstream 7.39.x PR for BXMSDOC-5459: Added clarification regarding users and roles

---

doc-content/drools-docs/src/main/asciidoc/LanguageReference/drl-operator-precedence-ref.adoc

Since 7.27.0.Final docs, "." was missed.

Add basic nested property access

---

doc-content/enterprise-only/fuse/installing-ba-fuse-karaf-maven-proc.adoc
doc-content/enterprise-only/fuse/installing-on-fuse-eap-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-5862
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-5862/#installing-on-fuse-eap-proc

Upstream PR for BXMSDOC-5862-7.39.x to 7.39.x Integrating PAM/DM 7.8 with Fuse

---

doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6142
Doc Previews:
[Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6142-RHPAM/#sso-client-adapter-proc)
[Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6142-RHDm/#sso-client-adapter-proc)

Upstream 7.39.x PR for BXMSDOC-6142: Deleted the step of removing single sign-on element

---

doc-content/enterprise-only/integration/sso-client-adapter-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6142
Doc Previews:
[Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6142-RHPAM-7.7/#sso-client-adapter-proc)
[Integrating Red Hat Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6142-RHDM-7.7/#sso-client-adapter-proc)

Upstream 7.33.x PR for BXMSDOC-6142: Deleted the step of removing single sign-on element

---

doc-content/enterprise-only/integration/sso-basic-auth-proc.adoc
doc-content/enterprise-only/integration/sso-kie-server-client-adapter-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6143
https://issues.redhat.com/browse/BXMSDOC-6144
Doc previews:
[Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6143-RHPAM/#sso-kie-server-client-adapter-proc)
[Integrating Red Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6143-RHDM/#sso-kie-server-client-adapter-proc)

Upstream master PR for BXMSDOC-6143: Replaced kie-execution-server with kie-server

---

doc-content/enterprise-only/integration/sso-basic-auth-proc.adoc
doc-content/enterprise-only/integration/sso-kie-server-client-adapter-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6143
https://issues.redhat.com/browse/BXMSDOC-6144
Doc previews:
[Integrating Red Hat Process Automation Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6143-RHPAM/#sso-kie-server-client-adapter-proc)
[Integrating Red Decision Manager with Red Hat Single Sign-On](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6143-RHDM/#sso-kie-server-client-adapter-proc)

Upstream 7.39.x PR for BXMSDOC-6143: Replaced kie-execution-server with kie-server

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_no_chain.yml

https://issues.redhat.com/browse/BXMSPROD-921
`pull_request.yml` event moved to `workflow_dispatch` to not trigger the flow by a PR and a new PR flow created just to build `kie-docs` (java 8 and 11, ubuntu and windows)
the pull_request.yml is still needed by the chain https://github.com/kiegroup/optaweb-employee-rostering/blob/22da730f5928fa33da3e4dcc6f0572012c07aa31/.github/workflows/pull_request.yml#L15  `build-command-upstream`

BXMSPROD-921 build chain event to workflow_dispatch and new pull request added

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/prometheus-monitoring-proc.adoc

**JIRAs:**
- [BXMSDOC-6171](https://issues.redhat.com/browse/BXMSDOC-6171)
- [BXMSDOC-6123](https://issues.redhat.com/browse/BXMSDOC-6123)
- [BXMSDOC-6191](https://issues.redhat.com/browse/BXMSDOC-6191)
- [7.7-RHPAM-Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHPAM-MMKS-7.7-DDF/#prometheus-monitoring-proc_execution-server)
- [7.7-RHDM-Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHDM-MMKS-7.7-DDF/#prometheus-monitoring-proc_execution-server)
- Please see **Chapter 18** in RHPAM and **Chapter 13** in RHDM docs for the changes.
- I have removed all the mentions of additional dependencies in the Spring Boot pom.xml.
- In section 18.1 --> Step no. 3 ---> Corrected syntax in …

Upstream 7.33.x PR for BXMSDOC-6171, 6123, 6191: Incorporate DDF changes in managing and monitoring KIE server doc.

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/prometheus-monitoring-proc.adoc

**JIRAs:**
- [BXMSDOC-6171](https://issues.redhat.com/browse/BXMSDOC-6171)
- [BXMSDOC-6123](https://issues.redhat.com/browse/BXMSDOC-6123)
- [BXMSDOC-6191](https://issues.redhat.com/browse/BXMSDOC-6191)
- [7.6-RHPAM-Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHPAM-MMKS-7.6-DDF/#prometheus-monitoring-proc_execution-server)
- [7.6-RHDM-Managing and monitoring KIE Server](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-RHDM-MMKS-7.6-DDF/#prometheus-monitoring-proc_execution-server)
- Please see **Chapter 17** in RHPAM and **Chapter 13** in RHDM docs for the changes.
- I have removed all the mentions of additional dependencies in the Spring Boot pom.xml.
- In section 17.1 --> Step no. 3 ---> Corrected syntax in …

Upstream 7.30.x PR for BXMSDOC-6171, 6123, 6191: Incorporate DDF changes in managing and monitoring KIE server doc.

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/cust-marshalling-cms-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/set-marshalling-proc.adoc

Found a little typo while going over the documentation of document marshalling. As per source code [DocumentStorageServiceImpl.java#L50-L51](
https://github.com/kiegroup/jbpm/blob/e52da0cfbcf17f36674d73bc7db20377c7e1984e/jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentStorageServiceImpl.java#L50-L51)
I have corrected the path from _PROJECT_HOME_/docs to _PROJECT_HOME_/.docs

Correct default document storage path

---

_artifacts/document-attributes.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/dmn-execution-business-process.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6395
Added a Note for Namespace and DMN Model Name fields in Invoking a Decision Model and Notation (DMN) service in a business process in the process designer document.
Doc preview:
[Designing business processes in Business Central 7.6](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6395-RHPAM-7.6/#dmn-execution-business-process)

Upstream 7.30.x PR for BXMSDOC-6395: Added a note for Namespace and DMN Model Name fields value to be same

---

_artifacts/document-attributes.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/dmn-execution-business-process.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6395
Added a Note for Namespace and DMN Model Name fields in Invoking a Decision Model and Notation (DMN) service in a business process in the process designer document.
Doc preview:
[Designing business processes in Business Central 7.5](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6395-RHPAM-7.5/#dmn-execution-business-process)

Upstream 7.26.x PR for BXMSDOC-6395: Added a note for Namespace and DMN Model Name fields value to be same

---

doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Installation/business-central-system-properties-ref.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6276)
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6504)
- [RHPAM-2808](https://issues.redhat.com/browse/RHPAM-2808)
- [RHPAM-II. Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6504-RHPAM-BCSettings/#business-central-system-properties-ref_configuring-central)
- [RHDM-II. Configuring Business Central settings and properties](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6504-RHDM-BCSettings/#business-central-system-properties-ref_configuring-central)
- For RHPAM: Under **II. Configuring Business Central settings and properties** --> Chapter 49. Business Central system properties --> Section Maven and miscellaneous
- For RHDM: …

Upstream master PR for BXMSDOC-6504: Document how to make LRUCache configurable to avoid large memory retention.

---

doc-content/enterprise-only/openshift/externaldb-build-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6430
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6430/#externaldb-build-proc_openshift-authoring
Pull request: michelehaglund#162

Upstream PR: BXMSDOC-6430-7.39.x to 7.39.x Added prereq links

---

doc-content/enterprise-only/openshift/externaldb-build-proc.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-6430
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6430/#externaldb-build-proc_openshift-authoring
Pull request: https://github.com/michelehaglund/kie-docs/pull/162

Upstream PR: BXMSDOC-6430 to Master Added prereq links

---

.github/workflows/push.yml
.gitignore
doc-content/drools-docs/pom.xml

Followups on https://github.com/kiegroup/kie-docs/pull/2816 and pivots to demonstrate automatic integrity check of DMN/FEEL builtin function adoc, if compared to main source repo
1. Maven antrun plugin is used to download from Drools repo source, the "master source" of the content adoc file
2. A check is performed to ensure the content is text-same by standard diff tools (embedded in Maven/Ant itself)
3. If the content is not the same, Maven build (of community doc) fails
since the content are already not the same for the 1st line, the Adoc comment in the file itself, this already fails.
In other words it fails because this line: https://github.com/kiegroup/kie-docs/blame/master/doc-content/drools-docs/src/main/asciidoc/DMN/ref-dmn-feel-builtin-functions.adoc#L1
it is already NOT the same …

BXMSDOC-6539 Demonstrate automatic integrity check of DMN/FEEL builtin fn adoc

---

README.md

As requested equivalent readme badges for the root README document on the `master-kogito`
Ref: https://github.com/kiegroup/kie-docs/pull/2873

BXMSDOC-6539 status badge on root README document (master-kogito)

---

assemblies/assembly-building-custom-dashboard-widgets.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-creating-external-components-proc.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-external-components-con.adoc

**JIRAs:** 
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6276) 
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6503)
- [RHPAM-Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6503-RHPAM-externalcomponents/#building-custom-dashboard-widgets-external-components-con)
- [RHDM-Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6503-RHDM-externalcomponents/#building-custom-dashboard-widgets-external-components-con)
- For **RHPAM**, go to IV. Building custom dashboard widgets ---> Chapter **57.5. External components**.
- For **RHDM**, go to IV. Building custom dashboard widgets  ---> Chapter **51.5. External components**.

Upstream master PR for BXMSDOC-6503: Document dashbuilder external components feature.

---

assemblies/assembly-building-custom-dashboard-widgets.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-creating-external-components-proc.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-external-components-con.adoc

**JIRAs:** 
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6276) 
- [Dedicated JIRA](https://issues.redhat.com/browse/BXMSDOC-6503)
- [RHPAM-Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6503-RHPAM-externalcomponents/#building-custom-dashboard-widgets-external-components-con)
- [RHDM-Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-6503-RHDM-externalcomponents/#building-custom-dashboard-widgets-external-components-con)
- For **RHPAM**, go to IV. Building custom dashboard widgets ---> Chapter **57.5. External components**.
- For **RHDM**, go to IV. Building custom dashboard widgets  ---> Chapter **51.5. External components**.

Upstream 7.44.x PR for BXMSDOC-6503: Document dashbuilder external components feature.

---

README.md
doc-content/kogito-docs/src/main/asciidoc/chap-kogito-release-notes.adoc
doc-content/kogito-docs/src/main/asciidoc/index.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/0.10.0/ref-kogito-rn-known-issues.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/0.9.0/ref-kogito-rn-known-issues.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ref-kogito-rn-key-features.adoc

This PR removes all the header references to the Dev Preview program in the kogito docs.

Removing headers with reference to dev preview

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-included-models-pmml-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6719
https://issues.redhat.com/browse/RHPAM-3251
Doc previews:
Enterprise documents
[Developing Decision Services in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6719-RHPAM/#dmn-included-models-pmml-proc_dmn-models)
[Developing Decision Services in Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6719-RHDM/#dmn-included-models-pmml-proc_dmn-models)
Community document
[Drools](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6719-DROOLS/#dmn-included-models-pmml-proc_dmn-models)

Upstream master PR for BXMSDOC-6719: Upgraded JPMML dependency version from 1.4.9 to 1.5.1

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.45.0.Final/drools-modularization.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.9.0.Final-section.adoc

@hmanwani-rh @mariofusco 
Current option has been documented in the old release notes but this invalidates
https://github.com/kiegroup/kie-docs/blob/master/doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.9.0.Final-section.adoc#alpha-network-compiler
What shall we do here?

[DROOLS-5658] updated option for ANC

---

doc-content/enterprise-only/installation/assembly_installing-on-eap-deployable.adoc
doc-content/enterprise-only/installation/kie-server-configure-central-proc.adoc

Updates bases on final QE input.
Original jira: https://issues.redhat.com/browse/BXMSDOC-6807
7.9 rendered output
DM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6807DM/#assembly-install-on-eap
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-6807PAM/#assembly-install-on-eap
Pull request: https://github.com/michelehaglund/kie-docs/pull/167/files

Upstream PR BXMSDOC-6807-7.44.x to 7.44.x: Installing and configuring DM/PAM on EAP

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Finalized release notes for Kogito 1.0
@sterobin fyi
Doc preview:
[Kogito community version](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-6707/#chap-kogito-release-notes)

BXMSDOC-6707: Finalized release notes for Kogito 1.0

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc

@r00ta I have updated the product version at four places, available in the following sections:
2.3. Creating a Maven project for a Kogito service
2.3.1. Creating a custom Kogito project using code scaffolding
Please review the changes and let me know if the changes are fine. 
Following is the doc preview of the Kogito community document:
[Kogito community documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-KOGITO-Fixversion/#proc-kogito-creating-project_kogito-creating-running)

Fixed product versions for creating projects for a Kogito service sections

---

doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/enterprise/chap-kogito-release-notes-enterprise.adoc

**JIRA**: [KOGITO-3807](https://issues.redhat.com/browse/KOGITO-3807): [DMN Designer] Convert DMN 1.1/1.3 models to version 1.2 - Documentation
Now the DMN Designer supports 1.1 and 1.3 models, non including DMN 1.3 features, when users that import assets on Kogito or Business Central . However, when users save their models, we're still saving them as DMN 1.2 models.
Thus, I've updated everything related to the DMN versions support, and also I've added an entry in the release notes section. Please, let me know if it needs any change :-)

[Kogito] KOGITO-3807: [DMN Designer] Convert DMN 1.1/1.3 models to version 1.2 - Documentation

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-included-models-pmml-proc.adoc
doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-kie-server-proc.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.48.0.Final/ReleaseNotesDrools.7.48.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.48.0.Final/drools-kie-pmml-deprecate.adoc

Added a note indicating deprecation of kie-pmml dependency. See the following links:
**JIRA**: https://issues.redhat.com/browse/BXMSDOC-7021
**BAPL**-https://issues.redhat.com/browse/BAPL-1790
****Doc previews**
**RHPAM sections:****
[4.3.2. Including PMML models within a DMN file in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7021-RHPAM/#dmn-included-models-pmml-proc_dmn-models)
[11.1. Embedding a PMML call directly in a Java application](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7021-RHPAM/#pmml-invocation-embedded-proc_pmml-models)
[11.2. Executing a PMML model using KIE server](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7021-RHPAM/#pmml-invocation-kie-server-proc_pmml-models)
**RHDM sections:**
[4.3.2. Including PMML models within a DMN file in Business …

Upstream master PR for BXMSDOC-7021: Added a note in DMN and PMML document indicating deprecation of kie-pmml 

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-included-models-pmml-proc.adoc
doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-embedded-proc.adoc
doc-content/drools-docs/src/main/asciidoc/PMML/pmml-invocation-kie-server-proc.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.48.0.Final/ReleaseNotesDrools.7.48.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.48.0.Final/drools-kie-pmml-deprecate.adoc

Added a note indicating deprecation of kie-pmml dependency. See the following links:
**JIRA**: https://issues.redhat.com/browse/BXMSDOC-7021
**BAPL**-https://issues.redhat.com/browse/BAPL-1790
****Doc previews**
**RHPAM sections:****
[4.3.2. Including PMML models within a DMN file in Business Central](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7021-RHPAM/#dmn-included-models-pmml-proc_dmn-models)
[11.1. Embedding a PMML call directly in a Java application](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7021-RHPAM/#pmml-invocation-embedded-proc_pmml-models)
[11.2. Executing a PMML model using KIE server](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7021-RHPAM/#pmml-invocation-kie-server-proc_pmml-models)
**RHDM sections:**
[4.3.2. Including PMML models within a DMN file in Business …

Upstream 7.48.x PR for BXMSDOC-7021: Added a note in DMN and PMML document indicating deprecation of kie-pmml 

---

doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-4144
Docs update for the pull request https://github.com/kiegroup/kogito-runtimes/pull/954 , document the config property of the tracing addon.
[Stetson] For Kogito 1.2, do not merge until 1.1 released.

KOGITO-4144 - Update tracing addon configuration docs

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-support-con.adoc

@tarilabs , @karreiro , @jomarko , @hmanwani-rh , would you mind verifying this new table on DMN version support? The request came from Rachid Snoussi on the Kogito side but it applies to DM/PAM the same. Matteo shared a quick table in the email thread that was actually very helpful, so we agreed that adding something like it in the docs would alone clarify things.
Side note: We're aware of the table header formatting issues/inconsistencies. It's a tooling issue where things look different in asciidoco vs. local enterprise build vs. customer portal enterprise build.
Links:
* [Jira](https://issues.redhat.com/browse/BXMSDOC-7142)
* [Enterprise rendered doc](http://file.rdu.redhat.com/~sterobin/BXMSDOC-7142_PAM/#dmn-support-con_dmn-models)
* [Community rendered …

BXMSDOC-7142-master: Add table for DMN version support.

---

assemblies/assembly-designing-business-processes.adoc
assemblies/assembly-dmn-models.adoc
assemblies/assembly-getting-started-decision-services.adoc
assemblies/assembly-getting-started-process-services.adoc
doc-content/drools-docs/src/main/asciidoc/DMN-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-new-project-creating-proc.adoc
doc-content/enterprise-only/getting-started/new-project-ds-proc.adoc
doc-content/enterprise-only/getting-started/new-project-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Process-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/proc-dmn-bpmn-maven-create.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/proc-vscode-extension.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7136
**Enterprise**
**Developing Process Services in RHPAM/RHDM** -
- Added a note and reference of Maven project procedure in [2.1. Installing the Red Hat Process Automation Manager VSCode Extension Bundle](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7136-BPMN-RHPAM/#proc-vscode-extension_business-processes).
- Added new chapter as [CHAPTER 3. Creating and Executing DMN and BPMN Models Using Maven](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7136-BPMN-RHPAM/#proc-dmn-bpmn-maven-create_business-processes)
**Developing Decision Services in RHPAM/RHDM**
- Added a note and reference of Maven project procedure in [2.1. Installing the Red Hat Process Automation Manager VSCode Extension …

Upstream master PR for BXMSDOC-7136: Added a note for VSCode incompatibility with Business central and created a section for Maven project procedure

---

assemblies/assembly-designing-business-processes.adoc
assemblies/assembly-dmn-models.adoc
assemblies/assembly-getting-started-decision-services.adoc
assemblies/assembly-getting-started-process-services.adoc
doc-content/drools-docs/src/main/asciidoc/DMN-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DMN/dmn-gs-new-project-creating-proc.adoc
doc-content/enterprise-only/getting-started/new-project-ds-proc.adoc
doc-content/enterprise-only/getting-started/new-project-proc.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/Process-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/proc-dmn-bpmn-maven-create.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Install/proc-vscode-extension.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7136
**Enterprise**
**Developing Process Services in RHPAM/RHDM** -
- Added a note and reference of Maven project procedure in [2.1. Installing the Red Hat Process Automation Manager VSCode Extension Bundle](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7136-BPMN-RHPAM/#proc-vscode-extension_business-processes).
- Added new chapter as [CHAPTER 3. Creating and Executing DMN and BPMN Models Using Maven](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7136-BPMN-RHPAM/#proc-dmn-bpmn-maven-create_business-processes)
**Developing Decision Services in RHPAM/RHDM**
- Added a note and reference of Maven project procedure in [2.1. Installing the Red Hat Process Automation Manager VSCode Extension …

Upstream 7.48.x PR for BXMSDOC-7136: Added a note for VSCode incompatibility with Business central and created a section for Maven project procedure

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/bpmn-intermediate-events-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7191
Doc previews:
Enterprise
**Designing business processes using BPMN models**
Added a note stating compensation not supporting data output feature in [4.2.2. Intermediate events section](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7191-BPMN-RHPAM/#bpmn-intermediate-events-ref_business-processes).
Community
**JBPM documentation**
Added a note stating compensation not supporting data output feature in [10.6.2. Intermediate events](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7191-JBPM/#bpmn-intermediate-events-ref_business-processes) section.

Upstream 7.48.x PR for BXMSDOC-7191: Added a statement for compensation event

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/bpmn-intermediate-events-ref.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7191
Doc previews:
Enterprise
**Designing business processes using BPMN models**
Added a note stating compensation not supporting data output feature in [4.2.2. Intermediate events section](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7191-BPMN-RHPAM/#bpmn-intermediate-events-ref_business-processes).
Community
**JBPM documentation**
Added a note stating compensation not supporting data output feature in [10.6.2. Intermediate events](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7191-JBPM/#bpmn-intermediate-events-ref_business-processes) section.

Upstream master PR for BXMSDOC-7191: Added a statement for compensation event

---

doc-content/enterprise-only/installation/assembly_installing-on-eap-deployable.adoc

Conditionalized the 5.3. Configuring JDBC data sources for KIE Server chapter for PAM. This section is already conditionalized in 7.9 and master. Therefore, the fix is applied for 7.8 version. 
Doc previews:
Chapter [5. Installing Red Hat Process Automation Manager from ZIP files](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6774-RHPAM/#assembly_installing-on-eap-deployable) in RHPAM with [5.3. Configuring JDBC data sources for KIE Server](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6774-RHPAM/#eap-data-source-add-proc) section. 
Chapter [5. Installing Red Hat Decision Manager from ZIP files](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6774-RHDM/#assembly_installing-on-eap-deployable) in RHDM without 5.3. Configuring JDBC data sources for KIE Server section.

Upstream 7.39.x PR for BXMSDOC-6774: conditionalized the Configuring JDBC data sources for KIE Server chapter for PAM and DM

---

doc-content/enterprise-only/bpmn/bpmn-support-con.adoc

In entreprise docs [1], fixing support for catching and throwing Link in:
-  _Table 2.3. BPMN2 catching events_ 
and 
- _Table 2.4. BPMN2 throwing and non-interrupting events_ 
[1] -  https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.9/html-single/developing_process_services_in_red_hat_process_automation_manager/index#bpmn-support_business-processes

Fixing entreprise docs: Support for catching and throwing Link Events

---

doc-content/enterprise-only/bpmn/bpmn-support-con.adoc

In entreprise docs [1], fixing support for catching and throwing Link in 7.10:
Table 2.3. BPMN2 catching events
and
Table 2.4. BPMN2 throwing and non-interrupting events

Upstream 7.48.x PR for Support for catching and throwing Link Events in 7.10

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

See: https://issues.redhat.com/browse/KOGITO-4210
With [this PR](https://github.com/kiegroup/kogito-cloud-operator/pull/733), the operator now expects that Quarkus applications have [the health extension](https://quarkus.io/guides/microprofile-health) imported. This is now clarified in the docs when setting up an example project and in the OpenShift section. I also added information about to set custom endpoints for probes.
[Stetson] Do not merge: For 1.3 and pending above PR.

[KOGITO-4210] Quarkus apps must have health extension

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6898
Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs
[28.1. Sending requests with the Knowledge Store REST API using a REST client or curl utility](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6898-RHPAM/#knowledge-store-rest-api-requests-proc_kie-apis)
Interacting with Red Hat Decision Manager using KIE APIs
[28.1. Sending requests with the Knowledge Store REST API using a REST client or curl utility](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6898-RHDM/#knowledge-store-rest-api-requests-proc_kie-apis)

Upstream 7.48.x PR for BXMSDOC-6898: Added accept-language as HTTP Header for REST API

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/controller-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-requests-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/security-management-rest-api-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-6898
Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs
[28.1. Sending requests with the Knowledge Store REST API using a REST client or curl utility](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6898-RHPAM/#knowledge-store-rest-api-requests-proc_kie-apis)
Interacting with Red Hat Decision Manager using KIE APIs
[28.1. Sending requests with the Knowledge Store REST API using a REST client or curl utility](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6898-RHDM/#knowledge-store-rest-api-requests-proc_kie-apis)

Upstream master PR for BXMSDOC-6898: Added accept-language as HTTP Header for REST API

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
**Interacting with Red Hat Process Automation Manager using KIE APIs**
[24.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM/#runtime-commands-samples-ref_kie-apis)
**Interacting with Red Hat Decision Manager using KIE APIs**
[24.1. Sample runtime commands in Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHDM/#runtime-commands-samples-ref_kie-apis)

Upstream 7.48.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.9
[24.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.9/#runtime-commands-samples-ref_kie-apis)

Upstream 7.44.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.8
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.8/#runtime-commands-samples-ref_kie-apis)

Upstream 7.39.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.7
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.7/#runtime-commands-samples-ref_kie-apis)

Upstream 7.33.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.6
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.6/#runtime-commands-samples-ref_kie-apis)

Upstream 7.30.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.4
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.4/#runtime-commands-samples-ref_kie-apis)

Upstream 7.23.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs 7.3
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.3/#runtime-commands-samples-ref_kie-apis)

Upstream 7.18.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/shared-kie-docs/src/main/asciidoc/Commands/runtime-commands-samples-ref.adoc

Doc previews:
Interacting with Red Hat Process Automation Manager using KIE APIs
[4.1. Sample runtime commands in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7213-RHPAM-7.1/#runtime-commands-samples-ref_kie-apis)

Upstream 7.11.x PR for BXMSDOC-7213: Changed the Java command for BatchExecutionCommand in KIE API doc

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Finalized release notes for Kogito 1.3, added a KOGITO-4512 as a known issue and added JIRA release note links. 
See JIRA: https://issues.redhat.com/browse/BXMSDOC-7143
Doc preview:
[Kogito documentation 1.3.0 ](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7143-KOGITO-release-notes/#chap-kogito-release-notes)

BXMSDOC-7143: Finalized release notes for Kogito 1.3

---

doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/TestScenarioEditor-section.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-global-settings-panel-con.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-global-settings-panel-dmn-based-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-global-settings-panel-rule-based-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-comparison-legacy-new-ref.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-coverage-report-con.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-coverage-report-dmn-based-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-scenarios-coverage-report-rule-based-proc.adoc

**JIRAs:**
- [Epic](https://issues.redhat.com/browse/BXMSDOC-6749)
- [Associated JIRA](https://issues.redhat.com/browse/BXMSDOC-7056)
**Enterprise document previews:**
- [RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7056-RHPAM-TS/#test-designer-global-settings-panel-con_test-scenarios)
- [RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7056-RHDM-TS/#test-designer-global-settings-panel-con_test-scenarios)
**Drools community document preview** 
Please check the following chapters from drools doc:
- [16.12.2. Global settings for test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7056-Drools-Doc/#test-designer-global-settings-panel-con_drl-rules)
- [16.12.12. Coverage reports …

Upstream 7.48.x PR for BXMSDOC-7056: Single-source and add test scenarios chapters in the upstream document.

---

assemblies/assembly-building-custom-dashboard-widgets.adoc
assemblies/assembly-configuring-central.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-components-con.adoc
doc-content/enterprise-only/pages/building-custom-dashboard-widgets-creating-dashboard-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/Authoring-section.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/adding-data-sets-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/data-sets-authoring-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/data-sets-caching-con.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/editing-data-sets-proc.adoc
doc-content/shared-kie-docs/src/main/asciidoc/Workbench/Authoring/DataSets/refreshing-data-sets-con.adoc

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-7225
**Enterprise document previews:**
- [RHPAM-IV. Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7225-RHPAM-DataSets/#data-sets-authoring-con_building-custom-dashboard-widgets)
- [RHDM-IV. Building custom dashboard widgets](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7225-RHDM-DataSets/#data-sets-authoring-con_building-custom-dashboard-widgets)
**Doc impact for enterprise documents:**
- Check section **54. Data sets authoring** in RHPAM doc
- Check section **48. Data sets authoring** in RHDM doc (Same as RHPAM)
**Community document previews:**
- [Drools document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7225-Drools/#data-sets-authoring-con_kie-apis)
- [jBPM …

Upstream 7.48.x PR for BXMSDOC-7225: Single-source and add "Data sets authoring" chapter in the upstream documents.

---

doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

@hmanwani-rh In this PR we updated the OpenShift section to emphasize that our operator does not create third-party resources anymore. Now users must create them before deploying Kogito services.
See: https://issues.redhat.com/browse/KOGITO-4199

[KOGITO-4199] KogitoInfra does not create third-party resources anymore

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-7303
**Doc preview links:** 
- [Release notes for Red Hat Process Automation Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7303-RN-WrapperModules-RHPAM/#new_wrapper_modules)
- [Release notes for Red Hat Decision Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7303-RN-WrapperModules-RHDM/#new_wrapper_modules)
- Please check section **3.6. New wrapper modules** in the **RHPAM** document. 
- Please check section **3.4. New wrapper modules** in the **RHDM** document. (Same as RHPAM)

Upstream 7.48.x PR for BXMSDOC-7303: Include "New wrapper modules" section to 7.10 RHPAM/RHDM release notes.

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-7303
**Doc preview links:** 
- [Release notes for Red Hat Process Automation Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7303-RN-WrapperModules-RHPAM/#new_wrapper_modules)
- [Release notes for Red Hat Decision Manager 7.10](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7303-RN-WrapperModules-RHDM/#new_wrapper_modules)
- Please check section **3.6. New wrapper modules** in the **RHPAM** document. 
- Please check section **3.4. New wrapper modules** in the **RHDM** document. (Same as RHPAM)

Upstream master PR for BXMSDOC-7303: Include "New wrapper modules" section to 7.10 RHPAM/RHDM release notes.

---

assemblies/assembly-guided-decision-tables.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/GuidedDecisionTableEditor-section.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-columns-create-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/proc-guided-decision-tables-columns-sort.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.52.0.Final/ReleaseNotesDrools.7.52.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.52.0.Final/sort-column-guided-decision-tables.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7467
BAPL: https://issues.redhat.com/browse/BAPL-1619
Epic: https://issues.redhat.com/browse/BXMSDOC-7297
Added a new section as **Sorting column values in guided decision tables** in guided decision table doc.
Doc previews:
Enterprise
[32. Sorting column values in guided decision tables](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7467-RHPAM/#proc-guided-decision-tables-columns-sort_guided-decision-tables) in RHPAM
[32. Sorting column values in guided decision tables](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7467-RHDM/#proc-guided-decision-tables-columns-sort_guided-decision-tables) in RHDM
Community
[16.4.6. Sorting column values in guided decision tables](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7467-DROOLS/#proc-guided-decisio …

Upstream master PR for BXMSDOC-7467: Added sorting capability information in guided decision tables doc

---

assemblies/assembly-guided-decision-tables.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/GuidedDecisionTableEditor-section.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/guided-decision-tables-columns-create-proc.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/proc-guided-decision-tables-columns-sort.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.52.0.Final/ReleaseNotesDrools.7.52.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.52.0.Final/sort-column-guided-decision-tables.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-7467
BAPL: https://issues.redhat.com/browse/BAPL-1619
Epic: https://issues.redhat.com/browse/BXMSDOC-7297
Added a new section as **Sorting column values in guided decision tables** in guided decision table doc.
Doc previews:
Enterprise
[32. Sorting column values in guided decision tables](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7467-RHPAM/#proc-guided-decision-tables-columns-sort_guided-decision-tables) in RHPAM
[32. Sorting column values in guided decision tables](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7467-RHDM/#proc-guided-decision-tables-columns-sort_guided-decision-tables) in RHDM
Community
[16.4.6. Sorting column values in guided decision tables](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-7467-DROOLS/#proc-guided-decisio …

Upstream 7.52.x PR for BXMSDOC-7467: Added sorting capability information in guided decision tables doc

---

doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.33.0.Final/lambda-externalisation.adoc

@hmanwani-rh discussing with users we realised that saying "optimized memory performance" and "lead to `OutOfMemory` error" in the same phrase is misleading. Also OOM errors are not really known in latest version so let's remove this

Removed misleading message on Lambda externalisation

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/appe-service-tasks.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/con_custom-tasks-overview.adoc

Modified the following to state milliseconds instead of seconds per reader comment:
ConnectTimeout: Connection timeout. The default value is 60000 milliseconds/60 seconds. The input value must be provided in milliseconds.
ReadTimeout: Timeout on response. The default value is 60000 milliseconds/60 seconds. The input value must be provided in milliseconds.
Original jira: https://issues.redhat.com/browse/BXMSDOC-7444
jBPM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7444_COMM/#con_custom-tasks-overview
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7444/#con_custom-tasks-overview

Upstream PR: BXMSDOC-7444-7.52.x to 7.52.x Changed instances of seconds to milliseconds per dev confirmation

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/appe-service-tasks.adoc
doc-content/jbpm-docs/src/main/asciidoc/BPMN2/con_custom-tasks-overview.adoc

Modified the following to state milliseconds instead of seconds per reader comment:
ConnectTimeout: Connection timeout. The default value is 60000 milliseconds/60 seconds. The input value must be provided in milliseconds.
ReadTimeout: Timeout on response. The default value is 60000 milliseconds/60 seconds. The input value must be provided in milliseconds.
Original jira: https://issues.redhat.com/browse/BXMSDOC-7444
jBPM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7444_COMM/#con_custom-tasks-overview
PAM: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7444/#con_custom-tasks-overview

Upstream PR: BXMSDOC-7444-master-final to Master Changed instances of seconds to milliseconds per dev confirmation

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

See: https://issues.redhat.com/browse/KOGITO-4958
With [this PR](https://github.com/kiegroup/kogito-cloud-operator/pull/841), the operator now expects that Spring Boot applications have the [Spring Boot Actuator dependency](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/production-ready-features.html) imported. This is now clarified in the docs when setting up an example project and in the OpenShift section.
- require Spring Boot Actuator dependency (when deploying on OpenShift/Kubernetes) in following sections:
- creating Kogito Maven project
- setting up probes
- deploying on OpenShift web console
- deploying with Kogito CLI
- remove note about startup probes not being supported (now implemented with [KOGITO-4322](https://github.com/kiegroup/kogito-operator/pull/826 …

[KOGITO-4958] Setup Spring Boot/custom probes

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/con-timer.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7572
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7572_2/#selecting_the_correct_timer_for_your_environment
Pull request: https://github.com/michelehaglund/kie-docs/pull/192

Upstream PR BXMSDOC-7572-master to Master Document timers best practices

---

doc-content/jbpm-docs/src/main/asciidoc/BPMN2/con-timer.adoc

Original jira: https://issues.redhat.com/browse/BXMSDOC-7572
Rendered output: http://file.rdu.redhat.com/~mhaglund/BXMSDOC-7572_2/#selecting_the_correct_timer_for_your_environment
Pull request: https://github.com/michelehaglund/kie-docs/pull/192

Upstream PR BXMSDOC-7572-7.52.x to 7.52.x Document timers best practices

---

doc-content/jbpm-docs/src/main/asciidoc/Kafka/kieserver-kafka-emit-proc.adoc

JIRA: [JBPM-9716](https://issues.redhat.com/browse/JBPM-9716)
Depends on https://github.com/kiegroup/jbpm/pull/1925

[JBPM-9716] Wrong bootstrap servers property in the Kafka Emitter

---

doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

Fixing typo on "DEPLOYING RED HAT PROCESS AUTOMATION MANAGER ON RED HAT OPENSHIFT CONTAINER PLATFORM" documentation v7.10.
https://issues.redhat.com/browse/BXMSDOC-7682

BXMSDOC-7682: fixing typo on openshift documentation

---

doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc

"backport" of https://github.com/kiegroup/kie-docs/pull/3567 to main Drools/RHDMN doc content.

RHPAM-3690 local network port conflict, note in the example docs

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.50.0.Final/ReleaseNotesDrools.7.50.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.50.0.Final/join-node-range-index.adoc

Sorry about the retrospective update. This feature was introduced in 7.50.0.Final but better than no document :)
https://issues.redhat.com/browse/DROOLS-5910

[DROOLS-5910] Enable range index for JoinNode

---

doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.50.0.Final/ReleaseNotesDrools.7.50.0.Final-section.adoc
doc-content/drools-docs/src/main/asciidoc/ReleaseNotes/ReleaseNotesDrools.7.50.0.Final/join-node-range-index.adoc

Backport https://github.com/kiegroup/kie-docs/commit/98aedaf7ea9114651be962fc632888c436e3b315 to 7.52.x

[7.52.x] [DROOLS-5910] Enable range index for JoinNode (#3606)

---

doc-content/shared-kie-docs/src/main/asciidoc/Install/proc-standalone-editors.adoc

Updates docs to show setContent with path and content in standalone editors doc
cc: @paulovmr @jstastny-cz @sterobin 
https://issues.redhat.com/browse/KOGITO-4915

KOGITO-4915: Fix docs after setContent fix for standalone editors

---

doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc

Updates docs to show setContent with path and content in standalone editors doc
related PR: https://github.com/kiegroup/kie-docs/pull/3469

KOGITO-4915 - SetContent fix for standalone editors

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc

See: https://issues.redhat.com/browse/KOGITO-4882
Small update to the docs to remove any reference from the old connector.

[KOGITO-4882] Removing SmallRye HTTP Connector references from our docs

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

Doc preview
RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-RHPAM/#dmn-execution-rest-proc_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-RHDM/#dmn-execution-rest-proc_dmn-models)

Upstream master PR for BXMSDOC-5984: Added best practice for Kie server endpoints in DMN

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-execution-rest-proc.adoc

Doc preview
RHPAM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-RHPAM/#dmn-execution-rest-proc_dmn-models)
RHDM - [Designing a decision service using DMN models](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5984-RHDM/#dmn-execution-rest-proc_dmn-models)

Upstream 7.52.x PR for BXMSDOC-5984: Added best practice for Kie server endpoints in DMN

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5985
Added a note for null fields in REST API response in KIE API document
Doc preview
RHPAM - [Interacting with Red Hat Process Automation Manager using KIE APIs](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5985-RHPAM/#kie-server-rest-api-requests-proc_kie-apis)
RHDM - [Interacting with Red Hat Decision Manager using KIE APIs](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5985-RHDM/#kie-server-rest-api-requests-proc_kie-apis)

Upstream master PR for BXMSDOC-5985: Null fields description for REST API response

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5985
Added a note for null fields in REST API response in KIE API document
Doc preview
RHPAM - [Interacting with Red Hat Process Automation Manager using KIE APIs](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5985-RHPAM/#kie-server-rest-api-requests-proc_kie-apis)
RHDM - [Interacting with Red Hat Decision Manager using KIE APIs](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5985-RHDM/#kie-server-rest-api-requests-proc_kie-apis)

Upstream 7.52.x PR for BXMSDOC-5985: Null fields description for REST API response

---

_artifacts/document-attributes.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-rest-api-requests-proc.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-5985
Added a note for null fields in REST API response in KIE API document
Doc preview
RHPAM - [Interacting with Red Hat Process Automation Manager using KIE APIs](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5985-7.10-RHPAM/#kie-server-rest-api-requests-proc_kie-apis)

Upstream 7.48.x PR for BXMSDOC-5985: Null fields description for REST API response

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc

Fix the typo regarding the available endpoint exposed by the svg addon.

KOGITO-5392:Typo in doc related with the svg addon rest endpoint path

---

_artifacts/document-attributes.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-expressions-syntax-dmn-based-ref.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-expressions-syntax-rule-based-ref.adoc

**DDF JIRA:** https://issues.redhat.com/browse/BXMSDOC-7527
- [RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7527-TS-RHPAM/#test-designer-expressions-syntax-dmn-based-ref)
- [RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7527-TS-RHDM/#test-designer-expressions-syntax-dmn-based-ref)
**Doc impact:** Check **70.2. Expression syntax in DMN-based test scenarios** in RHPAM doc. I have added a note about empty cells in DMN based test scenarios.

Upstream 7.52.x PR for BXMSDOC-7527: [DDF] Add a note about DMN based test scenarios.

---

_artifacts/document-attributes.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-expressions-syntax-dmn-based-ref.adoc
doc-content/drools-docs/src/main/asciidoc/AuthoringAssets/test-designer-expressions-syntax-rule-based-ref.adoc

**DDF JIRA:** https://issues.redhat.com/browse/BXMSDOC-7527
- [RHPAM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7527-TS-RHPAM/#test-designer-expressions-syntax-dmn-based-ref)
- [RHDM-Testing a decision service using test scenarios](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7527-TS-RHDM/#test-designer-expressions-syntax-dmn-based-ref)
**Doc impact:** Check **70.2. Expression syntax in DMN-based test scenarios** in RHPAM doc. I have added a note about empty cells in DMN based test scenarios.

Upstream master PR for BXMSDOC-7527: [DDF] Add a note about DMN based test scenarios.

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

Mentioned the new artifact that bundles all persistence scripts in the 5.5 persistence section and the release notes section.
Jira https://issues.redhat.com/browse/KOGITO-4724
The task was merged into version 1.10.

KOGITO-4724 sql script bundle note

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.10.0.Final/ReleaseNotesKogito.1.10.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.11.0.Final/ReleaseNotesKogito.1.11.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/chap-kogito-release-notes.adoc

This PR is created to have cumulative release notes in Kogito community docs starting from Kogito 1.10. With cumulative release notes, the contributors need to consider the following points:
* The new features file of release notes file for each version needs to be saved as its own module file in the release-notes folder (as updated in this PR)
* The new features file needs to be included in the chap-kogito-release-notes.adoc file as an include (as updated in this PR)
* The {PRODUCT_VERSION} attribute cannot be used in the new features file to avoid the version number updates in the previous version's new features section
Doc preview:
[Kogito 1.11 documentation](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8096-KOGITO/#chap-kogito-release-notes)

BXMSDOC-8096: Prepare cumulative release notes for Kogito

---

doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc

Small update to align with the changes on https://github.com/kiegroup/kogito-runtimes/pull/1554

[KOGITO-5719] Update Kogito Add-Ons to newly Quarkus Extensions

---

assemblies/assembly-decision-engine.adoc
assemblies/assembly-drl-rules.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/execution-control-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8062
Doc preview:
[Designing a decision service using DRL rules](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8062-RHPAM/#assembly-drl-rules)
[Decision engine in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8062-RHPAM/#assembly-decision-engine)

Upstream 7.59.x PR for BXMSDOC-8062: Removed rule unit section from DRL and decision engine doc

---

assemblies/assembly-decision-engine.adoc
assemblies/assembly-drl-rules.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/execution-control-con.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8062
Doc preview:
[Designing a decision service using DRL rules](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8062-RHPAM/#assembly-drl-rules)
[Decision engine in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8062-RHPAM/#assembly-decision-engine)

Upstream main PR for BXMSDOC-8062: Removed rule unit section from DRL and decision engine doc

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_no_chain.yml

erased windows-latest github action jobs since they seem to be not needed in kiegroup/kie-docs

disabled windows-latest for github action martix builds

---

.github/workflows/pull_request.yml

See build-chain update details at https://github.com/kiegroup/github-action-build-chain/pull/190
related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1798
- https://github.com/kiegroup/kie-soup/pull/235
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/576
- https://github.com/kiegroup/drools/pull/3959
- https://github.com/kiegroup/optaplanner/pull/1640
- https://github.com/kiegroup/lienzo-core/pull/156
- https://github.com/kiegroup/lienzo-tests/pull/130
- https://github.com/kiegroup/appformer/pull/1208
- https://github.com/kiegroup/kie-uberfire-extensions/pull/127
- https://github.com/kiegroup/jbpm/pull/2053
- https://github.com/kiegroup/kie-jpmml-integration/pull/69
- https://github.com/kiegroup/droolsjbpm-integration/pull/2638
- …

[ISSUE 117] build-chain upgraded to v2.6.13

---

doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc

* BXMSDOC-8312 Adds note to enable user and group management
* Fixes typo
* Update doc-content/enterprise-only/installation/run-dc-standalone-proc.adoc
Incorporating peer review suggestion.

BXMSDOC-8312: Add note to enable user and group management (#12)

---

assemblies/assembly-decision-engine.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/engine-event-listeners-con.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/engine-event-listeners-development-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc

* Improved documentation for decision engine event listeners
* Link to definitions of event classes
* Update doc-content/drools-docs/src/main/asciidoc/DecisionEngine/engine-event-listeners-con.adoc
* SME/peer review

[BXMSDOC-8281] Event listeners for decision engine - main

---

assemblies/assembly-decision-engine.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine-chapter.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/engine-event-listeners-con.adoc
doc-content/drools-docs/src/main/asciidoc/DecisionEngine/engine-event-listeners-development-con.adoc
doc-content/jbpm-docs/src/main/asciidoc/CoreEngine/event-listeners-development-con.adoc

* Improved documentation for decision engine event listeners
* Link to definitions of event classes
* Update doc-content/drools-docs/src/main/asciidoc/DecisionEngine/engine-event-listeners-con.adoc
* SME/peer review

[BXMSDOC-8281] Event listeners for decision engine - 7.59.x

---

doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-central-proc.adoc
doc-content/enterprise-only/openshift/operator-deploy-kieserver-proc.adoc

* Startup strategy configuration in OpenShift Operator
* Update doc-content/enterprise-only/openshift/operator-deploy-basic-proc.adoc

[BXMSDOC-8087] Startup strategy configuration in OpenShift Operator - 7.59.x

---

assemblies/assembly-deploying-kogito-microservices-on-openshift.adoc
assemblies/assembly-getting-started-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-microservices.adoc
doc-content/enterprise-only/getting-started-kogito/con-kogito-modelers.adoc
doc-content/enterprise-only/getting-started-kogito/proc-kogito-creating-maven-project.adoc
doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
titles-enterprise/getting-started-kogito/title.adoc

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8382
BAPL- https://issues.redhat.com/browse/BAPL-2253
Doc preview:
[Getting started with Red Hat build of Kogito microservices](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8382-RHPAM-final/#assembly-getting-started-kogito-microservices)

Upstream 7.59.x PR for BXMSDOC-8382: Remove Kogito process related docs updates and limit content updates to traditional components

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.12-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.12-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-kogito-productize-features-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**JIRAs**
- Epic: https://issues.redhat.com/browse/BXMSDOC-7825
- Dedicated JIRA: https://issues.redhat.com/browse/BXMSDOC-8373
- [Release notes for Red Hat Process Automation Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-RHPAM-RN-New/)
- [Release notes for Red Hat Decision Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-RHDM-RN-New/)
- From **Chapter 2**: Removed the references of kogito process management. 
- In RHDM doc Chapter 5. Deprecated components, removed the content related unified product.
- In Chapter 7, added a new known issue related to Openshft.
- Removed section 3.11.1. OptaPlanner quickstarts
- Removed section 3.11.1. OptaPlanner quickstarts
- Removed section 3.11.2. Micrometer with OptaPlanner
- Removed …

Upstream 7.59.x branch PR for BXMSDOC-8373: Remove any references of kogito process management and update the 7.12 release notes

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.12-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.12-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-kogito-productize-features-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**JIRAs**
- Epic: https://issues.redhat.com/browse/BXMSDOC-7825
- Dedicated JIRA: https://issues.redhat.com/browse/BXMSDOC-8373
- [Release notes for Red Hat Process Automation Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-RHPAM-RN-New/)
- [Release notes for Red Hat Decision Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-RHDM-RN-New/)
- From **Chapter 2**: Removed the references of kogito process management. 
- In RHDM doc Chapter 5. Deprecated components, removed the content related unified product.
- In Chapter 7, added a new known issue related to Openshft.
- Removed section 3.11.1. OptaPlanner quickstarts
- Removed section 3.11.1. OptaPlanner quickstarts
- Removed section 3.11.2. Micrometer with OptaPlanner
- Removed …

Upstream main branch PR for BXMSDOC-8373: Remove any references of kogito process management and update the 7.12 release notes

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.12-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.12-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Tracking JIRA:** https://issues.redhat.com/browse/BXMSDOC-8373
- [Release notes for Red Hat Process Automation Manager 7.12(Milestone 2)](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-7.12-RHPAM-Milestone2/)
- [Release notes for Red Hat Decision Manager 7.12 (Milestone 2)](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-7.12-RHDM-Milestone2)
- Removed Section 2.3. Support for BPMN processes in Red Hat build of Kogito
- Removed Section 2.4. Support for processes and decisions integration using Red Hat build of Kogito
- Added Section 3.11.1. OptaPlanner quickstarts
- Added Section 3.11.2. Micrometer with OptaPlanner
- Added Section 5.2. OptaPlanner 7
- Added Section 5.3. OptaPlanner tooling components in Business Central
- Added Section 6.5. Red Hat …

Upstream 7.59.x PR for BXMSDOC-8373: Update the release notes content as per 7.12 (Milestone 2).

---

_artifacts/document-attributes.adoc
doc-content/enterprise-only/release-notes/rn-7.12-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.12-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc
doc-content/enterprise-only/release-notes/rn-whats-new-con.adoc

**Tracking JIRA:** https://issues.redhat.com/browse/BXMSDOC-8373
- [Release notes for Red Hat Process Automation Manager 7.12(Milestone 2)](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-7.12-RHPAM-Milestone2/)
- [Release notes for Red Hat Decision Manager 7.12 (Milestone 2)](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8373-7.12-RHDM-Milestone2)
- Removed Section 2.3. Support for BPMN processes in Red Hat build of Kogito
- Removed Section 2.4. Support for processes and decisions integration using Red Hat build of Kogito
- Added Section 3.11.1. OptaPlanner quickstarts
- Added Section 3.11.2. Micrometer with OptaPlanner
- Added Section 5.2. OptaPlanner 7
- Added Section 5.3. OptaPlanner tooling components in Business Central
- Added Section 6.5. Red Hat …

Upstream main PR for BXMSDOC-8373: Update the release notes content as per 7.12 (Milestone 2).

---

_artifacts/document-attributes.adoc
assemblies/assembly-release-notes.adoc
doc-content/enterprise-only/release-notes/rn-7.12.1-fixed-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-7.12.1-known-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-deprecated-issues-ref.adoc
doc-content/enterprise-only/release-notes/rn-tech-preview-ref.adoc

**Associated JIRA:** https://issues.redhat.com/browse/BXMSDOC-8435
- [Release notes for Red Hat Process Automation Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8435-7.12.1-RHPAM-RN/)
- [Release notes for Red Hat Decision Manager 7.12](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8435-RHDM-7.12.1-This/#unified_product_deliverable_and_deprecation_of_red_hat_decision_manager_distribution_files)
Added fixed issues and known issues for the 7.12.1 release.

Upstream 7.59.x PR for BXMSDOC-8435: Update the release notes docs for RHPAM/RHDM 7.12.1

---

doc-content/kogito-docs/src/main/asciidoc/serverless/chap-kogito-orchestrating-serverless.adoc

Jira - https://github.com/VaniHaripriya/kie-docs/pull/new/KOGITO-6699
Removed references of Spring boot from Serverless documentation.

Kogito 6699- Drop Spring Boot support from Serverless Workflow

---

doc-content/shared-kie-docs/src/main/asciidoc/KieServer/kie-server-system-properties-ref.adoc

- As a limitation, asynchronous deployment does not work in Tomcat because it doesn't have ContainerManagerEJB. Clarifying it in the doc.
Explained in the JIRA:
https://issues.redhat.com/browse/DROOLS-6886

[DROOLS-6886] KIE Server asynchronous deployment does not work

---

doc-content/kogito-docs/pom.xml
doc-content/pom.xml
pom.xml

now the versions are synced with the main branch. Each time the job for updating the kie-docs is executed the version will be updated too. Until now the problem was, that this SNAPSHOT version was always one version behind.

synced to main SNAPSHOT version

---

doc-content/kogito-docs/src/main/asciidoc/bpmn/chap-kogito-developing-process-services.adoc
doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc
doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
doc-content/kogito-docs/src/main/asciidoc/openshift/chap-kogito-deploying-on-openshift.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.15.0.Final/ReleaseNotesKogito.1.15.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/serverless/chap-kogito-orchestrating-serverless.adoc
doc-content/kogito-docs/src/main/asciidoc/test-scenarios/chap-kogito-test-scenarios.adoc

JIRA: https://issues.redhat.com/browse/KOGITO-6884
The examples location in kogito-examples has changed. So, we need to review all the links on the KIE blog and in the following repos:
https://github.com/kiegroup/kogito-runtimes
https://github.com/kiegroup/kogito-examples
https://github.com/kiegroup/kie-docs/tree/main-kogito
[https://github.com/kiegroup/kogito-docs](https://github.com/kiegroup/kogito-examples)

KOGITO-6884 Updated links to examples

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/architecture-scenarios-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-storage-version-build-options-ref.adoc

* Changes for OpenShift 4 in Decisiong your DM architecture doc
* Clarified S2I
* Replaced CodeReady with VSCode
* Update doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/architecture-scenarios-ref.adoc

BXMSDOC-8600 Changes for OpenShift 4 and remove CodeReady in Designing your DM architecture - 7.67.x

---

doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/architecture-scenarios-ref.adoc
doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/project-storage-version-build-options-ref.adoc

* Changes for OpenShift 4 in Decisiong your DM architecture doc
* Clarified S2I
* Replaced CodeReady with VSCode
* Update doc-content/shared-kie-docs/src/main/asciidoc/KIE/Overview/architecture-scenarios-ref.adoc

BXMSDOC-8600 Changes for OpenShift 4 and remove CodeReady in Designing your DM architecture - 7.67.x-blue

---

doc-content/enterprise-only/getting-started-kogito/proc-kogito-custom-spring-boot-project-creating.adoc

The archetype was renamed in the past, so the example doesn't work with the old name anymore.

KOGITO-8061 Fix kogito-spring-boot-archetype name

---

doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.31.0.Final/ReleaseNotesKogito.1.31.0.Final.adoc
doc-content/kogito-docs/src/main/asciidoc/release-notes/ReleaseNotesKogito.1.31.1.Final/ReleaseNotesKogito.1.31.1.Final.adoc

Adding 1.31.1 for both as 1.31.0 doesnt exist aynmore ( 404 )

Fix links to SW docs

---

doc-content/enterprise-only/openshift/operator-deploy-security-proc.adoc

BXMSDOC-8653 baseFilter(AUTH_LDAP_BASE_FILTER) is incompatible with versions earlier than 7.12.0
* link 2
* link 3 etc.
<details>
<summary>
</summary>
> …

WIP: BXMSDOC-8653 7.67.x-blue baseFilter(AUTH_LDAP_BASE_FILTER) is incompatible with versions earlier than 7.12.0

---

doc-content/drools-docs/src/main/asciidoc/DMN/dmn-decision-tables-hit-policies-con.adoc

This PR is slightly related to changes in kie tooling. That will have 'self-contained' hit policies documentation from now on
* https://github.com/tiagobento/kie-tools/pull/68
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a …

Add 'rule order' and 'output order' hit policies

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/dsl/test.sh

apache/incubator-kie-kogito-pipelines#1090
apache/incubator-kie-kogito-runtimes#3233
apache/incubator-kie-kogito-apps#1882
apache/incubator-kie-kogito-examples#1810
apache/incubator-kie-kogito-images#1703
apache/incubator-kie-kogito-operator#1530
apache/incubator-kie-kogito-serverless-operator#257
apache/incubator-kie-kogito-docs#504
apache/incubator-kie-docs#4529
apache/incubator-kie-drools#5531
apache/incubator-kie-optaplanner#2985
apache/incubator-kie-optaplanner-quickstarts#607
apache/incubator-kie-benchmarks#262

kie-issues#574 Initial ASF Jenkins CI Setup

---

.ci/jenkins/Jenkinsfile.kie-kogito-post-release

apache/incubator-kie-issues#667
Fixing cleanup and settings.xml pipeline configuration to work correctly in ASF Jenkins.
* Deferred wipeout was causing issues when invoked in early stages
* Docker cleanup can't be done since the overall build is in docker container that uses the docker.sock from the host - it would attempt to erase itself.
* withSettingsXmlId shared library method does imply usage of a prohibited groovy method, thus replacing with explicit configFileProvider and passing as withSettingsXmlFile goes around that part of code. 
Complete list:
apache/incubator-kie-kogito-pipelines#1113
apache/incubator-kie-kogito-runtimes#3272
apache/incubator-kie-kogito-apps#1909
apache/incubator-kie-kogito-examples#1820
apache/incubator-kie-drools#5572
apache/incubator-kie-optaplanner#3010 …

kie-issues#667: fix cleanup and settingsXml handling
